repos:
  - repo: https://github.com/psf/black-pre-commit-mirror    
    rev: 25.1.0
    hooks:
    - id: black
      language_version: python3.11

  - repo: https://github.com/pycqa/flake8
    rev: "7.1.2"
    hooks:
    - id: flake8
      args: [--extend-ignore, E501]
      
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
    - id: prettier
      types: [javascript]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v9.21.0"
    hooks:
    - id: eslint
      args: [--no-config-lookup]
