repos:
  - repo: https://github.com/psf/black-pre-commit-mirror    
    rev: 24.4.0
    hooks:
    - id: black
      language_version: python3.11

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
    - id: prettier
      types: [javascript]

  - repo: https://github.com/pycqa/flake8
    rev: "7.0.0"
    hooks:
    - id: flake8
      args: [--extend-ignore, E501]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v9.1.1"
    hooks:
    - id: eslint
      args: [--no-config-lookup]
