name: u4i-prod

services:
  web:
    image: ghcr.io/4irl/u4i-prod:latest
    container_name: u4i-prod-flask
    ports: 
      - "127.0.0.1:8659:5000"
    depends_on:
      - db
      - redis
    environment:
      - PRODUCTION=true
      - REDIS_URI=redis://redis:6379/0
      - FLASK_DEBUG=false
      - MAILJET_API_KEY=/run/secrets/MAILJET_API_KEY
      - MAILJET_SECRET_KEY=/run/secrets/MAILJET_SECRET_KEY
      - BASE_EMAIL=/run/secrets/BASE_EMAIL
      - SECRET_KEY=/run/secrets/SECRET_KEY
      - POSTGRES_DB=/run/secrets/POSTGRES_DB
      - POSTGRES_USER=/run/secrets/POSTGRES_USER
      - POSTGRES_PASSWORD=/run/secrets/POSTGRES_PASSWORD
    secrets:
      - MAILJET_API_KEY
      - MAILJET_SECRET_KEY
      - BASE_EMAIL
      - SECRET_KEY
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    command: >
      sh -c "
      . /code/venv/bin/activate &&
      flask db upgrade &&
      gunicorn --workers 4 --bind 0.0.0.0:5000 --access-logfile - --error-logfile - run:app
      "

  db:
    image: postgres:16.3-bookworm
    container_name: u4i-prod-postgres
    environment:
      - POSTGRES_DB_FILE=/run/secrets/POSTGRES_DB
      - POSTGRES_USER_FILE=/run/secrets/POSTGRES_USER
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth=scram-sha-256
    secrets:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    container_name: u4i-prod-redis
    environment:
      - REDIS_PASSWORD=/run/secrets/REDIS_PASSWORD
    secrets:
      - REDIS_PASSWORD
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass $${REDIS_PASSWORD}'
    volumes:
      - redisdata:/data

secrets:
  POSTGRES_DB:
    file: ./secrets/POSTGRES_DB
  POSTGRES_USER:
    file: ./secrets/POSTGRES_USER
  POSTGRES_PASSWORD:
    file: ./secrets/POSTGRES_PASSWORD
  MAILJET_API_KEY:
    file: ./secrets/MAILJET_API_KEY
  MAILJET_SECRET_KEY:
    file: ./secrets/MAILJET_SECRET_KEY
  BASE_EMAIL:
    file: ./secrets/BASE_EMAIL
  REDIS_PASSWORD:
    file: ./secrets/REDIS_PASSWORD
  SECRET_KEY:
    file: ./secrets/SECRET_KEY

volumes:
  pgdata:
  redisdata:

