class ADMIN_METRICS_STRINGS:
    METRICS_DASHBOARD_TITLE: str = "Anonymous Metrics — Admin Dashboard"
    METRICS_REFRESH_BUTTON_LABEL: str = "Refresh"
    METRICS_TAB_API: str = "Top Endpoints"
    METRICS_TAB_UI: str = "Top UI Events"
    METRICS_TAB_DOMAIN: str = "Top Domain Actions"
    METRICS_TAB_PIPELINE_HEALTH: str = "Pipeline Health"
    METRICS_TAB_FLOWS: str = "Flows"
    METRICS_TAB_GAUGES: str = "Gauges"
    METRICS_TIMESERIES_SELECT_ARIA: str = "Select event for timeseries chart"
    METRICS_LAST_FLUSH_UNKNOWN: str = "Last flush unknown"
    METRICS_LAST_FLUSH_JUST_NOW: str = "Last flush just now"
    METRICS_LAST_FLUSH_SECONDS: str = "Last flush {{ n }}s ago"
    METRICS_LAST_FLUSH_MINUTES: str = "Last flush {{ n }}m ago"
    METRICS_LAST_FLUSH_STALE_MINUTES: str = "Last flush {{ n }}m ago (stale)"
    METRICS_LAST_FLUSH_STALE_HOURS: str = "Last flush {{ n }}h ago (stale)"
    METRICS_LAST_EVENT_UNKNOWN: str = "Last event unknown"
    METRICS_LAST_EVENT_JUST_NOW: str = "Last event just now"
    METRICS_LAST_EVENT_SECONDS: str = "Last event {{ n }}s ago"
    METRICS_LAST_EVENT_MINUTES: str = "Last event {{ n }}m ago"
    METRICS_LAST_EVENT_HOURS: str = "Last event {{ n }}h ago"
    METRICS_EMPTY_STATE: str = "No events recorded in the selected window."
    METRICS_FETCH_FAILED_BANNER: str = (
        "Refresh failed — showing last successful data. Retrying in 60 seconds."
    )
    METRICS_SUMMARY_TOTAL_EVENTS: str = "Total Events"
    METRICS_SUMMARY_API_HITS: str = "API hits"
    METRICS_SUMMARY_UI_EVENTS: str = "UI events"
    METRICS_SUMMARY_DOMAIN_ACTIONS: str = "Domain actions"
    METRICS_SUMMARY_DELTA_SUFFIX: str = " vs prev"
    METRICS_SUMMARY_DELTA_UNAVAILABLE: str = "—"
    METRICS_TOP_TABLE_HEADER_RANK: str = "#"
    METRICS_TOP_TABLE_HEADER_ENDPOINT: str = "Endpoint"
    METRICS_TOP_TABLE_HEADER_EVENT: str = "Event"
    METRICS_TOP_TABLE_HEADER_ACTION: str = "Action"
    METRICS_TOP_TABLE_HEADER_HITS: str = "Hits"
    METRICS_TOP_TABLE_HEADER_DELTA: str = "Δ vs prev"
    METRICS_TOP_TABLE_ROW_ARIA: str = "Show timeseries for {{ name }}"
    METRICS_CHART_Y_AXIS_LABEL: str = "Count"
    METRICS_TOP_RESOURCE_ALL: str = "All resources"
    METRICS_TOP_RESOURCE_UTUB: str = "UTubs"
    METRICS_TOP_RESOURCE_URL: str = "URLs"
    METRICS_TOP_RESOURCE_TAG: str = "Tags"
    METRICS_TOP_RESOURCE_MEMBER: str = "Members"
    METRICS_TOP_RESOURCE_AUTH: str = "Auth"
    METRICS_TOP_RESOURCE_SEARCH: str = "Search"
    METRICS_TOP_RESOURCE_FORM: str = "Forms"
    METRICS_TOP_RESOURCE_DECK: str = "Deck"
    METRICS_TOP_RESOURCE_NAV: str = "Navigation"
    METRICS_TOP_RESOURCE_ERROR: str = "Errors"
    METRICS_TOP_RESOURCE_CONTACT: str = "Contact"
    METRICS_TOP_RESOURCE_ADMIN: str = "Admin"
    METRICS_TOP_RESOURCE_OTHER: str = "Other"
    METRICS_TOP_DEVICE_ALL: str = "All devices"
    METRICS_TOP_DEVICE_MOBILE: str = "Mobile"
    METRICS_TOP_DEVICE_DESKTOP: str = "Desktop"
    METRICS_TOP_EMPTY_NO_MATCHES: str = "No events match the current filter."
    METRICS_PIPELINE_HEALTH_TITLE: str = "Pipeline Health"
    METRICS_PIPELINE_HEALTH_EMPTY_STATE: str = (
        "No ingest batches recorded in the selected window."
    )
    METRICS_PIPELINE_HEALTH_AXIS_LABEL: str = "Batches"
    METRICS_PIPELINE_HEALTH_AXIS_LABEL_X: str = "Events per batch"
    METRICS_PIPELINE_HEALTH_LEGEND_FETCH_DESKTOP: str = "fetch · desktop"
    METRICS_PIPELINE_HEALTH_LEGEND_FETCH_MOBILE: str = "fetch · mobile"
    METRICS_PIPELINE_HEALTH_LEGEND_BEACON_DESKTOP: str = "beacon · desktop"
    METRICS_PIPELINE_HEALTH_LEGEND_BEACON_MOBILE: str = "beacon · mobile"
    METRICS_PIPELINE_HEALTH_CHART_DESC: str = (
        "Stacked bar chart of accepted ingest batches grouped by batch size "
        "and split by transport and device type."
    )
    METRICS_FLOW_SUCCEEDED: str = "succeeded"
    METRICS_FLOW_CONVERSION: str = "conversion"
    METRICS_FLOW_DROPOFF: str = "drop-off"
    METRICS_FLOW_CATEGORY_UI: str = "UI"
    METRICS_FLOW_CATEGORY_API: str = "API"
    METRICS_FLOW_CATEGORY_DOMAIN: str = "Domain"
    METRICS_FLOW_EMPTY: str = "No funnel activity recorded in the selected window."
    METRICS_FLOWS_LOADED: str = "Flow funnels updated."
    METRICS_GAUGE_KIND_VOLUME: str = "Volume"
    METRICS_GAUGE_KIND_DISTRIBUTION_MAX: str = "Distribution (max)"
    METRICS_GAUGE_KIND_DISTRIBUTION_AVG: str = "Distribution (avg)"
    METRICS_GAUGE_SUPPRESSED_ARIA: str = "Value unavailable"
    METRICS_GAUGES_LOADED: str = "Gauge values updated."
