# Internal libraries
from backend.cli.mock_constants import (
    USERNAME_BASE,
    MOCK_UTUB_NAME_BASE,
    EMAIL_SUFFIX,
    MOCK_URL_STRINGS,
    MOCK_URL_TRACKING_STRIPPED,
    MOCK_URL_WITH_TRACKING_PARAMS,
)
from backend.utils.strings.admin_metrics_strs import ADMIN_METRICS_STRINGS
from backend.utils.strings.admin_portal_strs import (
    ADMIN_ACTION_STRINGS,
    ADMIN_PORTAL_STRINGS,
)
from backend.utils.strings.oauth_strs import EMAIL_COLLISION_MESSAGE
from backend.utils.strings.search_strs import CROSS_SEARCH_NO_RESULTS
from backend.utils.strings.splash_form_strs import (
    GOOGLE_OAUTH_LOGIN_BUTTON_TEXT,
    GOOGLE_OAUTH_REGISTER_BUTTON_TEXT,
)
from backend.utils.strings.tag_strs import (
    TAG_DECK_NO_TAGS as _TAG_DECK_NO_TAGS,
    TAG_FILTER_NO_RESULTS,
    TAG_SEARCH_NO_RESULTS as _TAG_SEARCH_NO_RESULTS,
)
from backend.utils.strings.url_strs import (
    ADD_URL_BUTTON,
    URL_IN_UTUB_TRACKING_PARAMS_STRIPPED,
    URL_SEARCH_NO_RESULTS,
    UTUB_NO_URLS,
)
from backend.utils.strings.user_settings_strs import USER_SETTINGS_STRINGS
from backend.utils.strings.user_strs import (
    COOKIE_BANNER_SEEN,
    MEMBER_SEARCH_NO_RESULTS,
)
from backend.utils.strings.utub_strs import UTUB_SEARCH_NO_RESULTS


class UI_TEST_STRINGS:
    BASE_URL = "http://127.0.0.1:"
    DOCKER_BASE_URL = "http://web:"

    TEST_USERNAME_1 = USERNAME_BASE + "1"
    # Using password as email
    TEST_PASSWORD_1 = TEST_USERNAME_1 + EMAIL_SUFFIX

    TEST_USERNAME_UNLISTED = USERNAME_BASE + "_UNLISTED"
    TEST_PASSWORD_UNLISTED = TEST_USERNAME_UNLISTED + EMAIL_SUFFIX

    # Google OAuth — button labels re-exported so UI tests assert the rendered
    # DOM text against the same backend source the templates render.
    GOOGLE_OAUTH_LOGIN_BUTTON_TEXT = GOOGLE_OAUTH_LOGIN_BUTTON_TEXT
    GOOGLE_OAUTH_REGISTER_BUTTON_TEXT = GOOGLE_OAUTH_REGISTER_BUTTON_TEXT

    # Google OAuth — reject-page copy re-exported so UI tests assert the
    # rendered banner text against the same backend source
    # (backend/splash/services/oauth/google_service.py) that renders it.
    OAUTH_EMAIL_COLLISION_MESSAGE = EMAIL_COLLISION_MESSAGE

    # Google OAuth — deterministic per-scenario identities fed to the fake
    # provider (backend/testing/fake_oauth_provider.py) via `set-identity`,
    # keeping the four UI scenarios from colliding with each other's state.
    OAUTH_RETURNING_USER_SUBJECT = "fake-oauth-subject-returning"
    OAUTH_RETURNING_USER_EMAIL = "oauth.returning@example.com"
    OAUTH_RETURNING_USER_NAME = "Returning OAuth User"
    OAUTH_RETURNING_USER_USERNAME = "oauthreturninguser"

    OAUTH_NEW_USER_SUBJECT = "fake-oauth-subject-new"
    OAUTH_NEW_USER_EMAIL = "oauth.newuser@example.com"
    # No spaces: this name becomes the derived username on account creation
    # (see `resolve_preferred_username`/`generate_unique_username_from_email`),
    # asserted verbatim via `assert_login_with_username`.
    OAUTH_NEW_USER_NAME = "NewOAuthUser"

    OAUTH_COLLISION_SUBJECT = "fake-oauth-subject-collision"
    OAUTH_COLLISION_EMAIL = "oauth.collision@example.com"
    OAUTH_COLLISION_NAME = "Collision OAuth User"
    OAUTH_COLLISION_PASSWORD = "P@ssword123!"
    OAUTH_COLLISION_USERNAME = "oauthcollisionpwuser"

    OAUTH_FORGOT_PASSWORD_SUBJECT = "fake-oauth-subject-forgot-password"
    OAUTH_FORGOT_PASSWORD_EMAIL = "oauth.forgotpassword@example.com"
    OAUTH_FORGOT_PASSWORD_NAME = "Forgot Password OAuth User"
    OAUTH_FORGOT_PASSWORD_USERNAME = "oauthforgotpassworduser"

    # Register
    PASSWORD_EQUALITY_FAILED = "Passwords are not identical."
    EMAIL_EQUALITY_FAILED = "Emails do not match."

    # UTubs
    TEST_UTUB_NAME_1 = MOCK_UTUB_NAME_BASE + "1"
    TEST_UTUB_NAME_2 = MOCK_UTUB_NAME_BASE + "2"

    # URLDeck header/subheader length-responsive font sizes (px). These mirror
    # the TypeScript constants in frontend/home/utubs/header-fit.ts — they are a
    # cross-language pairing and MUST be kept in sync when changing a font value
    # in either file.
    TITLE_MAX_FONT_PX: int = 32  # mirrors TITLE_MAX_FONT_PX in header-fit.ts
    TITLE_MIN_FONT_PX: int = 16  # mirrors TITLE_MIN_FONT_PX in header-fit.ts
    DESC_MAX_FONT_PX: int = 20  # mirrors DESC_MAX_FONT_PX in header-fit.ts
    DESC_MIN_FONT_PX: int = 14  # mirrors DESC_MIN_FONT_PX in header-fit.ts

    # A 30-char title (the UTub name cap) and a ~240-char description that
    # overflow a single line, forcing the fit logic down to its minimum font and
    # the text to wrap across multiple lines. Used by the URLDeck header-font
    # Selenium tests. The description stays under the MAX_DESCRIPTION_LENGTH (325)
    # column limit while still being long enough — with spaces so word-break wraps
    # at word boundaries — to clamp the description to its minimum font and span
    # several lines in the narrow URLDeck panel.
    SHORT_FIT_UTUB_NAME = "ShortName"
    SHORT_FIT_UTUB_DESCRIPTION = "A short description."
    LONG_FIT_UTUB_NAME = "Wxyz" * 6 + "QrstUv"  # exactly 30 chars, no spaces
    LONG_FIT_UTUB_DESCRIPTION = (
        "This UTub description is intentionally long enough that even at the "
        "smallest font size it cannot fit on one line and must wrap across "
        "several lines while staying fully visible and never truncated, "
        "which is the responsive font-fitting behaviour."
    )  # 244 chars; stays under the 325-char column limit yet still forces min-font wrapping

    # Tags
    TEST_TAG_NAME_1 = "Terrible"

    TEST_URL_STRING_CREATE = MOCK_URL_STRINGS[0]
    TEST_URL_TITLE_1 = "This is " + MOCK_URL_STRINGS[0] + "."
    TEST_URL_TITLE_UPDATE = "MS Support"

    # Tracking-param stripping (mirror backend mock constants + the user-facing
    # collision message; never duplicate the literals).
    URL_WITH_TRACKING_PARAMS = MOCK_URL_WITH_TRACKING_PARAMS
    URL_TRACKING_STRIPPED = MOCK_URL_TRACKING_STRIPPED
    URL_IN_UTUB_TRACKING_PARAMS_STRIPPED = URL_IN_UTUB_TRACKING_PARAMS_STRIPPED
    # A URL with legitimate (non-tracking) query params, used by the create/update
    # "preserve non-tracking params" UI tests to assert the query string survives.
    URL_WITH_NON_TRACKING_PARAMS = "https://www.example.com/p?q=search&sort=date"

    UTUB_SEARCH_NAMES = (
        "A1",
        "B1",
        "C1",
        "D1",
    )

    URL_SEARCH_UTUB_NAME = "URL Search Test UTub"

    URL_SEARCH_TITLES = (
        "Alpha News",
        "Beta Blog",
        "Charlie Docs",
        "Delta Forum",
    )

    URL_SEARCH_STRINGS = (
        "https://alpha-news.com",
        "https://beta-blog.org",
        "https://charlie-docs.io",
        "https://delta-forum.net",
    )

    # Cross-UTub search — shared query term appears in BOTH the title and the
    # url_string of one URL per UTub, so a match surfaces regardless of which
    # field(s) are selected. Two member UTubs (user is creator) each get one
    # matching URL plus a non-matching URL, so search yields >=2 groups.
    CROSS_SEARCH_QUERY_TERM = "orbit"
    CROSS_SEARCH_NO_MATCH_TERM = "zzqxnomatch"
    CROSS_SEARCH_UTUB_NAMES = (
        "Cross Search UTub One",
        "Cross Search UTub Two",
    )
    CROSS_SEARCH_MATCHING_TITLES = (
        "Orbit Mechanics One",
        "Orbit Dynamics Two",
    )
    CROSS_SEARCH_MATCHING_URLS = (
        "https://orbit-one.example.com",
        "https://orbit-two.example.org",
    )
    CROSS_SEARCH_FILLER_TITLES = (
        "Unrelated Page One",
        "Unrelated Page Two",
    )
    CROSS_SEARCH_FILLER_URLS = (
        "https://filler-one.example.com",
        "https://filler-two.example.org",
    )
    # Asserted rendered no-results text — locked to the backend source constant.
    CROSS_SEARCH_NO_RESULTS_TEXT = CROSS_SEARCH_NO_RESULTS

    TAG_FILTER_NO_URLS = TAG_FILTER_NO_RESULTS
    TAG_SEARCH_NO_TAGS = _TAG_SEARCH_NO_RESULTS  # intentional: attribute name follows TAG_FILTER_NO_URLS convention (describes test condition — "no tags found" — not the backend constant name TAG_SEARCH_NO_RESULTS)
    TAG_DECK_NO_TAGS = _TAG_DECK_NO_TAGS
    URL_SEARCH_NO_URLS = URL_SEARCH_NO_RESULTS
    UTUB_SEARCH_NO_UTUBS = UTUB_SEARCH_NO_RESULTS
    MEMBER_SEARCH_NO_MEMBERS = MEMBER_SEARCH_NO_RESULTS
    UTUB_NO_URLS = UTUB_NO_URLS
    ADD_URL_BUTTON = ADD_URL_BUTTON

    COOKIE_NAME, COOKIE_VALUE = COOKIE_BANNER_SEEN.split("=")

    # Admin metrics dashboard — re-export backend constants so test
    # assertions stay locked to the user-facing strings.
    ADMIN_PORTAL_TITLE = ADMIN_PORTAL_STRINGS.PORTAL_TITLE
    ADMIN_HEALTH_TITLE = ADMIN_PORTAL_STRINGS.HEALTH_TITLE
    ADMIN_USERS_TITLE = ADMIN_PORTAL_STRINGS.USERS_TITLE
    ADMIN_USERS_NO_RESULTS = ADMIN_PORTAL_STRINGS.USERS_NO_RESULTS
    ADMIN_USER_DETAIL_TITLE = ADMIN_PORTAL_STRINGS.USER_DETAIL_TITLE
    ADMIN_AUDIT_LOG_TITLE = ADMIN_PORTAL_STRINGS.AUDIT_LOG_TITLE
    ADMIN_AUDIT_LOG_NO_RESULTS = ADMIN_PORTAL_STRINGS.AUDIT_LOG_NO_RESULTS
    ADMIN_PORTAL_NAV_HEALTH = ADMIN_PORTAL_STRINGS.NAV_HEALTH
    ADMIN_PORTAL_NAV_DB_BROWSER = ADMIN_PORTAL_STRINGS.NAV_DB_BROWSER
    ADMIN_PORTAL_NAV_SYSTEM_OPS = ADMIN_PORTAL_STRINGS.NAV_SYSTEM_OPS
    ADMIN_PORTAL_NAV_USER_ACTIONS = ADMIN_PORTAL_STRINGS.NAV_USER_ACTIONS
    ADMIN_PORTAL_NAV_UTUB_ACTIONS = ADMIN_PORTAL_STRINGS.NAV_UTUB_ACTIONS
    ADMIN_PORTAL_NAV_AUDIT_LOG = ADMIN_PORTAL_STRINGS.NAV_AUDIT_LOG
    ADMIN_PORTAL_NAV_METRICS = ADMIN_PORTAL_STRINGS.NAV_METRICS
    # System Operations / UTub Actions page copy — locked to backend source
    ADMIN_SYSTEM_OPS_TITLE = ADMIN_PORTAL_STRINGS.SYSTEM_OPS_TITLE
    ADMIN_SYSTEM_OPS_SUBTITLE = ADMIN_PORTAL_STRINGS.SYSTEM_OPS_SUBTITLE
    ADMIN_USER_ACTIONS_TITLE = ADMIN_PORTAL_STRINGS.USER_ACTIONS_TITLE
    ADMIN_USER_ACTIONS_SUBTITLE = ADMIN_PORTAL_STRINGS.USER_ACTIONS_SUBTITLE
    ADMIN_UTUB_ACTIONS_TITLE = ADMIN_PORTAL_STRINGS.UTUB_ACTIONS_TITLE
    ADMIN_UTUB_ACTIONS_SUBTITLE = ADMIN_PORTAL_STRINGS.UTUB_ACTIONS_SUBTITLE
    ADMIN_UTUB_DETAIL_TITLE = ADMIN_PORTAL_STRINGS.UTUB_DETAIL_TITLE
    ADMIN_UTUB_DETAIL_MEMBERS_HEADING = ADMIN_PORTAL_STRINGS.UTUB_DETAIL_MEMBERS_HEADING
    ADMIN_UTUB_DETAIL_URLS_HEADING = ADMIN_PORTAL_STRINGS.UTUB_DETAIL_URLS_HEADING
    ADMIN_UTUB_DETAIL_NO_MEMBERS = ADMIN_PORTAL_STRINGS.UTUB_DETAIL_NO_MEMBERS
    ADMIN_UTUB_DETAIL_NO_URLS = ADMIN_PORTAL_STRINGS.UTUB_DETAIL_NO_URLS
    ADMIN_PORTAL_DB_BROWSER_TITLE = ADMIN_PORTAL_STRINGS.DB_BROWSER_TITLE
    ADMIN_PORTAL_DB_EMPTY_TABLE = ADMIN_PORTAL_STRINGS.DB_EMPTY_TABLE
    ADMIN_OPS_SECTION_TITLE = ADMIN_PORTAL_STRINGS.OPS_SECTION_TITLE
    ADMIN_OPS_VERIFY_TABLES_CONFIRM_TITLE = (
        ADMIN_PORTAL_STRINGS.OPS_VERIFY_TABLES_CONFIRM_TITLE
    )
    ADMIN_OPS_VERIFY_TABLES_DESC = ADMIN_PORTAL_STRINGS.OPS_VERIFY_TABLES_DESC
    ADMIN_OPS_VERIFY_OK = ADMIN_ACTION_STRINGS.OPS_VERIFY_OK
    ADMIN_PORTAL_DB_NO_SEARCH_RESULTS = ADMIN_PORTAL_STRINGS.DB_NO_SEARCH_RESULTS
    # Content moderation strings — locked to backend source so tests never duplicate literals
    ADMIN_MOD_LOCKED_BADGE = ADMIN_PORTAL_STRINGS.MOD_LOCKED_BADGE
    ADMIN_MOD_UTUB_LOCK_LABEL = ADMIN_PORTAL_STRINGS.MOD_UTUB_LOCK_LABEL
    ADMIN_MOD_UTUB_LOCK_CONFIRM_TITLE = ADMIN_PORTAL_STRINGS.MOD_UTUB_LOCK_CONFIRM_TITLE
    ADMIN_MOD_UTUB_UNLOCK_LABEL = ADMIN_PORTAL_STRINGS.MOD_UTUB_UNLOCK_LABEL
    ADMIN_MOD_UTUB_UNLOCK_CONFIRM_TITLE = (
        ADMIN_PORTAL_STRINGS.MOD_UTUB_UNLOCK_CONFIRM_TITLE
    )
    ADMIN_MOD_URL_PURGE_LABEL = ADMIN_PORTAL_STRINGS.MOD_URL_PURGE_LABEL
    ADMIN_MOD_URL_PURGE_CONFIRM_TITLE = ADMIN_PORTAL_STRINGS.MOD_URL_PURGE_CONFIRM_TITLE
    ADMIN_MOD_URL_PURGE_SUCCESS_PREFIX = "URL purged from"
    ADMIN_MOD_UTUB_TAG_DELETE_LABEL = ADMIN_PORTAL_STRINGS.MOD_UTUB_TAG_DELETE_LABEL
    ADMIN_MOD_UTUB_TAG_DELETE_CONFIRM_TITLE = (
        ADMIN_PORTAL_STRINGS.MOD_UTUB_TAG_DELETE_CONFIRM_TITLE
    )
    ADMIN_ACTION_REASON_REQUIRED = ADMIN_ACTION_STRINGS.REASON_REQUIRED
    # Account lifecycle strings — re-exported so tests never duplicate literals
    ADMIN_ACCOUNT_SECTION_TITLE = ADMIN_PORTAL_STRINGS.ACCOUNT_SECTION_TITLE
    ADMIN_ACCOUNT_SELF_ACTIONS_NA = ADMIN_PORTAL_STRINGS.ACCOUNT_SELF_ACTIONS_NA
    ADMIN_ACCOUNT_SUSPEND_LABEL = ADMIN_PORTAL_STRINGS.ACCOUNT_SUSPEND_LABEL
    ADMIN_ACCOUNT_SUSPEND_CONFIRM_TITLE = (
        ADMIN_PORTAL_STRINGS.ACCOUNT_SUSPEND_CONFIRM_TITLE
    )
    ADMIN_ACCOUNT_UNSUSPEND_LABEL = ADMIN_PORTAL_STRINGS.ACCOUNT_UNSUSPEND_LABEL
    ADMIN_ACCOUNT_UNSUSPEND_CONFIRM_TITLE = (
        ADMIN_PORTAL_STRINGS.ACCOUNT_UNSUSPEND_CONFIRM_TITLE
    )
    ADMIN_ACCOUNT_KILL_SESSIONS_LABEL = ADMIN_PORTAL_STRINGS.ACCOUNT_KILL_SESSIONS_LABEL
    ADMIN_ACCOUNT_KILL_SESSIONS_CONFIRM_TITLE = (
        ADMIN_PORTAL_STRINGS.ACCOUNT_KILL_SESSIONS_CONFIRM_TITLE
    )
    ADMIN_ACCOUNT_FORCE_RESET_LABEL = ADMIN_PORTAL_STRINGS.ACCOUNT_FORCE_RESET_LABEL
    ADMIN_ACCOUNT_FORCE_RESET_CONFIRM_TITLE = (
        ADMIN_PORTAL_STRINGS.ACCOUNT_FORCE_RESET_CONFIRM_TITLE
    )
    ADMIN_ACCOUNT_FORCE_RESET_NA = ADMIN_PORTAL_STRINGS.ACCOUNT_FORCE_RESET_NA
    ADMIN_ACCOUNT_FORCE_RESET_SUCCESS = ADMIN_ACTION_STRINGS.ACCOUNT_FORCE_RESET_SUCCESS
    ADMIN_ACCOUNT_KILL_SESSIONS_SUCCESS_SUBSTRING = "API token(s) revoked"
    # Phase 7 — account data actions
    ADMIN_ACCOUNT_ERASE_LABEL = ADMIN_PORTAL_STRINGS.ACCOUNT_ERASE_LABEL
    ADMIN_ACCOUNT_ERASE_CONFIRM_TITLE = ADMIN_PORTAL_STRINGS.ACCOUNT_ERASE_CONFIRM_TITLE
    ADMIN_ACCOUNT_ERASED_NA = ADMIN_PORTAL_STRINGS.ACCOUNT_ERASED_NA
    ADMIN_ACCOUNT_EMAIL_VERIFY_LABEL = ADMIN_PORTAL_STRINGS.ACCOUNT_EMAIL_VERIFY_LABEL
    ADMIN_ACCOUNT_EMAIL_VERIFY_CONFIRM_TITLE = (
        ADMIN_PORTAL_STRINGS.ACCOUNT_EMAIL_VERIFY_CONFIRM_TITLE
    )
    ADMIN_ACCOUNT_EMAIL_VERIFIED_NA = ADMIN_PORTAL_STRINGS.ACCOUNT_EMAIL_VERIFIED_NA
    ADMIN_ACCOUNT_EMAIL_RESEND_LABEL = ADMIN_PORTAL_STRINGS.ACCOUNT_EMAIL_RESEND_LABEL
    ADMIN_ACCOUNT_EMAIL_RESEND_CONFIRM_TITLE = (
        ADMIN_PORTAL_STRINGS.ACCOUNT_EMAIL_RESEND_CONFIRM_TITLE
    )
    ADMIN_ACCOUNT_OAUTH_SECTION_TITLE = ADMIN_PORTAL_STRINGS.ACCOUNT_OAUTH_SECTION_TITLE
    ADMIN_ACCOUNT_OAUTH_NONE = ADMIN_PORTAL_STRINGS.ACCOUNT_OAUTH_NONE
    ADMIN_ACCOUNT_UNLINK_LABEL = ADMIN_PORTAL_STRINGS.ACCOUNT_UNLINK_LABEL
    ADMIN_ACCOUNT_UNLINK_CONFIRM_TITLE = (
        ADMIN_PORTAL_STRINGS.ACCOUNT_UNLINK_CONFIRM_TITLE
    )
    ADMIN_ACCOUNT_UNLINK_NA = ADMIN_PORTAL_STRINGS.ACCOUNT_UNLINK_NA
    ADMIN_ACCOUNT_ERASE_SUCCESS = ADMIN_ACTION_STRINGS.ACCOUNT_ERASE_SUCCESS
    ADMIN_ACCOUNT_EMAIL_VERIFY_SUCCESS = (
        ADMIN_ACTION_STRINGS.ACCOUNT_EMAIL_VERIFY_SUCCESS
    )
    METRICS_DASHBOARD_TITLE = ADMIN_METRICS_STRINGS.METRICS_DASHBOARD_TITLE
    METRICS_TAB_API = ADMIN_METRICS_STRINGS.METRICS_TAB_API
    METRICS_TAB_UI = ADMIN_METRICS_STRINGS.METRICS_TAB_UI
    METRICS_TAB_DOMAIN = ADMIN_METRICS_STRINGS.METRICS_TAB_DOMAIN
    METRICS_TAB_PIPELINE_HEALTH = ADMIN_METRICS_STRINGS.METRICS_TAB_PIPELINE_HEALTH
    METRICS_TAB_FLOWS = ADMIN_METRICS_STRINGS.METRICS_TAB_FLOWS
    METRICS_TAB_GAUGES = ADMIN_METRICS_STRINGS.METRICS_TAB_GAUGES
    METRICS_FLOW_EMPTY = ADMIN_METRICS_STRINGS.METRICS_FLOW_EMPTY
    METRICS_REFRESH_BUTTON_LABEL = ADMIN_METRICS_STRINGS.METRICS_REFRESH_BUTTON_LABEL
    METRICS_TOP_DEVICE_ALL = ADMIN_METRICS_STRINGS.METRICS_TOP_DEVICE_ALL
    METRICS_TOP_DEVICE_MOBILE = ADMIN_METRICS_STRINGS.METRICS_TOP_DEVICE_MOBILE
    METRICS_TOP_DEVICE_DESKTOP = ADMIN_METRICS_STRINGS.METRICS_TOP_DEVICE_DESKTOP
    METRICS_PIPELINE_HEALTH_TITLE = ADMIN_METRICS_STRINGS.METRICS_PIPELINE_HEALTH_TITLE
    METRICS_PIPELINE_HEALTH_EMPTY_STATE = (
        ADMIN_METRICS_STRINGS.METRICS_PIPELINE_HEALTH_EMPTY_STATE
    )
    METRICS_PIPELINE_HEALTH_AXIS_LABEL = (
        ADMIN_METRICS_STRINGS.METRICS_PIPELINE_HEALTH_AXIS_LABEL
    )
    METRICS_PIPELINE_HEALTH_LEGEND_FETCH_DESKTOP = (
        ADMIN_METRICS_STRINGS.METRICS_PIPELINE_HEALTH_LEGEND_FETCH_DESKTOP
    )
    METRICS_PIPELINE_HEALTH_LEGEND_FETCH_MOBILE = (
        ADMIN_METRICS_STRINGS.METRICS_PIPELINE_HEALTH_LEGEND_FETCH_MOBILE
    )
    METRICS_PIPELINE_HEALTH_LEGEND_BEACON_DESKTOP = (
        ADMIN_METRICS_STRINGS.METRICS_PIPELINE_HEALTH_LEGEND_BEACON_DESKTOP
    )
    METRICS_PIPELINE_HEALTH_LEGEND_BEACON_MOBILE = (
        ADMIN_METRICS_STRINGS.METRICS_PIPELINE_HEALTH_LEGEND_BEACON_MOBILE
    )
    METRICS_PIPELINE_HEALTH_CHART_DESC = (
        ADMIN_METRICS_STRINGS.METRICS_PIPELINE_HEALTH_CHART_DESC
    )

    # User settings page — re-export backend constants so test
    # assertions stay locked to the user-facing strings.
    SETTINGS_PAGE_TITLE = USER_SETTINGS_STRINGS.PAGE_TITLE
    SETTINGS_TAB_ACCOUNT = USER_SETTINGS_STRINGS.TAB_ACCOUNT
    SETTINGS_TAB_STATS = USER_SETTINGS_STRINGS.TAB_STATS
    SETTINGS_TAB_PRIVACY_DATA = USER_SETTINGS_STRINGS.TAB_PRIVACY_DATA
    SETTINGS_TAB_UI_SETTINGS = USER_SETTINGS_STRINGS.TAB_UI_SETTINGS
    SETTINGS_PLACEHOLDER = USER_SETTINGS_STRINGS.PLACEHOLDER
