from __future__ import annotations

import json
import shutil
from pathlib import Path

import pytest
from click.testing import Result
from flask import Blueprint, Flask
from flask.testing import FlaskCliRunner

from backend.cli.endpoints import (
    AUDIT_NONE_PLACEHOLDER,
    AUDIT_SECTION_DRIFT,
    AUDIT_SECTION_JS,
    AUDIT_SECTION_MARKDOWN,
    AUDIT_SECTION_NO_JS,
    register_endpoints_cli,
)

pytestmark = pytest.mark.cli

DO_NOT_EDIT_HEADER = "<!-- Generated by `flask endpoints generate` — DO NOT EDIT. -->"
PROBE_ENDPOINT = "endpoints_cli_probe.probe_page"
PROBE_RULE = "/endpoints-cli-probe"

_REPO_ROOT = Path(__file__).resolve().parents[3]
COMMITTED_JSON = _REPO_ROOT / "docs" / "endpoints" / "endpoint-registry.json"
COMMITTED_MARKDOWN = _REPO_ROOT / "docs" / "endpoints" / "ENDPOINT_REGISTRY.md"
AUDIT_SECTIONS = (
    AUDIT_SECTION_DRIFT,
    AUDIT_SECTION_JS,
    AUDIT_SECTION_NO_JS,
    AUDIT_SECTION_MARKDOWN,
)

# Module-level so the registry's AST lookup can find the handler's `def`.
endpoints_cli_probe = Blueprint("endpoints_cli_probe", __name__)


@endpoints_cli_probe.route(PROBE_RULE, methods=["GET"])
def probe_page() -> str:
    return ""


def test_generate_writes_json_and_markdown(runner, tmp_path):
    """
    GIVEN a fully configured Flask app with all blueprints registered
    WHEN the developer runs `flask endpoints generate` with tmp output paths
    THEN it exits 0, the JSON parses with endpoints, and the markdown begins
        with the DO-NOT-EDIT comment
    """
    app, cli_runner = runner
    json_path = tmp_path / "x.json"
    markdown_path = tmp_path / "x.md"

    result = cli_runner.invoke(
        args=[
            "endpoints",
            "generate",
            "--output",
            str(json_path),
            "--markdown-output",
            str(markdown_path),
        ]
    )
    assert result.exit_code == 0, f"CLI failed: {result.output}"

    registry = json.loads(json_path.read_text(encoding="utf-8"))
    endpoint_count = len(registry["endpoints"])
    assert endpoint_count > 0
    assert f"wrote {endpoint_count} endpoints" in result.output
    assert markdown_path.read_text(encoding="utf-8").startswith(DO_NOT_EDIT_HEADER)


@pytest.mark.parametrize("bad_option", ["--output", "--markdown-output"])
def test_generate_to_nonexistent_directory_fails(runner, tmp_path, bad_option):
    """
    GIVEN a fully configured Flask app
    WHEN either output path points into a non-existent directory
    THEN exit_code != 0, the error names the missing directory and no file is
        written for the other (valid) path
    """
    app, cli_runner = runner
    missing_dir = tmp_path / "does_not_exist"
    paths = {
        "--output": tmp_path / "x.json",
        "--markdown-output": tmp_path / "x.md",
    }
    paths[bad_option] = missing_dir / "out"

    result = cli_runner.invoke(
        args=[
            "endpoints",
            "generate",
            "--output",
            str(paths["--output"]),
            "--markdown-output",
            str(paths["--markdown-output"]),
        ]
    )
    assert result.exit_code != 0
    assert "does not exist" in result.output.lower()
    assert str(missing_dir) in result.output
    assert not any(path.exists() for path in paths.values())


def _minimal_probe_app() -> Flask:
    """A DB-free Flask app with only the probe blueprint and the endpoints CLI."""
    minimal_app = Flask(__name__)
    minimal_app.register_blueprint(endpoints_cli_probe)
    register_endpoints_cli(minimal_app)
    return minimal_app


def test_generate_on_minimal_app_includes_probe_route(tmp_path):
    """
    GIVEN a DB-free minimal Flask app with one probe blueprint route
    WHEN the developer runs `flask endpoints generate`
    THEN the probe route appears in both the JSON and the markdown
    """
    minimal_app = _minimal_probe_app()
    json_path = tmp_path / "probe.json"
    markdown_path = tmp_path / "probe.md"

    result = minimal_app.test_cli_runner().invoke(
        args=[
            "endpoints",
            "generate",
            "--output",
            str(json_path),
            "--markdown-output",
            str(markdown_path),
        ]
    )
    assert result.exit_code == 0, f"CLI failed: {result.output}"

    registry = json.loads(json_path.read_text(encoding="utf-8"))
    assert [row["endpoint"] for row in registry["endpoints"]] == [PROBE_ENDPOINT]
    assert registry["endpoints"][0]["rule"] == PROBE_RULE
    assert f"### `GET {PROBE_RULE}` — `{PROBE_ENDPOINT}`" in markdown_path.read_text(
        encoding="utf-8"
    )


def test_generate_build_registry_error_fails_without_writing(tmp_path, monkeypatch):
    """
    GIVEN a DB-free minimal Flask app whose registry build raises ValueError
    WHEN the developer runs `flask endpoints generate`
    THEN exit_code != 0, the error message is surfaced, and neither output
        file is written
    """

    def _raise_build_error(*args: object, **kwargs: object) -> dict[str, object]:
        raise ValueError("probe: boom")

    monkeypatch.setattr("backend.cli.endpoints.build_registry", _raise_build_error)
    minimal_app = _minimal_probe_app()
    json_path = tmp_path / "probe.json"
    markdown_path = tmp_path / "probe.md"

    result = minimal_app.test_cli_runner().invoke(
        args=[
            "endpoints",
            "generate",
            "--output",
            str(json_path),
            "--markdown-output",
            str(markdown_path),
        ]
    )
    assert result.exit_code != 0
    assert "probe: boom" in result.output
    assert not json_path.exists()
    assert not markdown_path.exists()


def test_generate_to_directory_output_path_fails(tmp_path):
    """
    GIVEN a DB-free minimal Flask app
    WHEN `--markdown-output` points at an existing directory
    THEN exit_code != 0, the error says the path is a directory, and the JSON
        file is not written
    """
    minimal_app = _minimal_probe_app()
    json_path = tmp_path / "probe.json"

    result = minimal_app.test_cli_runner().invoke(
        args=[
            "endpoints",
            "generate",
            "--output",
            str(json_path),
            "--markdown-output",
            str(tmp_path),
        ]
    )
    assert result.exit_code != 0
    assert "is a directory" in result.output
    assert not json_path.exists()


def _invoke_audit(
    cli_runner: FlaskCliRunner, registry_path: Path, markdown_path: Path, *flags: str
) -> Result:
    return cli_runner.invoke(
        args=[
            "endpoints",
            "audit",
            *flags,
            "--registry",
            str(registry_path),
            "--markdown",
            str(markdown_path),
        ]
    )


def test_audit_strict_exits_zero_on_committed_registry(runner):
    """
    GIVEN the committed docs/endpoints artifacts and the live app
    WHEN `flask endpoints audit --strict` runs
    THEN it exits 0 and every section prints `(none)`
    """
    app, cli_runner = runner

    result = _invoke_audit(cli_runner, COMMITTED_JSON, COMMITTED_MARKDOWN, "--strict")

    assert result.exit_code == 0, result.output
    lines = result.output.splitlines()
    for section in AUDIT_SECTIONS:
        assert lines[lines.index(section) + 1] == AUDIT_NONE_PLACEHOLDER


def test_audit_strict_fails_when_committed_registry_lacks_an_endpoint(runner, tmp_path):
    """
    GIVEN a copy of the committed JSON with one endpoint deleted
    WHEN `flask endpoints audit --strict` runs against the copy
    THEN it exits 1 and names the endpoint as missing_in_registry
    """
    app, cli_runner = runner
    registry = json.loads(COMMITTED_JSON.read_text(encoding="utf-8"))
    removed_endpoint = registry["endpoints"].pop(0)["endpoint"]
    registry_path = tmp_path / "endpoint-registry.json"
    registry_path.write_text(json.dumps(registry), encoding="utf-8")

    result = _invoke_audit(cli_runner, registry_path, COMMITTED_MARKDOWN, "--strict")

    assert result.exit_code == 1, result.output
    assert f"missing_in_registry\t{removed_endpoint}\t" in result.output


def test_audit_without_strict_reports_but_exits_zero(runner, tmp_path):
    """
    GIVEN a committed markdown copy with a hand edit
    WHEN `flask endpoints audit` runs without --strict
    THEN it exits 0 but still prints the markdown_stale finding
    """
    app, cli_runner = runner
    markdown_path = tmp_path / "ENDPOINT_REGISTRY.md"
    shutil.copyfile(COMMITTED_MARKDOWN, markdown_path)
    with markdown_path.open("a", encoding="utf-8") as markdown_file:
        markdown_file.write("hand edit\n")

    result = _invoke_audit(cli_runner, COMMITTED_JSON, markdown_path)

    assert result.exit_code == 0, result.output
    assert "markdown_stale\t*\trun make generate-endpoints" in result.output


@pytest.mark.parametrize(
    ("registry_contents", "expected_detail"),
    [
        pytest.param(None, "committed registry not found", id="missing"),
        pytest.param("{not json", "committed registry unreadable", id="invalid-json"),
        pytest.param("[]", "committed registry has an invalid shape", id="bad-shape"),
        pytest.param(
            '{"endpoints": ["not a row"]}',
            "committed registry has an invalid shape",
            id="non-dict-row",
        ),
    ],
)
def test_audit_unusable_committed_registry_is_a_single_finding(
    runner, tmp_path, registry_contents, expected_detail
):
    """
    GIVEN a committed registry path that is missing, not JSON, or the wrong shape
    WHEN `flask endpoints audit --strict` runs
    THEN it exits 1 with one missing_in_registry finding (no traceback) and
        skips the markdown comparison
    """
    app, cli_runner = runner
    registry_path = tmp_path / "endpoint-registry.json"
    if registry_contents is not None:
        registry_path.write_text(registry_contents, encoding="utf-8")

    result = _invoke_audit(cli_runner, registry_path, COMMITTED_MARKDOWN, "--strict")

    assert result.exit_code == 1, result.output
    assert result.exception is None or isinstance(result.exception, SystemExit)
    assert f"missing_in_registry\t*\t{expected_detail}" in result.output
    assert result.output.count("missing_in_registry") == 1
    lines = result.output.splitlines()
    markdown_index = lines.index(AUDIT_SECTION_MARKDOWN)
    assert lines[markdown_index + 1] == AUDIT_NONE_PLACEHOLDER


def test_audit_missing_markdown_is_markdown_stale(runner, tmp_path):
    """
    GIVEN a markdown path that does not exist
    WHEN `flask endpoints audit --strict` runs
    THEN it exits 1 with a markdown_stale finding naming the path
    """
    app, cli_runner = runner
    markdown_path = tmp_path / "missing.md"

    result = _invoke_audit(cli_runner, COMMITTED_JSON, markdown_path, "--strict")

    assert result.exit_code == 1, result.output
    assert f"markdown_stale\t*\tcommitted markdown not found: {markdown_path}" in (
        result.output
    )


def test_audit_unreadable_markdown_is_markdown_stale(runner, tmp_path):
    """
    GIVEN a markdown path that is a directory, so reading it fails
    WHEN `flask endpoints audit --strict` runs
    THEN it exits 1 with a markdown_stale finding saying the markdown is unreadable
    """
    app, cli_runner = runner

    result = _invoke_audit(cli_runner, COMMITTED_JSON, tmp_path, "--strict")

    assert result.exit_code == 1, result.output
    assert result.exception is None or isinstance(result.exception, SystemExit)
    assert f"markdown_stale\t*\tcommitted markdown unreadable: {tmp_path}: " in (
        result.output
    )


def test_audit_build_registry_error_fails(tmp_path, monkeypatch):
    """
    GIVEN a DB-free minimal Flask app whose registry build raises ValueError
    WHEN the developer runs `flask endpoints audit`
    THEN exit_code != 0 and the error message is surfaced
    """

    def _raise_build_error(*args: object, **kwargs: object) -> dict[str, object]:
        raise ValueError("probe: boom")

    monkeypatch.setattr("backend.cli.endpoints.build_registry", _raise_build_error)
    minimal_app = _minimal_probe_app()

    result = _invoke_audit(
        minimal_app.test_cli_runner(),
        tmp_path / "probe.json",
        tmp_path / "probe.md",
    )

    assert result.exit_code != 0
    assert "probe: boom" in result.output


def test_audit_strict_reports_stale_indirect_entry(runner, monkeypatch):
    """
    GIVEN an INDIRECT_JS_ENDPOINTS map that also names a dead endpoint
    WHEN `flask endpoints audit --strict` runs against the committed artifacts
    THEN it exits 1 and lists indirect_entry_unknown under the stale-entries
        section
    """
    app, cli_runner = runner
    monkeypatch.setattr(
        "backend.cli.endpoints.INDIRECT_JS_ENDPOINTS",
        {"splash.reset_password": "page-self-url", "probe.gone": "page-self-url"},
    )

    result = _invoke_audit(cli_runner, COMMITTED_JSON, COMMITTED_MARKDOWN, "--strict")

    assert result.exit_code == 1, result.output
    lines = result.output.splitlines()
    stale_index = lines.index(AUDIT_SECTION_NO_JS)
    assert lines[stale_index + 1] == (
        "indirect_entry_unknown\tprobe.gone\tno live endpoint"
    )
