from __future__ import annotations

import json

import pytest
from flask import Blueprint, Flask

from backend.cli.endpoints import register_endpoints_cli

pytestmark = pytest.mark.cli

DO_NOT_EDIT_HEADER = "<!-- Generated by `flask endpoints generate` — DO NOT EDIT. -->"
PROBE_ENDPOINT = "endpoints_cli_probe.probe_page"
PROBE_RULE = "/endpoints-cli-probe"

# Module-level so the registry's AST lookup can find the handler's `def`.
endpoints_cli_probe = Blueprint("endpoints_cli_probe", __name__)


@endpoints_cli_probe.route(PROBE_RULE, methods=["GET"])
def probe_page() -> str:
    return ""


def test_generate_writes_json_and_markdown(runner, tmp_path):
    """
    GIVEN a fully configured Flask app with all blueprints registered
    WHEN the developer runs `flask endpoints generate` with tmp output paths
    THEN it exits 0, the JSON parses with endpoints, and the markdown begins
        with the DO-NOT-EDIT comment
    """
    app, cli_runner = runner
    json_path = tmp_path / "x.json"
    markdown_path = tmp_path / "x.md"

    result = cli_runner.invoke(
        args=[
            "endpoints",
            "generate",
            "--output",
            str(json_path),
            "--markdown-output",
            str(markdown_path),
        ]
    )
    assert result.exit_code == 0, f"CLI failed: {result.output}"

    registry = json.loads(json_path.read_text(encoding="utf-8"))
    endpoint_count = len(registry["endpoints"])
    assert endpoint_count > 0
    assert f"wrote {endpoint_count} endpoints" in result.output
    assert markdown_path.read_text(encoding="utf-8").startswith(DO_NOT_EDIT_HEADER)


@pytest.mark.parametrize("bad_option", ["--output", "--markdown-output"])
def test_generate_to_nonexistent_directory_fails(runner, tmp_path, bad_option):
    """
    GIVEN a fully configured Flask app
    WHEN either output path points into a non-existent directory
    THEN exit_code != 0, the error names the missing directory and no file is
        written for the other (valid) path
    """
    app, cli_runner = runner
    missing_dir = tmp_path / "does_not_exist"
    paths = {
        "--output": tmp_path / "x.json",
        "--markdown-output": tmp_path / "x.md",
    }
    paths[bad_option] = missing_dir / "out"

    result = cli_runner.invoke(
        args=[
            "endpoints",
            "generate",
            "--output",
            str(paths["--output"]),
            "--markdown-output",
            str(paths["--markdown-output"]),
        ]
    )
    assert result.exit_code != 0
    assert "does not exist" in result.output.lower()
    assert str(missing_dir) in result.output
    assert not any(path.exists() for path in paths.values())


def _minimal_probe_app() -> Flask:
    """A DB-free Flask app with only the probe blueprint and the endpoints CLI."""
    minimal_app = Flask(__name__)
    minimal_app.register_blueprint(endpoints_cli_probe)
    register_endpoints_cli(minimal_app)
    return minimal_app


def test_generate_on_minimal_app_includes_probe_route(tmp_path):
    """
    GIVEN a DB-free minimal Flask app with one probe blueprint route
    WHEN the developer runs `flask endpoints generate`
    THEN the probe route appears in both the JSON and the markdown
    """
    minimal_app = _minimal_probe_app()
    json_path = tmp_path / "probe.json"
    markdown_path = tmp_path / "probe.md"

    result = minimal_app.test_cli_runner().invoke(
        args=[
            "endpoints",
            "generate",
            "--output",
            str(json_path),
            "--markdown-output",
            str(markdown_path),
        ]
    )
    assert result.exit_code == 0, f"CLI failed: {result.output}"

    registry = json.loads(json_path.read_text(encoding="utf-8"))
    assert [row["endpoint"] for row in registry["endpoints"]] == [PROBE_ENDPOINT]
    assert registry["endpoints"][0]["rule"] == PROBE_RULE
    assert f"### `GET {PROBE_RULE}` — `{PROBE_ENDPOINT}`" in markdown_path.read_text(
        encoding="utf-8"
    )


def test_generate_build_registry_error_fails_without_writing(tmp_path, monkeypatch):
    """
    GIVEN a DB-free minimal Flask app whose registry build raises ValueError
    WHEN the developer runs `flask endpoints generate`
    THEN exit_code != 0, the error message is surfaced, and neither output
        file is written
    """

    def _raise_build_error(*args: object, **kwargs: object) -> dict[str, object]:
        raise ValueError("probe: boom")

    monkeypatch.setattr("backend.cli.endpoints.build_registry", _raise_build_error)
    minimal_app = _minimal_probe_app()
    json_path = tmp_path / "probe.json"
    markdown_path = tmp_path / "probe.md"

    result = minimal_app.test_cli_runner().invoke(
        args=[
            "endpoints",
            "generate",
            "--output",
            str(json_path),
            "--markdown-output",
            str(markdown_path),
        ]
    )
    assert result.exit_code != 0
    assert "probe: boom" in result.output
    assert not json_path.exists()
    assert not markdown_path.exists()


def test_generate_to_directory_output_path_fails(tmp_path):
    """
    GIVEN a DB-free minimal Flask app
    WHEN `--markdown-output` points at an existing directory
    THEN exit_code != 0, the error says the path is a directory, and the JSON
        file is not written
    """
    minimal_app = _minimal_probe_app()
    json_path = tmp_path / "probe.json"

    result = minimal_app.test_cli_runner().invoke(
        args=[
            "endpoints",
            "generate",
            "--output",
            str(json_path),
            "--markdown-output",
            str(tmp_path),
        ]
    )
    assert result.exit_code != 0
    assert "is a directory" in result.output
    assert not json_path.exists()
