/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/contact": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Submit a contact form */
    post: operations["submitContactUs"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/utubs/{utub_id}/members/{user_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** @description Remove a member from a UTub */
    delete: operations["removeMember"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/utubs/{utub_id}/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Add a member to a UTub */
    post: operations["createMember"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/metrics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Ingest a batch of UI-category metrics events from the browser */
    post: operations["ingest"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Register a new user account */
    post: operations["registerUser"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Log in to an existing account */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/send-validation-email": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Send an email validation link to the current user */
    post: operations["sendValidationEmail"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/forgot-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Send a password reset email */
    post: operations["forgotPassword"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reset-password/{token}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Reset a user password with a valid token */
    post: operations["resetPassword"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Health check endpoint. Pass ?db=true to verify all database tables exist. */
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/utubs/{utub_id}/urls": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Add a URL to a UTub */
    post: operations["createUrl"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/utubs/{utub_id}/urls/{utub_url_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Retrieve a URL from a UTub */
    get: operations["getUrl"];
    put?: never;
    post?: never;
    /** @description Delete a URL from a UTub */
    delete: operations["deleteUrl"];
    options?: never;
    head?: never;
    /** @description Update a URL string in a UTub */
    patch: operations["updateUrl"];
    trace?: never;
  };
  "/utubs/{utub_id}/urls/{utub_url_id}/title": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** @description Update a URL title in a UTub */
    patch: operations["updateUrlTitle"];
    trace?: never;
  };
  "/utubs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Retrieve a summary of all UTubs for the current user */
    get: operations["getUtubs"];
    put?: never;
    /** @description Create a new UTub */
    post: operations["createUtub"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/utubs/{utub_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Retrieve data for a single UTub */
    get: operations["getSingleUtub"];
    put?: never;
    post?: never;
    /** @description Delete a UTub */
    delete: operations["deleteUtub"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/utubs/{utub_id}/name": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** @description Update a UTub name */
    patch: operations["updateUtubName"];
    trace?: never;
  };
  "/utubs/{utub_id}/description": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** @description Update a UTub description */
    patch: operations["updateUtubDesc"];
    trace?: never;
  };
  "/utubs/{utub_id}/urls/{utub_url_id}/tags": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Add a tag to a URL in a UTub */
    post: operations["createUtubUrlTag"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/utubs/{utub_id}/urls/{utub_url_id}/tags/{utub_tag_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** @description Remove a tag from a URL in a UTub */
    delete: operations["deleteUtubUrlTag"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/utubs/{utub_id}/tags": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Add a tag to a UTub */
    post: operations["createUtubTag"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/utubs/{utub_id}/tags/{utub_tag_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** @description Delete a tag from a UTub */
    delete: operations["deleteUtubTag"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    SuccessEnvelope: {
      /**
       * @description Response status: Success, Failure, or No change
       * @enum {string}
       */
      status: "Success" | "Failure" | "No change";
      /** @description Human-readable response message, if applicable */
      message?: string;
    };
    ContactRequest: {
      /**
       * @description Subject line of the contact message
       * @example Bug report
       */
      subject: string;
      /** @description Body content of the contact message */
      content: string;
    };
    ContactResponseSchema: {
      /**
       * @description Response status: Success, Failure, or No change
       * @enum {string}
       */
      status: "Success" | "Failure" | "No change";
      /** @description Human-readable response message */
      message: string;
    };
    ErrorResponse: {
      /**
       * @description Error status, always Failure
       * @constant
       */
      status: "Failure";
      /** @description Human-readable error message */
      message: string;
      /**
       * @description Application-specific error code, if applicable
       * @default null
       */
      errorCode: number | null;
      /**
       * @description Map of field names to lists of validation error messages, if applicable
       * @default null
       */
      errors: {
        [key: string]: string[];
      } | null;
      /**
       * @description Additional error detail, if applicable
       * @default null
       */
      details: string | null;
      /**
       * @description URL string involved in the error, if applicable
       * @default null
       */
      urlString: string | null;
    };
    ErrorResponse_ContactErrorCodes: components["schemas"]["ErrorResponse"] & {
      errorCode?: components["schemas"]["ContactErrorCodes"];
    };
    /**
     * @description Error codes for ContactErrorCodes
     * @enum {integer}
     */
    ContactErrorCodes: 1;
    UserSchema: {
      /** @description Unique user ID */
      id: number;
      /** @description Username of the user */
      username: string;
    };
    MemberModifiedResponseSchema: {
      /** @description ID of the UTub the member was added to or removed from */
      utubID: number;
      /** @description User object for the member added or removed */
      member: components["schemas"]["UserSchema"];
    };
    AddMemberRequest: {
      /** @description Username of the member to add */
      username: string;
    };
    ErrorResponse_UTubMembersErrorCodes: components["schemas"]["ErrorResponse"] & {
      errorCode?: components["schemas"]["UTubMembersErrorCodes"];
    };
    /**
     * @description Error codes for UTubMembersErrorCodes
     * @enum {integer}
     */
    UTubMembersErrorCodes: 1 | 2;
    /**
     * @description One UI metrics event submitted by the browser.
     *
     *     Per-event dimension validation lives at the route layer
     *     (`validate_dimensions(...)`) — not in a `@model_validator` here. Pydantic
     *     v2 wraps `ValueError`/`AssertionError` raised inside validators, but a
     *     `ValidationError` raised inside a validator does NOT round-trip cleanly
     *     through that wrapper, so dimension shape checks happen post-decoration.
     */
    MetricsIngestEvent: {
      /**
       * @description UI-category EventName value emitted by the browser
       * @enum {string}
       */
      event_name:
        | "ui_utub_select"
        | "ui_utub_create_open"
        | "ui_utub_delete_confirm"
        | "ui_utub_name_edit_open"
        | "ui_utub_desc_edit_open"
        | "ui_url_access"
        | "ui_url_card_click"
        | "ui_url_create_open"
        | "ui_url_title_edit_open"
        | "ui_url_string_edit_open"
        | "ui_url_delete_confirm"
        | "ui_url_copy"
        | "ui_url_access_warning"
        | "ui_search_open"
        | "ui_search_close"
        | "ui_tag_apply"
        | "ui_tag_remove"
        | "ui_tag_create_open"
        | "ui_tag_delete_confirm"
        | "ui_tag_filter_toggle"
        | "ui_member_invite_open"
        | "ui_member_remove_confirm"
        | "ui_member_leave_confirm"
        | "ui_form_submit"
        | "ui_form_cancel"
        | "ui_validation_error"
        | "ui_deck_collapse"
        | "ui_deck_expand"
        | "ui_navbar_mobile_menu_open"
        | "ui_mobile_nav"
        | "ui_login_submit"
        | "ui_register_submit"
        | "ui_forgot_password_submit"
        | "ui_auth_form_switch"
        | "ui_rate_limit_hit";
      /**
       * @description Optional per-event dimension dict; shape enforced server-side via the matching `_Dim<EventName>` Pydantic model
       * @default null
       */
      dimensions: {
        [key: string]: string | number | boolean;
      } | null;
    };
    /** @description Top-level batch payload for `POST /api/metrics`. */
    MetricsIngestRequest: {
      /** @description Batch of UI-category metrics events to ingest (1-100 entries) */
      events: components["schemas"]["MetricsIngestEvent"][];
      /**
       * @description Client-generated batch identifier; used server-side for SET NX EX idempotency on retries
       * @default null
       */
      batch_id: string | null;
      /**
       * @description Optional CSRF token in the JSON body for navigator.sendBeacon callers that cannot set headers
       * @default null
       */
      csrf_token: string | null;
    };
    /**
     * @description Response payload returned by `POST /api/metrics`.
     *
     *     `accepted` is the number of events that the route handed off to
     *     `record_event(...)`. Because the writer is log-and-drop, individual events
     *     may have been silently dropped at the Redis layer; the field is informative
     *     but not authoritative.
     */
    MetricsIngestResponseSchema: {
      /**
       * @description Count of events accepted by the metrics ingest endpoint
       * @default 0
       */
      accepted: number;
    };
    ErrorResponse_MetricsErrorCodes: components["schemas"]["ErrorResponse"] & {
      errorCode?: components["schemas"]["MetricsErrorCodes"];
    };
    /**
     * @description Error codes for MetricsErrorCodes
     * @enum {integer}
     */
    MetricsErrorCodes: 1;
    RegisterRequest: {
      /**
       * @description Username for the new account
       * @example john_doe
       */
      username: string;
      /**
       * Format: email
       * @description Email address for the new account
       * @example user@example.com
       */
      email: string;
      /** @description Email confirmation, must match email */
      confirmEmail: string;
      /** @description Password for the new account */
      password: string;
      /** @description Password confirmation, must match password */
      confirmPassword: string;
    };
    RegisterResponseSchema: {
      /**
       * @description Response status: Success, Failure, or No change
       * @enum {string}
       */
      status: "Success" | "Failure" | "No change";
      /** @description Human-readable response message */
      message: string;
    };
    ErrorResponse_RegisterErrorCodes: components["schemas"]["ErrorResponse"] & {
      errorCode?: components["schemas"]["RegisterErrorCodes"];
    };
    /**
     * @description Error codes for RegisterErrorCodes
     * @enum {integer}
     */
    RegisterErrorCodes: 1 | 2;
    LoginRequest: {
      /**
       * @description Username for login
       * @example john_doe
       */
      username: string;
      /** @description Password for login */
      password: string;
    };
    /** @description Login successful with redirect URL */
    LoginRedirectResponseSchema: {
      /** @description URL to redirect to after login */
      redirectUrl: string;
    };
    ErrorResponse_LoginErrorCodes: components["schemas"]["ErrorResponse"] & {
      errorCode?: components["schemas"]["LoginErrorCodes"];
    };
    /**
     * @description Error codes for LoginErrorCodes
     * @enum {integer}
     */
    LoginErrorCodes: 1 | 2;
    EmailValidationResponseSchema: {
      /**
       * @description Response status: Success, Failure, or No change
       * @enum {string}
       */
      status: "Success" | "Failure" | "No change";
      /** @description Human-readable response message */
      message: string;
    };
    ForgotPasswordRequest: {
      /**
       * Format: email
       * @description Email address associated with the account
       * @example user@example.com
       */
      email: string;
    };
    ForgotPasswordResponseSchema: {
      /**
       * @description Response status: Success, Failure, or No change
       * @enum {string}
       */
      status: "Success" | "Failure" | "No change";
      /** @description Human-readable response message */
      message: string;
    };
    ErrorResponse_ForgotPasswordErrorCodes: components["schemas"]["ErrorResponse"] & {
      errorCode?: components["schemas"]["ForgotPasswordErrorCodes"];
    };
    /**
     * @description Error codes for ForgotPasswordErrorCodes
     * @enum {integer}
     */
    ForgotPasswordErrorCodes: 1 | 3;
    ResetPasswordRequest: {
      /** @description New password for the account */
      newPassword: string;
      /** @description New password confirmation, must match new password */
      confirmNewPassword: string;
    };
    ResetPasswordResponseSchema: {
      /**
       * @description Response status: Success, Failure, or No change
       * @enum {string}
       */
      status: "Success" | "Failure" | "No change";
      /** @description Human-readable response message */
      message: string;
    };
    ErrorResponse_ResetPasswordErrorCodes: components["schemas"]["ErrorResponse"] & {
      errorCode?: components["schemas"]["ResetPasswordErrorCodes"];
    };
    /**
     * @description Error codes for ResetPasswordErrorCodes
     * @enum {integer}
     */
    ResetPasswordErrorCodes: 1;
    HealthResponseSchema: {
      /** @description Service health status */
      status: string;
    };
    /** @description Status and message response */
    StatusMessageResponseSchema: {
      /**
       * @description Response status: Success, Failure, or No change
       * @enum {string}
       */
      status: "Success" | "Failure" | "No change";
      /** @description Human-readable response message */
      message: string;
    };
    CreateURLRequest: {
      /**
       * @description URL string to add
       * @example https://example.com
       */
      urlString: string;
      /** @description Display title for the URL */
      urlTitle: string;
    };
    /** @description URL item shape for creation responses (same fields as UtubUrlDeleteSchema). */
    UrlCreatedItemSchema: {
      /** @description Unique ID of the URL within the UTub */
      utubUrlID: number;
      /** @description The URL string */
      urlString: string;
      /** @description Display title for the URL */
      urlTitle: string;
    };
    UrlCreatedResponseSchema: {
      /** @description ID of the UTub the URL was added to */
      utubID: number;
      /** @description User ID of the user who added the URL */
      addedByUserID: number;
      /** @description URL item that was created */
      URL: components["schemas"]["UrlCreatedItemSchema"];
    };
    ErrorResponse_URLErrorCodes: components["schemas"]["ErrorResponse"] & {
      errorCode?: components["schemas"]["URLErrorCodes"];
    };
    /**
     * @description Error codes for URLErrorCodes
     * @enum {integer}
     */
    URLErrorCodes: 1 | 2 | 3 | 4 | 5 | 6 | 7;
    UtubTagOnAddDeleteSchema: {
      /** @description Unique tag ID within the UTub */
      utubTagID: number;
      /** @description Tag label text */
      tagString: string;
    };
    UtubUrlDetailSchema: {
      /** @description Unique ID of the URL within the UTub */
      utubUrlID: number;
      /** @description Display title for the URL */
      urlTitle: string;
      /** @description The URL string */
      urlString: string;
      /** @description List of tags applied to this URL */
      urlTags: components["schemas"]["UtubTagOnAddDeleteSchema"][];
    };
    UrlReadResponseSchema: {
      /** @description Detailed URL item retrieved */
      URL: components["schemas"]["UtubUrlDetailSchema"];
    };
    UpdateURLStringRequest: {
      /**
       * @description New URL string to replace the existing one
       * @example https://example.com
       */
      urlString: string;
    };
    UrlUpdatedResponseSchema: {
      /** @description ID of the UTub containing the URL */
      utubID: number;
      /** @description Name of the UTub containing the URL */
      utubName: string;
      /** @description Detailed URL item with updated URL string */
      URL: components["schemas"]["UtubUrlDetailSchema"];
    };
    UpdateURLTitleRequest: {
      /** @description New display title for the URL */
      urlTitle: string;
    };
    UrlTitleUpdatedResponseSchema: {
      /** @description Detailed URL item with updated title */
      URL: components["schemas"]["UtubUrlDetailSchema"];
    };
    UtubUrlDeleteSchema: {
      /** @description Unique ID of the URL within the UTub */
      utubUrlID: number;
      /** @description The URL string */
      urlString: string;
      /** @description Display title for the URL */
      urlTitle: string;
    };
    UrlDeletedResponseSchema: {
      /** @description ID of the UTub the URL was deleted from */
      utubID: number;
      /** @description URL item that was deleted */
      URL: components["schemas"]["UtubUrlDeleteSchema"];
      /** @description Map of tag ID to new applied count after deletion */
      tagCountsInUtub: {
        [key: string]: number;
      };
    };
    CreateUTubRequest: {
      /** @description Name of the UTub to create */
      utubName: string;
      /**
       * @description Optional description for the UTub
       * @default null
       */
      utubDescription: string | null;
    };
    UtubCreatedResponseSchema: {
      /** @description Unique ID of the newly created UTub */
      utubID: number;
      /** @description Name of the newly created UTub */
      utubName: string;
      /** @description Description of the newly created UTub, or null if not set */
      utubDescription: string | null;
      /** @description User ID of the UTub creator */
      utubCreatorID: number;
    };
    ErrorResponse_UTubErrorCodes: components["schemas"]["ErrorResponse"] & {
      errorCode?: components["schemas"]["UTubErrorCodes"];
    };
    /**
     * @description Error codes for UTubErrorCodes
     * @enum {integer}
     */
    UTubErrorCodes: 1 | 2;
    UtubTagSchema: {
      /** @description Unique tag ID within the UTub */
      id: number;
      /** @description Tag label text */
      tagString: string;
      /**
       * @description Number of URLs in the UTub this tag is applied to
       * @default 0
       */
      tagApplied: number;
    };
    UtubUrlSchema: {
      /** @description Unique ID of the URL within the UTub */
      utubUrlID: number;
      /** @description The URL string */
      urlString: string;
      /** @description List of tag IDs applied to this URL */
      utubUrlTagIDs: number[];
      /** @description Display title for the URL */
      urlTitle: string;
      /** @description Whether the current user can delete this URL */
      canDelete: boolean;
    };
    /** @description Full UTub detail with members, URLs, and tags */
    UtubDetailSchema: {
      /** @description Unique UTub ID */
      id: number;
      /** @description Name of the UTub */
      name: string;
      /** @description User ID of the UTub creator */
      createdByUserID: number;
      /**
       * Format: date-time
       * @description Creation timestamp of the UTub (ISO 8601)
       */
      createdAt: string;
      /** @description Description of the UTub */
      description: string;
      /** @description List of members in the UTub */
      members: components["schemas"]["UserSchema"][];
      /** @description List of URLs in the UTub */
      urls: components["schemas"]["UtubUrlSchema"][];
      /** @description List of tags used in the UTub */
      tags: components["schemas"]["UtubTagSchema"][];
      /** @description Whether the current user is the creator of the UTub */
      isCreator: boolean;
      /** @description ID of the currently authenticated user */
      currentUser: number;
    };
    UtubSummaryItemSchema: {
      /** @description Unique UTub ID */
      id: number;
      /** @description Name of the UTub */
      name: string;
      /** @description Role of the current user in the UTub */
      memberRole: string;
    };
    /** @description List of UTub summaries */
    UtubSummaryListSchema: {
      /** @description List of UTubs the user is a member of */
      utubs: components["schemas"]["UtubSummaryItemSchema"][];
    };
    UpdateUTubNameRequest: {
      /** @description New name for the UTub */
      utubName: string;
    };
    UtubNameUpdatedResponseSchema: {
      /** @description ID of the UTub whose name was updated */
      utubID: number;
      /** @description New name of the UTub */
      utubName: string;
    };
    UpdateUTubDescriptionRequest: {
      /**
       * @description New description for the UTub, or empty to clear
       * @default null
       */
      utubDescription: string | null;
    };
    /** @description UTub description updated */
    UtubDescUpdatedResponseSchema: {
      /** @description ID of the UTub whose description was updated */
      utubID: number;
      /** @description New description of the UTub, or null if cleared */
      utubDescription: string | null;
    };
    UtubDeletedResponseSchema: {
      /** @description ID of the deleted UTub */
      utubID: number;
      /** @description Name of the deleted UTub */
      utubName: string;
      /** @description Description of the deleted UTub, or null if not set */
      utubDescription: string | null;
    };
    AddTagRequest: {
      /**
       * @description Tag label to add
       * @example python
       */
      tagString: string;
    };
    UrlTagModifiedResponseSchema: {
      /** @description Updated list of tag IDs applied to the URL */
      utubUrlTagIDs: number[];
      /** @description Tag that was added or removed from the URL */
      utubTag: components["schemas"]["UtubTagOnAddDeleteSchema"];
      /** @description New count of URLs this tag is applied to after modification */
      tagCountsInUtub: number;
    };
    ErrorResponse_URLTagErrorCodes: components["schemas"]["ErrorResponse"] & {
      errorCode?: components["schemas"]["URLTagErrorCodes"];
    };
    /**
     * @description Error codes for URLTagErrorCodes
     * @enum {integer}
     */
    URLTagErrorCodes: 1 | 2;
    UtubTagAddedToUtubResponseSchema: {
      /** @description Tag that was added to the UTub */
      utubTag: components["schemas"]["UtubTagOnAddDeleteSchema"];
      /** @description New count of URLs this tag is applied to after addition */
      tagCountsInUtub: number;
    };
    ErrorResponse_UTubTagErrorCodes: components["schemas"]["ErrorResponse"] & {
      errorCode?: components["schemas"]["UTubTagErrorCodes"];
    };
    /**
     * @description Error codes for UTubTagErrorCodes
     * @enum {integer}
     */
    UTubTagErrorCodes: 1 | 2;
    UtubTagDeletedFromUtubResponseSchema: {
      /** @description Tag that was deleted from the UTub */
      utubTag: components["schemas"]["UtubTagOnAddDeleteSchema"];
      /** @description List of URL IDs that had this tag removed */
      utubUrlIDs: number[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  submitContactUs: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ContactRequest"];
      };
    };
    responses: {
      /** @description Contact */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContactResponseSchema"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse_ContactErrorCodes"];
        };
      };
    };
  };
  removeMember: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        utub_id: number;
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Member modified */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessEnvelope"] &
            components["schemas"]["MemberModifiedResponseSchema"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createMember: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        utub_id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["AddMemberRequest"];
      };
    };
    responses: {
      /** @description Member modified */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessEnvelope"] &
            components["schemas"]["MemberModifiedResponseSchema"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse_UTubMembersErrorCodes"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  ingest: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["MetricsIngestRequest"];
      };
    };
    responses: {
      /**
       * @description Response payload returned by `POST /api/metrics`.
       *
       *         `accepted` is the number of events that the route handed off to
       *         `record_event(...)`. Because the writer is log-and-drop, individual events
       *         may have been silently dropped at the Redis layer; the field is informative
       *         but not authoritative.
       */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessEnvelope"] &
            components["schemas"]["MetricsIngestResponseSchema"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse_MetricsErrorCodes"];
        };
      };
    };
  };
  registerUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description Register */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RegisterResponseSchema"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse_RegisterErrorCodes"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Login successful with redirect URL */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessEnvelope"] &
            components["schemas"]["LoginRedirectResponseSchema"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse_LoginErrorCodes"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  sendValidationEmail: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Email validation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmailValidationResponseSchema"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Too many requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  forgotPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ForgotPasswordRequest"];
      };
    };
    responses: {
      /** @description Forgot password */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ForgotPasswordResponseSchema"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse_ForgotPasswordErrorCodes"];
        };
      };
    };
  };
  resetPassword: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ResetPasswordRequest"];
      };
    };
    responses: {
      /** @description Reset password */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResetPasswordResponseSchema"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse_ResetPasswordErrorCodes"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Health */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponseSchema"];
        };
      };
      /** @description Service unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatusMessageResponseSchema"];
        };
      };
    };
  };
  createUrl: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        utub_id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["CreateURLRequest"];
      };
    };
    responses: {
      /** @description URL created */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessEnvelope"] &
            components["schemas"]["UrlCreatedResponseSchema"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse_URLErrorCodes"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse_URLErrorCodes"];
        };
      };
    };
  };
  getUrl: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        utub_id: number;
        utub_url_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description URL read */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessEnvelope"] &
            components["schemas"]["UrlReadResponseSchema"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  deleteUrl: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        utub_id: number;
        utub_url_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description URL deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessEnvelope"] &
            components["schemas"]["UrlDeletedResponseSchema"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateUrl: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        utub_id: number;
        utub_url_id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["UpdateURLStringRequest"];
      };
    };
    responses: {
      /** @description URL updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessEnvelope"] &
            components["schemas"]["UrlUpdatedResponseSchema"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse_URLErrorCodes"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse_URLErrorCodes"];
        };
      };
    };
  };
  updateUrlTitle: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        utub_id: number;
        utub_url_id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["UpdateURLTitleRequest"];
      };
    };
    responses: {
      /** @description URL title updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessEnvelope"] &
            components["schemas"]["UrlTitleUpdatedResponseSchema"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse_URLErrorCodes"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getUtubs: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of UTub summaries */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessEnvelope"] &
            components["schemas"]["UtubSummaryListSchema"];
        };
      };
    };
  };
  createUtub: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["CreateUTubRequest"];
      };
    };
    responses: {
      /** @description UTub created */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessEnvelope"] &
            components["schemas"]["UtubCreatedResponseSchema"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse_UTubErrorCodes"];
        };
      };
    };
  };
  getSingleUtub: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        utub_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Full UTub detail with members, URLs, and tags */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessEnvelope"] &
            components["schemas"]["UtubDetailSchema"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  deleteUtub: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        utub_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description UTub deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessEnvelope"] &
            components["schemas"]["UtubDeletedResponseSchema"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateUtubName: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        utub_id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["UpdateUTubNameRequest"];
      };
    };
    responses: {
      /** @description UTub name updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessEnvelope"] &
            components["schemas"]["UtubNameUpdatedResponseSchema"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse_UTubErrorCodes"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateUtubDesc: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        utub_id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["UpdateUTubDescriptionRequest"];
      };
    };
    responses: {
      /** @description UTub description updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessEnvelope"] &
            components["schemas"]["UtubDescUpdatedResponseSchema"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse_UTubErrorCodes"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createUtubUrlTag: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        utub_id: number;
        utub_url_id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["AddTagRequest"];
      };
    };
    responses: {
      /** @description URL tag modified */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessEnvelope"] &
            components["schemas"]["UrlTagModifiedResponseSchema"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse_URLTagErrorCodes"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  deleteUtubUrlTag: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        utub_id: number;
        utub_url_id: number;
        utub_tag_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description URL tag modified */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessEnvelope"] &
            components["schemas"]["UrlTagModifiedResponseSchema"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createUtubTag: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        utub_id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["AddTagRequest"];
      };
    };
    responses: {
      /** @description UTub tag added to UTub */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessEnvelope"] &
            components["schemas"]["UtubTagAddedToUtubResponseSchema"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse_UTubTagErrorCodes"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  deleteUtubTag: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        utub_id: number;
        utub_tag_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description UTub tag deleted from UTub */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessEnvelope"] &
            components["schemas"]["UtubTagDeletedFromUtubResponseSchema"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
