// Generated by `flask metrics generate-resources` — DO NOT EDIT.
// Source of truth: backend/metrics/resources.py
//
// Resource taxonomy for the admin metrics dashboard's top-events filter. Each
// `RESOURCES` key mirrors a `Resource` enum member; the value is the wire
// string the backend Pydantic validator expects.
//
// `RESOURCES_BY_CATEGORY` lists, per `EventCategory`, the resources that can
// appear on that dashboard tab. Cross-category pairs (e.g. `category=domain`
// with `resource=auth`) are rejected at the schema layer.

export const RESOURCES = {
  UTUB: "utub",
  URL: "url",
  TAG: "tag",
  MEMBER: "member",
  AUTH: "auth",
  SEARCH: "search",
  FORM: "form",
  DECK: "deck",
  NAV: "nav",
  ERROR: "error",
  CONTACT: "contact",
  ADMIN: "admin",
  OTHER: "other",
} as const;

export type ResourceName = (typeof RESOURCES)[keyof typeof RESOURCES];

export const RESOURCES_BY_CATEGORY = {
  api: [
    "utub",
    "url",
    "tag",
    "member",
    "auth",
    "admin",
    "contact",
    "other",
  ] as const,
  domain: ["utub", "url", "tag", "member", "auth"] as const,
  ui: [
    "utub",
    "url",
    "search",
    "tag",
    "member",
    "form",
    "error",
    "deck",
    "nav",
    "auth",
    "contact",
  ] as const,
} as const;
