// Generated by `flask metrics generate-flows` — DO NOT EDIT.
// Source of truth: backend/metrics/flows.py
//
// Admin-dashboard conversion-funnel ("flow") display metadata. `FLOW_IDS`
// mirrors the `FlowId` StrEnum; `FLOW_METADATA` carries each flow's display
// name and ordered, variable-length `stepLabels` (one entry per `FlowStep`,
// in funnel order). The funnel-card renderer pairs these labels with the
// per-step counts returned by `GET /api/metrics/query/flow`.

export const FLOW_IDS = {
  CREATE_UTUB: "create_utub",
  ADD_URL_TO_UTUB: "add_url_to_utub",
  REGISTER: "register",
  LOGIN: "login",
} as const;

export type FlowId = (typeof FLOW_IDS)[keyof typeof FLOW_IDS];

export const FLOW_METADATA = {
  create_utub: {
    displayName: "Create UTub",
    stepLabels: [
      "Open UTub form",
      "Submit",
      "POST /utubs",
      "UTub created",
    ] as const,
  },
  add_url_to_utub: {
    displayName: "Add URL to UTub",
    stepLabels: [
      "Open URL form",
      "Submit",
      "POST .../urls",
      "URL added",
    ] as const,
  },
  register: {
    displayName: "Register",
    stepLabels: [
      "Open register form",
      "Submit",
      "POST /register",
      "Registered",
    ] as const,
  },
  login: {
    displayName: "Login",
    stepLabels: [
      "Open login form",
      "Submit",
      "POST /login",
      "Logged in",
    ] as const,
  },
} as const satisfies Record<
  FlowId,
  {
    displayName: string;
    stepLabels: readonly string[];
  }
>;
