// Generated by `flask metrics generate-dim-types` — DO NOT EDIT.
// Source of truth: backend/metrics/dimension_models.py
//
// Per-event dimension shapes mirrored from the Pydantic `_Dim<Event>` models.
// Frontend `emit()` narrows its second argument against `UIEventDimensions[E]`
// so any literal that drifts from the backend Pydantic literal fails to compile.

export type SearchActive = "true" | "false";

export type TagScope = "utub" | "url";

export type HomeForm =
  | "url_create"
  | "url_title_edit"
  | "url_string_edit"
  | "utub_create"
  | "utub_name_edit"
  | "utub_desc_edit"
  | "tag_create"
  | "member_invite";

export type ValidationForm =
  | "url_create"
  | "url_title_edit"
  | "url_string_edit"
  | "utub_create"
  | "utub_name_edit"
  | "utub_desc_edit"
  | "tag_create"
  | "member_invite"
  | "login"
  | "register"
  | "forgot_password"
  | "reset_password"
  | "email_validation";

export type DimUtubSelect = {
  device_type: 1 | 2;
  search_active: "true" | "false";
};

export type DimDeviceOnly = {
  device_type: 1 | 2;
};

export type DimUtubNameEditOpen = {
  device_type: 1 | 2;
  trigger: "pencil_icon" | "keyboard";
};

export type DimUtubDescEditOpen = {
  device_type: 1 | 2;
  trigger: "pencil_icon" | "keyboard" | "create_button";
};

export type DimUrlAccess = {
  device_type: 1 | 2;
  trigger: "corner_button" | "url_text" | "main_button";
  search_active: "true" | "false";
  active_tag_count: number;
};

export type DimUrlCardClick = {
  device_type: 1 | 2;
  search_active: "true" | "false";
  active_tag_count: number;
};

export type DimUrlCopy = {
  device_type: 1 | 2;
  result: "success" | "failure";
};

export type DimSearchOpen = {
  device_type: 1 | 2;
  target: "utubs" | "urls";
};

export type DimSearchClose = {
  device_type: 1 | 2;
  target: "utubs" | "urls";
};

export type DimTagCreateOpen = {
  device_type: 1 | 2;
  scope: "utub" | "url";
};

export type DimTagDeleteOpen = {
  device_type: 1 | 2;
  scope: "utub" | "url";
};

export type DimTagDeleteConfirm = {
  device_type: 1 | 2;
  scope: "utub" | "url";
};

export type DimTagDeleteCancel = {
  device_type: 1 | 2;
  scope: "utub" | "url";
};

export type DimFormSubmit = {
  device_type: 1 | 2;
  trigger: "enter_key" | "button_click";
  form:
    | "url_create"
    | "url_title_edit"
    | "url_string_edit"
    | "utub_create"
    | "utub_name_edit"
    | "utub_desc_edit"
    | "tag_create"
    | "member_invite";
};

export type DimFormCancel = {
  device_type: 1 | 2;
  trigger: "escape_key" | "cancel_button" | "outside_click";
  form:
    | "url_create"
    | "url_title_edit"
    | "url_string_edit"
    | "utub_create"
    | "utub_name_edit"
    | "utub_desc_edit"
    | "tag_create"
    | "member_invite";
};

export type DimValidationError = {
  device_type: 1 | 2;
  form:
    | "url_create"
    | "url_title_edit"
    | "url_string_edit"
    | "utub_create"
    | "utub_name_edit"
    | "utub_desc_edit"
    | "tag_create"
    | "member_invite"
    | "login"
    | "register"
    | "forgot_password"
    | "reset_password"
    | "email_validation";
};

export type DimDeckCollapse = {
  device_type: 1 | 2;
  deck: "members" | "tags" | "utubs";
};

export type DimDeckExpand = {
  device_type: 1 | 2;
  deck: "members" | "tags" | "utubs";
};

export type DimMobileNav = {
  device_type: 1 | 2;
  target: "utubs" | "urls" | "members" | "tags";
};

export type DimAuthFormSwitch = {
  device_type: 1 | 2;
  target: "login" | "register" | "forgot_password";
};

export type DimAuthModalOpen = {
  device_type: 1 | 2;
  form: "login" | "register";
};

export type DimEmailValidationSubmit = {
  device_type: 1 | 2;
  trigger: "manual_click" | "auto_after_register";
};

export type UIEventDimensions = {
  ui_utub_select: DimUtubSelect;
  ui_utub_create_open: DimDeviceOnly;
  ui_utub_delete_open: DimDeviceOnly;
  ui_utub_delete_confirm: DimDeviceOnly;
  ui_utub_delete_cancel: DimDeviceOnly;
  ui_utub_name_edit_open: DimUtubNameEditOpen;
  ui_utub_desc_edit_open: DimUtubDescEditOpen;
  ui_url_access: DimUrlAccess;
  ui_url_card_click: DimUrlCardClick;
  ui_url_create_open: DimDeviceOnly;
  ui_url_title_edit_open: DimDeviceOnly;
  ui_url_string_edit_open: DimDeviceOnly;
  ui_url_delete_open: DimDeviceOnly;
  ui_url_delete_confirm: DimDeviceOnly;
  ui_url_delete_cancel: DimDeviceOnly;
  ui_url_copy: DimUrlCopy;
  ui_url_access_warning: DimDeviceOnly;
  ui_url_access_warning_dismiss: DimDeviceOnly;
  ui_search_open: DimSearchOpen;
  ui_search_close: DimSearchClose;
  ui_tag_apply: DimDeviceOnly;
  ui_tag_remove: DimDeviceOnly;
  ui_tag_create_open: DimTagCreateOpen;
  ui_tag_delete_open: DimTagDeleteOpen;
  ui_tag_delete_confirm: DimTagDeleteConfirm;
  ui_tag_delete_cancel: DimTagDeleteCancel;
  ui_tag_filter_toggle: DimDeviceOnly;
  ui_member_invite_open: DimDeviceOnly;
  ui_member_remove_open: DimDeviceOnly;
  ui_member_remove_confirm: DimDeviceOnly;
  ui_member_remove_cancel: DimDeviceOnly;
  ui_member_leave_open: DimDeviceOnly;
  ui_member_leave_confirm: DimDeviceOnly;
  ui_member_leave_cancel: DimDeviceOnly;
  ui_form_submit: DimFormSubmit;
  ui_form_cancel: DimFormCancel;
  ui_validation_error: DimValidationError;
  ui_deck_collapse: DimDeckCollapse;
  ui_deck_expand: DimDeckExpand;
  ui_navbar_mobile_menu_open: DimDeviceOnly;
  ui_navbar_mobile_menu_close: DimDeviceOnly;
  ui_mobile_nav: DimMobileNav;
  ui_login_submit: DimDeviceOnly;
  ui_register_submit: DimDeviceOnly;
  ui_forgot_password_submit: DimDeviceOnly;
  ui_auth_form_switch: DimAuthFormSwitch;
  ui_auth_modal_open: DimAuthModalOpen;
  ui_reset_password_submit: DimDeviceOnly;
  ui_email_validation_submit: DimEmailValidationSubmit;
  ui_contact_submit: DimDeviceOnly;
  ui_error_page_refresh: DimDeviceOnly;
  ui_rate_limit_hit: DimDeviceOnly;
};
