// Generated by `flask metrics generate-dim-values` — DO NOT EDIT.
// Source of truth: backend/metrics/dimension_models.py
//
// Runtime constants for every dim-value Literal alias and IntEnum referenced by
// the Pydantic `_Dim<Event>` models. Use these constants at every `emit()` call
// site and test assertion so there is a single source of truth for every dim
// value, locked to Pydantic via codegen, available at both compile time AND
// runtime for query-service and dashboard consumption.

export const SEARCH_ACTIVE = {
  TRUE: "true",
  FALSE: "false",
} as const;

export type SearchActive = (typeof SEARCH_ACTIVE)[keyof typeof SEARCH_ACTIVE];

export const TAG_SCOPE = {
  UTUB: "utub",
  URL: "url",
} as const;

export type TagScope = (typeof TAG_SCOPE)[keyof typeof TAG_SCOPE];

export const HOME_FORM = {
  URL_CREATE: "url_create",
  URL_TITLE_EDIT: "url_title_edit",
  URL_STRING_EDIT: "url_string_edit",
  UTUB_CREATE: "utub_create",
  UTUB_NAME_EDIT: "utub_name_edit",
  UTUB_DESC_EDIT: "utub_desc_edit",
  TAG_CREATE: "tag_create",
  MEMBER_INVITE: "member_invite",
} as const;

export type HomeForm = (typeof HOME_FORM)[keyof typeof HOME_FORM];

export const VALIDATION_FORM = {
  URL_CREATE: "url_create",
  URL_TITLE_EDIT: "url_title_edit",
  URL_STRING_EDIT: "url_string_edit",
  UTUB_CREATE: "utub_create",
  UTUB_NAME_EDIT: "utub_name_edit",
  UTUB_DESC_EDIT: "utub_desc_edit",
  TAG_CREATE: "tag_create",
  MEMBER_INVITE: "member_invite",
  LOGIN: "login",
  REGISTER: "register",
  FORGOT_PASSWORD: "forgot_password",
  RESET_PASSWORD: "reset_password",
  EMAIL_VALIDATION: "email_validation",
} as const;

export type ValidationForm =
  (typeof VALIDATION_FORM)[keyof typeof VALIDATION_FORM];

/**
 * Device type emitted with every UI event. Values match the
 * `DeviceType` IntEnum in `backend/metrics/events.py`. The derived
 * `DeviceType` type below makes this const the single source of
 * truth for both the runtime values and the compile-time type.
 */
export const DEVICE_TYPE = {
  MOBILE: 1,
  DESKTOP: 2,
} as const;

export type DeviceType = (typeof DEVICE_TYPE)[keyof typeof DEVICE_TYPE];

export const AUTH_CANCEL_FORM = {
  LOGIN: "login",
  REGISTER: "register",
} as const;

export const AUTH_CANCEL_TRIGGER = {
  NAVIGATION: "navigation",
} as const;

export const AUTH_FORM_SWITCH_TARGET = {
  LOGIN: "login",
  REGISTER: "register",
  FORGOT_PASSWORD: "forgot_password",
} as const;

export const AUTH_MODAL_OPEN_FORM = AUTH_CANCEL_FORM;

export const CROSS_UTUB_SEARCH_CLOSE_TARGET = {
  CROSS_UTUB: "cross_utub",
} as const;

export const CROSS_UTUB_SEARCH_CLOSE_TRIGGER = {
  TRIGGER_ICON: "trigger_icon",
  ESCAPE_KEY: "escape_key",
  RETURN_HOME: "return_home",
  DECK_SWITCH: "deck_switch",
  RESULT_NAV: "result_nav",
  HISTORY_NAV: "history_nav",
} as const;

export const CROSS_UTUB_SEARCH_OPEN_TARGET = CROSS_UTUB_SEARCH_CLOSE_TARGET;

export const CROSS_UTUB_SEARCH_REFRESH_TARGET = CROSS_UTUB_SEARCH_CLOSE_TARGET;

export const CROSS_UTUB_SEARCH_RESULT_ACCESS_TARGET =
  CROSS_UTUB_SEARCH_CLOSE_TARGET;

export const CROSS_UTUB_SEARCH_RESULT_ACCESS_TRIGGER = {
  URL_TEXT: "url_text",
  CORNER_BUTTON: "corner_button",
} as const;

export const DECK_COLLAPSE_DECK = {
  MEMBERS: "members",
  TAGS: "tags",
  UTUBS: "utubs",
} as const;

export const DECK_EXPAND_DECK = DECK_COLLAPSE_DECK;

export const EMAIL_VALIDATION_SUBMIT_TRIGGER = {
  MANUAL_CLICK: "manual_click",
  AUTO_AFTER_REGISTER: "auto_after_register",
} as const;

export const FORM_CANCEL_TRIGGER = {
  ESCAPE_KEY: "escape_key",
  CANCEL_BUTTON: "cancel_button",
  OUTSIDE_CLICK: "outside_click",
  NAVIGATION: "navigation",
} as const;

export const FORM_SUBMIT_TRIGGER = {
  ENTER_KEY: "enter_key",
  BUTTON_CLICK: "button_click",
} as const;

export const LHS_COLLAPSE_SOURCE = {
  SEAM: "seam",
  URL_HEADER: "url_header",
} as const;

export const LHS_EXPAND_SOURCE = LHS_COLLAPSE_SOURCE;

export const MEMBER_SEARCH_CLOSE_TARGET = {
  MEMBERS: "members",
} as const;

export const MEMBER_SEARCH_OPEN_TARGET = MEMBER_SEARCH_CLOSE_TARGET;

export const MOBILE_NAV_TARGET = {
  UTUBS: "utubs",
  URLS: "urls",
  MEMBERS: "members",
  TAGS: "tags",
} as const;

export const MOBILE_NAV_TRIGGER = {
  TAP: "tap",
  HISTORY_NAV: "history_nav",
} as const;

export const TAG_SEARCH_CLOSE_TARGET = {
  TAGS: "tags",
} as const;

export const TAG_SEARCH_OPEN_TARGET = TAG_SEARCH_CLOSE_TARGET;

export const TAG_SHEET_TOGGLE_ACTION = {
  OPEN: "open",
  CLOSE: "close",
} as const;

export const URL_ACCESS_TRIGGER = {
  CORNER_BUTTON: "corner_button",
  URL_TEXT: "url_text",
  MAIN_BUTTON: "main_button",
} as const;

export const URL_COPY_RESULT = {
  SUCCESS: "success",
  FAILURE: "failure",
} as const;

export const URL_SEARCH_CLOSE_TARGET = {
  URLS: "urls",
} as const;

export const URL_SEARCH_OPEN_TARGET = URL_SEARCH_CLOSE_TARGET;

export const UTUB_DESC_EDIT_OPEN_TRIGGER = {
  PENCIL_ICON: "pencil_icon",
  KEYBOARD: "keyboard",
  CREATE_BUTTON: "create_button",
} as const;

export const UTUB_NAME_EDIT_OPEN_TRIGGER = {
  PENCIL_ICON: "pencil_icon",
  KEYBOARD: "keyboard",
} as const;

export const UTUB_SEARCH_CLOSE_TARGET = {
  UTUBS: "utubs",
} as const;

export const UTUB_SEARCH_OPEN_TARGET = UTUB_SEARCH_CLOSE_TARGET;
