// Generated by `flask metrics generate-dim-types` — DO NOT EDIT.
// Source of truth: backend/metrics/dimension_models.py
//
// Per-event dimension shapes mirrored from the Pydantic `_Dim<Event>` models.
// Frontend `emit()` narrows its second argument against `UIEventDimensions[E]`
// so any literal that drifts from the backend Pydantic literal fails to compile.
//
// The named `DeviceType`/`HomeForm`/`ValidationForm`/`SearchActive`/`TagScope`
// aliases are imported from `./metrics-dim-values.js` so the runtime const and
// the compile-time type share a single source of truth (the const object).

import type {
  DeviceType,
  HomeForm,
  SearchActive,
  TagScope,
  ValidationForm,
} from "./metrics-dim-values.js";

export type DimUtubSelect = {
  device_type: DeviceType;
  search_active: SearchActive;
};

export type DimDeviceOnly = {
  device_type: DeviceType;
};

export type DimUtubNameEditOpen = {
  device_type: DeviceType;
  trigger: "pencil_icon" | "keyboard";
};

export type DimUtubDescEditOpen = {
  device_type: DeviceType;
  trigger: "pencil_icon" | "keyboard" | "create_button";
};

export type DimUrlAccess = {
  device_type: DeviceType;
  trigger: "corner_button" | "url_text" | "main_button";
  search_active: SearchActive;
  active_tag_count: number;
};

export type DimUrlCardClick = {
  device_type: DeviceType;
  search_active: SearchActive;
  active_tag_count: number;
};

export type DimUrlCopy = {
  device_type: DeviceType;
  result: "success" | "failure";
};

export type DimUtubSearchOpen = {
  device_type: DeviceType;
  target: "utubs";
};

export type DimUtubSearchClose = {
  device_type: DeviceType;
  target: "utubs";
};

export type DimUrlSearchOpen = {
  device_type: DeviceType;
  target: "urls";
};

export type DimUrlSearchClose = {
  device_type: DeviceType;
  target: "urls";
};

export type DimCrossUtubSearchOpen = {
  device_type: DeviceType;
  target: "cross_utub";
};

export type DimCrossUtubSearchClose = {
  device_type: DeviceType;
  target: "cross_utub";
  trigger:
    | "trigger_icon"
    | "escape_key"
    | "return_home"
    | "deck_switch"
    | "result_nav"
    | "history_nav";
};

export type DimCrossUtubSearchRefresh = {
  device_type: DeviceType;
  target: "cross_utub";
};

export type DimCrossUtubSearchResultAccess = {
  device_type: DeviceType;
  target: "cross_utub";
  trigger: "url_text" | "corner_button";
};

export type DimTagCreateOpen = {
  device_type: DeviceType;
  scope: TagScope;
};

export type DimTagDeleteOpen = {
  device_type: DeviceType;
  scope: TagScope;
};

export type DimTagDeleteConfirm = {
  device_type: DeviceType;
  scope: TagScope;
};

export type DimTagDeleteCancel = {
  device_type: DeviceType;
  scope: TagScope;
};

export type DimFormSubmit = {
  device_type: DeviceType;
  trigger: "enter_key" | "button_click";
  form: HomeForm;
};

export type DimFormCancel = {
  device_type: DeviceType;
  trigger: "escape_key" | "cancel_button" | "outside_click" | "navigation";
  form: HomeForm;
};

export type DimValidationError = {
  device_type: DeviceType;
  form: ValidationForm;
};

export type DimDeckCollapse = {
  device_type: DeviceType;
  deck: "members" | "tags" | "utubs";
};

export type DimDeckExpand = {
  device_type: DeviceType;
  deck: "members" | "tags" | "utubs";
};

export type DimMobileNav = {
  device_type: DeviceType;
  target: "utubs" | "urls" | "members" | "tags";
};

export type DimAuthCancel = {
  device_type: DeviceType;
  form: "login" | "register";
  trigger: "navigation";
};

export type DimAuthFormSwitch = {
  device_type: DeviceType;
  target: "login" | "register" | "forgot_password";
};

export type DimAuthModalOpen = {
  device_type: DeviceType;
  form: "login" | "register";
};

export type DimEmailValidationSubmit = {
  device_type: DeviceType;
  trigger: "manual_click" | "auto_after_register";
};

export type UIEventDimensions = {
  ui_utub_select: DimUtubSelect;
  ui_utub_create_open: DimDeviceOnly;
  ui_utub_delete_open: DimDeviceOnly;
  ui_utub_delete_confirm: DimDeviceOnly;
  ui_utub_delete_cancel: DimDeviceOnly;
  ui_utub_name_edit_open: DimUtubNameEditOpen;
  ui_utub_desc_edit_open: DimUtubDescEditOpen;
  ui_url_access: DimUrlAccess;
  ui_url_card_click: DimUrlCardClick;
  ui_url_create_open: DimDeviceOnly;
  ui_url_title_edit_open: DimDeviceOnly;
  ui_url_string_edit_open: DimDeviceOnly;
  ui_url_delete_open: DimDeviceOnly;
  ui_url_delete_confirm: DimDeviceOnly;
  ui_url_delete_cancel: DimDeviceOnly;
  ui_url_copy: DimUrlCopy;
  ui_url_access_warning: DimDeviceOnly;
  ui_url_access_warning_dismiss: DimDeviceOnly;
  ui_utub_search_open: DimUtubSearchOpen;
  ui_utub_search_close: DimUtubSearchClose;
  ui_url_search_open: DimUrlSearchOpen;
  ui_url_search_close: DimUrlSearchClose;
  ui_cross_utub_search_open: DimCrossUtubSearchOpen;
  ui_cross_utub_search_close: DimCrossUtubSearchClose;
  ui_cross_utub_search_refresh: DimCrossUtubSearchRefresh;
  ui_cross_utub_search_result_access: DimCrossUtubSearchResultAccess;
  ui_tag_apply: DimDeviceOnly;
  ui_tag_remove: DimDeviceOnly;
  ui_tag_create_open: DimTagCreateOpen;
  ui_tag_delete_open: DimTagDeleteOpen;
  ui_tag_delete_confirm: DimTagDeleteConfirm;
  ui_tag_delete_cancel: DimTagDeleteCancel;
  ui_tag_filter_toggle: DimDeviceOnly;
  ui_member_invite_open: DimDeviceOnly;
  ui_member_remove_open: DimDeviceOnly;
  ui_member_remove_confirm: DimDeviceOnly;
  ui_member_remove_cancel: DimDeviceOnly;
  ui_member_leave_open: DimDeviceOnly;
  ui_member_leave_confirm: DimDeviceOnly;
  ui_member_leave_cancel: DimDeviceOnly;
  ui_form_submit: DimFormSubmit;
  ui_form_cancel: DimFormCancel;
  ui_validation_error: DimValidationError;
  ui_deck_collapse: DimDeckCollapse;
  ui_deck_expand: DimDeckExpand;
  ui_navbar_dropdown_open: DimDeviceOnly;
  ui_navbar_dropdown_close: DimDeviceOnly;
  ui_mobile_nav: DimMobileNav;
  ui_login_submit: DimDeviceOnly;
  ui_register_submit: DimDeviceOnly;
  ui_forgot_password_submit: DimDeviceOnly;
  ui_auth_cancel: DimAuthCancel;
  ui_auth_form_switch: DimAuthFormSwitch;
  ui_auth_modal_open: DimAuthModalOpen;
  ui_reset_password_submit: DimDeviceOnly;
  ui_email_validation_submit: DimEmailValidationSubmit;
  ui_contact_submit: DimDeviceOnly;
  ui_error_page_refresh: DimDeviceOnly;
  ui_rate_limit_hit: DimDeviceOnly;
};
