from flask import current_app
from flask_login import current_user

from backend.metrics.dimension_models import get_all_dimension_keys
from backend.metrics.events import DEVICE_TYPE_DIM_KEY, DeviceType
from backend.models.user_preferences import resolve_preferences
from backend.models.utub_members import Member_Role
from backend.splash.constants import EmailValidationErrorCodes
from backend.utils.all_routes import generate_admin_routes_js, generate_routes_js
from backend.utils.datetime_utils import utc_now
from backend.utils.oauth_config import (
    should_register_github_oauth,
    should_register_google_oauth,
)
from backend.utils.strings.admin_metrics_strs import ADMIN_METRICS_STRINGS
from backend.utils.strings.admin_portal_strs import ADMIN_ACTION_STRINGS
from backend.utils.strings.email_validation_strs import (
    VALIDATE_MY_EMAIL,
    VALIDATE_YOUR_EMAIL,
)
from backend.utils.strings.form_strs import MAY_HAVE_ALREADY_BEEN_DELETED
from backend.utils.strings.oauth_strs import LINK_PASSWORD_REQUIRED_MESSAGE
from backend.utils.strings.splash_form_strs import (
    FORGOT_YOUR_PASSWORD,
    GITHUB_OAUTH_LOGIN_BUTTON_TEXT,
    GITHUB_OAUTH_REGISTER_BUTTON_TEXT,
    GOOGLE_OAUTH_LOGIN_BUTTON_TEXT,
    GOOGLE_OAUTH_REGISTER_BUTTON_TEXT,
    LOGIN,
    LOGIN_TITLE,
    REGISTER,
    REGISTRATION_EMAIL_RESEND_ERROR,
    REGISTRATION_EMAIL_RESEND_SENDING,
    REGISTRATION_EMAIL_RESENT,
)
from backend.utils.strings.splash_marketing_strs import (
    SPLASH_FEATURE_1_BODY,
    SPLASH_FEATURE_1_TITLE,
    SPLASH_FEATURE_2_BODY,
    SPLASH_FEATURE_2_TITLE,
    SPLASH_FEATURE_3_BODY,
    SPLASH_FEATURE_3_TITLE,
    SPLASH_FEATURES_HEADING,
    SPLASH_META_DESCRIPTION,
    SPLASH_MOCK_TAG_1,
    SPLASH_MOCK_TAG_2,
    SPLASH_MOCK_TAG_3,
    SPLASH_MOCK_URL_1_TITLE,
    SPLASH_MOCK_URL_1_URL,
    SPLASH_MOCK_URL_2_TITLE,
    SPLASH_MOCK_URL_2_URL,
    SPLASH_MOCK_URL_3_TITLE,
    SPLASH_MOCK_URL_3_URL,
    SPLASH_MOCK_UTUB_1_NAME,
    SPLASH_MOCK_UTUB_2_NAME,
    SPLASH_MOCK_UTUB_3_NAME,
    SPLASH_MOCK_UTUB_4_NAME,
    SPLASH_MOCK_UTUB_DESCRIPTION,
    SPLASH_PRODUCT_PREVIEW_CAPTION,
    SPLASH_PRODUCT_PREVIEW_HEADING,
    SPLASH_TAGLINE,
)
from backend.utils.strings.search_strs import (
    CROSS_SEARCH_COUNT_TEMPLATE,
    CROSS_SEARCH_FIELD_TAG,
    CROSS_SEARCH_FIELD_TITLE,
    CROSS_SEARCH_FIELD_URL,
    CROSS_SEARCH_HISTORY_CLEAR,
    CROSS_SEARCH_HISTORY_HEADING,
    CROSS_SEARCH_NO_RESULTS,
    CROSS_SEARCH_PLACEHOLDER,
    CROSS_SEARCH_REFRESH_LABEL,
    CROSS_SEARCH_SHORT_QUERY,
    CROSS_SEARCH_SUBMIT_LABEL,
    CROSS_SEARCH_TRIGGER_CLOSE_LABEL,
    CROSS_SEARCH_TRIGGER_OPEN_LABEL,
)
from backend.utils.strings.tag_strs import (
    ADD_TAGS_ARIA_LABEL,
    ADD_TAGS_PLACEHOLDER,
    ADD_TAGS_SUBMIT,
    ADD_URL_TAG_TOOLTIP,
    DELETE_UTUB_TAG_WARNING,
    TAG_CREATE_NEW,
    TAG_DECK_NO_TAGS,
    TAG_FILTER_NO_RESULTS,
    TAG_SEARCH_COUNT_TEMPLATE,
    TAG_SEARCH_NO_RESULTS,
    TAG_SEARCH_PLACEHOLDER,
    TAG_SHEET_ANNOUNCEMENT_CLOSE,
    TAG_SHEET_ANNOUNCEMENT_OPEN,
    TAGS_EMPTY_HINT,
    TAGS_LIMIT_REACHED,
    TAGS_MATCH_COUNT,
    TAGS_MATCH_COUNT_ONE,
    TAGS_NO_MATCHES,
    TAGS_OPTIONAL_LABEL,
    URL_BULK_ADD_TAGS_ARIA,
    URL_BULK_CARD_APPLIED,
    URL_BULK_CARD_SKIPPED,
    URL_BULK_TAGS_APPLIED,
    URL_BULK_TAGS_APPLIED_ONE,
    URL_BULK_TAGS_NO_CHANGES,
    URL_BULK_TAGS_NONE,
    URL_BULK_TAGS_NONE_SOME_SKIPPED,
    URL_BULK_TAGS_PARTIAL,
    URL_BULK_TAGS_STALE_SELECTION,
    URL_BULK_TAGS_SUBMITTING,
)
from backend.utils.strings.url_strs import (
    ACCESS_URL_TOOLTIP,
    ACCESS_URL_WARNING,
    ADD_URL_BUTTON,
    COPIED_URL_FAILURE_TOOLIP,
    COPIED_URL_TOOLTIP,
    COPY_URL_TOOLTIP,
    DELETE_URL_TOOLTIP,
    DELETE_URL_WARNING,
    EDIT_URL_TITLE_TOOLTIP,
    EDIT_URL_TOOLTIP,
    UNABLE_TO_COPY_URLS,
    UNABLE_TO_VALIDATE_THIS_URL,
    URL_ADDED_BY,
    URL_ADDED_ON,
    URL_BULK_CARD_ALREADY_THERE,
    URL_BULK_CARD_COPIED,
    URL_BULK_COPY_ALL_LOCKED,
    URL_BULK_COPY_ARIA,
    URL_BULK_COPY_FILTER_PLACEHOLDER,
    URL_BULK_COPY_LABEL,
    URL_BULK_COPY_NO_MATCHES,
    URL_BULK_COPY_SUBMITTING,
    URL_BULK_N_HIDDEN,
    URL_BULK_NONE_SELECTED,
    URL_BULK_SELECTED_COUNT,
    URL_BULK_SELECTED_COUNT_ONE,
    URL_DATE_ADDED_ARIA,
    URL_DATE_ADDED_LABEL,
    URL_SEARCH_NO_RESULTS,
    URLS_COPIED,
    URLS_COPIED_PARTIAL,
    URLS_COPY_NONE_NEW,
    UTUB_NO_URLS,
)
from backend.utils.strings.user_settings_strs import USER_SETTINGS_STRINGS
from backend.utils.strings.user_strs import (
    COOKIE_BANNER_KEY,
    COOKIE_BANNER_SEEN,
    EMAIL_CHANGE_STATUS_QUERY_PARAM,
    MEMBER_DELETE_WARNING,
    MEMBER_LEAVE_WARNING,
    MEMBER_SEARCH_COUNT_TEMPLATE,
    MEMBER_SEARCH_NO_RESULTS,
    MEMBER_SEARCH_PLACEHOLDER,
)
from backend.utils.strings.utub_strs import (
    FIELD_SAVED,
    FIELD_SAVED_LABEL_URL,
    FIELD_SAVED_LABEL_URL_TITLE,
    FIELD_SAVED_LABEL_UTUB_DESCRIPTION,
    FIELD_SAVED_LABEL_UTUB_NAME,
    MOBILE_PANEL_ANNOUNCEMENT_MEMBERS,
    MOBILE_PANEL_ANNOUNCEMENT_URLS,
    MOBILE_PANEL_ANNOUNCEMENT_UTUBS,
    MOBILE_PANEL_QUERY_PARAM,
    URL_ADDED_ANNOUNCEMENT,
    UTUB_CREATE_MSG,
    UTUB_CREATE_SAME_NAME,
    UTUB_DELETE_WARNING,
    UTUB_ID_QUERY_PARAM,
    UTUB_IS_LOCKED,
    UTUB_NO_LONGER_AVAILABLE,
    UTUB_SEARCH_COUNT_TEMPLATE,
    UTUB_SEARCH_NO_RESULTS,
    UTUB_SEARCH_PLACEHOLDER,
    UTUB_SELECT,
    UTUB_UPDATE_SAME_NAME,
)


class EMAIL_CONSTANTS:
    MAX_EMAIL_ATTEMPTS_IN_HOUR = 5
    WAIT_TO_RETRY_BEFORE_MAX_ATTEMPTS = 60
    WAIT_TO_ATTEMPT_AFTER_MAX_ATTEMPTS = 3600


class USER_CONSTANTS:
    MIN_USERNAME_LENGTH = 3
    MAX_USERNAME_LENGTH_ACTUAL = 25
    MAX_USERNAME_LENGTH = MAX_USERNAME_LENGTH_ACTUAL - 5
    MIN_EMAIL_LENGTH = 1
    MAX_EMAIL_LENGTH = 320
    MIN_PASSWORD_LENGTH = 12
    MAX_PASSWORD_INPUT_LENGTH = 64
    MAX_PASSWORD_LENGTH = 166
    MIN_REQUIRED_FIELD_LENGTH = 1
    PASSWORD_RESET_ATTEMPTS = 5
    WAIT_TO_RETRY_FORGOT_PASSWORD_MIN = 60
    WAIT_TO_RETRY_FORGOT_PASSWORD_MAX = 3600
    # Username changes are capped per rolling 24h per user via a Redis-only
    # counter (see settings-account-basics plan, Decision #4) — no DB migration.
    MAX_USERNAME_CHANGES_PER_DAY = 3
    USERNAME_CHANGE_WINDOW_SECONDS = 86_400
    # Email changes are capped per rolling 24h per user via a Redis-only counter
    # (mirrors the username-change pair) — prevents email-bombing an arbitrary
    # target address with confirmation links.
    MAX_EMAIL_CHANGES_PER_DAY = 3
    EMAIL_CHANGE_WINDOW_SECONDS = 86_400
    # Per-user brute-force lockout shared by BOTH re-auth gates (change-password
    # and the settings OAuth-link password re-auth) via a fail-open Redis counter
    # (see backend/utils/reauth_throttle.py, DD-1). 10 failures per rolling 15
    # minutes per user; the counter is keyed `reauth-fail:{user_id}` for both.
    MAX_REAUTH_FAILURES = 10
    REAUTH_LOCKOUT_WINDOW_SECONDS = 900


class UTUB_CONSTANTS:
    MAX_NAME_LENGTH = 30
    MIN_NAME_LENGTH = 1
    MAX_DESCRIPTION_LENGTH = 325
    MEMBER_ROLES = Member_Role


class URL_CONSTANTS:
    MIN_URL_TITLE_LENGTH = 1
    MIN_URL_LENGTH = 1
    MAX_URL_TITLE_LENGTH = 100
    MAX_URL_LENGTH = 8000
    # Max URLs targetable in one bulk copy-to-UTub request — a generous
    # "Select All" ceiling that bounds request cost (mirrors MAX_BULK_TAG_URLS).
    MAX_BULK_COPY_URLS = 100
    # Max destination UTubs targetable in one bulk copy-to-UTub request —
    # bounds the urls×destinations request cost.
    MAX_BULK_COPY_DESTINATIONS = 25


class TAG_CONSTANTS:
    MIN_TAG_LENGTH = 1
    MAX_TAG_LENGTH = 30
    MAX_URL_TAGS = 20
    # Max URLs targetable in one bulk tag-apply request — a generous "Select All"
    # ceiling that bounds request cost.
    MAX_BULK_TAG_URLS = 100


class SEARCH_CONSTANTS:
    MIN_QUERY_LENGTH: int = 1
    MAX_QUERY_LENGTH: int = 100


class CONFIG_CONSTANTS:
    SESSION_LIFETIME = 31 * 86400  # 31 days before session and CSRF expiration


class SPLASH_CONSTANTS:
    EMAIL_VALIDATION_ERROR_CODES = EmailValidationErrorCodes


class STRINGS:
    UTUB_QUERY_PARAM = UTUB_ID_QUERY_PARAM
    MOBILE_PANEL_QUERY_PARAM = MOBILE_PANEL_QUERY_PARAM
    EMAIL_CHANGE_STATUS_QUERY_PARAM = EMAIL_CHANGE_STATUS_QUERY_PARAM
    MOBILE_PANEL_ANNOUNCEMENT_UTUBS = MOBILE_PANEL_ANNOUNCEMENT_UTUBS
    MOBILE_PANEL_ANNOUNCEMENT_URLS = MOBILE_PANEL_ANNOUNCEMENT_URLS
    MOBILE_PANEL_ANNOUNCEMENT_MEMBERS = MOBILE_PANEL_ANNOUNCEMENT_MEMBERS
    UTUB_NO_LONGER_AVAILABLE = UTUB_NO_LONGER_AVAILABLE
    ADMIN_ACTION_REASON_LABEL = ADMIN_ACTION_STRINGS.REASON_LABEL
    ADMIN_ACTION_REASON_REQUIRED = ADMIN_ACTION_STRINGS.REASON_REQUIRED
    ADMIN_ACTION_GENERIC_ERROR = ADMIN_ACTION_STRINGS.GENERIC_ERROR
    ADMIN_ACTION_SUBMIT_DEFAULT = ADMIN_ACTION_STRINGS.SUBMIT_DEFAULT
    ADMIN_ACTION_DISMISS = ADMIN_ACTION_STRINGS.DISMISS
    ADMIN_ACTION_SUCCESS_DEFAULT = ADMIN_ACTION_STRINGS.SUCCESS_DEFAULT
    VALIDATE_MY_EMAIL = VALIDATE_MY_EMAIL
    VALIDATE_YOUR_EMAIL = VALIDATE_YOUR_EMAIL
    FORGOT_YOUR_PASSWORD = FORGOT_YOUR_PASSWORD
    LOGIN_TITLE = LOGIN_TITLE
    REGISTER = REGISTER
    LOGIN = LOGIN
    GOOGLE_OAUTH_LOGIN_BUTTON_TEXT = GOOGLE_OAUTH_LOGIN_BUTTON_TEXT
    GOOGLE_OAUTH_REGISTER_BUTTON_TEXT = GOOGLE_OAUTH_REGISTER_BUTTON_TEXT
    GITHUB_OAUTH_LOGIN_BUTTON_TEXT = GITHUB_OAUTH_LOGIN_BUTTON_TEXT
    GITHUB_OAUTH_REGISTER_BUTTON_TEXT = GITHUB_OAUTH_REGISTER_BUTTON_TEXT
    REGISTRATION_EMAIL_RESEND_SENDING = REGISTRATION_EMAIL_RESEND_SENDING
    REGISTRATION_EMAIL_RESENT = REGISTRATION_EMAIL_RESENT
    REGISTRATION_EMAIL_RESEND_ERROR = REGISTRATION_EMAIL_RESEND_ERROR

    SPLASH_TAGLINE = SPLASH_TAGLINE
    SPLASH_FEATURES_HEADING = SPLASH_FEATURES_HEADING
    SPLASH_FEATURE_1_TITLE = SPLASH_FEATURE_1_TITLE
    SPLASH_FEATURE_1_BODY = SPLASH_FEATURE_1_BODY
    SPLASH_FEATURE_2_TITLE = SPLASH_FEATURE_2_TITLE
    SPLASH_FEATURE_2_BODY = SPLASH_FEATURE_2_BODY
    SPLASH_FEATURE_3_TITLE = SPLASH_FEATURE_3_TITLE
    SPLASH_FEATURE_3_BODY = SPLASH_FEATURE_3_BODY
    SPLASH_PRODUCT_PREVIEW_HEADING = SPLASH_PRODUCT_PREVIEW_HEADING
    SPLASH_PRODUCT_PREVIEW_CAPTION = SPLASH_PRODUCT_PREVIEW_CAPTION
    SPLASH_MOCK_UTUB_1_NAME = SPLASH_MOCK_UTUB_1_NAME
    SPLASH_MOCK_UTUB_2_NAME = SPLASH_MOCK_UTUB_2_NAME
    SPLASH_MOCK_UTUB_3_NAME = SPLASH_MOCK_UTUB_3_NAME
    SPLASH_MOCK_UTUB_4_NAME = SPLASH_MOCK_UTUB_4_NAME
    SPLASH_MOCK_UTUB_DESCRIPTION = SPLASH_MOCK_UTUB_DESCRIPTION
    SPLASH_MOCK_URL_1_TITLE = SPLASH_MOCK_URL_1_TITLE
    SPLASH_MOCK_URL_1_URL = SPLASH_MOCK_URL_1_URL
    SPLASH_MOCK_URL_2_TITLE = SPLASH_MOCK_URL_2_TITLE
    SPLASH_MOCK_URL_2_URL = SPLASH_MOCK_URL_2_URL
    SPLASH_MOCK_URL_3_TITLE = SPLASH_MOCK_URL_3_TITLE
    SPLASH_MOCK_URL_3_URL = SPLASH_MOCK_URL_3_URL
    SPLASH_MOCK_TAG_1 = SPLASH_MOCK_TAG_1
    SPLASH_MOCK_TAG_2 = SPLASH_MOCK_TAG_2
    SPLASH_MOCK_TAG_3 = SPLASH_MOCK_TAG_3
    SPLASH_META_DESCRIPTION = SPLASH_META_DESCRIPTION

    UTUB_CREATE_SAME_NAME = UTUB_CREATE_SAME_NAME
    UTUB_UPDATE_SAME_NAME = UTUB_UPDATE_SAME_NAME
    UTUB_DELETE_WARNING = UTUB_DELETE_WARNING
    UTUB_CREATE_MSG = UTUB_CREATE_MSG
    UTUB_SELECT = UTUB_SELECT
    FIELD_SAVED = FIELD_SAVED
    FIELD_SAVED_LABEL_UTUB_NAME = FIELD_SAVED_LABEL_UTUB_NAME
    FIELD_SAVED_LABEL_UTUB_DESCRIPTION = FIELD_SAVED_LABEL_UTUB_DESCRIPTION
    FIELD_SAVED_LABEL_URL_TITLE = FIELD_SAVED_LABEL_URL_TITLE
    FIELD_SAVED_LABEL_URL = FIELD_SAVED_LABEL_URL
    URL_ADDED_ANNOUNCEMENT = URL_ADDED_ANNOUNCEMENT
    UTUB_IS_LOCKED = UTUB_IS_LOCKED
    UTUB_SEARCH_NO_RESULTS = UTUB_SEARCH_NO_RESULTS
    UTUB_SEARCH_PLACEHOLDER = UTUB_SEARCH_PLACEHOLDER
    UTUB_SEARCH_COUNT_TEMPLATE = UTUB_SEARCH_COUNT_TEMPLATE

    MEMBER_DELETE_WARNING = MEMBER_DELETE_WARNING
    MEMBER_LEAVE_WARNING = MEMBER_LEAVE_WARNING
    MEMBER_SEARCH_NO_RESULTS = MEMBER_SEARCH_NO_RESULTS
    MEMBER_SEARCH_PLACEHOLDER = MEMBER_SEARCH_PLACEHOLDER
    MEMBER_SEARCH_COUNT_TEMPLATE = MEMBER_SEARCH_COUNT_TEMPLATE

    DELETE_URL_WARNING = DELETE_URL_WARNING
    UNABLE_TO_VALIDATE_THIS_URL = UNABLE_TO_VALIDATE_THIS_URL
    ACCESS_URL_WARNING = ACCESS_URL_WARNING
    URL_SEARCH_NO_RESULTS = URL_SEARCH_NO_RESULTS
    URL_BULK_SELECTED_COUNT = URL_BULK_SELECTED_COUNT
    URL_BULK_SELECTED_COUNT_ONE = URL_BULK_SELECTED_COUNT_ONE
    URL_BULK_NONE_SELECTED = URL_BULK_NONE_SELECTED
    URL_BULK_N_HIDDEN = URL_BULK_N_HIDDEN
    UTUB_NO_URLS = UTUB_NO_URLS
    ADD_URL_BUTTON = ADD_URL_BUTTON
    URL_ADDED_BY = URL_ADDED_BY
    URL_ADDED_ON = URL_ADDED_ON
    URL_DATE_ADDED_LABEL = URL_DATE_ADDED_LABEL
    URL_DATE_ADDED_ARIA = URL_DATE_ADDED_ARIA
    # Bulk copy-to-UTub (Phase 3) — read by bulk-actions/bulk-copy.ts.
    URLS_COPIED = URLS_COPIED
    URLS_COPIED_PARTIAL = URLS_COPIED_PARTIAL
    URLS_COPY_NONE_NEW = URLS_COPY_NONE_NEW
    URL_BULK_CARD_COPIED = URL_BULK_CARD_COPIED
    URL_BULK_CARD_ALREADY_THERE = URL_BULK_CARD_ALREADY_THERE
    URL_BULK_COPY_LABEL = URL_BULK_COPY_LABEL
    URL_BULK_COPY_SUBMITTING = URL_BULK_COPY_SUBMITTING
    URL_BULK_COPY_ALL_LOCKED = URL_BULK_COPY_ALL_LOCKED
    URL_BULK_COPY_ARIA = URL_BULK_COPY_ARIA
    URL_BULK_COPY_FILTER_PLACEHOLDER = URL_BULK_COPY_FILTER_PLACEHOLDER
    URL_BULK_COPY_NO_MATCHES = URL_BULK_COPY_NO_MATCHES
    UNABLE_TO_COPY_URLS = UNABLE_TO_COPY_URLS

    CROSS_SEARCH_NO_RESULTS = CROSS_SEARCH_NO_RESULTS
    CROSS_SEARCH_SHORT_QUERY = CROSS_SEARCH_SHORT_QUERY
    CROSS_SEARCH_PLACEHOLDER = CROSS_SEARCH_PLACEHOLDER
    CROSS_SEARCH_COUNT_TEMPLATE = CROSS_SEARCH_COUNT_TEMPLATE
    CROSS_SEARCH_FIELD_URL = CROSS_SEARCH_FIELD_URL
    CROSS_SEARCH_FIELD_TITLE = CROSS_SEARCH_FIELD_TITLE
    CROSS_SEARCH_FIELD_TAG = CROSS_SEARCH_FIELD_TAG
    CROSS_SEARCH_HISTORY_HEADING = CROSS_SEARCH_HISTORY_HEADING
    CROSS_SEARCH_HISTORY_CLEAR = CROSS_SEARCH_HISTORY_CLEAR
    CROSS_SEARCH_TRIGGER_OPEN_LABEL = CROSS_SEARCH_TRIGGER_OPEN_LABEL
    CROSS_SEARCH_TRIGGER_CLOSE_LABEL = CROSS_SEARCH_TRIGGER_CLOSE_LABEL
    CROSS_SEARCH_SUBMIT_LABEL = CROSS_SEARCH_SUBMIT_LABEL
    CROSS_SEARCH_REFRESH_LABEL = CROSS_SEARCH_REFRESH_LABEL

    UTUB_TAG_DELETE_WARNING = DELETE_UTUB_TAG_WARNING
    TAG_FILTER_NO_RESULTS = TAG_FILTER_NO_RESULTS
    TAG_SEARCH_NO_RESULTS = TAG_SEARCH_NO_RESULTS
    TAG_SEARCH_PLACEHOLDER = TAG_SEARCH_PLACEHOLDER
    TAG_SEARCH_COUNT_TEMPLATE = TAG_SEARCH_COUNT_TEMPLATE
    TAG_DECK_NO_TAGS = TAG_DECK_NO_TAGS
    TAG_SHEET_ANNOUNCEMENT_OPEN = TAG_SHEET_ANNOUNCEMENT_OPEN
    TAG_SHEET_ANNOUNCEMENT_CLOSE = TAG_SHEET_ANNOUNCEMENT_CLOSE
    ADD_TAGS_PLACEHOLDER = ADD_TAGS_PLACEHOLDER
    ADD_TAGS_SUBMIT = ADD_TAGS_SUBMIT
    ADD_TAGS_ARIA_LABEL = ADD_TAGS_ARIA_LABEL
    TAGS_OPTIONAL_LABEL = TAGS_OPTIONAL_LABEL
    TAG_CREATE_NEW = TAG_CREATE_NEW
    TAGS_LIMIT_REACHED = TAGS_LIMIT_REACHED
    TAGS_NO_MATCHES = TAGS_NO_MATCHES
    TAGS_MATCH_COUNT = TAGS_MATCH_COUNT
    TAGS_MATCH_COUNT_ONE = TAGS_MATCH_COUNT_ONE
    TAGS_EMPTY_HINT = TAGS_EMPTY_HINT
    URL_BULK_ADD_TAGS_ARIA = URL_BULK_ADD_TAGS_ARIA
    URL_BULK_TAGS_APPLIED = URL_BULK_TAGS_APPLIED
    URL_BULK_TAGS_APPLIED_ONE = URL_BULK_TAGS_APPLIED_ONE
    URL_BULK_TAGS_PARTIAL = URL_BULK_TAGS_PARTIAL
    URL_BULK_TAGS_NONE = URL_BULK_TAGS_NONE
    URL_BULK_TAGS_NONE_SOME_SKIPPED = URL_BULK_TAGS_NONE_SOME_SKIPPED
    URL_BULK_TAGS_NO_CHANGES = URL_BULK_TAGS_NO_CHANGES
    URL_BULK_CARD_APPLIED = URL_BULK_CARD_APPLIED
    URL_BULK_CARD_SKIPPED = URL_BULK_CARD_SKIPPED
    URL_BULK_TAGS_STALE_SELECTION = URL_BULK_TAGS_STALE_SELECTION
    URL_BULK_TAGS_SUBMITTING = URL_BULK_TAGS_SUBMITTING

    COPY_URL_TOOLTIP = COPY_URL_TOOLTIP
    COPIED_URL_TOOLTIP = COPIED_URL_TOOLTIP
    COPIED_URL_FAILURE_TOOLIP = COPIED_URL_FAILURE_TOOLIP
    ACCESS_URL_TOOLTIP = ACCESS_URL_TOOLTIP
    ADD_URL_TAG_TOOLTIP = ADD_URL_TAG_TOOLTIP
    EDIT_URL_TOOLTIP = EDIT_URL_TOOLTIP
    EDIT_URL_TITLE_TOOLTIP = EDIT_URL_TITLE_TOOLTIP
    DELETE_URL_TOOLTIP = DELETE_URL_TOOLTIP
    MAY_HAVE_ALREADY_BEEN_DELETED = MAY_HAVE_ALREADY_BEEN_DELETED
    COOKIE_BANNER_SEEN = COOKIE_BANNER_SEEN
    COOKIE_BANNER_KEY = COOKIE_BANNER_KEY

    METRICS_DASHBOARD_TITLE = ADMIN_METRICS_STRINGS.METRICS_DASHBOARD_TITLE
    METRICS_REFRESH_BUTTON_LABEL = ADMIN_METRICS_STRINGS.METRICS_REFRESH_BUTTON_LABEL
    METRICS_TAB_API = ADMIN_METRICS_STRINGS.METRICS_TAB_API
    METRICS_TAB_UI = ADMIN_METRICS_STRINGS.METRICS_TAB_UI
    METRICS_TAB_DOMAIN = ADMIN_METRICS_STRINGS.METRICS_TAB_DOMAIN
    METRICS_TAB_PIPELINE_HEALTH = ADMIN_METRICS_STRINGS.METRICS_TAB_PIPELINE_HEALTH
    METRICS_TAB_FLOWS = ADMIN_METRICS_STRINGS.METRICS_TAB_FLOWS
    METRICS_TAB_GAUGES = ADMIN_METRICS_STRINGS.METRICS_TAB_GAUGES
    METRICS_TIMESERIES_SELECT_ARIA = (
        ADMIN_METRICS_STRINGS.METRICS_TIMESERIES_SELECT_ARIA
    )
    METRICS_LAST_FLUSH_UNKNOWN = ADMIN_METRICS_STRINGS.METRICS_LAST_FLUSH_UNKNOWN
    METRICS_LAST_FLUSH_JUST_NOW = ADMIN_METRICS_STRINGS.METRICS_LAST_FLUSH_JUST_NOW
    METRICS_LAST_FLUSH_SECONDS = ADMIN_METRICS_STRINGS.METRICS_LAST_FLUSH_SECONDS
    METRICS_LAST_FLUSH_MINUTES = ADMIN_METRICS_STRINGS.METRICS_LAST_FLUSH_MINUTES
    METRICS_LAST_FLUSH_STALE_MINUTES = (
        ADMIN_METRICS_STRINGS.METRICS_LAST_FLUSH_STALE_MINUTES
    )
    METRICS_LAST_FLUSH_STALE_HOURS = (
        ADMIN_METRICS_STRINGS.METRICS_LAST_FLUSH_STALE_HOURS
    )
    METRICS_LAST_EVENT_UNKNOWN = ADMIN_METRICS_STRINGS.METRICS_LAST_EVENT_UNKNOWN
    METRICS_LAST_EVENT_JUST_NOW = ADMIN_METRICS_STRINGS.METRICS_LAST_EVENT_JUST_NOW
    METRICS_LAST_EVENT_SECONDS = ADMIN_METRICS_STRINGS.METRICS_LAST_EVENT_SECONDS
    METRICS_LAST_EVENT_MINUTES = ADMIN_METRICS_STRINGS.METRICS_LAST_EVENT_MINUTES
    METRICS_LAST_EVENT_HOURS = ADMIN_METRICS_STRINGS.METRICS_LAST_EVENT_HOURS
    METRICS_EMPTY_STATE = ADMIN_METRICS_STRINGS.METRICS_EMPTY_STATE
    METRICS_FETCH_FAILED_BANNER = ADMIN_METRICS_STRINGS.METRICS_FETCH_FAILED_BANNER
    METRICS_SUMMARY_TOTAL_EVENTS = ADMIN_METRICS_STRINGS.METRICS_SUMMARY_TOTAL_EVENTS
    METRICS_SUMMARY_API_HITS = ADMIN_METRICS_STRINGS.METRICS_SUMMARY_API_HITS
    METRICS_SUMMARY_UI_EVENTS = ADMIN_METRICS_STRINGS.METRICS_SUMMARY_UI_EVENTS
    METRICS_SUMMARY_DOMAIN_ACTIONS = (
        ADMIN_METRICS_STRINGS.METRICS_SUMMARY_DOMAIN_ACTIONS
    )
    METRICS_SUMMARY_DELTA_SUFFIX = ADMIN_METRICS_STRINGS.METRICS_SUMMARY_DELTA_SUFFIX
    METRICS_SUMMARY_DELTA_UNAVAILABLE = (
        ADMIN_METRICS_STRINGS.METRICS_SUMMARY_DELTA_UNAVAILABLE
    )
    METRICS_TOP_TABLE_HEADER_RANK = ADMIN_METRICS_STRINGS.METRICS_TOP_TABLE_HEADER_RANK
    METRICS_TOP_TABLE_HEADER_ENDPOINT = (
        ADMIN_METRICS_STRINGS.METRICS_TOP_TABLE_HEADER_ENDPOINT
    )
    METRICS_TOP_TABLE_HEADER_EVENT = (
        ADMIN_METRICS_STRINGS.METRICS_TOP_TABLE_HEADER_EVENT
    )
    METRICS_TOP_TABLE_HEADER_ACTION = (
        ADMIN_METRICS_STRINGS.METRICS_TOP_TABLE_HEADER_ACTION
    )
    METRICS_TOP_TABLE_HEADER_HITS = ADMIN_METRICS_STRINGS.METRICS_TOP_TABLE_HEADER_HITS
    METRICS_TOP_TABLE_HEADER_DELTA = (
        ADMIN_METRICS_STRINGS.METRICS_TOP_TABLE_HEADER_DELTA
    )
    METRICS_TOP_TABLE_ROW_ARIA = ADMIN_METRICS_STRINGS.METRICS_TOP_TABLE_ROW_ARIA
    METRICS_CHART_Y_AXIS_LABEL = ADMIN_METRICS_STRINGS.METRICS_CHART_Y_AXIS_LABEL
    METRICS_TOP_RESOURCE_ALL = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_ALL
    METRICS_TOP_RESOURCE_UTUB = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_UTUB
    METRICS_TOP_RESOURCE_URL = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_URL
    METRICS_TOP_RESOURCE_TAG = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_TAG
    METRICS_TOP_RESOURCE_MEMBER = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_MEMBER
    METRICS_TOP_RESOURCE_AUTH = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_AUTH
    METRICS_TOP_RESOURCE_SEARCH = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_SEARCH
    METRICS_TOP_RESOURCE_FORM = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_FORM
    METRICS_TOP_RESOURCE_DECK = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_DECK
    METRICS_TOP_RESOURCE_NAV = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_NAV
    METRICS_TOP_RESOURCE_ERROR = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_ERROR
    METRICS_TOP_RESOURCE_CONTACT = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_CONTACT
    METRICS_TOP_RESOURCE_ADMIN = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_ADMIN
    METRICS_TOP_RESOURCE_OTHER = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_OTHER
    METRICS_TOP_DEVICE_ALL = ADMIN_METRICS_STRINGS.METRICS_TOP_DEVICE_ALL
    METRICS_TOP_DEVICE_MOBILE = ADMIN_METRICS_STRINGS.METRICS_TOP_DEVICE_MOBILE
    METRICS_TOP_DEVICE_DESKTOP = ADMIN_METRICS_STRINGS.METRICS_TOP_DEVICE_DESKTOP
    METRICS_TOP_EMPTY_NO_MATCHES = ADMIN_METRICS_STRINGS.METRICS_TOP_EMPTY_NO_MATCHES
    METRICS_PIPELINE_HEALTH_TITLE = ADMIN_METRICS_STRINGS.METRICS_PIPELINE_HEALTH_TITLE
    METRICS_PIPELINE_HEALTH_EMPTY_STATE = (
        ADMIN_METRICS_STRINGS.METRICS_PIPELINE_HEALTH_EMPTY_STATE
    )
    METRICS_PIPELINE_HEALTH_AXIS_LABEL = (
        ADMIN_METRICS_STRINGS.METRICS_PIPELINE_HEALTH_AXIS_LABEL
    )
    METRICS_PIPELINE_HEALTH_AXIS_LABEL_X = (
        ADMIN_METRICS_STRINGS.METRICS_PIPELINE_HEALTH_AXIS_LABEL_X
    )
    METRICS_PIPELINE_HEALTH_LEGEND_FETCH_DESKTOP = (
        ADMIN_METRICS_STRINGS.METRICS_PIPELINE_HEALTH_LEGEND_FETCH_DESKTOP
    )
    METRICS_PIPELINE_HEALTH_LEGEND_FETCH_MOBILE = (
        ADMIN_METRICS_STRINGS.METRICS_PIPELINE_HEALTH_LEGEND_FETCH_MOBILE
    )
    METRICS_PIPELINE_HEALTH_LEGEND_BEACON_DESKTOP = (
        ADMIN_METRICS_STRINGS.METRICS_PIPELINE_HEALTH_LEGEND_BEACON_DESKTOP
    )
    METRICS_PIPELINE_HEALTH_LEGEND_BEACON_MOBILE = (
        ADMIN_METRICS_STRINGS.METRICS_PIPELINE_HEALTH_LEGEND_BEACON_MOBILE
    )
    METRICS_PIPELINE_HEALTH_CHART_DESC = (
        ADMIN_METRICS_STRINGS.METRICS_PIPELINE_HEALTH_CHART_DESC
    )
    METRICS_FLOW_SUCCEEDED = ADMIN_METRICS_STRINGS.METRICS_FLOW_SUCCEEDED
    METRICS_FLOW_CONVERSION = ADMIN_METRICS_STRINGS.METRICS_FLOW_CONVERSION
    METRICS_FLOW_DROPOFF = ADMIN_METRICS_STRINGS.METRICS_FLOW_DROPOFF
    METRICS_FLOW_CATEGORY_UI = ADMIN_METRICS_STRINGS.METRICS_FLOW_CATEGORY_UI
    METRICS_FLOW_CATEGORY_API = ADMIN_METRICS_STRINGS.METRICS_FLOW_CATEGORY_API
    METRICS_FLOW_CATEGORY_DOMAIN = ADMIN_METRICS_STRINGS.METRICS_FLOW_CATEGORY_DOMAIN
    METRICS_FLOW_EMPTY = ADMIN_METRICS_STRINGS.METRICS_FLOW_EMPTY
    METRICS_FLOWS_LOADED = ADMIN_METRICS_STRINGS.METRICS_FLOWS_LOADED
    METRICS_GAUGE_KIND_VOLUME = ADMIN_METRICS_STRINGS.METRICS_GAUGE_KIND_VOLUME
    METRICS_GAUGE_KIND_DISTRIBUTION_MAX = (
        ADMIN_METRICS_STRINGS.METRICS_GAUGE_KIND_DISTRIBUTION_MAX
    )
    METRICS_GAUGE_KIND_DISTRIBUTION_AVG = (
        ADMIN_METRICS_STRINGS.METRICS_GAUGE_KIND_DISTRIBUTION_AVG
    )
    METRICS_GAUGE_SUPPRESSED_ARIA = ADMIN_METRICS_STRINGS.METRICS_GAUGE_SUPPRESSED_ARIA
    METRICS_GAUGES_LOADED = ADMIN_METRICS_STRINGS.METRICS_GAUGES_LOADED
    METRICS_GAUGE_SELECT_PROMPT = ADMIN_METRICS_STRINGS.METRICS_GAUGE_SELECT_PROMPT
    METRICS_GAUGE_COL_NAME = ADMIN_METRICS_STRINGS.METRICS_GAUGE_COL_NAME
    METRICS_GAUGE_COL_VALUE = ADMIN_METRICS_STRINGS.METRICS_GAUGE_COL_VALUE
    METRICS_GAUGES_EMPTY = ADMIN_METRICS_STRINGS.METRICS_GAUGES_EMPTY
    METRICS_TAB_LATENCY = ADMIN_METRICS_STRINGS.METRICS_TAB_LATENCY
    METRICS_LATENCY_EMPTY = ADMIN_METRICS_STRINGS.METRICS_LATENCY_EMPTY
    METRICS_LATENCY_SELECT_PROMPT = ADMIN_METRICS_STRINGS.METRICS_LATENCY_SELECT_PROMPT
    METRICS_LATENCY_COL_ENDPOINT = ADMIN_METRICS_STRINGS.METRICS_LATENCY_COL_ENDPOINT
    METRICS_LATENCY_COL_P50 = ADMIN_METRICS_STRINGS.METRICS_LATENCY_COL_P50
    METRICS_LATENCY_COL_P95 = ADMIN_METRICS_STRINGS.METRICS_LATENCY_COL_P95
    METRICS_LATENCY_COL_P99 = ADMIN_METRICS_STRINGS.METRICS_LATENCY_COL_P99
    METRICS_LATENCY_COL_SAMPLES = ADMIN_METRICS_STRINGS.METRICS_LATENCY_COL_SAMPLES
    METRICS_LATENCY_Y_AXIS_LABEL = ADMIN_METRICS_STRINGS.METRICS_LATENCY_Y_AXIS_LABEL
    METRICS_LATENCY_ROW_ARIA = ADMIN_METRICS_STRINGS.METRICS_LATENCY_ROW_ARIA
    METRICS_LATENCY_SERIES_ARIA_P50 = (
        ADMIN_METRICS_STRINGS.METRICS_LATENCY_SERIES_ARIA_P50
    )
    METRICS_LATENCY_SERIES_ARIA_P95 = (
        ADMIN_METRICS_STRINGS.METRICS_LATENCY_SERIES_ARIA_P95
    )
    METRICS_LATENCY_SERIES_ARIA_P99 = (
        ADMIN_METRICS_STRINGS.METRICS_LATENCY_SERIES_ARIA_P99
    )
    METRICS_LATENCY_APPROXIMATE_NOTE = (
        ADMIN_METRICS_STRINGS.METRICS_LATENCY_APPROXIMATE_NOTE
    )
    METRICS_LATENCY_DAILY_RESOLUTION_NOTE = (
        ADMIN_METRICS_STRINGS.METRICS_LATENCY_DAILY_RESOLUTION_NOTE
    )

    SETTINGS_PAGE_TITLE = USER_SETTINGS_STRINGS.PAGE_TITLE
    SETTINGS_TABLIST_ARIA_LABEL = USER_SETTINGS_STRINGS.TABLIST_ARIA_LABEL
    SETTINGS_TAB_ACCOUNT = USER_SETTINGS_STRINGS.TAB_ACCOUNT
    SETTINGS_TAB_STATS = USER_SETTINGS_STRINGS.TAB_STATS
    SETTINGS_TAB_PRIVACY_DATA = USER_SETTINGS_STRINGS.TAB_PRIVACY_DATA
    SETTINGS_TAB_UI_SETTINGS = USER_SETTINGS_STRINGS.TAB_UI_SETTINGS
    SETTINGS_PLACEHOLDER = USER_SETTINGS_STRINGS.PLACEHOLDER
    SETTINGS_CONNECTED_ACCOUNTS_TITLE = USER_SETTINGS_STRINGS.CONNECTED_ACCOUNTS_TITLE
    SETTINGS_CONNECTED_ACCOUNTS_HINT = USER_SETTINGS_STRINGS.CONNECTED_ACCOUNTS_HINT
    SETTINGS_CONNECTED_LAST_METHOD_NOTE = (
        USER_SETTINGS_STRINGS.CONNECTED_LAST_METHOD_NOTE
    )
    SETTINGS_CONNECTED_STATUS_CONNECTED = (
        USER_SETTINGS_STRINGS.CONNECTED_STATUS_CONNECTED
    )
    SETTINGS_CONNECTED_STATUS_NOT_CONNECTED = (
        USER_SETTINGS_STRINGS.CONNECTED_STATUS_NOT_CONNECTED
    )
    SETTINGS_CONNECTED_STATUS_NOT_CONNECTED_PROOF = (
        USER_SETTINGS_STRINGS.CONNECTED_STATUS_NOT_CONNECTED_PROOF
    )
    SETTINGS_CONNECT_BUTTON_TEXT = USER_SETTINGS_STRINGS.CONNECT_BUTTON_TEXT
    SETTINGS_DISCONNECT_BUTTON_TEXT = USER_SETTINGS_STRINGS.DISCONNECT_BUTTON_TEXT
    SETTINGS_CONNECT_CONTINUE_BUTTON_TEXT = (
        USER_SETTINGS_STRINGS.CONNECT_CONTINUE_BUTTON_TEXT
    )
    SETTINGS_CONNECT_CANCEL_BUTTON_TEXT = (
        USER_SETTINGS_STRINGS.CONNECT_CANCEL_BUTTON_TEXT
    )
    SETTINGS_CONNECT_PASSWORD_PROMPT = LINK_PASSWORD_REQUIRED_MESSAGE

    SETTINGS_ACCOUNT_INFO_TITLE = USER_SETTINGS_STRINGS.ACCOUNT_INFO_TITLE
    SETTINGS_ACCOUNT_INFO_HINT = USER_SETTINGS_STRINGS.ACCOUNT_INFO_HINT
    SETTINGS_ACCOUNT_USERNAME_LABEL = USER_SETTINGS_STRINGS.ACCOUNT_USERNAME_LABEL
    SETTINGS_ACCOUNT_EMAIL_LABEL = USER_SETTINGS_STRINGS.ACCOUNT_EMAIL_LABEL
    SETTINGS_ACCOUNT_MEMBER_SINCE_LABEL = (
        USER_SETTINGS_STRINGS.ACCOUNT_MEMBER_SINCE_LABEL
    )
    SETTINGS_ACCOUNT_EMAIL_STATUS_LABEL = (
        USER_SETTINGS_STRINGS.ACCOUNT_EMAIL_STATUS_LABEL
    )
    SETTINGS_ACCOUNT_EMAIL_VERIFIED = USER_SETTINGS_STRINGS.ACCOUNT_EMAIL_VERIFIED
    SETTINGS_ACCOUNT_EMAIL_UNVERIFIED = USER_SETTINGS_STRINGS.ACCOUNT_EMAIL_UNVERIFIED
    # Pending email-change note — two distinct attribute names (DD-18) so the
    # Jinja-only initial-render copy and the JS-bridged in-place-patch copy never
    # collide as duplicate class attributes even though both render the same
    # sentence. Only ACCOUNT_PENDING_EMAIL_NOTE is exposed through
    # generate_strings_js() (see below); INITIAL_NOTE stays Jinja-only.
    SETTINGS_ACCOUNT_PENDING_EMAIL_INITIAL_NOTE = (
        USER_SETTINGS_STRINGS.ACCOUNT_PENDING_EMAIL_INITIAL_NOTE
    )
    SETTINGS_ACCOUNT_PENDING_EMAIL_NOTE = (
        USER_SETTINGS_STRINGS.ACCOUNT_PENDING_EMAIL_NOTE
    )

    SETTINGS_CHANGE_USERNAME_TITLE = USER_SETTINGS_STRINGS.CHANGE_USERNAME_TITLE
    SETTINGS_CHANGE_USERNAME_HINT = USER_SETTINGS_STRINGS.CHANGE_USERNAME_HINT
    SETTINGS_CHANGE_USERNAME_LABEL = USER_SETTINGS_STRINGS.CHANGE_USERNAME_LABEL
    SETTINGS_CHANGE_USERNAME_BUTTON = USER_SETTINGS_STRINGS.CHANGE_USERNAME_BUTTON

    SETTINGS_CHANGE_PASSWORD_TITLE = USER_SETTINGS_STRINGS.CHANGE_PASSWORD_TITLE
    SETTINGS_CHANGE_PASSWORD_HINT = USER_SETTINGS_STRINGS.CHANGE_PASSWORD_HINT
    SETTINGS_CHANGE_PASSWORD_CURRENT_LABEL = (
        USER_SETTINGS_STRINGS.CHANGE_PASSWORD_CURRENT_LABEL
    )
    SETTINGS_CHANGE_PASSWORD_NEW_LABEL = USER_SETTINGS_STRINGS.CHANGE_PASSWORD_NEW_LABEL
    SETTINGS_CHANGE_PASSWORD_CONFIRM_LABEL = (
        USER_SETTINGS_STRINGS.CHANGE_PASSWORD_CONFIRM_LABEL
    )
    SETTINGS_CHANGE_PASSWORD_BUTTON = USER_SETTINGS_STRINGS.CHANGE_PASSWORD_BUTTON
    SETTINGS_CHANGE_PASSWORD_OAUTH_ONLY_NOTE = (
        USER_SETTINGS_STRINGS.CHANGE_PASSWORD_OAUTH_ONLY_NOTE
    )

    SETTINGS_CHANGE_EMAIL_TITLE = USER_SETTINGS_STRINGS.CHANGE_EMAIL_TITLE
    SETTINGS_CHANGE_EMAIL_HINT = USER_SETTINGS_STRINGS.CHANGE_EMAIL_HINT
    SETTINGS_CHANGE_EMAIL_NEW_LABEL = USER_SETTINGS_STRINGS.CHANGE_EMAIL_NEW_LABEL
    SETTINGS_CHANGE_EMAIL_CONFIRM_LABEL = (
        USER_SETTINGS_STRINGS.CHANGE_EMAIL_CONFIRM_LABEL
    )
    SETTINGS_CHANGE_EMAIL_PASSWORD_LABEL = (
        USER_SETTINGS_STRINGS.CHANGE_EMAIL_PASSWORD_LABEL
    )
    SETTINGS_CHANGE_EMAIL_BUTTON = USER_SETTINGS_STRINGS.CHANGE_EMAIL_BUTTON
    SETTINGS_CHANGE_EMAIL_OAUTH_ONLY_NOTE = (
        USER_SETTINGS_STRINGS.CHANGE_EMAIL_OAUTH_ONLY_NOTE
    )
    SETTINGS_CHANGE_EMAIL_PENDING_WARNING = (
        USER_SETTINGS_STRINGS.CHANGE_EMAIL_PENDING_WARNING
    )

    SETTINGS_STATS_SECTION_TITLE = USER_SETTINGS_STRINGS.STATS_SECTION_TITLE
    SETTINGS_STATS_SECTION_HINT = USER_SETTINGS_STRINGS.STATS_SECTION_HINT
    SETTINGS_STATS_UTUBS_CREATED = USER_SETTINGS_STRINGS.STATS_UTUBS_CREATED
    SETTINGS_STATS_MEMBER_OF = USER_SETTINGS_STRINGS.STATS_MEMBER_OF
    SETTINGS_STATS_MEMBER_OF_SUB = USER_SETTINGS_STRINGS.STATS_MEMBER_OF_SUB
    SETTINGS_STATS_URLS_ADDED = USER_SETTINGS_STRINGS.STATS_URLS_ADDED
    SETTINGS_STATS_TAGS_CREATED = USER_SETTINGS_STRINGS.STATS_TAGS_CREATED
    SETTINGS_STATS_TAGS_APPLIED = USER_SETTINGS_STRINGS.STATS_TAGS_APPLIED
    SETTINGS_STATS_TAGS_APPLIED_SUB = USER_SETTINGS_STRINGS.STATS_TAGS_APPLIED_SUB
    SETTINGS_STATS_MEMBER_SINCE = USER_SETTINGS_STRINGS.STATS_MEMBER_SINCE
    SETTINGS_STATS_JOINED_TODAY = USER_SETTINGS_STRINGS.STATS_JOINED_TODAY

    # Log out everywhere (Account tab, security area)
    SETTINGS_LOGOUT_EVERYWHERE_TITLE = USER_SETTINGS_STRINGS.LOGOUT_EVERYWHERE_TITLE
    SETTINGS_LOGOUT_EVERYWHERE_HINT = USER_SETTINGS_STRINGS.LOGOUT_EVERYWHERE_HINT
    SETTINGS_LOGOUT_EVERYWHERE_BUTTON = USER_SETTINGS_STRINGS.LOGOUT_EVERYWHERE_BUTTON
    SETTINGS_LOGOUT_EVERYWHERE_MODAL_TITLE = (
        USER_SETTINGS_STRINGS.LOGOUT_EVERYWHERE_MODAL_TITLE
    )
    SETTINGS_LOGOUT_EVERYWHERE_MODAL_WARNING_LEAD = (
        USER_SETTINGS_STRINGS.LOGOUT_EVERYWHERE_MODAL_WARNING_LEAD
    )
    SETTINGS_LOGOUT_EVERYWHERE_MODAL_WARNING_BODY = (
        USER_SETTINGS_STRINGS.LOGOUT_EVERYWHERE_MODAL_WARNING_BODY
    )
    SETTINGS_LOGOUT_EVERYWHERE_MODAL_CONFIRM_BUTTON = (
        USER_SETTINGS_STRINGS.LOGOUT_EVERYWHERE_MODAL_CONFIRM_BUTTON
    )

    # Privacy & Data tab — Export my data (Phase 5)
    SETTINGS_EXPORT_SECTION_TITLE = USER_SETTINGS_STRINGS.EXPORT_SECTION_TITLE
    SETTINGS_EXPORT_SECTION_HINT = USER_SETTINGS_STRINGS.EXPORT_SECTION_HINT
    SETTINGS_EXPORT_CARD_TITLE = USER_SETTINGS_STRINGS.EXPORT_CARD_TITLE
    SETTINGS_EXPORT_CARD_HINT = USER_SETTINGS_STRINGS.EXPORT_CARD_HINT
    SETTINGS_EXPORT_BUTTON = USER_SETTINGS_STRINGS.EXPORT_BUTTON
    SETTINGS_EXPORT_SESSIONS_ZONE_LABEL = (
        USER_SETTINGS_STRINGS.EXPORT_SESSIONS_ZONE_LABEL
    )
    SETTINGS_EXPORT_PREPARING = USER_SETTINGS_STRINGS.EXPORT_PREPARING
    SETTINGS_EXPORT_STARTED = USER_SETTINGS_STRINGS.EXPORT_STARTED
    SETTINGS_EXPORT_ERROR = USER_SETTINGS_STRINGS.EXPORT_ERROR
    SETTINGS_DELETE_BLOCKED_BY_EXPORT = USER_SETTINGS_STRINGS.DELETE_BLOCKED_BY_EXPORT
    SETTINGS_EXPORT_BLOCKED_BY_DELETE = USER_SETTINGS_STRINGS.EXPORT_BLOCKED_BY_DELETE

    # Danger zone + account-removal modals (Account tab, Phase 4)
    SETTINGS_DANGER_ZONE_TITLE = USER_SETTINGS_STRINGS.DANGER_ZONE_TITLE
    SETTINGS_DANGER_ZONE_HINT = USER_SETTINGS_STRINGS.DANGER_ZONE_HINT
    SETTINGS_DANGER_ZONE_DELETE_CARD_TITLE = (
        USER_SETTINGS_STRINGS.DANGER_ZONE_DELETE_CARD_TITLE
    )
    SETTINGS_DANGER_ZONE_DELETE_CARD_BODY = (
        USER_SETTINGS_STRINGS.DANGER_ZONE_DELETE_CARD_BODY
    )
    SETTINGS_DANGER_ZONE_DELETE_CARD_BUTTON = (
        USER_SETTINGS_STRINGS.DANGER_ZONE_DELETE_CARD_BUTTON
    )
    SETTINGS_MODAL_CANCEL_BUTTON = USER_SETTINGS_STRINGS.MODAL_CANCEL_BUTTON
    SETTINGS_MODAL_CLOSE_ARIA_LABEL = USER_SETTINGS_STRINGS.MODAL_CLOSE_ARIA_LABEL
    SETTINGS_REMOVAL_REAUTH_SECTION_LABEL = (
        USER_SETTINGS_STRINGS.REMOVAL_REAUTH_SECTION_LABEL
    )
    SETTINGS_REMOVAL_REAUTH_PROVIDER_BUTTON = (
        USER_SETTINGS_STRINGS.REMOVAL_REAUTH_PROVIDER_BUTTON
    )
    SETTINGS_REMOVAL_REAUTH_REDIRECT_HINT = (
        USER_SETTINGS_STRINGS.REMOVAL_REAUTH_REDIRECT_HINT
    )
    SETTINGS_REMOVAL_PASSWORD_PLACEHOLDER = (
        USER_SETTINGS_STRINGS.REMOVAL_PASSWORD_PLACEHOLDER
    )
    SETTINGS_DELETE_MODAL_TITLE = USER_SETTINGS_STRINGS.DELETE_MODAL_TITLE
    SETTINGS_DELETE_MODAL_WARNING_LEAD = USER_SETTINGS_STRINGS.DELETE_MODAL_WARNING_LEAD
    SETTINGS_DELETE_MODAL_WARNING_BODY = USER_SETTINGS_STRINGS.DELETE_MODAL_WARNING_BODY
    SETTINGS_DELETE_MODAL_NOTICE_TRANSFER = (
        USER_SETTINGS_STRINGS.DELETE_MODAL_NOTICE_TRANSFER
    )
    SETTINGS_DELETE_MODAL_NOTICE_SOLO = USER_SETTINGS_STRINGS.DELETE_MODAL_NOTICE_SOLO
    SETTINGS_DELETE_MODAL_NOTICE_ATTRIBUTION = (
        USER_SETTINGS_STRINGS.DELETE_MODAL_NOTICE_ATTRIBUTION
    )
    SETTINGS_DELETE_MODAL_NOTICE_RETENTION = (
        USER_SETTINGS_STRINGS.DELETE_MODAL_NOTICE_RETENTION
    )
    SETTINGS_DELETE_MODAL_CONFIRM_USERNAME_PREFIX = (
        USER_SETTINGS_STRINGS.DELETE_MODAL_CONFIRM_USERNAME_PREFIX
    )
    SETTINGS_DELETE_MODAL_CONFIRM_USERNAME_SUFFIX = (
        USER_SETTINGS_STRINGS.DELETE_MODAL_CONFIRM_USERNAME_SUFFIX
    )
    SETTINGS_DELETE_MODAL_CONFIRM_USERNAME_PLACEHOLDER = (
        USER_SETTINGS_STRINGS.DELETE_MODAL_CONFIRM_USERNAME_PLACEHOLDER
    )
    SETTINGS_DELETE_MODAL_PASSWORD_LABEL = (
        USER_SETTINGS_STRINGS.DELETE_MODAL_PASSWORD_LABEL
    )
    SETTINGS_DELETE_MODAL_CONFIRM_BUTTON = (
        USER_SETTINGS_STRINGS.DELETE_MODAL_CONFIRM_BUTTON
    )

    # Display tab (Phase 6)
    SETTINGS_UI_SETTINGS_SECTION_INTRO = USER_SETTINGS_STRINGS.UI_SETTINGS_SECTION_INTRO
    SETTINGS_UI_SETTINGS_THEME_LABEL = USER_SETTINGS_STRINGS.UI_SETTINGS_THEME_LABEL
    SETTINGS_UI_SETTINGS_THEME_DESC = USER_SETTINGS_STRINGS.UI_SETTINGS_THEME_DESC
    SETTINGS_UI_SETTINGS_THEME_LIGHT = USER_SETTINGS_STRINGS.UI_SETTINGS_THEME_LIGHT
    SETTINGS_UI_SETTINGS_THEME_DARK = USER_SETTINGS_STRINGS.UI_SETTINGS_THEME_DARK
    SETTINGS_UI_SETTINGS_THEME_SYSTEM = USER_SETTINGS_STRINGS.UI_SETTINGS_THEME_SYSTEM
    SETTINGS_UI_SETTINGS_VIEW_LABEL = USER_SETTINGS_STRINGS.UI_SETTINGS_VIEW_LABEL
    SETTINGS_UI_SETTINGS_VIEW_DESC = USER_SETTINGS_STRINGS.UI_SETTINGS_VIEW_DESC
    SETTINGS_UI_SETTINGS_VIEW_OPTION_LIST = (
        USER_SETTINGS_STRINGS.UI_SETTINGS_VIEW_OPTION_LIST
    )
    SETTINGS_UI_SETTINGS_VIEW_OPTION_COMPACT = (
        USER_SETTINGS_STRINGS.UI_SETTINGS_VIEW_OPTION_COMPACT
    )
    SETTINGS_UI_SETTINGS_VIEW_OPTION_CARDS = (
        USER_SETTINGS_STRINGS.UI_SETTINGS_VIEW_OPTION_CARDS
    )
    SETTINGS_UI_SETTINGS_SORT_LABEL = USER_SETTINGS_STRINGS.UI_SETTINGS_SORT_LABEL
    SETTINGS_UI_SETTINGS_SORT_DESC = USER_SETTINGS_STRINGS.UI_SETTINGS_SORT_DESC
    SETTINGS_UI_SETTINGS_SORT_OPTION_NEWEST = (
        USER_SETTINGS_STRINGS.UI_SETTINGS_SORT_OPTION_NEWEST
    )
    SETTINGS_UI_SETTINGS_SORT_OPTION_OLDEST = (
        USER_SETTINGS_STRINGS.UI_SETTINGS_SORT_OPTION_OLDEST
    )
    SETTINGS_UI_SETTINGS_SORT_OPTION_TITLE_AZ = (
        USER_SETTINGS_STRINGS.UI_SETTINGS_SORT_OPTION_TITLE_AZ
    )
    SETTINGS_UI_SETTINGS_DENSITY_LABEL = USER_SETTINGS_STRINGS.UI_SETTINGS_DENSITY_LABEL
    SETTINGS_UI_SETTINGS_DENSITY_DESC = USER_SETTINGS_STRINGS.UI_SETTINGS_DENSITY_DESC
    SETTINGS_UI_SETTINGS_DENSITY_OPTION_COMFORTABLE = (
        USER_SETTINGS_STRINGS.UI_SETTINGS_DENSITY_OPTION_COMFORTABLE
    )
    SETTINGS_UI_SETTINGS_DENSITY_OPTION_COMPACT = (
        USER_SETTINGS_STRINGS.UI_SETTINGS_DENSITY_OPTION_COMPACT
    )
    SETTINGS_UI_SETTINGS_DATE_FORMAT_LABEL = (
        USER_SETTINGS_STRINGS.UI_SETTINGS_DATE_FORMAT_LABEL
    )
    SETTINGS_UI_SETTINGS_DATE_FORMAT_DESC = (
        USER_SETTINGS_STRINGS.UI_SETTINGS_DATE_FORMAT_DESC
    )
    SETTINGS_UI_SETTINGS_DATE_FORMAT_OPTION_ISO = (
        USER_SETTINGS_STRINGS.UI_SETTINGS_DATE_FORMAT_OPTION_ISO
    )
    SETTINGS_UI_SETTINGS_DATE_FORMAT_OPTION_US = (
        USER_SETTINGS_STRINGS.UI_SETTINGS_DATE_FORMAT_OPTION_US
    )
    SETTINGS_UI_SETTINGS_DATE_FORMAT_OPTION_EU = (
        USER_SETTINGS_STRINGS.UI_SETTINGS_DATE_FORMAT_OPTION_EU
    )
    SETTINGS_PREFERENCES_SAVED = USER_SETTINGS_STRINGS.PREFERENCES_SAVED


class CONSTANTS:
    EMAILS = EMAIL_CONSTANTS()
    USERS = USER_CONSTANTS()
    UTUBS = UTUB_CONSTANTS()
    URLS = URL_CONSTANTS()
    TAGS = TAG_CONSTANTS()
    CONFIG = CONFIG_CONSTANTS()
    STRINGS = STRINGS()
    SPLASH = SPLASH_CONSTANTS()
    SEARCH = SEARCH_CONSTANTS()


def generate_constants_js() -> (
    dict[str, int | list[str] | dict[str, str] | dict[str, int]]
):
    """
    Generate constants configuration for frontend JavaScript.
    Returns a dict that can be passed to Jinja and converted to JSON.
    """
    return {
        # Member roles
        "MEMBER_ROLES": {
            role.name: role.value for role in CONSTANTS.UTUBS.MEMBER_ROLES
        },
        # UTub constants
        "UTUBS_MAX_NAME_LENGTH": CONSTANTS.UTUBS.MAX_NAME_LENGTH,
        "UTUBS_MIN_NAME_LENGTH": CONSTANTS.UTUBS.MIN_NAME_LENGTH,
        "UTUBS_MAX_DESCRIPTION_LENGTH": CONSTANTS.UTUBS.MAX_DESCRIPTION_LENGTH,
        # URL constants
        "URLS_TITLE_MIN_LENGTH": CONSTANTS.URLS.MIN_URL_TITLE_LENGTH,
        "URLS_TITLE_MAX_LENGTH": CONSTANTS.URLS.MAX_URL_TITLE_LENGTH,
        "URLS_MIN_LENGTH": CONSTANTS.URLS.MIN_URL_LENGTH,
        "URLS_MAX_LENGTH": CONSTANTS.URLS.MAX_URL_LENGTH,
        # Tag constants
        "TAGS_MIN_LENGTH": CONSTANTS.TAGS.MIN_TAG_LENGTH,
        "TAGS_MAX_LENGTH": CONSTANTS.TAGS.MAX_TAG_LENGTH,
        "TAGS_MAX_ON_URLS": CONSTANTS.TAGS.MAX_URL_TAGS,
        # Splash constants
        "VALIDATE_EMAIL_ERROR_CODES": {
            error_code.name: error_code.value
            for error_code in CONSTANTS.SPLASH.EMAIL_VALIDATION_ERROR_CODES
        },
        # Metrics dimension allow-list (source of truth: DIMENSION_MODELS)
        "DIMENSION_KEYS": list(get_all_dimension_keys()),
        # Metrics device-type wire values (source of truth: backend.metrics.events.DeviceType)
        "DEVICE_TYPE": {member.name: member.value for member in DeviceType},
        # Backend-defined JSONB key for the device_type dimension — frontend
        # references via APP_CONFIG.constants.DEVICE_TYPE_DIM_KEY when building
        # /api/metrics/query/* URLSearchParams.
        "DEVICE_TYPE_DIM_KEY": DEVICE_TYPE_DIM_KEY,
    }


def generate_strings_js() -> dict[str, str]:
    """
    Generate strings configuration for frontend JavaScript.
    Returns a dict that can be passed to Jinja and converted to JSON.
    """

    return {
        # Query Param Strings
        "UTUB_QUERY_PARAM": CONSTANTS.STRINGS.UTUB_QUERY_PARAM,
        "MOBILE_PANEL_QUERY_PARAM": CONSTANTS.STRINGS.MOBILE_PANEL_QUERY_PARAM,
        "EMAIL_CHANGE_STATUS_QUERY_PARAM": CONSTANTS.STRINGS.EMAIL_CHANGE_STATUS_QUERY_PARAM,
        "MOBILE_PANEL_ANNOUNCEMENT_UTUBS": CONSTANTS.STRINGS.MOBILE_PANEL_ANNOUNCEMENT_UTUBS,
        "MOBILE_PANEL_ANNOUNCEMENT_URLS": CONSTANTS.STRINGS.MOBILE_PANEL_ANNOUNCEMENT_URLS,
        "MOBILE_PANEL_ANNOUNCEMENT_MEMBERS": CONSTANTS.STRINGS.MOBILE_PANEL_ANNOUNCEMENT_MEMBERS,
        "UTUB_NO_LONGER_AVAILABLE": CONSTANTS.STRINGS.UTUB_NO_LONGER_AVAILABLE,
        # Admin action strings
        "ADMIN_ACTION_REASON_LABEL": CONSTANTS.STRINGS.ADMIN_ACTION_REASON_LABEL,
        "ADMIN_ACTION_REASON_REQUIRED": CONSTANTS.STRINGS.ADMIN_ACTION_REASON_REQUIRED,
        "ADMIN_ACTION_GENERIC_ERROR": CONSTANTS.STRINGS.ADMIN_ACTION_GENERIC_ERROR,
        "ADMIN_ACTION_SUBMIT_DEFAULT": CONSTANTS.STRINGS.ADMIN_ACTION_SUBMIT_DEFAULT,
        "ADMIN_ACTION_DISMISS": CONSTANTS.STRINGS.ADMIN_ACTION_DISMISS,
        "ADMIN_ACTION_SUCCESS_DEFAULT": CONSTANTS.STRINGS.ADMIN_ACTION_SUCCESS_DEFAULT,
        # Splash strings
        "VALIDATE_MY_EMAIL": CONSTANTS.STRINGS.VALIDATE_MY_EMAIL,
        "VALIDATE_YOUR_EMAIL": CONSTANTS.STRINGS.VALIDATE_YOUR_EMAIL,
        "FORGOT_YOUR_PASSWORD": CONSTANTS.STRINGS.FORGOT_YOUR_PASSWORD,
        "LOGIN_TITLE": CONSTANTS.STRINGS.LOGIN_TITLE,
        "REGISTRATION_EMAIL_RESEND_SENDING": (
            CONSTANTS.STRINGS.REGISTRATION_EMAIL_RESEND_SENDING
        ),
        "REGISTRATION_EMAIL_RESENT": CONSTANTS.STRINGS.REGISTRATION_EMAIL_RESENT,
        "REGISTRATION_EMAIL_RESEND_ERROR": (
            CONSTANTS.STRINGS.REGISTRATION_EMAIL_RESEND_ERROR
        ),
        # General Strings
        "MAY_HAVE_ALREADY_BEEN_DELETED": CONSTANTS.STRINGS.MAY_HAVE_ALREADY_BEEN_DELETED,
        # UTub Strings
        "UTUB_CREATE_SAME_NAME": CONSTANTS.STRINGS.UTUB_CREATE_SAME_NAME,
        "UTUB_UPDATE_SAME_NAME": CONSTANTS.STRINGS.UTUB_UPDATE_SAME_NAME,
        "UTUB_DELETE_WARNING": CONSTANTS.STRINGS.UTUB_DELETE_WARNING,
        "UTUB_CREATE_MSG": CONSTANTS.STRINGS.UTUB_CREATE_MSG,
        "UTUB_SELECT": CONSTANTS.STRINGS.UTUB_SELECT,
        "FIELD_SAVED": CONSTANTS.STRINGS.FIELD_SAVED,
        "FIELD_SAVED_LABEL_UTUB_NAME": CONSTANTS.STRINGS.FIELD_SAVED_LABEL_UTUB_NAME,
        "FIELD_SAVED_LABEL_UTUB_DESCRIPTION": (
            CONSTANTS.STRINGS.FIELD_SAVED_LABEL_UTUB_DESCRIPTION
        ),
        "FIELD_SAVED_LABEL_URL_TITLE": CONSTANTS.STRINGS.FIELD_SAVED_LABEL_URL_TITLE,
        "FIELD_SAVED_LABEL_URL": CONSTANTS.STRINGS.FIELD_SAVED_LABEL_URL,
        "URL_ADDED_ANNOUNCEMENT": CONSTANTS.STRINGS.URL_ADDED_ANNOUNCEMENT,
        "UTUB_IS_LOCKED": CONSTANTS.STRINGS.UTUB_IS_LOCKED,
        "UTUB_SEARCH_NO_RESULTS": CONSTANTS.STRINGS.UTUB_SEARCH_NO_RESULTS,
        "UTUB_SEARCH_PLACEHOLDER": CONSTANTS.STRINGS.UTUB_SEARCH_PLACEHOLDER,
        "UTUB_SEARCH_COUNT_TEMPLATE": CONSTANTS.STRINGS.UTUB_SEARCH_COUNT_TEMPLATE,
        # Member Strings
        "MEMBER_DELETE_WARNING": CONSTANTS.STRINGS.MEMBER_DELETE_WARNING,
        "MEMBER_LEAVE_WARNING": CONSTANTS.STRINGS.MEMBER_LEAVE_WARNING,
        "MEMBER_SEARCH_NO_RESULTS": CONSTANTS.STRINGS.MEMBER_SEARCH_NO_RESULTS,
        "MEMBER_SEARCH_PLACEHOLDER": CONSTANTS.STRINGS.MEMBER_SEARCH_PLACEHOLDER,
        "MEMBER_SEARCH_COUNT_TEMPLATE": CONSTANTS.STRINGS.MEMBER_SEARCH_COUNT_TEMPLATE,
        # URL Strings
        "DELETE_URL_WARNING": CONSTANTS.STRINGS.DELETE_URL_WARNING,
        "INVALID_URL": CONSTANTS.STRINGS.UNABLE_TO_VALIDATE_THIS_URL,
        "ACCESS_URL_WARNING": CONSTANTS.STRINGS.ACCESS_URL_WARNING,
        "URL_SEARCH_NO_RESULTS": CONSTANTS.STRINGS.URL_SEARCH_NO_RESULTS,
        # Multi-select bulk-action bar SR announcements (bulk-actions/bulk-bar.ts)
        "URL_BULK_SELECTED_COUNT": CONSTANTS.STRINGS.URL_BULK_SELECTED_COUNT,
        "URL_BULK_SELECTED_COUNT_ONE": CONSTANTS.STRINGS.URL_BULK_SELECTED_COUNT_ONE,
        "URL_BULK_NONE_SELECTED": CONSTANTS.STRINGS.URL_BULK_NONE_SELECTED,
        "URL_BULK_N_HIDDEN": CONSTANTS.STRINGS.URL_BULK_N_HIDDEN,
        "UTUB_NO_URLS": CONSTANTS.STRINGS.UTUB_NO_URLS,
        "ADD_URL_BUTTON": CONSTANTS.STRINGS.ADD_URL_BUTTON,
        # URL card date-added attribution badge — static label words (cards.ts
        # composes the dynamic username/date around them).
        "URL_ADDED_BY": CONSTANTS.STRINGS.URL_ADDED_BY,
        "URL_ADDED_ON": CONSTANTS.STRINGS.URL_ADDED_ON,
        "URL_DATE_ADDED_LABEL": CONSTANTS.STRINGS.URL_DATE_ADDED_LABEL,
        "URL_DATE_ADDED_ARIA": CONSTANTS.STRINGS.URL_DATE_ADDED_ARIA,
        # Cross-UTub Search Strings
        "CROSS_SEARCH_NO_RESULTS": CONSTANTS.STRINGS.CROSS_SEARCH_NO_RESULTS,
        "CROSS_SEARCH_SHORT_QUERY": CONSTANTS.STRINGS.CROSS_SEARCH_SHORT_QUERY,
        "CROSS_SEARCH_PLACEHOLDER": CONSTANTS.STRINGS.CROSS_SEARCH_PLACEHOLDER,
        "CROSS_SEARCH_COUNT_TEMPLATE": CONSTANTS.STRINGS.CROSS_SEARCH_COUNT_TEMPLATE,
        "CROSS_SEARCH_FIELD_URL": CONSTANTS.STRINGS.CROSS_SEARCH_FIELD_URL,
        "CROSS_SEARCH_FIELD_TITLE": CONSTANTS.STRINGS.CROSS_SEARCH_FIELD_TITLE,
        "CROSS_SEARCH_FIELD_TAG": CONSTANTS.STRINGS.CROSS_SEARCH_FIELD_TAG,
        "CROSS_SEARCH_HISTORY_HEADING": CONSTANTS.STRINGS.CROSS_SEARCH_HISTORY_HEADING,
        "CROSS_SEARCH_HISTORY_CLEAR": CONSTANTS.STRINGS.CROSS_SEARCH_HISTORY_CLEAR,
        "CROSS_SEARCH_TRIGGER_OPEN_LABEL": CONSTANTS.STRINGS.CROSS_SEARCH_TRIGGER_OPEN_LABEL,
        "CROSS_SEARCH_TRIGGER_CLOSE_LABEL": CONSTANTS.STRINGS.CROSS_SEARCH_TRIGGER_CLOSE_LABEL,
        "CROSS_SEARCH_SUBMIT_LABEL": CONSTANTS.STRINGS.CROSS_SEARCH_SUBMIT_LABEL,
        "CROSS_SEARCH_REFRESH_LABEL": CONSTANTS.STRINGS.CROSS_SEARCH_REFRESH_LABEL,
        # Tag Strings
        "UTUB_TAG_DELETE_WARNING": CONSTANTS.STRINGS.UTUB_TAG_DELETE_WARNING,
        "TAG_FILTER_NO_RESULTS": CONSTANTS.STRINGS.TAG_FILTER_NO_RESULTS,
        "TAG_SEARCH_NO_RESULTS": CONSTANTS.STRINGS.TAG_SEARCH_NO_RESULTS,
        "TAG_SEARCH_PLACEHOLDER": CONSTANTS.STRINGS.TAG_SEARCH_PLACEHOLDER,
        "TAG_SEARCH_COUNT_TEMPLATE": CONSTANTS.STRINGS.TAG_SEARCH_COUNT_TEMPLATE,
        "TAG_DECK_NO_TAGS": CONSTANTS.STRINGS.TAG_DECK_NO_TAGS,
        "TAG_SHEET_ANNOUNCEMENT_OPEN": CONSTANTS.STRINGS.TAG_SHEET_ANNOUNCEMENT_OPEN,
        "TAG_SHEET_ANNOUNCEMENT_CLOSE": CONSTANTS.STRINGS.TAG_SHEET_ANNOUNCEMENT_CLOSE,
        # Combobox (multi-tag apply) Strings
        "ADD_TAGS_PLACEHOLDER": CONSTANTS.STRINGS.ADD_TAGS_PLACEHOLDER,
        "ADD_TAGS_SUBMIT": CONSTANTS.STRINGS.ADD_TAGS_SUBMIT,
        "ADD_TAGS_ARIA_LABEL": CONSTANTS.STRINGS.ADD_TAGS_ARIA_LABEL,
        "TAGS_OPTIONAL_LABEL": CONSTANTS.STRINGS.TAGS_OPTIONAL_LABEL,
        "TAG_CREATE_NEW": CONSTANTS.STRINGS.TAG_CREATE_NEW,
        "TAGS_LIMIT_REACHED": CONSTANTS.STRINGS.TAGS_LIMIT_REACHED,
        "TAGS_NO_MATCHES": CONSTANTS.STRINGS.TAGS_NO_MATCHES,
        "TAGS_MATCH_COUNT": CONSTANTS.STRINGS.TAGS_MATCH_COUNT,
        "TAGS_MATCH_COUNT_ONE": CONSTANTS.STRINGS.TAGS_MATCH_COUNT_ONE,
        "TAGS_EMPTY_HINT": CONSTANTS.STRINGS.TAGS_EMPTY_HINT,
        # Bulk multi-URL tag-apply Strings (Phase 2)
        "URL_BULK_ADD_TAGS_ARIA": CONSTANTS.STRINGS.URL_BULK_ADD_TAGS_ARIA,
        "URL_BULK_TAGS_APPLIED": CONSTANTS.STRINGS.URL_BULK_TAGS_APPLIED,
        "URL_BULK_TAGS_APPLIED_ONE": CONSTANTS.STRINGS.URL_BULK_TAGS_APPLIED_ONE,
        "URL_BULK_TAGS_PARTIAL": CONSTANTS.STRINGS.URL_BULK_TAGS_PARTIAL,
        "URL_BULK_TAGS_NONE": CONSTANTS.STRINGS.URL_BULK_TAGS_NONE,
        "URL_BULK_TAGS_NONE_SOME_SKIPPED": CONSTANTS.STRINGS.URL_BULK_TAGS_NONE_SOME_SKIPPED,
        "URL_BULK_TAGS_NO_CHANGES": CONSTANTS.STRINGS.URL_BULK_TAGS_NO_CHANGES,
        "URL_BULK_CARD_APPLIED": CONSTANTS.STRINGS.URL_BULK_CARD_APPLIED,
        "URL_BULK_CARD_SKIPPED": CONSTANTS.STRINGS.URL_BULK_CARD_SKIPPED,
        "URL_BULK_TAGS_STALE_SELECTION": CONSTANTS.STRINGS.URL_BULK_TAGS_STALE_SELECTION,
        "URL_BULK_TAGS_SUBMITTING": CONSTANTS.STRINGS.URL_BULK_TAGS_SUBMITTING,
        # Bulk copy-to-UTub Strings (Phase 3) — read by bulk-actions/bulk-copy.ts
        "URLS_COPIED": CONSTANTS.STRINGS.URLS_COPIED,
        "URLS_COPIED_PARTIAL": CONSTANTS.STRINGS.URLS_COPIED_PARTIAL,
        "URLS_COPY_NONE_NEW": CONSTANTS.STRINGS.URLS_COPY_NONE_NEW,
        "URL_BULK_CARD_COPIED": CONSTANTS.STRINGS.URL_BULK_CARD_COPIED,
        "URL_BULK_CARD_ALREADY_THERE": CONSTANTS.STRINGS.URL_BULK_CARD_ALREADY_THERE,
        "URL_BULK_COPY_LABEL": CONSTANTS.STRINGS.URL_BULK_COPY_LABEL,
        "URL_BULK_COPY_SUBMITTING": CONSTANTS.STRINGS.URL_BULK_COPY_SUBMITTING,
        "URL_BULK_COPY_ALL_LOCKED": CONSTANTS.STRINGS.URL_BULK_COPY_ALL_LOCKED,
        "URL_BULK_COPY_ARIA": CONSTANTS.STRINGS.URL_BULK_COPY_ARIA,
        "URL_BULK_COPY_FILTER_PLACEHOLDER": CONSTANTS.STRINGS.URL_BULK_COPY_FILTER_PLACEHOLDER,
        "URL_BULK_COPY_NO_MATCHES": CONSTANTS.STRINGS.URL_BULK_COPY_NO_MATCHES,
        "UNABLE_TO_COPY_URLS": CONSTANTS.STRINGS.UNABLE_TO_COPY_URLS,
        # Tooltips
        "COPY_URL_TOOLTIP": CONSTANTS.STRINGS.COPY_URL_TOOLTIP,
        "COPIED_URL_TOOLTIP": CONSTANTS.STRINGS.COPIED_URL_TOOLTIP,
        "COPIED_URL_FAILURE_TOOLIP": CONSTANTS.STRINGS.COPIED_URL_FAILURE_TOOLIP,
        "ACCESS_URL_TOOLTIP": CONSTANTS.STRINGS.ACCESS_URL_TOOLTIP,
        "ADD_URL_TAG_TOOLTIP": CONSTANTS.STRINGS.ADD_URL_TAG_TOOLTIP,
        "EDIT_URL_TOOLTIP": CONSTANTS.STRINGS.EDIT_URL_TOOLTIP,
        "EDIT_URL_TITLE_TOOLTIP": CONSTANTS.STRINGS.EDIT_URL_TITLE_TOOLTIP,
        "DELETE_URL_TOOLTIP": CONSTANTS.STRINGS.DELETE_URL_TOOLTIP,
        "COOKIE_BANNER_SEEN": CONSTANTS.STRINGS.COOKIE_BANNER_SEEN,
        "COOKIE_BANNER_KEY": CONSTANTS.STRINGS.COOKIE_BANNER_KEY,
        # Admin Metrics Dashboard Strings
        "METRICS_TIMESERIES_SELECT_ARIA": CONSTANTS.STRINGS.METRICS_TIMESERIES_SELECT_ARIA,
        "METRICS_LAST_FLUSH_UNKNOWN": CONSTANTS.STRINGS.METRICS_LAST_FLUSH_UNKNOWN,
        "METRICS_LAST_FLUSH_JUST_NOW": CONSTANTS.STRINGS.METRICS_LAST_FLUSH_JUST_NOW,
        "METRICS_LAST_FLUSH_SECONDS": CONSTANTS.STRINGS.METRICS_LAST_FLUSH_SECONDS,
        "METRICS_LAST_FLUSH_MINUTES": CONSTANTS.STRINGS.METRICS_LAST_FLUSH_MINUTES,
        "METRICS_LAST_FLUSH_STALE_MINUTES": CONSTANTS.STRINGS.METRICS_LAST_FLUSH_STALE_MINUTES,
        "METRICS_LAST_FLUSH_STALE_HOURS": CONSTANTS.STRINGS.METRICS_LAST_FLUSH_STALE_HOURS,
        "METRICS_LAST_EVENT_UNKNOWN": CONSTANTS.STRINGS.METRICS_LAST_EVENT_UNKNOWN,
        "METRICS_LAST_EVENT_JUST_NOW": CONSTANTS.STRINGS.METRICS_LAST_EVENT_JUST_NOW,
        "METRICS_LAST_EVENT_SECONDS": CONSTANTS.STRINGS.METRICS_LAST_EVENT_SECONDS,
        "METRICS_LAST_EVENT_MINUTES": CONSTANTS.STRINGS.METRICS_LAST_EVENT_MINUTES,
        "METRICS_LAST_EVENT_HOURS": CONSTANTS.STRINGS.METRICS_LAST_EVENT_HOURS,
        "METRICS_EMPTY_STATE": CONSTANTS.STRINGS.METRICS_EMPTY_STATE,
        "METRICS_FETCH_FAILED_BANNER": CONSTANTS.STRINGS.METRICS_FETCH_FAILED_BANNER,
        "METRICS_SUMMARY_TOTAL_EVENTS": CONSTANTS.STRINGS.METRICS_SUMMARY_TOTAL_EVENTS,
        "METRICS_SUMMARY_API_HITS": CONSTANTS.STRINGS.METRICS_SUMMARY_API_HITS,
        "METRICS_SUMMARY_UI_EVENTS": CONSTANTS.STRINGS.METRICS_SUMMARY_UI_EVENTS,
        "METRICS_SUMMARY_DOMAIN_ACTIONS": CONSTANTS.STRINGS.METRICS_SUMMARY_DOMAIN_ACTIONS,
        "METRICS_SUMMARY_DELTA_SUFFIX": CONSTANTS.STRINGS.METRICS_SUMMARY_DELTA_SUFFIX,
        "METRICS_SUMMARY_DELTA_UNAVAILABLE": CONSTANTS.STRINGS.METRICS_SUMMARY_DELTA_UNAVAILABLE,
        "METRICS_TOP_TABLE_HEADER_RANK": CONSTANTS.STRINGS.METRICS_TOP_TABLE_HEADER_RANK,
        "METRICS_TOP_TABLE_HEADER_ENDPOINT": CONSTANTS.STRINGS.METRICS_TOP_TABLE_HEADER_ENDPOINT,
        "METRICS_TOP_TABLE_HEADER_EVENT": CONSTANTS.STRINGS.METRICS_TOP_TABLE_HEADER_EVENT,
        "METRICS_TOP_TABLE_HEADER_ACTION": CONSTANTS.STRINGS.METRICS_TOP_TABLE_HEADER_ACTION,
        "METRICS_TOP_TABLE_HEADER_HITS": CONSTANTS.STRINGS.METRICS_TOP_TABLE_HEADER_HITS,
        "METRICS_TOP_TABLE_HEADER_DELTA": CONSTANTS.STRINGS.METRICS_TOP_TABLE_HEADER_DELTA,
        "METRICS_TOP_TABLE_ROW_ARIA": CONSTANTS.STRINGS.METRICS_TOP_TABLE_ROW_ARIA,
        "METRICS_CHART_Y_AXIS_LABEL": CONSTANTS.STRINGS.METRICS_CHART_Y_AXIS_LABEL,
        "METRICS_TOP_RESOURCE_ALL": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_ALL,
        "METRICS_TOP_RESOURCE_UTUB": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_UTUB,
        "METRICS_TOP_RESOURCE_URL": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_URL,
        "METRICS_TOP_RESOURCE_TAG": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_TAG,
        "METRICS_TOP_RESOURCE_MEMBER": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_MEMBER,
        "METRICS_TOP_RESOURCE_AUTH": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_AUTH,
        "METRICS_TOP_RESOURCE_SEARCH": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_SEARCH,
        "METRICS_TOP_RESOURCE_FORM": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_FORM,
        "METRICS_TOP_RESOURCE_DECK": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_DECK,
        "METRICS_TOP_RESOURCE_NAV": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_NAV,
        "METRICS_TOP_RESOURCE_ERROR": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_ERROR,
        "METRICS_TOP_RESOURCE_CONTACT": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_CONTACT,
        "METRICS_TOP_RESOURCE_ADMIN": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_ADMIN,
        "METRICS_TOP_RESOURCE_OTHER": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_OTHER,
        "METRICS_TOP_DEVICE_ALL": CONSTANTS.STRINGS.METRICS_TOP_DEVICE_ALL,
        "METRICS_TOP_DEVICE_MOBILE": CONSTANTS.STRINGS.METRICS_TOP_DEVICE_MOBILE,
        "METRICS_TOP_DEVICE_DESKTOP": CONSTANTS.STRINGS.METRICS_TOP_DEVICE_DESKTOP,
        "METRICS_TOP_EMPTY_NO_MATCHES": CONSTANTS.STRINGS.METRICS_TOP_EMPTY_NO_MATCHES,
        "METRICS_PIPELINE_HEALTH_TITLE": (
            CONSTANTS.STRINGS.METRICS_PIPELINE_HEALTH_TITLE
        ),
        "METRICS_PIPELINE_HEALTH_EMPTY_STATE": (
            CONSTANTS.STRINGS.METRICS_PIPELINE_HEALTH_EMPTY_STATE
        ),
        "METRICS_PIPELINE_HEALTH_AXIS_LABEL": (
            CONSTANTS.STRINGS.METRICS_PIPELINE_HEALTH_AXIS_LABEL
        ),
        "METRICS_PIPELINE_HEALTH_AXIS_LABEL_X": (
            CONSTANTS.STRINGS.METRICS_PIPELINE_HEALTH_AXIS_LABEL_X
        ),
        "METRICS_PIPELINE_HEALTH_LEGEND_FETCH_DESKTOP": (
            CONSTANTS.STRINGS.METRICS_PIPELINE_HEALTH_LEGEND_FETCH_DESKTOP
        ),
        "METRICS_PIPELINE_HEALTH_LEGEND_FETCH_MOBILE": (
            CONSTANTS.STRINGS.METRICS_PIPELINE_HEALTH_LEGEND_FETCH_MOBILE
        ),
        "METRICS_PIPELINE_HEALTH_LEGEND_BEACON_DESKTOP": (
            CONSTANTS.STRINGS.METRICS_PIPELINE_HEALTH_LEGEND_BEACON_DESKTOP
        ),
        "METRICS_PIPELINE_HEALTH_LEGEND_BEACON_MOBILE": (
            CONSTANTS.STRINGS.METRICS_PIPELINE_HEALTH_LEGEND_BEACON_MOBILE
        ),
        "METRICS_PIPELINE_HEALTH_CHART_DESC": (
            CONSTANTS.STRINGS.METRICS_PIPELINE_HEALTH_CHART_DESC
        ),
        "METRICS_FLOW_SUCCEEDED": CONSTANTS.STRINGS.METRICS_FLOW_SUCCEEDED,
        "METRICS_FLOW_CONVERSION": CONSTANTS.STRINGS.METRICS_FLOW_CONVERSION,
        "METRICS_FLOW_DROPOFF": CONSTANTS.STRINGS.METRICS_FLOW_DROPOFF,
        "METRICS_FLOW_CATEGORY_UI": CONSTANTS.STRINGS.METRICS_FLOW_CATEGORY_UI,
        "METRICS_FLOW_CATEGORY_API": CONSTANTS.STRINGS.METRICS_FLOW_CATEGORY_API,
        "METRICS_FLOW_CATEGORY_DOMAIN": (
            CONSTANTS.STRINGS.METRICS_FLOW_CATEGORY_DOMAIN
        ),
        "METRICS_FLOW_EMPTY": CONSTANTS.STRINGS.METRICS_FLOW_EMPTY,
        "METRICS_FLOWS_LOADED": CONSTANTS.STRINGS.METRICS_FLOWS_LOADED,
        "METRICS_GAUGE_KIND_VOLUME": CONSTANTS.STRINGS.METRICS_GAUGE_KIND_VOLUME,
        "METRICS_GAUGE_KIND_DISTRIBUTION_MAX": (
            CONSTANTS.STRINGS.METRICS_GAUGE_KIND_DISTRIBUTION_MAX
        ),
        "METRICS_GAUGE_KIND_DISTRIBUTION_AVG": (
            CONSTANTS.STRINGS.METRICS_GAUGE_KIND_DISTRIBUTION_AVG
        ),
        "METRICS_GAUGE_SUPPRESSED_ARIA": (
            CONSTANTS.STRINGS.METRICS_GAUGE_SUPPRESSED_ARIA
        ),
        "METRICS_GAUGES_LOADED": CONSTANTS.STRINGS.METRICS_GAUGES_LOADED,
        "METRICS_GAUGE_SELECT_PROMPT": CONSTANTS.STRINGS.METRICS_GAUGE_SELECT_PROMPT,
        "METRICS_GAUGE_COL_NAME": CONSTANTS.STRINGS.METRICS_GAUGE_COL_NAME,
        "METRICS_GAUGE_COL_VALUE": CONSTANTS.STRINGS.METRICS_GAUGE_COL_VALUE,
        "METRICS_GAUGES_EMPTY": CONSTANTS.STRINGS.METRICS_GAUGES_EMPTY,
        "METRICS_TAB_LATENCY": CONSTANTS.STRINGS.METRICS_TAB_LATENCY,
        "METRICS_LATENCY_EMPTY": CONSTANTS.STRINGS.METRICS_LATENCY_EMPTY,
        "METRICS_LATENCY_SELECT_PROMPT": (
            CONSTANTS.STRINGS.METRICS_LATENCY_SELECT_PROMPT
        ),
        "METRICS_LATENCY_COL_ENDPOINT": (
            CONSTANTS.STRINGS.METRICS_LATENCY_COL_ENDPOINT
        ),
        "METRICS_LATENCY_COL_P50": CONSTANTS.STRINGS.METRICS_LATENCY_COL_P50,
        "METRICS_LATENCY_COL_P95": CONSTANTS.STRINGS.METRICS_LATENCY_COL_P95,
        "METRICS_LATENCY_COL_P99": CONSTANTS.STRINGS.METRICS_LATENCY_COL_P99,
        "METRICS_LATENCY_COL_SAMPLES": (CONSTANTS.STRINGS.METRICS_LATENCY_COL_SAMPLES),
        "METRICS_LATENCY_Y_AXIS_LABEL": (
            CONSTANTS.STRINGS.METRICS_LATENCY_Y_AXIS_LABEL
        ),
        "METRICS_LATENCY_ROW_ARIA": CONSTANTS.STRINGS.METRICS_LATENCY_ROW_ARIA,
        "METRICS_LATENCY_SERIES_ARIA_P50": (
            CONSTANTS.STRINGS.METRICS_LATENCY_SERIES_ARIA_P50
        ),
        "METRICS_LATENCY_SERIES_ARIA_P95": (
            CONSTANTS.STRINGS.METRICS_LATENCY_SERIES_ARIA_P95
        ),
        "METRICS_LATENCY_SERIES_ARIA_P99": (
            CONSTANTS.STRINGS.METRICS_LATENCY_SERIES_ARIA_P99
        ),
        "METRICS_LATENCY_APPROXIMATE_NOTE": (
            CONSTANTS.STRINGS.METRICS_LATENCY_APPROXIMATE_NOTE
        ),
        "METRICS_LATENCY_DAILY_RESOLUTION_NOTE": (
            CONSTANTS.STRINGS.METRICS_LATENCY_DAILY_RESOLUTION_NOTE
        ),
        # Settings — change-email pending-note (DD-6). Bridged because
        # change-email.ts reads it via APP_CONFIG.strings on a successful submit
        # to patch the account-info card in place. Must stay verbatim-in-sync
        # with the Jinja-only SETTINGS_ACCOUNT_PENDING_EMAIL_INITIAL_NOTE (DD-18).
        "SETTINGS_ACCOUNT_PENDING_EMAIL_NOTE": (
            CONSTANTS.STRINGS.SETTINGS_ACCOUNT_PENDING_EMAIL_NOTE
        ),
        # Settings — Privacy & Data export status/error copy (Phase 5). Bridged
        # because data-export.ts / account-removal.ts write these into the DOM via
        # APP_CONFIG.strings (in-panel status region + cross-panel guard notices).
        "SETTINGS_EXPORT_PREPARING": CONSTANTS.STRINGS.SETTINGS_EXPORT_PREPARING,
        "SETTINGS_EXPORT_STARTED": CONSTANTS.STRINGS.SETTINGS_EXPORT_STARTED,
        "SETTINGS_EXPORT_ERROR": CONSTANTS.STRINGS.SETTINGS_EXPORT_ERROR,
        "SETTINGS_DELETE_BLOCKED_BY_EXPORT": (
            CONSTANTS.STRINGS.SETTINGS_DELETE_BLOCKED_BY_EXPORT
        ),
        "SETTINGS_EXPORT_BLOCKED_BY_DELETE": (
            CONSTANTS.STRINGS.SETTINGS_EXPORT_BLOCKED_BY_DELETE
        ),
        "SETTINGS_PREFERENCES_SAVED": CONSTANTS.STRINGS.SETTINGS_PREFERENCES_SAVED,
    }


def provide_config_for_constants() -> dict:
    """
    Provides configuration to templates:
    - CONSTANTS: Python objects for Jinja template rendering
    - CONFIG: JSON-serializable dict for JavaScript
    - google_oauth_enabled / github_oauth_enabled: whether each provider's
      OAuth button/routes should be exposed to the user, per whether that
      provider's credentials are configured
    """
    routes = generate_routes_js()
    if current_user.is_authenticated and current_user.is_admin():
        routes.update(generate_admin_routes_js())
    debug_enabled = current_app.config["DEBUG"] or (
        current_user.is_authenticated and current_user.is_admin()
    )
    # Resolved theme for the app-wide pre-paint <html data-theme> stamp
    # (layout.html). Rendered into <head> — NOT the <body> CONFIG JSON blob —
    # so it lands before styles paint and avoids a light/dark flash. Anonymous
    # users (and authenticated users with no UserPreferences row) resolve to the
    # shared ``Theme.SYSTEM`` ("system") default via ``resolve_preferences``.
    preferences_row = (
        current_user.preferences if current_user.is_authenticated else None
    )
    user_theme = resolve_preferences(preferences_row).theme.value
    return dict(
        CONSTANTS=CONSTANTS(),
        user_theme=user_theme,
        CONFIG=dict(
            routes=routes,
            constants=generate_constants_js(),
            strings=generate_strings_js(),
            debugEnabled=debug_enabled,
        ),
        current_year=utc_now().year,
        google_oauth_enabled=should_register_google_oauth(
            current_app.config.get("GOOGLE_OAUTH_CLIENT_ID"),
            current_app.config.get("GOOGLE_OAUTH_CLIENT_SECRET"),
        ),
        github_oauth_enabled=should_register_github_oauth(
            current_app.config.get("GITHUB_OAUTH_CLIENT_ID"),
            current_app.config.get("GITHUB_OAUTH_CLIENT_SECRET"),
        ),
    )
