from flask_login import current_user

from backend.metrics.dimension_models import get_all_dimension_keys
from backend.metrics.events import DEVICE_TYPE_DIM_KEY, DeviceType
from backend.models.utub_members import Member_Role
from backend.splash.constants import EmailValidationErrorCodes
from backend.utils.all_routes import generate_admin_routes_js, generate_routes_js
from backend.utils.strings.admin_metrics_strs import ADMIN_METRICS_STRINGS
from backend.utils.strings.email_validation_strs import (
    VALIDATE_MY_EMAIL,
    VALIDATE_YOUR_EMAIL,
)
from backend.utils.strings.form_strs import MAY_HAVE_ALREADY_BEEN_DELETED
from backend.utils.strings.splash_form_strs import FORGOT_YOUR_PASSWORD, LOGIN_TITLE
from backend.utils.strings.tag_strs import (
    ADD_URL_TAG_TOOLTIP,
    DELETE_UTUB_TAG_WARNING,
    TAG_FILTER_NO_RESULTS,
)
from backend.utils.strings.url_strs import (
    ACCESS_URL_TOOLTIP,
    ACCESS_URL_WARNING,
    ADD_URL_BUTTON,
    COPIED_URL_FAILURE_TOOLIP,
    COPIED_URL_TOOLTIP,
    COPY_URL_TOOLTIP,
    DELETE_URL_TOOLTIP,
    DELETE_URL_WARNING,
    EDIT_URL_TITLE_TOOLTIP,
    EDIT_URL_TOOLTIP,
    UNABLE_TO_VALIDATE_THIS_URL,
    URL_SEARCH_NO_RESULTS,
    UTUB_NO_URLS,
)
from backend.utils.strings.user_strs import (
    COOKIE_BANNER_KEY,
    COOKIE_BANNER_SEEN,
    MEMBER_DELETE_WARNING,
    MEMBER_LEAVE_WARNING,
)
from backend.utils.strings.utub_strs import (
    UTUB_CREATE_MSG,
    UTUB_CREATE_SAME_NAME,
    UTUB_DELETE_WARNING,
    UTUB_ID_QUERY_PARAM,
    UTUB_SEARCH_COUNT_TEMPLATE,
    UTUB_SEARCH_NO_RESULTS,
    UTUB_SEARCH_PLACEHOLDER,
    UTUB_SELECT,
    UTUB_UPDATE_SAME_NAME,
)


class EMAIL_CONSTANTS:
    MAX_EMAIL_ATTEMPTS_IN_HOUR = 5
    WAIT_TO_RETRY_BEFORE_MAX_ATTEMPTS = 60
    WAIT_TO_ATTEMPT_AFTER_MAX_ATTEMPTS = 3600


class USER_CONSTANTS:
    MIN_USERNAME_LENGTH = 3
    MAX_USERNAME_LENGTH_ACTUAL = 25
    MAX_USERNAME_LENGTH = MAX_USERNAME_LENGTH_ACTUAL - 5
    MIN_EMAIL_LENGTH = 1
    MAX_EMAIL_LENGTH = 320
    MIN_PASSWORD_LENGTH = 12
    MAX_PASSWORD_INPUT_LENGTH = 64
    MAX_PASSWORD_LENGTH = 166
    MIN_REQUIRED_FIELD_LENGTH = 1
    PASSWORD_RESET_ATTEMPTS = 5
    WAIT_TO_RETRY_FORGOT_PASSWORD_MIN = 60
    WAIT_TO_RETRY_FORGOT_PASSWORD_MAX = 3600


class UTUB_CONSTANTS:
    MAX_NAME_LENGTH = 30
    MIN_NAME_LENGTH = 1
    MAX_DESCRIPTION_LENGTH = 500
    MEMBER_ROLES = Member_Role


class URL_CONSTANTS:
    MIN_URL_TITLE_LENGTH = 1
    MIN_URL_LENGTH = 1
    MAX_URL_TITLE_LENGTH = 100
    MAX_URL_LENGTH = 8000


class TAG_CONSTANTS:
    MIN_TAG_LENGTH = 1
    MAX_TAG_LENGTH = 30
    MAX_URL_TAGS = 5


class CONFIG_CONSTANTS:
    SESSION_LIFETIME = 31 * 86400  # 31 days before session and CSRF expiration


class SPLASH_CONSTANTS:
    EMAIL_VALIDATION_ERROR_CODES = EmailValidationErrorCodes


class STRINGS:
    UTUB_QUERY_PARAM = UTUB_ID_QUERY_PARAM
    VALIDATE_MY_EMAIL = VALIDATE_MY_EMAIL
    VALIDATE_YOUR_EMAIL = VALIDATE_YOUR_EMAIL
    FORGOT_YOUR_PASSWORD = FORGOT_YOUR_PASSWORD
    LOGIN_TITLE = LOGIN_TITLE

    UTUB_CREATE_SAME_NAME = UTUB_CREATE_SAME_NAME
    UTUB_UPDATE_SAME_NAME = UTUB_UPDATE_SAME_NAME
    UTUB_DELETE_WARNING = UTUB_DELETE_WARNING
    UTUB_CREATE_MSG = UTUB_CREATE_MSG
    UTUB_SELECT = UTUB_SELECT
    UTUB_SEARCH_NO_RESULTS = UTUB_SEARCH_NO_RESULTS
    UTUB_SEARCH_PLACEHOLDER = UTUB_SEARCH_PLACEHOLDER
    UTUB_SEARCH_COUNT_TEMPLATE = UTUB_SEARCH_COUNT_TEMPLATE

    MEMBER_DELETE_WARNING = MEMBER_DELETE_WARNING
    MEMBER_LEAVE_WARNING = MEMBER_LEAVE_WARNING

    DELETE_URL_WARNING = DELETE_URL_WARNING
    UNABLE_TO_VALIDATE_THIS_URL = UNABLE_TO_VALIDATE_THIS_URL
    ACCESS_URL_WARNING = ACCESS_URL_WARNING
    URL_SEARCH_NO_RESULTS = URL_SEARCH_NO_RESULTS
    UTUB_NO_URLS = UTUB_NO_URLS
    ADD_URL_BUTTON = ADD_URL_BUTTON

    UTUB_TAG_DELETE_WARNING = DELETE_UTUB_TAG_WARNING
    TAG_FILTER_NO_RESULTS = TAG_FILTER_NO_RESULTS

    COPY_URL_TOOLTIP = COPY_URL_TOOLTIP
    COPIED_URL_TOOLTIP = COPIED_URL_TOOLTIP
    COPIED_URL_FAILURE_TOOLIP = COPIED_URL_FAILURE_TOOLIP
    ACCESS_URL_TOOLTIP = ACCESS_URL_TOOLTIP
    ADD_URL_TAG_TOOLTIP = ADD_URL_TAG_TOOLTIP
    EDIT_URL_TOOLTIP = EDIT_URL_TOOLTIP
    EDIT_URL_TITLE_TOOLTIP = EDIT_URL_TITLE_TOOLTIP
    DELETE_URL_TOOLTIP = DELETE_URL_TOOLTIP
    MAY_HAVE_ALREADY_BEEN_DELETED = MAY_HAVE_ALREADY_BEEN_DELETED
    COOKIE_BANNER_SEEN = COOKIE_BANNER_SEEN
    COOKIE_BANNER_KEY = COOKIE_BANNER_KEY

    METRICS_DASHBOARD_TITLE = ADMIN_METRICS_STRINGS.METRICS_DASHBOARD_TITLE
    METRICS_REFRESH_BUTTON_LABEL = ADMIN_METRICS_STRINGS.METRICS_REFRESH_BUTTON_LABEL
    METRICS_TAB_API = ADMIN_METRICS_STRINGS.METRICS_TAB_API
    METRICS_TAB_UI = ADMIN_METRICS_STRINGS.METRICS_TAB_UI
    METRICS_TAB_DOMAIN = ADMIN_METRICS_STRINGS.METRICS_TAB_DOMAIN
    METRICS_TIMESERIES_SELECT_ARIA = (
        ADMIN_METRICS_STRINGS.METRICS_TIMESERIES_SELECT_ARIA
    )
    METRICS_LAST_FLUSH_JUST_NOW = ADMIN_METRICS_STRINGS.METRICS_LAST_FLUSH_JUST_NOW
    METRICS_LAST_FLUSH_SECONDS = ADMIN_METRICS_STRINGS.METRICS_LAST_FLUSH_SECONDS
    METRICS_LAST_FLUSH_MINUTES = ADMIN_METRICS_STRINGS.METRICS_LAST_FLUSH_MINUTES
    METRICS_LAST_FLUSH_STALE_MINUTES = (
        ADMIN_METRICS_STRINGS.METRICS_LAST_FLUSH_STALE_MINUTES
    )
    METRICS_LAST_FLUSH_STALE_HOURS = (
        ADMIN_METRICS_STRINGS.METRICS_LAST_FLUSH_STALE_HOURS
    )
    METRICS_LAST_EVENT_JUST_NOW = ADMIN_METRICS_STRINGS.METRICS_LAST_EVENT_JUST_NOW
    METRICS_LAST_EVENT_SECONDS = ADMIN_METRICS_STRINGS.METRICS_LAST_EVENT_SECONDS
    METRICS_LAST_EVENT_MINUTES = ADMIN_METRICS_STRINGS.METRICS_LAST_EVENT_MINUTES
    METRICS_LAST_EVENT_HOURS = ADMIN_METRICS_STRINGS.METRICS_LAST_EVENT_HOURS
    METRICS_EMPTY_STATE = ADMIN_METRICS_STRINGS.METRICS_EMPTY_STATE
    METRICS_FETCH_FAILED_BANNER = ADMIN_METRICS_STRINGS.METRICS_FETCH_FAILED_BANNER
    METRICS_SUMMARY_TOTAL_EVENTS = ADMIN_METRICS_STRINGS.METRICS_SUMMARY_TOTAL_EVENTS
    METRICS_SUMMARY_API_HITS = ADMIN_METRICS_STRINGS.METRICS_SUMMARY_API_HITS
    METRICS_SUMMARY_UI_EVENTS = ADMIN_METRICS_STRINGS.METRICS_SUMMARY_UI_EVENTS
    METRICS_SUMMARY_DOMAIN_ACTIONS = (
        ADMIN_METRICS_STRINGS.METRICS_SUMMARY_DOMAIN_ACTIONS
    )
    METRICS_SUMMARY_DELTA_SUFFIX = ADMIN_METRICS_STRINGS.METRICS_SUMMARY_DELTA_SUFFIX
    METRICS_SUMMARY_DELTA_UNAVAILABLE = (
        ADMIN_METRICS_STRINGS.METRICS_SUMMARY_DELTA_UNAVAILABLE
    )
    METRICS_TOP_TABLE_HEADER_RANK = ADMIN_METRICS_STRINGS.METRICS_TOP_TABLE_HEADER_RANK
    METRICS_TOP_TABLE_HEADER_ENDPOINT = (
        ADMIN_METRICS_STRINGS.METRICS_TOP_TABLE_HEADER_ENDPOINT
    )
    METRICS_TOP_TABLE_HEADER_EVENT = (
        ADMIN_METRICS_STRINGS.METRICS_TOP_TABLE_HEADER_EVENT
    )
    METRICS_TOP_TABLE_HEADER_ACTION = (
        ADMIN_METRICS_STRINGS.METRICS_TOP_TABLE_HEADER_ACTION
    )
    METRICS_TOP_TABLE_HEADER_HITS = ADMIN_METRICS_STRINGS.METRICS_TOP_TABLE_HEADER_HITS
    METRICS_TOP_TABLE_HEADER_DELTA = (
        ADMIN_METRICS_STRINGS.METRICS_TOP_TABLE_HEADER_DELTA
    )
    METRICS_TOP_TABLE_ROW_ARIA = ADMIN_METRICS_STRINGS.METRICS_TOP_TABLE_ROW_ARIA
    METRICS_CHART_Y_AXIS_LABEL = ADMIN_METRICS_STRINGS.METRICS_CHART_Y_AXIS_LABEL
    METRICS_TOP_RESOURCE_ALL = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_ALL
    METRICS_TOP_RESOURCE_UTUB = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_UTUB
    METRICS_TOP_RESOURCE_URL = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_URL
    METRICS_TOP_RESOURCE_TAG = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_TAG
    METRICS_TOP_RESOURCE_MEMBER = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_MEMBER
    METRICS_TOP_RESOURCE_AUTH = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_AUTH
    METRICS_TOP_RESOURCE_SEARCH = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_SEARCH
    METRICS_TOP_RESOURCE_FORM = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_FORM
    METRICS_TOP_RESOURCE_DECK = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_DECK
    METRICS_TOP_RESOURCE_NAV = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_NAV
    METRICS_TOP_RESOURCE_ERROR = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_ERROR
    METRICS_TOP_RESOURCE_CONTACT = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_CONTACT
    METRICS_TOP_RESOURCE_ADMIN = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_ADMIN
    METRICS_TOP_RESOURCE_OTHER = ADMIN_METRICS_STRINGS.METRICS_TOP_RESOURCE_OTHER
    METRICS_TOP_DEVICE_LABEL = ADMIN_METRICS_STRINGS.METRICS_TOP_DEVICE_LABEL
    METRICS_TOP_DEVICE_ALL = ADMIN_METRICS_STRINGS.METRICS_TOP_DEVICE_ALL
    METRICS_TOP_DEVICE_MOBILE = ADMIN_METRICS_STRINGS.METRICS_TOP_DEVICE_MOBILE
    METRICS_TOP_DEVICE_DESKTOP = ADMIN_METRICS_STRINGS.METRICS_TOP_DEVICE_DESKTOP
    METRICS_TOP_EMPTY_NO_MATCHES = ADMIN_METRICS_STRINGS.METRICS_TOP_EMPTY_NO_MATCHES


class CONSTANTS:
    EMAILS = EMAIL_CONSTANTS()
    USERS = USER_CONSTANTS()
    UTUBS = UTUB_CONSTANTS()
    URLS = URL_CONSTANTS()
    TAGS = TAG_CONSTANTS()
    CONFIG = CONFIG_CONSTANTS()
    STRINGS = STRINGS()
    SPLASH = SPLASH_CONSTANTS()


def generate_constants_js() -> (
    dict[str, int | list[str] | dict[str, str] | dict[str, int]]
):
    """
    Generate constants configuration for frontend JavaScript.
    Returns a dict that can be passed to Jinja and converted to JSON.
    """
    return {
        # Member roles
        "MEMBER_ROLES": {
            role.name: role.value for role in CONSTANTS.UTUBS.MEMBER_ROLES
        },
        # UTub constants
        "UTUBS_MAX_NAME_LENGTH": CONSTANTS.UTUBS.MAX_NAME_LENGTH,
        "UTUBS_MIN_NAME_LENGTH": CONSTANTS.UTUBS.MIN_NAME_LENGTH,
        "UTUBS_MAX_DESCRIPTION_LENGTH": CONSTANTS.UTUBS.MAX_DESCRIPTION_LENGTH,
        # URL constants
        "URLS_TITLE_MIN_LENGTH": CONSTANTS.URLS.MIN_URL_TITLE_LENGTH,
        "URLS_TITLE_MAX_LENGTH": CONSTANTS.URLS.MAX_URL_TITLE_LENGTH,
        "URLS_MIN_LENGTH": CONSTANTS.URLS.MIN_URL_LENGTH,
        "URLS_MAX_LENGTH": CONSTANTS.URLS.MAX_URL_LENGTH,
        # Tag constants
        "TAGS_MIN_LENGTH": CONSTANTS.TAGS.MIN_TAG_LENGTH,
        "TAGS_MAX_LENGTH": CONSTANTS.TAGS.MAX_TAG_LENGTH,
        "TAGS_MAX_ON_URLS": CONSTANTS.TAGS.MAX_URL_TAGS,
        # Splash constants
        "VALIDATE_EMAIL_ERROR_CODES": {
            error_code.name: error_code.value
            for error_code in CONSTANTS.SPLASH.EMAIL_VALIDATION_ERROR_CODES
        },
        # Metrics dimension allow-list (source of truth: DIMENSION_MODELS)
        "DIMENSION_KEYS": list(get_all_dimension_keys()),
        # Metrics device-type wire values (source of truth: backend.metrics.events.DeviceType)
        "DEVICE_TYPE": {member.name: member.value for member in DeviceType},
        # Backend-defined JSONB key for the device_type dimension — frontend
        # references via APP_CONFIG.constants.DEVICE_TYPE_DIM_KEY when building
        # /api/metrics/query/* URLSearchParams.
        "DEVICE_TYPE_DIM_KEY": DEVICE_TYPE_DIM_KEY,
    }


def generate_strings_js() -> dict[str, str]:
    """
    Generate strings configuration for frontend JavaScript.
    Returns a dict that can be passed to Jinja and converted to JSON.
    """

    return {
        # Query Param Strings
        "UTUB_QUERY_PARAM": CONSTANTS.STRINGS.UTUB_QUERY_PARAM,
        # Splash strings
        "VALIDATE_MY_EMAIL": CONSTANTS.STRINGS.VALIDATE_MY_EMAIL,
        "VALIDATE_YOUR_EMAIL": CONSTANTS.STRINGS.VALIDATE_YOUR_EMAIL,
        "FORGOT_YOUR_PASSWORD": CONSTANTS.STRINGS.FORGOT_YOUR_PASSWORD,
        "LOGIN_TITLE": CONSTANTS.STRINGS.LOGIN_TITLE,
        # General Strings
        "MAY_HAVE_ALREADY_BEEN_DELETED": CONSTANTS.STRINGS.MAY_HAVE_ALREADY_BEEN_DELETED,
        # UTub Strings
        "UTUB_CREATE_SAME_NAME": CONSTANTS.STRINGS.UTUB_CREATE_SAME_NAME,
        "UTUB_UPDATE_SAME_NAME": CONSTANTS.STRINGS.UTUB_UPDATE_SAME_NAME,
        "UTUB_DELETE_WARNING": CONSTANTS.STRINGS.UTUB_DELETE_WARNING,
        "UTUB_CREATE_MSG": CONSTANTS.STRINGS.UTUB_CREATE_MSG,
        "UTUB_SELECT": CONSTANTS.STRINGS.UTUB_SELECT,
        "UTUB_SEARCH_NO_RESULTS": CONSTANTS.STRINGS.UTUB_SEARCH_NO_RESULTS,
        "UTUB_SEARCH_PLACEHOLDER": CONSTANTS.STRINGS.UTUB_SEARCH_PLACEHOLDER,
        "UTUB_SEARCH_COUNT_TEMPLATE": CONSTANTS.STRINGS.UTUB_SEARCH_COUNT_TEMPLATE,
        # Member Strings
        "MEMBER_DELETE_WARNING": CONSTANTS.STRINGS.MEMBER_DELETE_WARNING,
        "MEMBER_LEAVE_WARNING": CONSTANTS.STRINGS.MEMBER_LEAVE_WARNING,
        # URL Strings
        "DELETE_URL_WARNING": CONSTANTS.STRINGS.DELETE_URL_WARNING,
        "INVALID_URL": CONSTANTS.STRINGS.UNABLE_TO_VALIDATE_THIS_URL,
        "ACCESS_URL_WARNING": CONSTANTS.STRINGS.ACCESS_URL_WARNING,
        "URL_SEARCH_NO_RESULTS": CONSTANTS.STRINGS.URL_SEARCH_NO_RESULTS,
        "UTUB_NO_URLS": CONSTANTS.STRINGS.UTUB_NO_URLS,
        "ADD_URL_BUTTON": CONSTANTS.STRINGS.ADD_URL_BUTTON,
        # Tag Strings
        "UTUB_TAG_DELETE_WARNING": CONSTANTS.STRINGS.UTUB_TAG_DELETE_WARNING,
        "TAG_FILTER_NO_RESULTS": CONSTANTS.STRINGS.TAG_FILTER_NO_RESULTS,
        # Tooltips
        "COPY_URL_TOOLTIP": CONSTANTS.STRINGS.COPY_URL_TOOLTIP,
        "COPIED_URL_TOOLTIP": CONSTANTS.STRINGS.COPIED_URL_TOOLTIP,
        "COPIED_URL_FAILURE_TOOLIP": CONSTANTS.STRINGS.COPIED_URL_FAILURE_TOOLIP,
        "ACCESS_URL_TOOLTIP": CONSTANTS.STRINGS.ACCESS_URL_TOOLTIP,
        "ADD_URL_TAG_TOOLTIP": CONSTANTS.STRINGS.ADD_URL_TAG_TOOLTIP,
        "EDIT_URL_TOOLTIP": CONSTANTS.STRINGS.EDIT_URL_TOOLTIP,
        "EDIT_URL_TITLE_TOOLTIP": CONSTANTS.STRINGS.EDIT_URL_TITLE_TOOLTIP,
        "DELETE_URL_TOOLTIP": CONSTANTS.STRINGS.DELETE_URL_TOOLTIP,
        "COOKIE_BANNER_SEEN": CONSTANTS.STRINGS.COOKIE_BANNER_SEEN,
        "COOKIE_BANNER_KEY": CONSTANTS.STRINGS.COOKIE_BANNER_KEY,
        # Admin Metrics Dashboard Strings
        "METRICS_TIMESERIES_SELECT_ARIA": CONSTANTS.STRINGS.METRICS_TIMESERIES_SELECT_ARIA,
        "METRICS_LAST_FLUSH_JUST_NOW": CONSTANTS.STRINGS.METRICS_LAST_FLUSH_JUST_NOW,
        "METRICS_LAST_FLUSH_SECONDS": CONSTANTS.STRINGS.METRICS_LAST_FLUSH_SECONDS,
        "METRICS_LAST_FLUSH_MINUTES": CONSTANTS.STRINGS.METRICS_LAST_FLUSH_MINUTES,
        "METRICS_LAST_FLUSH_STALE_MINUTES": CONSTANTS.STRINGS.METRICS_LAST_FLUSH_STALE_MINUTES,
        "METRICS_LAST_FLUSH_STALE_HOURS": CONSTANTS.STRINGS.METRICS_LAST_FLUSH_STALE_HOURS,
        "METRICS_LAST_EVENT_JUST_NOW": CONSTANTS.STRINGS.METRICS_LAST_EVENT_JUST_NOW,
        "METRICS_LAST_EVENT_SECONDS": CONSTANTS.STRINGS.METRICS_LAST_EVENT_SECONDS,
        "METRICS_LAST_EVENT_MINUTES": CONSTANTS.STRINGS.METRICS_LAST_EVENT_MINUTES,
        "METRICS_LAST_EVENT_HOURS": CONSTANTS.STRINGS.METRICS_LAST_EVENT_HOURS,
        "METRICS_EMPTY_STATE": CONSTANTS.STRINGS.METRICS_EMPTY_STATE,
        "METRICS_FETCH_FAILED_BANNER": CONSTANTS.STRINGS.METRICS_FETCH_FAILED_BANNER,
        "METRICS_SUMMARY_TOTAL_EVENTS": CONSTANTS.STRINGS.METRICS_SUMMARY_TOTAL_EVENTS,
        "METRICS_SUMMARY_API_HITS": CONSTANTS.STRINGS.METRICS_SUMMARY_API_HITS,
        "METRICS_SUMMARY_UI_EVENTS": CONSTANTS.STRINGS.METRICS_SUMMARY_UI_EVENTS,
        "METRICS_SUMMARY_DOMAIN_ACTIONS": CONSTANTS.STRINGS.METRICS_SUMMARY_DOMAIN_ACTIONS,
        "METRICS_SUMMARY_DELTA_SUFFIX": CONSTANTS.STRINGS.METRICS_SUMMARY_DELTA_SUFFIX,
        "METRICS_SUMMARY_DELTA_UNAVAILABLE": CONSTANTS.STRINGS.METRICS_SUMMARY_DELTA_UNAVAILABLE,
        "METRICS_TOP_TABLE_HEADER_RANK": CONSTANTS.STRINGS.METRICS_TOP_TABLE_HEADER_RANK,
        "METRICS_TOP_TABLE_HEADER_ENDPOINT": CONSTANTS.STRINGS.METRICS_TOP_TABLE_HEADER_ENDPOINT,
        "METRICS_TOP_TABLE_HEADER_EVENT": CONSTANTS.STRINGS.METRICS_TOP_TABLE_HEADER_EVENT,
        "METRICS_TOP_TABLE_HEADER_ACTION": CONSTANTS.STRINGS.METRICS_TOP_TABLE_HEADER_ACTION,
        "METRICS_TOP_TABLE_HEADER_HITS": CONSTANTS.STRINGS.METRICS_TOP_TABLE_HEADER_HITS,
        "METRICS_TOP_TABLE_HEADER_DELTA": CONSTANTS.STRINGS.METRICS_TOP_TABLE_HEADER_DELTA,
        "METRICS_TOP_TABLE_ROW_ARIA": CONSTANTS.STRINGS.METRICS_TOP_TABLE_ROW_ARIA,
        "METRICS_CHART_Y_AXIS_LABEL": CONSTANTS.STRINGS.METRICS_CHART_Y_AXIS_LABEL,
        "METRICS_TOP_RESOURCE_ALL": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_ALL,
        "METRICS_TOP_RESOURCE_UTUB": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_UTUB,
        "METRICS_TOP_RESOURCE_URL": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_URL,
        "METRICS_TOP_RESOURCE_TAG": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_TAG,
        "METRICS_TOP_RESOURCE_MEMBER": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_MEMBER,
        "METRICS_TOP_RESOURCE_AUTH": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_AUTH,
        "METRICS_TOP_RESOURCE_SEARCH": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_SEARCH,
        "METRICS_TOP_RESOURCE_FORM": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_FORM,
        "METRICS_TOP_RESOURCE_DECK": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_DECK,
        "METRICS_TOP_RESOURCE_NAV": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_NAV,
        "METRICS_TOP_RESOURCE_ERROR": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_ERROR,
        "METRICS_TOP_RESOURCE_CONTACT": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_CONTACT,
        "METRICS_TOP_RESOURCE_ADMIN": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_ADMIN,
        "METRICS_TOP_RESOURCE_OTHER": CONSTANTS.STRINGS.METRICS_TOP_RESOURCE_OTHER,
        "METRICS_TOP_DEVICE_ALL": CONSTANTS.STRINGS.METRICS_TOP_DEVICE_ALL,
        "METRICS_TOP_DEVICE_MOBILE": CONSTANTS.STRINGS.METRICS_TOP_DEVICE_MOBILE,
        "METRICS_TOP_DEVICE_DESKTOP": CONSTANTS.STRINGS.METRICS_TOP_DEVICE_DESKTOP,
        "METRICS_TOP_EMPTY_NO_MATCHES": CONSTANTS.STRINGS.METRICS_TOP_EMPTY_NO_MATCHES,
    }


def provide_config_for_constants() -> dict:
    """
    Provides configuration to templates:
    - CONSTANTS: Python objects for Jinja template rendering
    - CONFIG: JSON-serializable dict for JavaScript
    """
    routes = generate_routes_js()
    if current_user.is_authenticated and current_user.is_admin():
        routes.update(generate_admin_routes_js())
    return dict(
        CONSTANTS=CONSTANTS(),
        CONFIG=dict(
            routes=routes,
            constants=generate_constants_js(),
            strings=generate_strings_js(),
        ),
    )
