from backend.metrics.dimension_models import get_all_dimension_keys
from backend.models.utub_members import Member_Role
from backend.splash.constants import EmailValidationErrorCodes
from backend.utils.all_routes import generate_routes_js
from backend.utils.strings.email_validation_strs import (
    VALIDATE_MY_EMAIL,
    VALIDATE_YOUR_EMAIL,
)
from backend.utils.strings.form_strs import MAY_HAVE_ALREADY_BEEN_DELETED
from backend.utils.strings.splash_form_strs import FORGOT_YOUR_PASSWORD, LOGIN_TITLE
from backend.utils.strings.tag_strs import (
    ADD_URL_TAG_TOOLTIP,
    DELETE_UTUB_TAG_WARNING,
    TAG_FILTER_NO_RESULTS,
)
from backend.utils.strings.url_strs import (
    ACCESS_URL_TOOLTIP,
    ACCESS_URL_WARNING,
    ADD_URL_BUTTON,
    COPIED_URL_FAILURE_TOOLIP,
    COPIED_URL_TOOLTIP,
    COPY_URL_TOOLTIP,
    DELETE_URL_TOOLTIP,
    DELETE_URL_WARNING,
    EDIT_URL_TOOLTIP,
    UNABLE_TO_VALIDATE_THIS_URL,
    URL_SEARCH_NO_RESULTS,
    UTUB_NO_URLS,
)
from backend.utils.strings.user_strs import (
    COOKIE_BANNER_KEY,
    COOKIE_BANNER_SEEN,
    MEMBER_DELETE_WARNING,
    MEMBER_LEAVE_WARNING,
)
from backend.utils.strings.utub_strs import (
    UTUB_CREATE_MSG,
    UTUB_CREATE_SAME_NAME,
    UTUB_DELETE_WARNING,
    UTUB_ID_QUERY_PARAM,
    UTUB_SEARCH_COUNT_TEMPLATE,
    UTUB_SEARCH_NO_RESULTS,
    UTUB_SEARCH_PLACEHOLDER,
    UTUB_SELECT,
    UTUB_UPDATE_SAME_NAME,
)


class EMAIL_CONSTANTS:
    MAX_EMAIL_ATTEMPTS_IN_HOUR = 5
    WAIT_TO_RETRY_BEFORE_MAX_ATTEMPTS = 60
    WAIT_TO_ATTEMPT_AFTER_MAX_ATTEMPTS = 3600


class USER_CONSTANTS:
    MIN_USERNAME_LENGTH = 3
    MAX_USERNAME_LENGTH_ACTUAL = 25
    MAX_USERNAME_LENGTH = MAX_USERNAME_LENGTH_ACTUAL - 5
    MIN_EMAIL_LENGTH = 1
    MAX_EMAIL_LENGTH = 320
    MIN_PASSWORD_LENGTH = 12
    MAX_PASSWORD_INPUT_LENGTH = 64
    MAX_PASSWORD_LENGTH = 166
    MIN_REQUIRED_FIELD_LENGTH = 1
    PASSWORD_RESET_ATTEMPTS = 5
    WAIT_TO_RETRY_FORGOT_PASSWORD_MIN = 60
    WAIT_TO_RETRY_FORGOT_PASSWORD_MAX = 3600


class UTUB_CONSTANTS:
    MAX_NAME_LENGTH = 30
    MIN_NAME_LENGTH = 1
    MAX_DESCRIPTION_LENGTH = 500
    MEMBER_ROLES = Member_Role


class URL_CONSTANTS:
    MIN_URL_TITLE_LENGTH = 1
    MIN_URL_LENGTH = 1
    MAX_URL_TITLE_LENGTH = 100
    MAX_URL_LENGTH = 8000


class TAG_CONSTANTS:
    MIN_TAG_LENGTH = 1
    MAX_TAG_LENGTH = 30
    MAX_URL_TAGS = 5


class CONFIG_CONSTANTS:
    SESSION_LIFETIME = 31 * 86400  # 31 days before session and CSRF expiration


class SPLASH_CONSTANTS:
    EMAIL_VALIDATION_ERROR_CODES = EmailValidationErrorCodes


class STRINGS:
    UTUB_QUERY_PARAM = UTUB_ID_QUERY_PARAM
    VALIDATE_MY_EMAIL = VALIDATE_MY_EMAIL
    VALIDATE_YOUR_EMAIL = VALIDATE_YOUR_EMAIL
    FORGOT_YOUR_PASSWORD = FORGOT_YOUR_PASSWORD
    LOGIN_TITLE = LOGIN_TITLE

    UTUB_CREATE_SAME_NAME = UTUB_CREATE_SAME_NAME
    UTUB_UPDATE_SAME_NAME = UTUB_UPDATE_SAME_NAME
    UTUB_DELETE_WARNING = UTUB_DELETE_WARNING
    UTUB_CREATE_MSG = UTUB_CREATE_MSG
    UTUB_SELECT = UTUB_SELECT
    UTUB_SEARCH_NO_RESULTS = UTUB_SEARCH_NO_RESULTS
    UTUB_SEARCH_PLACEHOLDER = UTUB_SEARCH_PLACEHOLDER
    UTUB_SEARCH_COUNT_TEMPLATE = UTUB_SEARCH_COUNT_TEMPLATE

    MEMBER_DELETE_WARNING = MEMBER_DELETE_WARNING
    MEMBER_LEAVE_WARNING = MEMBER_LEAVE_WARNING

    DELETE_URL_WARNING = DELETE_URL_WARNING
    UNABLE_TO_VALIDATE_THIS_URL = UNABLE_TO_VALIDATE_THIS_URL
    ACCESS_URL_WARNING = ACCESS_URL_WARNING
    URL_SEARCH_NO_RESULTS = URL_SEARCH_NO_RESULTS
    UTUB_NO_URLS = UTUB_NO_URLS
    ADD_URL_BUTTON = ADD_URL_BUTTON

    UTUB_TAG_DELETE_WARNING = DELETE_UTUB_TAG_WARNING
    TAG_FILTER_NO_RESULTS = TAG_FILTER_NO_RESULTS

    COPY_URL_TOOLTIP = COPY_URL_TOOLTIP
    COPIED_URL_TOOLTIP = COPIED_URL_TOOLTIP
    COPIED_URL_FAILURE_TOOLIP = COPIED_URL_FAILURE_TOOLIP
    ACCESS_URL_TOOLTIP = ACCESS_URL_TOOLTIP
    ADD_URL_TAG_TOOLTIP = ADD_URL_TAG_TOOLTIP
    EDIT_URL_TOOLTIP = EDIT_URL_TOOLTIP
    DELETE_URL_TOOLTIP = DELETE_URL_TOOLTIP
    MAY_HAVE_ALREADY_BEEN_DELETED = MAY_HAVE_ALREADY_BEEN_DELETED
    COOKIE_BANNER_SEEN = COOKIE_BANNER_SEEN
    COOKIE_BANNER_KEY = COOKIE_BANNER_KEY


class CONSTANTS:
    EMAILS = EMAIL_CONSTANTS()
    USERS = USER_CONSTANTS()
    UTUBS = UTUB_CONSTANTS()
    URLS = URL_CONSTANTS()
    TAGS = TAG_CONSTANTS()
    CONFIG = CONFIG_CONSTANTS()
    STRINGS = STRINGS()
    SPLASH = SPLASH_CONSTANTS()


def generate_constants_js() -> (
    dict[str, int | list[str] | dict[str, str] | dict[str, int]]
):
    """
    Generate constants configuration for frontend JavaScript.
    Returns a dict that can be passed to Jinja and converted to JSON.
    """
    return {
        # Member roles
        "MEMBER_ROLES": {
            role.name: role.value for role in CONSTANTS.UTUBS.MEMBER_ROLES
        },
        # UTub constants
        "UTUBS_MAX_NAME_LENGTH": CONSTANTS.UTUBS.MAX_NAME_LENGTH,
        "UTUBS_MIN_NAME_LENGTH": CONSTANTS.UTUBS.MIN_NAME_LENGTH,
        "UTUBS_MAX_DESCRIPTION_LENGTH": CONSTANTS.UTUBS.MAX_DESCRIPTION_LENGTH,
        # URL constants
        "URLS_TITLE_MIN_LENGTH": CONSTANTS.URLS.MIN_URL_TITLE_LENGTH,
        "URLS_TITLE_MAX_LENGTH": CONSTANTS.URLS.MAX_URL_TITLE_LENGTH,
        "URLS_MIN_LENGTH": CONSTANTS.URLS.MIN_URL_LENGTH,
        "URLS_MAX_LENGTH": CONSTANTS.URLS.MAX_URL_LENGTH,
        # Tag constants
        "TAGS_MIN_LENGTH": CONSTANTS.TAGS.MIN_TAG_LENGTH,
        "TAGS_MAX_LENGTH": CONSTANTS.TAGS.MAX_TAG_LENGTH,
        "TAGS_MAX_ON_URLS": CONSTANTS.TAGS.MAX_URL_TAGS,
        # Splash constants
        "VALIDATE_EMAIL_ERROR_CODES": {
            error_code.name: error_code.value
            for error_code in CONSTANTS.SPLASH.EMAIL_VALIDATION_ERROR_CODES
        },
        # Metrics dimension allow-list (source of truth: DIMENSION_MODELS)
        "DIMENSION_KEYS": list(get_all_dimension_keys()),
    }


def generate_strings_js() -> dict[str, str]:
    """
    Generate strings configuration for frontend JavaScript.
    Returns a dict that can be passed to Jinja and converted to JSON.
    """

    return {
        # Query Param Strings
        "UTUB_QUERY_PARAM": CONSTANTS.STRINGS.UTUB_QUERY_PARAM,
        # Splash strings
        "VALIDATE_MY_EMAIL": CONSTANTS.STRINGS.VALIDATE_MY_EMAIL,
        "VALIDATE_YOUR_EMAIL": CONSTANTS.STRINGS.VALIDATE_YOUR_EMAIL,
        "FORGOT_YOUR_PASSWORD": CONSTANTS.STRINGS.FORGOT_YOUR_PASSWORD,
        "LOGIN_TITLE": CONSTANTS.STRINGS.LOGIN_TITLE,
        # General Strings
        "MAY_HAVE_ALREADY_BEEN_DELETED": CONSTANTS.STRINGS.MAY_HAVE_ALREADY_BEEN_DELETED,
        # UTub Strings
        "UTUB_CREATE_SAME_NAME": CONSTANTS.STRINGS.UTUB_CREATE_SAME_NAME,
        "UTUB_UPDATE_SAME_NAME": CONSTANTS.STRINGS.UTUB_UPDATE_SAME_NAME,
        "UTUB_DELETE_WARNING": CONSTANTS.STRINGS.UTUB_DELETE_WARNING,
        "UTUB_CREATE_MSG": CONSTANTS.STRINGS.UTUB_CREATE_MSG,
        "UTUB_SELECT": CONSTANTS.STRINGS.UTUB_SELECT,
        "UTUB_SEARCH_NO_RESULTS": CONSTANTS.STRINGS.UTUB_SEARCH_NO_RESULTS,
        "UTUB_SEARCH_PLACEHOLDER": CONSTANTS.STRINGS.UTUB_SEARCH_PLACEHOLDER,
        "UTUB_SEARCH_COUNT_TEMPLATE": CONSTANTS.STRINGS.UTUB_SEARCH_COUNT_TEMPLATE,
        # Member Strings
        "MEMBER_DELETE_WARNING": CONSTANTS.STRINGS.MEMBER_DELETE_WARNING,
        "MEMBER_LEAVE_WARNING": CONSTANTS.STRINGS.MEMBER_LEAVE_WARNING,
        # URL Strings
        "DELETE_URL_WARNING": CONSTANTS.STRINGS.DELETE_URL_WARNING,
        "INVALID_URL": CONSTANTS.STRINGS.UNABLE_TO_VALIDATE_THIS_URL,
        "ACCESS_URL_WARNING": CONSTANTS.STRINGS.ACCESS_URL_WARNING,
        "URL_SEARCH_NO_RESULTS": CONSTANTS.STRINGS.URL_SEARCH_NO_RESULTS,
        "UTUB_NO_URLS": CONSTANTS.STRINGS.UTUB_NO_URLS,
        "ADD_URL_BUTTON": CONSTANTS.STRINGS.ADD_URL_BUTTON,
        # Tag Strings
        "UTUB_TAG_DELETE_WARNING": CONSTANTS.STRINGS.UTUB_TAG_DELETE_WARNING,
        "TAG_FILTER_NO_RESULTS": CONSTANTS.STRINGS.TAG_FILTER_NO_RESULTS,
        # Tooltips
        "COPY_URL_TOOLTIP": CONSTANTS.STRINGS.COPY_URL_TOOLTIP,
        "COPIED_URL_TOOLTIP": CONSTANTS.STRINGS.COPIED_URL_TOOLTIP,
        "COPIED_URL_FAILURE_TOOLIP": CONSTANTS.STRINGS.COPIED_URL_FAILURE_TOOLIP,
        "ACCESS_URL_TOOLTIP": CONSTANTS.STRINGS.ACCESS_URL_TOOLTIP,
        "ADD_URL_TAG_TOOLTIP": CONSTANTS.STRINGS.ADD_URL_TAG_TOOLTIP,
        "EDIT_URL_TOOLTIP": CONSTANTS.STRINGS.EDIT_URL_TOOLTIP,
        "DELETE_URL_TOOLTIP": CONSTANTS.STRINGS.DELETE_URL_TOOLTIP,
        "COOKIE_BANNER_SEEN": CONSTANTS.STRINGS.COOKIE_BANNER_SEEN,
        "COOKIE_BANNER_KEY": CONSTANTS.STRINGS.COOKIE_BANNER_KEY,
    }


def provide_config_for_constants() -> dict:
    """
    Provides configuration to templates:
    - CONSTANTS: Python objects for Jinja template rendering
    - CONFIG: JSON-serializable dict for JavaScript
    """
    return dict(
        CONSTANTS=CONSTANTS(),
        CONFIG=dict(
            routes=generate_routes_js(),
            constants=generate_constants_js(),
            strings=generate_strings_js(),
        ),
    )
