USERS = "Users"
FORGOT_PASSWORDS = "ForgotPasswords"
EMAIL_VALIDATIONS = "EmailValidations"
UTUBS = "Utubs"
URLS = "Urls"
UTUB_TAGS = "UtubTags"
UTUB_MEMBERS = "UtubMembers"
UTUB_URLS = "UtubUrls"
UTUB_URL_TAGS = "UtubUrlTags"
CONTACT_FORM_ENTRIES = "ContactFormEntries"
EVENT_REGISTRY = "EventRegistry"
ANONYMOUS_METRICS = "AnonymousMetrics"
ALEMBIC_VERSION = "alembic_version"


class TABLE_NAMES:
    USERS = USERS
    FORGOT_PASSWORDS = FORGOT_PASSWORDS
    EMAIL_VALIDATIONS = EMAIL_VALIDATIONS
    UTUBS = UTUBS
    URLS = URLS
    UTUB_TAGS = UTUB_TAGS
    UTUB_MEMBERS = UTUB_MEMBERS
    UTUB_URLS = UTUB_URLS
    UTUB_URL_TAGS = UTUB_URL_TAGS
    ALEMBIC_VERSION = ALEMBIC_VERSION
    CONTACT_FORM_ENTRIES = CONTACT_FORM_ENTRIES
    EVENT_REGISTRY = EVENT_REGISTRY
    ANONYMOUS_METRICS = ANONYMOUS_METRICS

    SORTED_TABLES_FOR_DELETION = (
        ANONYMOUS_METRICS,
        EVENT_REGISTRY,
        UTUB_URL_TAGS,
        UTUB_TAGS,
        UTUB_URLS,
        UTUB_MEMBERS,
        URLS,
        UTUBS,
        EMAIL_VALIDATIONS,
        FORGOT_PASSWORDS,
        CONTACT_FORM_ENTRIES,
        USERS,
    )
