name: u4i-local

services:
  web:
    container_name: u4i-local-web
    build:
      context: .
      dockerfile: docker/DockerfileLocal
    ports: 
      - "8659:5000"
    user: u4i-host:u4i-host-group
    depends_on:
      - db
      - test-db
    env_file:
      - .env
    environment:
      - PRODUCTION=false
      - REDIS_URI=redis://redis:6379/0
      - TEST_REDIS_URI=redis://redis:6379/1
      - FLASK_DEBUG=true
      - FLASK_ENV=development
      - BASE_EMAIL=u4i@urls4irl.app
      - DOCKER=true
      - SELENIUM_URL=http://selenium:4444/wd/hub
    volumes:
      - ./run.py:/code/u4i/run.py
      - ./pytest.ini:/code/u4i/pytest.ini
      - ./src:/code/u4i/src
      - ./tests:/code/u4i/tests
      - ./migrations:/code/u4i/migrations
      - ./migrations/versions:/code/u4i/migrations/versions
      - ./utils:/code/u4i/utils
      - app_logs:/app/volume
    command: ["bash", "startup-flask.sh"]

  selenium:
    image: selenium/standalone-chromium:latest
    container_name: u4i-selenium
    depends_on:
      - web
    environment:
      - START_XVFB=false
      - SE_NODE_MAX_SESSIONS=5
      - JAVA_OPTS=-XX:ActiveProcessorCount=5
      - SE_NODE_OVERRIDE_MAX_SESSIONS=5
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm

  workflow:
    container_name: u4i-local-workflow
    build:
      context: .
      dockerfile: docker/Dockerfile_Workflow
    env_file:
      - .env
    depends_on:
      - web
    environment:
      - PRODUCTION=false
      - DEV_SERVER=false
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - NOTIFICATION_URL=${NOTIFICATION_URL}
    volumes:
      - app_logs:/app/volume
      - pgdata:/var/lib/postgresql/data:ro
      - workflow_logs:/app/workflow_logs
      - backups:/backups
    command: ["bash", "/app/startup-workflow.sh"]
    restart: unless-stopped

  db:
    image: postgres:16.3-bookworm
    container_name: u4i-local-postgres
    env_file:
     - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  test-db:
    image: postgres:16.3-bookworm
    container_name: u4i-local-postgres-test
    env_file:
     - .env
    environment:
      - POSTGRES_DB=${POSTGRES_TEST_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:6.2
    container_name: u4i-local-redis
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
  app_logs:
  workflow_logs:
  backups:

