"""Add valid column to urls

Revision ID: 5895ca590d75
Revises: 799cc1c01a1c
Create Date: 2024-12-08 18:02:19.644591

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = "5895ca590d75"
down_revision = "799cc1c01a1c"
branch_labels = None
depends_on = None

url_valid_enum = ENUM(
    "VALIDATED",
    "INVALIDATED",
    "UNKNOWN",
    name="possible_url_validation",
    create_type=True,
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    url_valid_enum.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table("Urls", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "isValidated",
                sa.Enum(
                    "VALIDATED",
                    "INVALIDATED",
                    "UNKNOWN",
                    name="possible_url_validation",
                ),
                nullable=False,
                server_default="UNKNOWN",
            )
        )

    op.execute("""UPDATE "Urls" SET "isValidated"='VALIDATED'""")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Urls", schema=None) as batch_op:
        batch_op.drop_column("isValidated")

    op.execute("""DROP TYPE possible_url_validation""")

    # ### end Alembic commands ###
