"""add UserPreferences table

Revision ID: 58dfdcfa3921
Revises: e1a4c7f2b9d6
Create Date: 2026-08-07 13:42:05.671920

Adds the ``UserPreferences`` table, a one-to-one child of ``Users`` that stores
a user's Settings Display-tab choices: an app-wide ``theme`` (light / dark /
system) plus four view preferences (default UTub view, default sort, list
density, and date format). Each preference is a native Postgres enum column
storing the lowercase string value of its Python enum; every physical column
name is camelCase (``userID``, ``defaultView``, ``defaultSort``, ``dateFormat``,
``createdAt``, ``updatedAt``) to match the ORM model's ``name=`` kwargs and this
project's column-naming convention. The one-to-one relationship is enforced by
the named ``unique_user_preferences`` unique constraint on ``userID``, and the
foreign key cascades on delete so a hard-deleted account cannot leave an orphan
preferences row (soft "tombstone" erasure deletes the row explicitly instead,
since no cascade fires on an in-place anonymization).

This migration is purely additive and fully reversible. The autogenerated draft
also picked up several pieces of unrelated pre-existing schema drift (a stale
``Providers`` table, a ``UserOAuthIdentities`` provider foreign key, and a
``UtubMembers`` ``unique_member`` constraint that the models already declare);
those were hand-stripped so this revision touches only the ``UserPreferences``
table. Because Alembic's autogenerate does NOT emit drops for the named Postgres
enum TYPEs it creates alongside the table, the downgrade explicitly drops each
enum type after dropping the table — without this a later re-``upgrade`` after a
``downgrade`` fails with a ``DuplicateObject`` ("type already exists") error.
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "58dfdcfa3921"
down_revision = "e1a4c7f2b9d6"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "UserPreferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("userID", sa.Integer(), nullable=False),
        sa.Column(
            "theme",
            sa.Enum("light", "dark", "system", name="theme_enum"),
            nullable=False,
        ),
        sa.Column(
            "defaultView",
            sa.Enum("list", "compact", "cards", name="view_mode_enum"),
            nullable=False,
        ),
        sa.Column(
            "defaultSort",
            sa.Enum("newest", "oldest", "title_az", name="sort_order_enum"),
            nullable=False,
        ),
        sa.Column(
            "density",
            sa.Enum("comfortable", "compact", name="density_enum"),
            nullable=False,
        ),
        sa.Column(
            "dateFormat",
            sa.Enum("iso", "us", "eu", name="date_format_enum"),
            nullable=False,
        ),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updatedAt", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["userID"], ["Users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("userID", name="unique_user_preferences"),
    )


def downgrade():
    op.drop_table("UserPreferences")
    # Alembic's autogenerate omits enum-TYPE drops, so drop each named Postgres
    # enum type explicitly. Without this, re-upgrading after a downgrade fails
    # with a DuplicateObject ("type already exists") error. checkfirst=True keeps
    # the downgrade safe if a type is already absent.
    bind = op.get_bind()
    for enum_name in (
        "theme_enum",
        "view_mode_enum",
        "sort_order_enum",
        "density_enum",
        "date_format_enum",
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
