"""Initial migration.

Revision ID: b8a616da8c5b
Revises: 
Create Date: 2022-04-03 17:23:57.518389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8a616da8c5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Urls', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_Urls_url_string'), ['url_string'])

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_User_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_User_username'), ['username'])

    with op.batch_alter_table('Utub', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utub_description', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Utub', schema=None) as batch_op:
        batch_op.drop_column('utub_description')

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_User_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_User_email'), type_='unique')

    with op.batch_alter_table('Urls', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_Urls_url_string'), type_='unique')

    # ### end Alembic commands ###
