"""Remove email validation row on user validation

Revision ID: cbacf42d21d0
Revises: 5895ca590d75
Create Date: 2025-04-11 15:11:41.336083

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cbacf42d21d0"
down_revision = "5895ca590d75"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "emailValidated",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("false"),
            )
        )

    op.execute(
        """
        UPDATE "Users"
        SET "emailValidated" = true
        WHERE "Users"."id" in (
            SELECT "EmailValidations"."userID"
            FROM "EmailValidations"
            WHERE "EmailValidations"."isValidated" = TRUE
        )
    """
    )

    op.execute("""DELETE FROM "EmailValidations" """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(
        """
        INSERT INTO "EmailValidations" ("userID", "isValidated", "validationToken", "attempts", "createdAt")
        SELECT "Users"."id", "Users"."emailValidated", '', 0, NOW()
        FROM "Users"
    """
    )

    with op.batch_alter_table("Users", schema=None) as batch_op:
        batch_op.drop_column("emailValidated")

    # ### end Alembic commands ###
