from __future__ import annotations

from enum import IntEnum
from typing import Annotated, Literal, get_args, get_origin

from pydantic import BaseModel

from backend.metrics.dimension_models import DIMENSION_MODELS
from backend.metrics.events import EVENT_CATEGORY, EventCategory

_FILE_HEADER = """\
// Generated by `flask metrics generate-dim-types` — DO NOT EDIT.
// Source of truth: backend/metrics/dimension_models.py
//
// Per-event dimension shapes mirrored from the Pydantic `_Dim<Event>` models.
// Frontend `emit()` narrows its second argument against `UIEventDimensions[E]`
// so any literal that drifts from the backend Pydantic literal fails to compile.
"""


def _ts_for_annotation(annotation: object) -> str:
    """Map a Pydantic field annotation to a TypeScript type expression."""
    if get_origin(annotation) is Annotated:
        annotation = get_args(annotation)[0]
    origin = get_origin(annotation)
    if origin is Literal:
        members = get_args(annotation)
        formatted_members: list[str] = []
        for member in members:
            if isinstance(member, str):
                formatted_members.append(f'"{member}"')
            else:
                formatted_members.append(str(member))
        return " | ".join(formatted_members)
    if isinstance(annotation, type) and issubclass(annotation, IntEnum):
        enum_values = sorted({int(member.value) for member in annotation})
        return " | ".join(str(value) for value in enum_values)
    if annotation is int:
        return "number"
    if annotation is bool:
        return "boolean"
    if annotation is str:
        return "string"
    raise ValueError(
        f"Unsupported annotation in dim codegen: {annotation!r}. "
        "Extend `_ts_for_annotation` to handle this type."
    )


def _ts_type_name_for_class(model: type[BaseModel]) -> str:
    """Strip the leading underscore on private Pydantic dim classes."""
    return model.__name__.lstrip("_")


def _emit_class_type(model: type[BaseModel]) -> str:
    lines = [f"export type {_ts_type_name_for_class(model)} = {{"]
    for field_name, field_info in model.model_fields.items():
        ts_type = _ts_for_annotation(field_info.annotation)
        lines.append(f"  {field_name}: {ts_type};")
    lines.append("};")
    return "\n".join(lines)


def generate_dim_types_ts() -> str:
    """Render the TS source for per-event dim types + the UIEventDimensions map.

    Walks `DIMENSION_MODELS` filtered to `EventCategory.UI`. Distinct Pydantic
    classes are emitted once (so e.g. `_DimDeviceOnly` produces one TS alias
    referenced by every UI event whose dim model is `_DimDeviceOnly`). The
    final `UIEventDimensions` map names every UI `EventName` so the TS
    compiler enforces exhaustive coverage at the consumer.
    """
    seen_classes: dict[type[BaseModel], None] = {}
    for event_name, model in DIMENSION_MODELS.items():
        if model is None:
            continue
        if EVENT_CATEGORY[event_name] != EventCategory.UI:
            continue
        seen_classes.setdefault(model, None)

    parts: list[str] = [_FILE_HEADER]
    for model in seen_classes:
        parts.append("")
        parts.append(_emit_class_type(model))

    parts.append("")
    parts.append("export type UIEventDimensions = {")
    for event_name, model in DIMENSION_MODELS.items():
        if model is None:
            continue
        if EVENT_CATEGORY[event_name] != EventCategory.UI:
            continue
        wire_name = event_name.value
        ts_class = _ts_type_name_for_class(model)
        parts.append(f'  "{wire_name}": {ts_class};')
    parts.append("};")

    return "\n".join(parts) + "\n"
