from __future__ import annotations

import importlib
from enum import IntEnum
from typing import Annotated, Literal, get_args, get_origin

from pydantic import BaseModel

from backend.metrics.dimension_models import DIMENSION_MODELS
from backend.metrics.events import EVENT_CATEGORY, DeviceType, EventCategory, EventName

_DIMENSIONS_FILE_HEADER = """\
// Generated by `flask metrics generate-dim-types` — DO NOT EDIT.
// Source of truth: backend/metrics/dimension_models.py
//
// Per-event dimension shapes mirrored from the Pydantic `_Dim<Event>` models.
// Frontend `emit()` narrows its second argument against `UIEventDimensions[E]`
// so any literal that drifts from the backend Pydantic literal fails to compile.
"""

_VALUES_FILE_HEADER = """\
// Generated by `flask metrics generate-dim-values` — DO NOT EDIT.
// Source of truth: backend/metrics/dimension_models.py
//
// Runtime constants for every dim-value Literal alias and IntEnum referenced by
// the Pydantic `_Dim<Event>` models. Use these constants at every `emit()` call
// site and test assertion so there is a single source of truth for every dim
// value, locked to Pydantic via codegen, available at both compile time AND
// runtime for query-service and dashboard consumption.
"""

_EVENTS_FILE_HEADER = """\
// Generated by `flask metrics generate-events` — DO NOT EDIT.
// Source of truth: backend/metrics/events.py
//
// Wire-format identifiers for UI events emitted via `emit()`. Each key mirrors
// the matching `EventName.UI_*` member; the value is the wire string the
// backend Pydantic validator expects.
"""

# JSDoc emitted above the named `DeviceType` alias in `metrics-dimensions.d.ts`.
# Points readers to the runtime constants module so they can resolve magic
# numbers (1/2) back to the named MOBILE/DESKTOP enum entries.
_DEVICE_TYPE_JSDOC = """\
/**
 * Device type emitted with every UI event. Values match the
 * `DeviceType` IntEnum in `backend/metrics/events.py` — see the
 * `DEVICE_TYPE` constant in `./metrics-dim-values.js` for the named
 * mapping (`MOBILE`, `DESKTOP`).
 */"""

# Named module-level Literal aliases declared in dimension_models. Each pairs
# the in-Python alias name to the UPPER_SNAKE constant name in the generated TS.
_NAMED_LITERAL_ALIASES: tuple[tuple[str, str], ...] = (
    ("SearchActive", "SEARCH_ACTIVE"),
    ("TagScope", "TAG_SCOPE"),
    ("HomeForm", "HOME_FORM"),
    ("ValidationForm", "VALIDATION_FORM"),
)


def _ts_for_annotation(annotation: object) -> str:
    """Map a Pydantic field annotation to a TypeScript type expression."""
    if get_origin(annotation) is Annotated:
        annotation = get_args(annotation)[0]
    origin = get_origin(annotation)
    if origin is Literal:
        members = get_args(annotation)
        formatted_members: list[str] = []
        for member in members:
            if isinstance(member, str):
                formatted_members.append(f'"{member}"')
            else:
                formatted_members.append(str(member))
        return " | ".join(formatted_members)
    if isinstance(annotation, type) and issubclass(annotation, IntEnum):
        # Return the IntEnum class name so callers reference a named TS alias
        # (e.g. `DeviceType`) instead of an opaque inline literal union like
        # `1 | 2`. The named alias is emitted once at the top of the dim-types
        # file (see `generate_dim_types_ts`).
        return annotation.__name__
    if annotation is int:
        return "number"
    if annotation is bool:
        return "boolean"
    if annotation is str:
        return "string"
    raise ValueError(
        f"Unsupported annotation in dim codegen: {annotation!r}. "
        "Extend `_ts_for_annotation` to handle this type."
    )


def _ts_type_name_for_class(model: type[BaseModel]) -> str:
    """Strip the leading underscore on private Pydantic dim classes."""
    return model.__name__.lstrip("_")


def _emit_class_type(model: type[BaseModel]) -> str:
    lines = [f"export type {_ts_type_name_for_class(model)} = {{"]
    for field_name, field_info in model.model_fields.items():
        ts_type = _ts_for_annotation(field_info.annotation)
        lines.append(f"  {field_name}: {ts_type};")
    lines.append("};")
    return "\n".join(lines)


def _emit_named_literal_alias(alias_name: str, annotation: object) -> str:
    ts_type = _ts_for_annotation(annotation)
    return f"export type {alias_name} = {ts_type};"


def generate_dim_types_ts() -> str:
    """Render the TS source for per-event dim types + the UIEventDimensions map.

    Walks `DIMENSION_MODELS` filtered to `EventCategory.UI`. Distinct Pydantic
    classes are emitted once (so e.g. `_DimDeviceOnly` produces one TS alias
    referenced by every UI event whose dim model is `_DimDeviceOnly`). The
    final `UIEventDimensions` map names every UI `EventName` so the TS
    compiler enforces exhaustive coverage at the consumer.

    Also emits sibling `export type` aliases for each named Pydantic Literal
    alias (`SearchActive`, `TagScope`, `HomeForm`, `ValidationForm`) so the
    runtime-constants module can import them for `satisfies` constraints.
    """
    seen_classes: dict[type[BaseModel], None] = {}
    for event_name, model in DIMENSION_MODELS.items():
        if model is None:
            continue
        if EVENT_CATEGORY[event_name] != EventCategory.UI:
            continue
        seen_classes.setdefault(model, None)

    parts: list[str] = [_DIMENSIONS_FILE_HEADER]

    # Named `DeviceType` alias — emitted once so every dim model can reference
    # it instead of inlining the literal union (`1 | 2`). The IntEnum's int
    # values define the alias; `metrics-dim-values.ts` ships the matching
    # named constants (`MOBILE`/`DESKTOP`).
    device_type_values = sorted({int(member.value) for member in DeviceType})
    device_type_union = " | ".join(str(value) for value in device_type_values)
    parts.append("")
    parts.append(_DEVICE_TYPE_JSDOC)
    parts.append(f"export type {DeviceType.__name__} = {device_type_union};")

    dimension_module = importlib.import_module("backend.metrics.dimension_models")
    for alias_name, _constant_name in _NAMED_LITERAL_ALIASES:
        alias_annotation = getattr(dimension_module, alias_name)
        parts.append("")
        parts.append(_emit_named_literal_alias(alias_name, alias_annotation))

    for model in seen_classes:
        parts.append("")
        parts.append(_emit_class_type(model))

    parts.append("")
    parts.append("export type UIEventDimensions = {")
    for event_name, model in DIMENSION_MODELS.items():
        if model is None:
            continue
        if EVENT_CATEGORY[event_name] != EventCategory.UI:
            continue
        wire_name = event_name.value
        ts_class = _ts_type_name_for_class(model)
        parts.append(f'  "{wire_name}": {ts_class};')
    parts.append("};")

    return "\n".join(parts) + "\n"


def _literal_members(annotation: object) -> tuple[object, ...] | None:
    """Return the Literal members for `annotation`, unwrapping `Annotated` if present."""
    if get_origin(annotation) is Annotated:
        annotation = get_args(annotation)[0]
    if get_origin(annotation) is Literal:
        return get_args(annotation)
    return None


def _string_to_constant_key(literal_value: str) -> str:
    """Turn a wire string like ``url_create`` into ``URL_CREATE``."""
    return literal_value.upper()


def _format_const_object(
    constant_name: str,
    members: tuple[str, ...],
    satisfies_clause: str | None,
) -> str:
    body_lines = [f"export const {constant_name} = {{"]
    for value in members:
        key = _string_to_constant_key(value)
        body_lines.append(f'  {key}: "{value}",')
    closing = "} as const"
    if satisfies_clause:
        closing += f" satisfies {satisfies_clause}"
    closing += ";"
    body_lines.append(closing)
    return "\n".join(body_lines)


def _event_name_to_field_prefix(class_name: str) -> str:
    """Convert ``_DimFormSubmit`` -> ``FORM_SUBMIT`` for inline-field constant naming."""
    bare = class_name.lstrip("_")
    if bare.startswith("Dim"):
        bare = bare[3:]
    result_chars: list[str] = []
    for index, char in enumerate(bare):
        if char.isupper() and index > 0:
            result_chars.append("_")
        result_chars.append(char.upper())
    return "".join(result_chars)


def generate_dim_values_ts() -> str:
    """Render the TS source for runtime constants for every dim-value literal.

    Emits one `as const` object per:
      * Named module-level Pydantic Literal alias (`SearchActive`, `TagScope`,
        `HomeForm`, `ValidationForm`) — keyed by the alias name in UPPER_SNAKE.
      * Inline Literal field on each `_Dim<Event>` UI model — keyed by
        ``<EVENT_NAME>_<FIELD_NAME>`` where ``EVENT_NAME`` is the dim-class name
        with the leading ``_Dim`` stripped. Repeated value tuples are emitted
        once under the lexicographically-first name and re-exported under
        subsequent names as aliases (so `DECK_EXPAND_DECK = DECK_COLLAPSE_DECK`).
      * The `DeviceType` IntEnum — keyed `DEVICE_TYPE` with the int values.

    Skips fields whose annotation is not a Literal/IntEnum (e.g. `int`, `bool`,
    `str`) — there is no meaningful constant to emit for arbitrary numbers.
    """
    dimension_module = importlib.import_module("backend.metrics.dimension_models")

    parts: list[str] = [_VALUES_FILE_HEADER]

    # Import all named-alias types so the `satisfies Record<string, Alias>` clauses
    # narrow the const-object values to the corresponding Pydantic Literal alias.
    parts.append("")
    alias_imports = ", ".join(name for name, _ in _NAMED_LITERAL_ALIASES)
    parts.append(f'import type {{ {alias_imports} }} from "./metrics-dimensions.js";')

    # Named module-level Literal aliases — emit one const per alias.
    for alias_name, constant_name in _NAMED_LITERAL_ALIASES:
        alias_annotation = getattr(dimension_module, alias_name)
        members = _literal_members(alias_annotation)
        if members is None:
            raise ValueError(
                f"Expected {alias_name!r} to be a Literal alias but got {alias_annotation!r}."
            )
        string_members = tuple(member for member in members if isinstance(member, str))
        if len(string_members) != len(members):
            raise ValueError(
                f"Named alias {alias_name!r} has non-string Literal members; codegen only supports str."
            )
        parts.append("")
        parts.append(
            _format_const_object(
                constant_name,
                string_members,
                satisfies_clause=f"Record<string, {alias_name}>",
            )
        )

    # DeviceType IntEnum.
    parts.append("")
    device_lines = ["export const DEVICE_TYPE = {"]
    for member in DeviceType:
        device_lines.append(f"  {member.name}: {int(member.value)},")
    device_lines.append("} as const;")
    parts.append("\n".join(device_lines))

    # Inline Literal fields on `_Dim<Event>` UI models. Collect each
    # (class_name, field_name, members) where `members` is the Literal tuple
    # and `class_name` is the class that owns the field. Skip fields whose
    # annotation matches a named alias (those are already emitted above) so the
    # call sites can pick either the alias constant or the per-event constant.
    named_alias_annotations: set[object] = set()
    for alias_name, _constant_name in _NAMED_LITERAL_ALIASES:
        named_alias_annotations.add(getattr(dimension_module, alias_name))

    inline_field_entries: list[tuple[str, str, tuple[str, ...]]] = []
    for event_name, model in DIMENSION_MODELS.items():
        if model is None:
            continue
        if EVENT_CATEGORY[event_name] != EventCategory.UI:
            continue
        for field_name, field_info in model.model_fields.items():
            annotation = field_info.annotation
            if annotation in named_alias_annotations:
                continue
            members = _literal_members(annotation)
            if members is None:
                continue
            string_members = tuple(
                member for member in members if isinstance(member, str)
            )
            if len(string_members) != len(members):
                continue
            inline_field_entries.append((model.__name__, field_name, string_members))

    # De-dupe by value tuple. Sort by (class_name, field_name) so the
    # lexicographically-first event/field wins as the canonical constant; later
    # entries with the same tuple become re-exports.
    inline_field_entries.sort(key=lambda entry: (entry[0], entry[1]))
    canonical_by_members: dict[tuple[str, ...], str] = {}
    seen_constant_names: set[str] = set()
    for class_name, field_name, string_members in inline_field_entries:
        constant_name = (
            f"{_event_name_to_field_prefix(class_name)}_{field_name.upper()}"
        )
        if constant_name in seen_constant_names:
            continue
        seen_constant_names.add(constant_name)
        canonical_constant = canonical_by_members.get(string_members)
        if canonical_constant is None:
            canonical_by_members[string_members] = constant_name
            parts.append("")
            parts.append(
                _format_const_object(
                    constant_name,
                    string_members,
                    satisfies_clause=None,
                )
            )
        else:
            parts.append("")
            parts.append(f"export const {constant_name} = {canonical_constant};")

    return "\n".join(parts) + "\n"


def generate_ui_events_ts() -> str:
    """Render the TS source for the `UI_EVENTS` runtime constant + `UIEventName` type.

    Walks `EventName` filtered to `EVENT_CATEGORY[event] == EventCategory.UI`,
    emitting one key per UI event (e.g. ``UI_UTUB_SELECT: "ui_utub_select"``).
    Codegen guarantees coverage by walking the Python enum directly, so no
    runtime exhaustiveness assertion is needed.

    The `UIEventName` type is derived from the const object's values via
    indexed-access, making the const object the single source of truth for
    both the wire strings and the type.
    """
    parts: list[str] = [_EVENTS_FILE_HEADER]
    parts.append("")
    parts.append("export const UI_EVENTS = {")
    for event_name in EventName:
        if EVENT_CATEGORY[event_name] != EventCategory.UI:
            continue
        parts.append(f'  {event_name.name}: "{event_name.value}",')
    parts.append("} as const;")
    parts.append("")
    parts.append(
        "export type UIEventName = (typeof UI_EVENTS)[keyof typeof UI_EVENTS];"
    )
    return "\n".join(parts) + "\n"
