from __future__ import annotations

import importlib
from enum import IntEnum
from typing import Annotated, Literal, get_args, get_origin

from pydantic import BaseModel

from backend.metrics.dimension_models import DIMENSION_MODELS
from backend.metrics.events import EVENT_CATEGORY, DeviceType, EventCategory, EventName

_DIMENSIONS_FILE_HEADER = """\
// Generated by `flask metrics generate-dim-types` — DO NOT EDIT.
// Source of truth: backend/metrics/dimension_models.py
//
// Per-event dimension shapes mirrored from the Pydantic `_Dim<Event>` models.
// Frontend `emit()` narrows its second argument against `UIEventDimensions[E]`
// so any literal that drifts from the backend Pydantic literal fails to compile.
//
// The named `DeviceType`/`HomeForm`/`ValidationForm`/`SearchActive`/`TagScope`
// aliases are imported from `./metrics-dim-values.js` so the runtime const and
// the compile-time type share a single source of truth (the const object).
"""

_VALUES_FILE_HEADER = """\
// Generated by `flask metrics generate-dim-values` — DO NOT EDIT.
// Source of truth: backend/metrics/dimension_models.py
//
// Runtime constants for every dim-value Literal alias and IntEnum referenced by
// the Pydantic `_Dim<Event>` models. Use these constants at every `emit()` call
// site and test assertion so there is a single source of truth for every dim
// value, locked to Pydantic via codegen, available at both compile time AND
// runtime for query-service and dashboard consumption.
"""

_EVENTS_FILE_HEADER = """\
// Generated by `flask metrics generate-events` — DO NOT EDIT.
// Source of truth: backend/metrics/events.py
//
// Wire-format identifiers for UI events emitted via `emit()`. Each key mirrors
// the matching `EventName.UI_*` member; the value is the wire string the
// backend Pydantic validator expects.
"""

# JSDoc emitted above the `DEVICE_TYPE` runtime const in `metrics-dim-values.ts`.
# Points readers to the backend IntEnum that defines the int values so the
# named mapping (`MOBILE`, `DESKTOP`) can be cross-referenced.
_DEVICE_TYPE_JSDOC = """\
/**
 * Device type emitted with every UI event. Values match the
 * `DeviceType` IntEnum in `backend/metrics/events.py`. The derived
 * `DeviceType` type below makes this const the single source of
 * truth for both the runtime values and the compile-time type.
 */"""

# Named module-level Literal aliases declared in dimension_models. Each pairs
# the in-Python alias name to the UPPER_SNAKE constant name in the generated TS.
_NAMED_LITERAL_ALIASES: tuple[tuple[str, str], ...] = (
    ("SearchActive", "SEARCH_ACTIVE"),
    ("TagScope", "TAG_SCOPE"),
    ("HomeForm", "HOME_FORM"),
    ("ValidationForm", "VALIDATION_FORM"),
)


def _named_alias_annotations() -> dict[int, str]:
    """Map ``id(alias)`` -> alias_name for every named Pydantic Literal alias.

    Identity-keyed so callers can detect when a Pydantic field's annotation
    IS the named module-level alias (e.g. ``form: HomeForm``) and emit the
    alias name instead of inlining the literal union. Pydantic preserves
    identity for typing-alias annotations, so ``finfo.annotation is HomeForm``
    holds.
    """
    dimension_module = importlib.import_module("backend.metrics.dimension_models")
    identity_to_name: dict[int, str] = {}
    for alias_name, _constant_name in _NAMED_LITERAL_ALIASES:
        alias_annotation = getattr(dimension_module, alias_name)
        identity_to_name[id(alias_annotation)] = alias_name
    return identity_to_name


def _ts_for_annotation(annotation: object, named_aliases: dict[int, str]) -> str:
    """Map a Pydantic field annotation to a TypeScript type expression.

    ``named_aliases`` is the identity-keyed map produced once per codegen run
    by ``_named_alias_annotations()`` and threaded through ``_emit_class_type``
    so this function never re-imports the dimension module on a hot path.
    """
    if get_origin(annotation) is Annotated:
        annotation = get_args(annotation)[0]
    # Detect named Pydantic Literal aliases by identity BEFORE the Literal
    # branch fires, so e.g. `form: HomeForm` emits `HomeForm` instead of
    # inlining the eight-member literal union. The named aliases are imported
    # from `./metrics-dim-values.js` at the top of the dim-types file.
    alias_name = named_aliases.get(id(annotation))
    if alias_name is not None:
        return alias_name
    origin = get_origin(annotation)
    if origin is Literal:
        members = get_args(annotation)
        formatted_members: list[str] = []
        for member in members:
            if isinstance(member, str):
                formatted_members.append(f'"{member}"')
            else:
                formatted_members.append(str(member))
        return " | ".join(formatted_members)
    if isinstance(annotation, type) and issubclass(annotation, IntEnum):
        # Return the IntEnum class name so callers reference a named TS alias
        # (e.g. `DeviceType`) instead of an opaque inline literal union like
        # `1 | 2`. The named alias lives in `./metrics-dim-values.js` and is
        # imported at the top of the dim-types file.
        return annotation.__name__
    if annotation is int:
        return "number"
    if annotation is bool:
        return "boolean"
    if annotation is str:
        return "string"
    raise ValueError(
        f"Unsupported annotation in dim codegen: {annotation!r}. "
        "Extend `_ts_for_annotation` to handle this type."
    )


def _ts_type_name_for_class(model: type[BaseModel]) -> str:
    """Strip the leading underscore on private Pydantic dim classes."""
    return model.__name__.lstrip("_")


def _emit_class_type(model: type[BaseModel], named_aliases: dict[int, str]) -> str:
    lines = [f"export type {_ts_type_name_for_class(model)} = {{"]
    for field_name, field_info in model.model_fields.items():
        ts_type = _ts_for_annotation(field_info.annotation, named_aliases)
        lines.append(f"  {field_name}: {ts_type};")
    lines.append("};")
    return "\n".join(lines)


def generate_dim_types_ts() -> str:
    """Render the TS source for per-event dim types + the UIEventDimensions map.

    Walks `DIMENSION_MODELS` filtered to `EventCategory.UI`. Distinct Pydantic
    classes are emitted once (so e.g. `_DimDeviceOnly` produces one TS alias
    referenced by every UI event whose dim model is `_DimDeviceOnly`). The
    final `UIEventDimensions` map names every UI `EventName` so the TS
    compiler enforces exhaustive coverage at the consumer.

    The `DeviceType` IntEnum and named Pydantic Literal aliases (`HomeForm`,
    `ValidationForm`, `SearchActive`, `TagScope`) live in
    `./metrics-dim-values.js` — derived directly from each runtime const via
    `(typeof CONST)[keyof typeof CONST]`. They are imported here so dim-class
    field annotations like `form: HomeForm` resolve to the named alias.
    """
    seen_classes: dict[type[BaseModel], None] = {}
    for event_name, model in DIMENSION_MODELS.items():
        if model is None:
            continue
        if EVENT_CATEGORY[event_name] != EventCategory.UI:
            continue
        seen_classes.setdefault(model, None)

    # Build the identity-keyed named-alias map ONCE per codegen run and thread
    # it through `_emit_class_type` -> `_ts_for_annotation`. Avoids the
    # importlib + alias-lookup work firing for every dim field.
    named_aliases = _named_alias_annotations()

    parts: list[str] = [_DIMENSIONS_FILE_HEADER]

    # Import the named types from the runtime-constants file so dim-class
    # fields (`device_type: DeviceType`, `form: HomeForm`, etc.) resolve to a
    # single source of truth — the `as const` object — instead of being
    # inlined twice. Alphabetized per project style.
    imported_alias_names = sorted(
        [DeviceType.__name__]
        + [alias_name for alias_name, _constant_name in _NAMED_LITERAL_ALIASES]
    )
    parts.append("")
    parts.append("import type {")
    for alias_name in imported_alias_names:
        parts.append(f"  {alias_name},")
    parts.append('} from "./metrics-dim-values.js";')

    for model in seen_classes:
        parts.append("")
        parts.append(_emit_class_type(model, named_aliases))

    parts.append("")
    parts.append("export type UIEventDimensions = {")
    for event_name, model in DIMENSION_MODELS.items():
        if model is None:
            continue
        if EVENT_CATEGORY[event_name] != EventCategory.UI:
            continue
        wire_name = event_name.value
        ts_class = _ts_type_name_for_class(model)
        parts.append(f'  "{wire_name}": {ts_class};')
    parts.append("};")

    return "\n".join(parts) + "\n"


def _literal_members(annotation: object) -> tuple[object, ...] | None:
    """Return the Literal members for `annotation`, unwrapping `Annotated` if present."""
    if get_origin(annotation) is Annotated:
        annotation = get_args(annotation)[0]
    if get_origin(annotation) is Literal:
        return get_args(annotation)
    return None


def _string_to_constant_key(literal_value: str) -> str:
    """Turn a wire string like ``url_create`` into ``URL_CREATE``."""
    return literal_value.upper()


def _format_const_object(
    constant_name: str,
    members: tuple[str, ...],
    satisfies_clause: str | None,
) -> str:
    body_lines = [f"export const {constant_name} = {{"]
    for value in members:
        key = _string_to_constant_key(value)
        body_lines.append(f'  {key}: "{value}",')
    closing = "} as const"
    if satisfies_clause:
        closing += f" satisfies {satisfies_clause}"
    closing += ";"
    body_lines.append(closing)
    return "\n".join(body_lines)


def _emit_derived_type(alias_name: str, constant_name: str) -> str:
    """Return ``export type Alias = (typeof CONST)[keyof typeof CONST];``.

    Derives the type from the const object so the const is the single source
    of truth for both runtime values and the compile-time type. Any drift
    between the two becomes impossible — TS infers the type from the literal
    const values directly.
    """
    return (
        f"export type {alias_name} = "
        f"(typeof {constant_name})[keyof typeof {constant_name}];"
    )


def _event_name_to_field_prefix(class_name: str) -> str:
    """Convert ``_DimFormSubmit`` -> ``FORM_SUBMIT`` for inline-field constant naming."""
    bare = class_name.lstrip("_")
    if bare.startswith("Dim"):
        bare = bare[3:]
    result_chars: list[str] = []
    for index, char in enumerate(bare):
        if char.isupper() and index > 0:
            result_chars.append("_")
        result_chars.append(char.upper())
    return "".join(result_chars)


def generate_dim_values_ts() -> str:
    """Render the TS source for runtime constants for every dim-value literal.

    Emits one `as const` object per:
      * Named module-level Pydantic Literal alias (`SearchActive`, `TagScope`,
        `HomeForm`, `ValidationForm`) — keyed by the alias name in UPPER_SNAKE.
      * Inline Literal field on each `_Dim<Event>` UI model — keyed by
        ``<EVENT_NAME>_<FIELD_NAME>`` where ``EVENT_NAME`` is the dim-class name
        with the leading ``_Dim`` stripped. Repeated value tuples are emitted
        once under the lexicographically-first name and re-exported under
        subsequent names as aliases (so `DECK_EXPAND_DECK = DECK_COLLAPSE_DECK`).
      * The `DeviceType` IntEnum — keyed `DEVICE_TYPE` with the int values.

    For the `DeviceType` IntEnum and each named Literal alias, also emits a
    derived ``export type Alias = (typeof CONST)[keyof typeof CONST];`` so the
    const object is the single source of truth for both runtime values and the
    compile-time type. The dim-types file imports these named types from here.

    Skips fields whose annotation is not a Literal/IntEnum (e.g. `int`, `bool`,
    `str`) — there is no meaningful constant to emit for arbitrary numbers.
    """
    dimension_module = importlib.import_module("backend.metrics.dimension_models")

    parts: list[str] = [_VALUES_FILE_HEADER]

    # Named module-level Literal aliases — emit one const + derived type per
    # alias. The derived type makes the const the single source of truth, so
    # the `satisfies Record<string, X>` guard is no longer needed: any drift
    # between const and type is structurally impossible.
    for alias_name, constant_name in _NAMED_LITERAL_ALIASES:
        alias_annotation = getattr(dimension_module, alias_name)
        members = _literal_members(alias_annotation)
        if members is None:
            raise ValueError(
                f"Expected {alias_name!r} to be a Literal alias but got {alias_annotation!r}."
            )
        string_members = tuple(member for member in members if isinstance(member, str))
        if len(string_members) != len(members):
            raise ValueError(
                f"Named alias {alias_name!r} has non-string Literal members; codegen only supports str."
            )
        parts.append("")
        parts.append(
            _format_const_object(
                constant_name,
                string_members,
                satisfies_clause=None,
            )
        )
        parts.append("")
        parts.append(_emit_derived_type(alias_name, constant_name))

    # DeviceType IntEnum + derived type. The derived `DeviceType` type takes
    # its values from the const, so the named MOBILE/DESKTOP entries and the
    # `1 | 2` compile-time literal can never disagree.
    parts.append("")
    parts.append(_DEVICE_TYPE_JSDOC)
    device_lines = ["export const DEVICE_TYPE = {"]
    for member in DeviceType:
        device_lines.append(f"  {member.name}: {int(member.value)},")
    device_lines.append("} as const;")
    parts.append("\n".join(device_lines))
    parts.append("")
    parts.append(_emit_derived_type(DeviceType.__name__, "DEVICE_TYPE"))

    # Inline Literal fields on `_Dim<Event>` UI models. Collect each
    # (class_name, field_name, members) where `members` is the Literal tuple
    # and `class_name` is the class that owns the field. Skip fields whose
    # annotation matches a named alias (those are already emitted above) so the
    # call sites can pick either the alias constant or the per-event constant.
    named_alias_annotations: set[object] = set()
    for alias_name, _constant_name in _NAMED_LITERAL_ALIASES:
        named_alias_annotations.add(getattr(dimension_module, alias_name))

    inline_field_entries: list[tuple[str, str, tuple[str, ...]]] = []
    for event_name, model in DIMENSION_MODELS.items():
        if model is None:
            continue
        if EVENT_CATEGORY[event_name] != EventCategory.UI:
            continue
        for field_name, field_info in model.model_fields.items():
            annotation = field_info.annotation
            if annotation in named_alias_annotations:
                continue
            members = _literal_members(annotation)
            if members is None:
                continue
            string_members = tuple(
                member for member in members if isinstance(member, str)
            )
            if len(string_members) != len(members):
                continue
            inline_field_entries.append((model.__name__, field_name, string_members))

    # De-dupe by value tuple. Sort by (class_name, field_name) so the
    # lexicographically-first event/field wins as the canonical constant; later
    # entries with the same tuple become re-exports.
    inline_field_entries.sort(key=lambda entry: (entry[0], entry[1]))
    canonical_by_members: dict[tuple[str, ...], str] = {}
    seen_constant_names: set[str] = set()
    for class_name, field_name, string_members in inline_field_entries:
        constant_name = (
            f"{_event_name_to_field_prefix(class_name)}_{field_name.upper()}"
        )
        if constant_name in seen_constant_names:
            continue
        seen_constant_names.add(constant_name)
        canonical_constant = canonical_by_members.get(string_members)
        if canonical_constant is None:
            canonical_by_members[string_members] = constant_name
            parts.append("")
            parts.append(
                _format_const_object(
                    constant_name,
                    string_members,
                    satisfies_clause=None,
                )
            )
        else:
            parts.append("")
            parts.append(f"export const {constant_name} = {canonical_constant};")

    return "\n".join(parts) + "\n"


def generate_ui_events_ts() -> str:
    """Render the TS source for the `UI_EVENTS` runtime constant + `UIEventName` type.

    Walks `EventName` filtered to `EVENT_CATEGORY[event] == EventCategory.UI`,
    emitting one key per UI event (e.g. ``UI_UTUB_SELECT: "ui_utub_select"``).
    Codegen guarantees coverage by walking the Python enum directly, so no
    runtime exhaustiveness assertion is needed.

    The `UIEventName` type is derived from the const object's values via
    indexed-access, making the const object the single source of truth for
    both the wire strings and the type.
    """
    parts: list[str] = [_EVENTS_FILE_HEADER]
    parts.append("")
    parts.append("export const UI_EVENTS = {")
    for event_name in EventName:
        if EVENT_CATEGORY[event_name] != EventCategory.UI:
            continue
        parts.append(f'  {event_name.name}: "{event_name.value}",')
    parts.append("} as const;")
    parts.append("")
    parts.append(
        "export type UIEventName = (typeof UI_EVENTS)[keyof typeof UI_EVENTS];"
    )
    return "\n".join(parts) + "\n"
