class EMAIL_CONSTANTS:
    MAX_EMAIL_ATTEMPTS_IN_HOUR = 5
    WAIT_TO_RETRY_BEFORE_MAX_ATTEMPTS = 60
    WAIT_TO_ATTEMPT_AFTER_MAX_ATTEMPTS = 3600


class USER_CONSTANTS:
    MAX_USERNAME_LENGTH_ACTUAL = 25
    MAX_USERNAME_LENGTH = MAX_USERNAME_LENGTH_ACTUAL - 5
    PASSWORD_RESET_ATTEMPTS = 5
    WAIT_TO_RETRY_FORGOT_PASSWORD_MIN = 60
    WAIT_TO_RETRY_FORGOT_PASSWORD_MAX = 3600


class UTUB_CONSTANTS:
    MAX_NAME_LENGTH = 30
    MAX_DESCRIPTION_LENGTH = 500
