# Config Env vars labels
class CONFIG_ENVS:
    SECRET_KEY = "SECRET_KEY"
    MAILJET_SECRET_KEY = "MAILJET_SECRET_KEY"
    MAILJET_API_KEY = "MAILJET_API_KEY"
    BASE_EMAIL = "BASE_EMAIL"
    REDIS_URI = "REDIS_URI"
    POSTGRES_USER = "POSTGRES_USER"
    POSTGRES_DB = "POSTGRES_DB"
    POSTGRES_PASSWORD = "POSTGRES_PASSWORD"
    POSTGRES_TEST_DB = "POSTGRES_TEST_DB"
    DOCKER = "DOCKER"
    PRODUCTION = "PRODUCTION"
    ASSET_VERSION = "ASSET_VERSION"
