from src.utils.strings.model_strs import (
    EMAIL,
    NAME,
    PASSWORD,
    TAG_STRING,
    URL_STRING,
    URL_TITLE,
    USERNAME,
    UTUB_DESCRIPTION,
)
from src.utils.strings.utub_strs import UTUB_NAME

# Strings for all forms
CSRF_TOKEN = "csrf_token"


class GENERAL_FORM:
    CSRF_TOKEN = CSRF_TOKEN
    EMAIL = EMAIL
    PASSWORD = PASSWORD


class TAG_FORM(GENERAL_FORM):
    TAG_STRING = TAG_STRING


class URL_FORM(GENERAL_FORM):
    URL_STRING = URL_STRING
    URL_TITLE = URL_TITLE


class ADD_USER_FORM(GENERAL_FORM):
    USERNAME = USERNAME


class UTUB_FORM(GENERAL_FORM):
    NAME = NAME
    UTUB_NAME = UTUB_NAME
    UTUB_DESCRIPTION = UTUB_DESCRIPTION


class UTUB_DESCRIPTION_FORM(GENERAL_FORM):
    UTUB_DESCRIPTION = UTUB_DESCRIPTION
    UTUB_DESCRIPTION_FOR_FORM = UTUB_DESCRIPTION
