HOST = "Host"
USER_AGENT = "User-Agent"
ACCEPT = "Accept"
CONNECTION = "Connection"
ACCEPT_ENCODING = "Accept-Encoding"
ACCEPT_LANGUAGE = "Accept-Language"
SEC_FETCH_DEST = "Sec-Fetch-Dest"
SEC_FETCH_MODE = "Sec-Fetch-Mode"
SEC_FETCH_USER = "Sec-Fetch-User"
LOCATION = "Location"
X_REQUESTED_WITH = "X-Requested-With"
X_CSRF_TOKEN = "X-CSRFToken"
XMLHTTPREQUEST = "XMLHttpRequest"
COOKIE = "Cookie"
ORIGIN = "Origin"
REFERER = "Referer"
CF_MITIGATED = "cf-mitigated"
ERROR_FROM_CLOUDFRONT = "error from cloudfront"
X_CACHE = "x-cache"
CLOUDFLARE_SERVER = "cloudflare"
SERVER = "server"
GOOGLE_CACHE = "https://webcache.googleusercontent.com/search?q=cache:"
WAYBACK_ARCHIVE = "https://web.archive.org/web/"
ORIGINAL = "original"
URL = "url"
CONTENT_TYPE = "Content-Type"
CONTENT_LENGTH = "Content-Length"
HTML_CONTENT = "text/html"
URL_VALIDATION_MODULE = "urlValidationModule"
SHORT_URLS = "short-url-domains"


class URL_VALIDATION:
    HOST = HOST
    USER_AGENT = USER_AGENT
    ACCEPT = ACCEPT
    CONNECTION = CONNECTION
    ACCEPT_ENCODING = ACCEPT_ENCODING
    ACCEPT_LANGUAGE = ACCEPT_LANGUAGE
    SEC_FETCH_DEST = SEC_FETCH_DEST
    SEC_FETCH_MODE = SEC_FETCH_MODE
    SEC_FETCH_USER = SEC_FETCH_USER
    LOCATION = LOCATION
    X_REQUESTED_WITH = X_REQUESTED_WITH
    X_CSRF_TOKEN = X_CSRF_TOKEN
    XMLHTTPREQUEST = XMLHTTPREQUEST
    COOKIE = COOKIE
    ORIGIN = ORIGIN
    REFERER = REFERER
    CF_MITIGATED = CF_MITIGATED
    ERROR_FROM_CLOUDFRONT = ERROR_FROM_CLOUDFRONT
    X_CACHE = X_CACHE
    CLOUDFLARE_SERVER = CLOUDFLARE_SERVER
    SERVER = SERVER
    GOOGLE_CACHE = GOOGLE_CACHE
    WAYBACK_ARCHIVE = WAYBACK_ARCHIVE
    ORIGINAL = ORIGINAL
    URL = URL
    CONTENT_TYPE = CONTENT_TYPE
    CONTENT_LENGTH = CONTENT_LENGTH
    HTML_CONTENT = HTML_CONTENT
    URL_VALIDATION_MODULE = URL_VALIDATION_MODULE
    SHORT_URLS = SHORT_URLS
    INVALID_HEADERS = {
        header.lower()
        for header in (
            CONTENT_TYPE,
            X_REQUESTED_WITH,
            X_CSRF_TOKEN,
            CONTENT_LENGTH,
            COOKIE,
            ORIGIN,
            REFERER,
        )
    }
