from src.utils.strings.json_strs import FAILURE_GENERAL, REDIRECT
from src.utils.strings.model_strs import (
    ADDED_BY,
    URL_ID,
    URL_STRING,
    URL_TITLE,
    UTUB_URL_TAG_IDS,
    URL_TAGS,
    UTUB_URL_ID,
)
from src.utils.strings.utub_strs import UTUB_GENERAL

# Strings for URL success
URLS = "urls"
URL = "URL"
URL_CREATED_ADDED = "New URL created and added to UTub."
URL_ADDED = "URL added to UTub."
URL_REMOVED = "URL removed from this UTub."
URL_TITLE_MODIFIED = "URL title was modified."
URL_OR_TITLE_MODIFIED = "URL and/or URL title modified."
URL_MODIFIED = "URL modified."
URL_FOUND_IN_UTUB = "URL found in UTub."
TAG_IN_UTUB = "tagInUTub"


class URL_GENERAL:
    URL = URL
    REDIRECT = REDIRECT
    UTUB_URL_TAG_IDS = UTUB_URL_TAG_IDS
    URL_ID = URL_ID
    TAG_IN_UTUB = TAG_IN_UTUB


class URL_SUCCESS(URL_GENERAL, UTUB_GENERAL):
    URL_ADDED = URL_ADDED
    URL_STRING = URL_STRING
    URL_TITLE = URL_TITLE
    ADDED_BY = ADDED_BY
    URL_REMOVED = URL_REMOVED
    URL_CREATED_ADDED = URL_CREATED_ADDED
    URL_TITLE_MODIFIED = URL_TITLE_MODIFIED
    URL_OR_TITLE_MODIFIED = URL_OR_TITLE_MODIFIED
    URL_MODIFIED = URL_MODIFIED
    UTUB_URL_ID = UTUB_URL_ID
    URL_FOUND_IN_UTUB = URL_FOUND_IN_UTUB
    URL_TAGS = URL_TAGS


# Strings for URL failure
UNABLE_TO_DELETE_URL = "Unable to remove this URL."
UNABLE_TO_ADD_URL = "Unable to add this URL."
UNABLE_TO_VALIDATE_THIS_URL = "Unable to validate this URL."
URL_IN_UTUB = "URL already in UTub."
UNABLE_TO_ADD_URL_FORM = "Unable to add this URL, please check inputs."
UNABLE_TO_MODIFY_URL_FORM = "Unable to update, please check inputs."
UNABLE_TO_MODIFY_URL = "Unable to modify this URL."
UNABLE_TO_RETRIEVE_URL = "Unable to retrieve this URL."
EMPTY_URL = "URL cannot be empty."
TOO_MANY_WAYBACK_ATTEMPTS = "Too many attempts, please try again in one minute."
UNEXPECTED_VALIDATION_EXCEPTION = "Unexpected exception while validating the URL."


class URL_FAILURE(FAILURE_GENERAL):
    UNABLE_TO_VALIDATE_THIS_URL = UNABLE_TO_VALIDATE_THIS_URL
    UNABLE_TO_ADD_URL = UNABLE_TO_ADD_URL
    UNABLE_TO_DELETE_URL = UNABLE_TO_DELETE_URL
    URL_IN_UTUB = URL_IN_UTUB
    UNABLE_TO_ADD_URL_FORM = UNABLE_TO_ADD_URL_FORM
    UNABLE_TO_MODIFY_URL = UNABLE_TO_MODIFY_URL
    UNABLE_TO_RETRIEVE_URL = UNABLE_TO_RETRIEVE_URL
    EMPTY_URL = EMPTY_URL
    UNABLE_TO_MODIFY_URL_FORM = UNABLE_TO_MODIFY_URL_FORM
    URL_TITLE = URL_TITLE
    URL_STRING = URL_STRING
    TOO_MANY_WAYBACK_ATTEMPTS = TOO_MANY_WAYBACK_ATTEMPTS
    UNEXPECTED_VALIDATION_EXCEPTION = UNEXPECTED_VALIDATION_EXCEPTION


# Strings for URL no change
URL_AND_TITLE_NOT_MODIFIED = "URL and URL title were not modified."
URL_NOT_MODIFIED = "URL not modified."
URL_TITLE_NOT_MODIFIED = "URL title not modified."


class URL_NO_CHANGE:
    URL_AND_TITLE_NOT_MODIFIED = URL_AND_TITLE_NOT_MODIFIED
    URL_NOT_MODIFIED = URL_NOT_MODIFIED
    URL_TITLE_NOT_MODIFIED = URL_TITLE_NOT_MODIFIED
