"""Host capacity derivation, run by `make capacity` from the repo root.

Derives the UI and integration pytest-xdist worker counts from the Docker
host's cores and memory, plus the ceilings that must grow with them (the
metrics-Redis database count, and the shared Postgres cluster's
`max_connections`, test-role connection limit and `shared_buffers`). Stdlib
only: it runs on the host under bare mise python, before any container exists.

Subcommands (see `main`): `generate` writes the gitignored env file,
`ensure` regenerates it only when the host fingerprint changed (run before
every stack/test target), `show` prints the resolved values and live memory,
`logs-owner-fix` re-owns the `app_logs` volume's log dir to the recorded
HOST_UID:HOST_GID (run before every stack start), and `admit` refuses a new
spoke past the U4I_SPOKE_MAX ceiling (spoke admission).
"""

from __future__ import annotations

import argparse
import hashlib
import math
import os
import subprocess
import sys
import tempfile
from collections.abc import Callable
from dataclasses import dataclass, replace
from pathlib import Path
from typing import TypeVar

# Metrics-Redis indices no test run may lease; mirrors
# len(scripts.testrun_resources.METRICS_RESERVED_INDICES) (a parity test pins it).
METRICS_REDIS_RESERVED_DBS: int = 1
# How many simultaneous pytest invocations each Redis lease pool must hold: the
# metrics pool at n_max (derived per host), and the shared-redis session pool at
# HARD_N_CEILING (fixed, see SHARED_REDIS_DATABASES), so two runs always fit both.
LEASE_CONCURRENT_RUNS: int = 2
# Assumes SQLAlchemy's library-default QueuePool (pool_size=5 + max_overflow=10):
# the app sets no explicit pool options (backend/__init__.py only defaults
# SQLALCHEMY_ENGINE_OPTIONS to {}). Update this if pool settings are ever added
# to SQLALCHEMY_ENGINE_OPTIONS in backend/config.py.
CONN_PER_WORKER: int = 15
CONN_BASE: int = 50
# The cluster's max_connections = the test role's limit + dev app/workflow
# headroom + Postgres's superuser_reserved_connections default.
DEV_CONN_BUDGET: int = 30
SUPERUSER_RESERVED: int = 3
# shared_buffers = 1/64 of usable memory, clamped (a shared dev box, not prod).
PG_SHARED_BUFFERS_MIN_MB: int = 64
PG_SHARED_BUFFERS_MAX_MB: int = 256
PG_SHARED_BUFFERS_DIVISOR: int = 64
MB_PER_GB: int = 1024
# The per-run worker cap: each worker leases one shared-redis session index.
HARD_N_CEILING: int = 30
# Shared-redis indices no test run may lease: dev DB 0 and the session pool's base DB.
SESSION_REDIS_RESERVED_DBS: int = 2
SHARED_REDIS_DATABASES_FLOOR: int = 32
BASE_GB: float = 2.0
WORKER_GB: float = 0.5
# Idle footprints for spoke admission (measured on the reference Linux host):
# hub Postgres ~230 MB + hub Playwright ~339 MiB after a UI run (master Phase 8).
HUB_IDLE_GB: float = 0.6
# One idle spoke (web + db-init + redis + redis-metrics): 213-225 MB (master Phase 6).
SPOKE_IDLE_GB: float = 0.25
DEFAULT_MEM_FRACTION: float = 0.70
DEFAULT_MEM_SAFETY: float = 0.90

N_UI_MIN: int = 2
N_UI_MAX: int = 12
N_INT_MIN: int = 2
N_INT_MAX: int = 16
REDIS_METRICS_DATABASES_FLOOR: int = 16
BYTES_PER_GB: int = 1024**3

BINDING_CPU: str = "cpu"
BINDING_MEMORY: str = "memory"
BINDING_OVERRIDE: str = "override"

DEFAULT_MEMINFO_PATH: Path = Path("/proc/meminfo")
DEFAULT_CGROUP_PATH: Path = Path("/sys/fs/cgroup/memory.max")
BYTES_PER_KB: int = 1024
DOCKER_INFO_TIMEOUT_SECONDS: int = 30
AUTO: str = "auto"

# `logs-owner-fix` finds the spoke's volume and web image from U4I_PROJECT (compose.local.yaml's `name:`),
# which the Makefile computes and exports.
PROJECT_ENV_VAR: str = "U4I_PROJECT"
LOGS_VOLUME_NAME: str = "app_logs"
LOGS_VOLUME_MOUNT: str = "/app/volume"
LOGS_DIR: str = f"{LOGS_VOLUME_MOUNT}/logs"
LOGS_DIR_MODE: str = "775"  # as web's image sets it
# A 0 uid/gid (root host) maps here, mirroring docker/Dockerfile.Local's fallback.
ROOT_ID_FALLBACK: int = 1001
DOCKER_RUN_TIMEOUT_SECONDS: int = 120
# The live-memory read runs on every test-run poll and spoke admit, so a hung
# daemon must not stall it for DOCKER_RUN_TIMEOUT_SECONDS. token_budget.py
# duplicates this constant (a parity test pins the two together).
LIVE_MEMORY_DOCKER_TIMEOUT_SECONDS: int = 10

# Where a live available-memory reading came from.
LIVE_SOURCE_HOST: str = "host"  # this host's /proc/meminfo (Linux)
LIVE_SOURCE_VM: str = "vm"  # the Docker VM's, via the hub db container (macOS/Colima)
LIVE_SOURCE_NONE: str = "none"  # unreadable: callers fall back to static capacity

# `admit` lists the compose project of every running container on the shared network.
COMPOSE_PROJECT_FORMAT: str = '{{.Label "com.docker.compose.project"}}'
ADMISSION_PREFIX: str = "spoke admission: "
# The capacity-file keys the admission decision and its refusal message read.
ADMISSION_KEYS: tuple[str, ...] = (
    "U4I_N_MAX",
    "U4I_USABLE_MB",
    "U4I_HUB_IDLE_MB",
    "U4I_SPOKE_IDLE_MB",
    "U4I_SPOKE_MAX",
)

GENERATED_HEADER: str = "# GENERATED by make capacity — DO NOT EDIT"
DECISION_PREFIX: str = "# decision: "
DECISION_SPOKE_MAX_TOKEN: str = "spoke_max="
FINGERPRINT_KEY: str = "U4I_CAPACITY_FINGERPRINT"
OVERRIDE_N_UI_KEY: str = "U4I_OVERRIDE_N_UI"
OVERRIDE_N_INT_KEY: str = "U4I_OVERRIDE_N_INT"
OVERRIDE_MEM_FRACTION_KEY: str = "U4I_OVERRIDE_MEM_FRACTION"
# Values baked into running containers. A spoke interlock change needs `make up [p=…] d=1`
# (U4I_PG_TEST_CONN_LIMIT too: `make up` → `hub-up` → `cluster-init` re-applies the role's limit).
# A hub interlock is baked into the hub `db`'s Postgres `command:` args, which `hub-up`'s
# `--no-recreate db` never restarts, so it needs every spoke down, then `hub-down` + `hub-up`.
# The hub (db args, cluster-init's U4I_PG_TEST_CONN_LIMIT) reads ONLY the primary clone's capacity
# file ($PRIMARY_ROOT/docker/.capacity.generated.env, PRIMARY_ROOT exported by the Makefile). When a
# linked worktree writes its own file, HUB_READ_KEYS changes there reach the hub only after
# `make capacity` in the primary clone, so they get PRIMARY_ONLY_NOTE instead of the tier messages.
SPOKE_INTERLOCK_KEYS: tuple[str, ...] = (
    "REDIS_METRICS_DATABASES",
    "U4I_PG_TEST_CONN_LIMIT",
    "HOST_UID",
    "HOST_GID",
)
HUB_INTERLOCK_KEYS: tuple[str, ...] = ("U4I_PG_MAX_CONN", "U4I_PG_SHARED_BUFFERS_MB")
INTERLOCK_KEYS: tuple[str, ...] = SPOKE_INTERLOCK_KEYS + HUB_INTERLOCK_KEYS
SPOKE_RECREATE_MESSAGE: str = "recreate required: run 'make up [p=…] d=1'"
HUB_RECREATE_MESSAGE: str = (
    "hub recreate required: run 'make down' in every spoke, "
    "then 'make hub-down' and 'make hub-up'"
)
PRIMARY_ROOT_ENV_VAR: str = "PRIMARY_ROOT"
PRIMARY_CAPACITY_RELATIVE_PATH: Path = Path("docker") / ".capacity.generated.env"
HUB_READ_KEYS: tuple[str, ...] = (*HUB_INTERLOCK_KEYS, "U4I_PG_TEST_CONN_LIMIT")
PRIMARY_ONLY_NOTE: str = (
    "note: the hub reads the primary clone's capacity file, so these apply only "
    "after 'make capacity' in {primary_root}"
)
# Every `KEY=value` line `render_env` emits, in order.
ENV_KEYS: tuple[str, ...] = (
    "U4I_N_UI",
    "U4I_N_INT",
    "U4I_N_MAX",
    "REDIS_METRICS_DATABASES",
    "U4I_PG_TEST_CONN_LIMIT",
    "U4I_PG_MAX_CONN",
    "U4I_PG_SHARED_BUFFERS_MB",
    "U4I_USABLE_MB",
    "U4I_HUB_IDLE_MB",
    "U4I_SPOKE_IDLE_MB",
    "U4I_BASE_MB",
    "U4I_WORKER_MB",
    "U4I_SPOKE_MAX",
    "HOST_UID",
    "HOST_GID",
    FINGERPRINT_KEY,
    OVERRIDE_N_UI_KEY,
    OVERRIDE_N_INT_KEY,
    OVERRIDE_MEM_FRACTION_KEY,
)

ValueT = TypeVar("ValueT", int, float)


class InfeasibleCapacity(ValueError):
    """A requested worker count or memory fraction cannot run on this host."""


class DockerInfoError(RuntimeError):
    """`docker info` failed or printed something unparseable."""


class DockerRunError(RuntimeError):
    """A `logs-owner-fix` docker command failed to launch or its repair failed."""


class CorruptCapacityFile(ValueError):
    """The capacity env file holds a value `logs-owner-fix` cannot use."""


DockerRunner = Callable[[list[str]], subprocess.CompletedProcess[str]]


@dataclass(frozen=True)
class AdmissionResult:
    """`admit`'s decision: `others` are the other running spokes (sorted)."""

    admitted: bool
    others: tuple[str, ...]
    message: str


@dataclass(frozen=True)
class LiveMemory:
    """Available memory right now (bytes, None when unreadable) and its LIVE_SOURCE_*."""

    available_bytes: int | None
    source: str


@dataclass(frozen=True)
class Probe:
    ncpu: int
    mem_total_bytes: int
    mem_available_bytes: int | None
    cgroup_max_bytes: int | None
    host_uid: int
    host_gid: int


@dataclass(frozen=True)
class Overrides:
    n_ui: int | None = None
    n_int: int | None = None
    mem_fraction: float | None = None


@dataclass(frozen=True)
class Capacity:
    n_ui: int
    n_int: int
    n_max: int
    redis_metrics_databases: int
    pg_test_conn_limit: int
    pg_max_conn: int
    pg_shared_buffers_mb: int
    usable_gb: float
    binding_constraint: str
    spoke_max: int
    spoke_max_clamped: bool


def clamp(value: int, low: int, high: int) -> int:
    return max(low, min(value, high))


def round_up_pow2(value: int) -> int:
    return 1 << max(value - 1, 0).bit_length()


# The local shared `redis --databases` count (docker/compose.local.yaml hardcodes
# it; a parity test pins the two together). Minus SESSION_REDIS_RESERVED_DBS, it
# leaves a session index per worker for LEASE_CONCURRENT_RUNS runs at HARD_N_CEILING.
SHARED_REDIS_DATABASES: int = max(
    SHARED_REDIS_DATABASES_FLOOR,
    round_up_pow2(SESSION_REDIS_RESERVED_DBS + LEASE_CONCURRENT_RUNS * HARD_N_CEILING),
)


def _usable_gb(probe: Probe, mem_fraction: float, mem_safety: float) -> float:
    total_gb = probe.mem_total_bytes / BYTES_PER_GB * mem_fraction
    known_available = [
        available_bytes
        for available_bytes in (probe.mem_available_bytes, probe.cgroup_max_bytes)
        if available_bytes is not None
    ]
    if not known_available:
        return total_gb
    return min(total_gb, min(known_available) / BYTES_PER_GB * mem_safety)


def _memory_guard(usable_gb: float) -> int:
    # Round before flooring: binary-float rounding on usable_gb (e.g. 237.99999999999997
    # instead of 238.0) can otherwise make the floor under-count by one worker.
    return max(1, math.floor(round((usable_gb - BASE_GB) / WORKER_GB, 6)))


def _spoke_ceiling(usable_gb: float) -> tuple[int, bool]:
    """(spokes that fit, whether the floor clamped to 1): spokes that fit on an idle
    host with room for one minimum test run; informational — admission reads live
    memory. Round before flooring, as in `_memory_guard`, so binary-float rounding
    can't under-count by one."""
    spokes_that_fit = math.floor(
        round((usable_gb - HUB_IDLE_GB - _gb_needed(1)) / SPOKE_IDLE_GB, 6)
    )
    return max(1, spokes_that_fit), spokes_that_fit < 1


def _gb_needed(worker_count: int) -> float:
    return BASE_GB + worker_count * WORKER_GB


def _resolve_workers(
    knob: str,
    cpu_derived: int,
    override: int | None,
    memory_guard: int,
    usable_gb: float,
) -> tuple[int, bool]:
    """Return (worker count, whether memory reduced the CPU-derived value)."""
    if override is None:
        return min(cpu_derived, memory_guard), memory_guard < cpu_derived
    if override < 1:
        raise InfeasibleCapacity(
            f"{knob}={override} is below 1 worker; "
            f"rerun with {knob}>=1 (or {knob}=auto)"
        )
    if override > HARD_N_CEILING:
        raise InfeasibleCapacity(
            f"{knob}={override} exceeds the per-run hard ceiling of "
            f"{HARD_N_CEILING} (shared redis runs --databases "
            f"{SHARED_REDIS_DATABASES}, sized so {LEASE_CONCURRENT_RUNS} "
            f"concurrent runs of {HARD_N_CEILING} workers each lease one "
            f"session index per worker); rerun with {knob}<={HARD_N_CEILING}"
        )
    if override > memory_guard:
        raise InfeasibleCapacity(
            f"{knob}={override} needs {_gb_needed(override):.1f} GB but only "
            f"{usable_gb:.1f} GB is usable (at most {memory_guard} workers fit); "
            f"rerun with a smaller {knob} or raise U4I_MEM_FRACTION on a dedicated host"
        )
    return override, False


def derive(
    probe: Probe,
    overrides: Overrides,
    mem_fraction: float,
    mem_safety: float,
) -> Capacity:
    """Derive worker counts and interlocks from a host probe.

    `mem_fraction` is caller-resolved: `overrides.mem_fraction` when set,
    else `DEFAULT_MEM_FRACTION`. Raises `InfeasibleCapacity` when an override
    cannot run on this host.

    `mem_safety` is always the internal `DEFAULT_MEM_SAFETY` constant, not a
    user-exposed knob (no override path feeds it), so it is not validated here.
    """
    if not 0 < mem_fraction <= 1:
        raise InfeasibleCapacity(
            f"U4I_MEM_FRACTION={mem_fraction} is outside (0, 1]; "
            f"rerun with U4I_MEM_FRACTION between 0 and 1 (or U4I_MEM_FRACTION=auto)"
        )
    # Sized from the fingerprinted inputs only (total × fraction, cgroup; never
    # MemAvailable), so no value in the file jitters between runs: live memory
    # gates each test-run and spoke start instead.
    usable_gb = _usable_gb(
        replace(probe, mem_available_bytes=None), mem_fraction, mem_safety
    )
    memory_guard = _memory_guard(usable_gb)

    n_ui, ui_memory_bound = _resolve_workers(
        "U4I_N_UI",
        clamp(probe.ncpu * 2 // 3, N_UI_MIN, N_UI_MAX),
        overrides.n_ui,
        memory_guard,
        usable_gb,
    )
    n_int, int_memory_bound = _resolve_workers(
        "U4I_N_INT",
        clamp(probe.ncpu, N_INT_MIN, N_INT_MAX),
        overrides.n_int,
        memory_guard,
        usable_gb,
    )

    if ui_memory_bound or int_memory_bound:
        binding_constraint = BINDING_MEMORY
    elif overrides.n_ui is not None or overrides.n_int is not None:
        binding_constraint = BINDING_OVERRIDE
    else:
        binding_constraint = BINDING_CPU

    n_max = max(n_ui, n_int)
    pg_test_conn_limit = n_max * CONN_PER_WORKER + CONN_BASE
    spoke_max, spoke_max_clamped = _spoke_ceiling(usable_gb)
    return Capacity(
        n_ui=n_ui,
        n_int=n_int,
        n_max=n_max,
        redis_metrics_databases=max(
            REDIS_METRICS_DATABASES_FLOOR,
            round_up_pow2(METRICS_REDIS_RESERVED_DBS + LEASE_CONCURRENT_RUNS * n_max),
        ),
        pg_test_conn_limit=pg_test_conn_limit,
        pg_max_conn=pg_test_conn_limit + DEV_CONN_BUDGET + SUPERUSER_RESERVED,
        pg_shared_buffers_mb=clamp(
            int(usable_gb * MB_PER_GB) // PG_SHARED_BUFFERS_DIVISOR,
            PG_SHARED_BUFFERS_MIN_MB,
            PG_SHARED_BUFFERS_MAX_MB,
        ),
        usable_gb=usable_gb,
        binding_constraint=binding_constraint,
        spoke_max=spoke_max,
        spoke_max_clamped=spoke_max_clamped,
    )


# --- probing -----------------------------------------------------------------


def parse_meminfo(text: str, key: str) -> int | None:
    """Return `key`'s value from /proc/meminfo text in bytes, or None.

    A malformed value is treated like a missing key (unknown), not an error.
    """
    for line in text.splitlines():
        name, _, rest = line.partition(":")
        if name == key:
            try:
                return int(rest.split()[0]) * BYTES_PER_KB
            except (IndexError, ValueError):
                return None
    return None


def parse_cgroup_max(text: str) -> int | None:
    """Return a cgroup v2 `memory.max` limit in bytes; None for `max`.

    A malformed value is treated like a missing file (unknown), not an error.
    """
    limit = text.strip()
    if limit == "max":
        return None
    try:
        return int(limit)
    except ValueError:
        return None


def parse_docker_info(output: str) -> tuple[int, int]:
    """Parse `docker info --format '{{.NCPU}} {{.MemTotal}}'` into (cores, bytes)."""
    fields = output.split()
    if len(fields) != 2 or not all(
        field.isascii() and field.isdecimal() for field in fields
    ):
        raise DockerInfoError(f"unexpected docker info output: {output!r}")
    return int(fields[0]), int(fields[1])


def run_docker_info() -> str:
    try:
        result = subprocess.run(
            ["docker", "info", "--format", "{{.NCPU}} {{.MemTotal}}"],
            capture_output=True,
            text=True,
            timeout=DOCKER_INFO_TIMEOUT_SECONDS,
        )
    except subprocess.TimeoutExpired as timed_out:
        raise DockerInfoError(
            f"docker info timed out after {DOCKER_INFO_TIMEOUT_SECONDS}s"
        ) from timed_out
    except OSError as launch_error:
        raise DockerInfoError(str(launch_error)) from launch_error
    if result.returncode != 0:
        raise DockerInfoError(
            result.stderr.strip() or f"docker info exited {result.returncode}"
        )
    return result.stdout


def _read_optional(path: Path) -> str | None:
    try:
        return path.read_text()
    except (OSError, UnicodeDecodeError):
        return None


def probe(
    docker_info_reader: Callable[[], str],
    meminfo_path: Path,
    cgroup_path: Path,
) -> Probe:
    """Probe the Docker host. Missing meminfo/cgroup files (macOS) give None."""
    ncpu, mem_total_bytes = parse_docker_info(docker_info_reader())
    meminfo_text = _read_optional(meminfo_path)
    cgroup_text = _read_optional(cgroup_path)
    return Probe(
        ncpu=ncpu,
        mem_total_bytes=mem_total_bytes,
        mem_available_bytes=(
            parse_meminfo(meminfo_text, "MemAvailable") if meminfo_text else None
        ),
        cgroup_max_bytes=parse_cgroup_max(cgroup_text) if cgroup_text else None,
        host_uid=os.getuid(),
        host_gid=os.getgid(),
    )


def _probe_host() -> Probe:
    return probe(run_docker_info, DEFAULT_MEMINFO_PATH, DEFAULT_CGROUP_PATH)


# --- env file ----------------------------------------------------------------


def fingerprint(host_probe: Probe, overrides: Overrides) -> str:
    """Hash of the stable host inputs. Excludes mem_available (jitters per run)."""
    source = (
        f"{host_probe.ncpu}|{host_probe.mem_total_bytes}|"
        f"{host_probe.cgroup_max_bytes}|{host_probe.host_uid}|{host_probe.host_gid}|"
        f"{overrides.n_ui}|{overrides.n_int}|{overrides.mem_fraction}"
    )
    return hashlib.sha256(source.encode()).hexdigest()


def _blank_if_none(value: int | float | None) -> str:
    return "" if value is None else str(value)


def render_env(
    capacity: Capacity, host_probe: Probe, overrides: Overrides, fp: str
) -> str:
    values = {
        "U4I_N_UI": capacity.n_ui,
        "U4I_N_INT": capacity.n_int,
        "U4I_N_MAX": capacity.n_max,
        "REDIS_METRICS_DATABASES": capacity.redis_metrics_databases,
        "U4I_PG_TEST_CONN_LIMIT": capacity.pg_test_conn_limit,
        "U4I_PG_MAX_CONN": capacity.pg_max_conn,
        "U4I_PG_SHARED_BUFFERS_MB": capacity.pg_shared_buffers_mb,
        "U4I_USABLE_MB": int(round(capacity.usable_gb * MB_PER_GB, 6)),
        "U4I_HUB_IDLE_MB": int(HUB_IDLE_GB * MB_PER_GB),
        "U4I_SPOKE_IDLE_MB": int(SPOKE_IDLE_GB * MB_PER_GB),
        "U4I_BASE_MB": int(BASE_GB * MB_PER_GB),
        "U4I_WORKER_MB": int(WORKER_GB * MB_PER_GB),
        "U4I_SPOKE_MAX": capacity.spoke_max,
        "HOST_UID": host_probe.host_uid,
        "HOST_GID": host_probe.host_gid,
        FINGERPRINT_KEY: fp,
        OVERRIDE_N_UI_KEY: _blank_if_none(overrides.n_ui),
        OVERRIDE_N_INT_KEY: _blank_if_none(overrides.n_int),
        OVERRIDE_MEM_FRACTION_KEY: _blank_if_none(overrides.mem_fraction),
    }
    decision = (
        f"{DECISION_PREFIX}n_ui={capacity.n_ui} n_int={capacity.n_int} "
        f"binding={capacity.binding_constraint} usable_gb={capacity.usable_gb:.1f} "
        f"{DECISION_SPOKE_MAX_TOKEN}{capacity.spoke_max}"
        f"{' (clamped)' if capacity.spoke_max_clamped else ''}"
    )
    body = "".join(f"{key}={value}\n" for key, value in values.items())
    return f"{GENERATED_HEADER}\n{decision}\n{body}"


def _parse_env(text: str) -> dict[str, str]:
    parsed: dict[str, str] = {}
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        parsed[key] = value
    return parsed


def read_env(path: Path) -> dict[str, str]:
    """Return the `KEY=value` lines of an env file; comments are ignored."""
    return _parse_env(path.read_text())


def _decision_spoke_max(text: str) -> str | None:
    """The `spoke_max=<n>` token the `# decision:` line recorded, or None."""
    for line in text.splitlines():
        if line.startswith(DECISION_PREFIX):
            for token in line.removeprefix(DECISION_PREFIX).split():
                if token.startswith(DECISION_SPOKE_MAX_TOKEN):
                    return token.removeprefix(DECISION_SPOKE_MAX_TOKEN)
    return None


def _is_consistent(existing_text: str | None, new: dict[str, str]) -> bool:
    """The file's keys equal `new`, and U4I_SPOKE_MAX matches its `# decision:` token.

    Both are written by one render, so a U4I_SPOKE_MAX that disagrees with the
    decision line is a hand edit, and the file is rewritten rather than kept.
    """
    if existing_text is None:
        return False
    existing = _parse_env(existing_text)
    if existing != new:
        return False
    return existing["U4I_SPOKE_MAX"] == _decision_spoke_max(existing_text)


def changed_interlocks(old: dict[str, str], new: dict[str, str]) -> list[str]:
    return [key for key in INTERLOCK_KEYS if old.get(key) != new.get(key)]


def _write_atomically(path: Path, content: str) -> None:
    """Write via a same-directory temp file + os.replace (no partial reads).

    The file keeps NamedTemporaryFile's owner-only 0600 mode: only host-side
    make/compose (running as this user) read it.
    """
    temp_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            "w",
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as temp_file:
            temp_path = Path(temp_file.name)
            temp_file.write(content)
        os.replace(temp_path, path)
    except BaseException:
        if temp_path is not None:
            temp_path.unlink(missing_ok=True)
        raise


# --- override resolution -----------------------------------------------------


def _auto_or(
    parse: Callable[[str], ValueT], kind: str
) -> Callable[[str], ValueT | str]:
    """Build an argparse `type=` that accepts `parse`-able values or `auto`."""

    def parse_flag(value: str) -> ValueT | str:
        if value == AUTO:
            return AUTO
        try:
            return parse(value)
        except ValueError as bad_value:
            raise argparse.ArgumentTypeError(
                f"expected {kind} or '{AUTO}', got {value!r}"
            ) from bad_value

    return parse_flag


def _recorded(
    recorded: dict[str, str], key: str, parse: Callable[[str], ValueT]
) -> ValueT | None:
    raw_value = recorded.get(key, "")
    if not raw_value:
        return None
    try:
        return parse(raw_value)
    except ValueError as bad_value:
        raise InfeasibleCapacity(
            f"recorded {key}={raw_value!r} is malformed; "
            f"rerun with 'make capacity' and that knob set to a value or 'auto'"
        ) from bad_value


def _resolve(
    flag_value: ValueT | str | None, recorded_value: ValueT | None
) -> ValueT | None:
    """A flag wins (`auto` clears); no flag reuses the recorded override.

    The flag parsers yield a number or the literal `AUTO`, so any str is `auto`.
    """
    if flag_value is None:
        return recorded_value
    if isinstance(flag_value, str):
        return None
    return flag_value


def _resolve_overrides(
    recorded: dict[str, str],
    n_ui_flag: int | str | None,
    n_int_flag: int | str | None,
    mem_fraction_flag: float | str | None,
) -> Overrides:
    return Overrides(
        n_ui=_resolve(n_ui_flag, _recorded(recorded, OVERRIDE_N_UI_KEY, int)),
        n_int=_resolve(n_int_flag, _recorded(recorded, OVERRIDE_N_INT_KEY, int)),
        mem_fraction=_resolve(
            mem_fraction_flag, _recorded(recorded, OVERRIDE_MEM_FRACTION_KEY, float)
        ),
    )


def _read_existing_text(path: Path) -> str | None:
    """The capacity file's raw text, or None when it does not exist."""
    return path.read_text() if path.exists() else None


# --- app_logs ownership ------------------------------------------------------


def run_docker(args: list[str]) -> subprocess.CompletedProcess[str]:
    """Run `docker <args>`; a launch failure or timeout raises DockerRunError."""
    try:
        return subprocess.run(
            ["docker", *args],
            capture_output=True,
            text=True,
            timeout=DOCKER_RUN_TIMEOUT_SECONDS,
        )
    except subprocess.TimeoutExpired as timed_out:
        raise DockerRunError(
            f"docker {args[0]} timed out after {DOCKER_RUN_TIMEOUT_SECONDS}s"
        ) from timed_out
    except OSError as launch_error:
        raise DockerRunError(str(launch_error)) from launch_error


def _lookup(docker: DockerRunner, args: list[str]) -> str:
    """Stripped stdout of a docker lookup; empty (skip) when it exits non-zero."""
    result = docker(args)
    if result.returncode != 0:
        sys.stderr.write(result.stderr)
        return ""
    return result.stdout.strip()


def _logs_owner(recorded: dict[str, str], output: Path) -> str:
    """The `uid:gid` web runs as: the recorded host ids, 0 mapped to 1001."""
    raw_ids = (recorded.get("HOST_UID", ""), recorded.get("HOST_GID", ""))
    if not all(raw_id.isascii() and raw_id.isdecimal() for raw_id in raw_ids):
        raise CorruptCapacityFile(
            f"HOST_UID/HOST_GID invalid in {output} — run 'make capacity'"
        )
    owner_ids = [int(raw_id) or ROOT_ID_FALLBACK for raw_id in raw_ids]
    return ":".join(str(owner_id) for owner_id in owner_ids)


def _logs_owner_fix(output: Path, project: str, docker: DockerRunner) -> None:
    """Re-own the app_logs log dir to HOST_UID:HOST_GID when another uid owns it.

    `project` is the spoke's compose project, which names its volume and web
    image. Uses `docker run` against the existing web image, not `compose run`,
    so a missing volume is never created (and seeded by a stale image). Skips
    quietly with no volume, image, or log dir yet (a fresh machine).
    """
    volume_filters = [
        flag
        for volume_filter in (
            f"label=com.docker.compose.project={project}",
            f"label=com.docker.compose.volume={LOGS_VOLUME_NAME}",
        )
        for flag in ("--filter", volume_filter)
    ]
    volume = _lookup(docker, ["volume", "ls", "-q", *volume_filters])
    image = _lookup(docker, ["image", "ls", "-q", f"{project}-web:latest"])
    if not volume or not image:
        return
    wanted = _logs_owner(read_env(output), output)
    mount = f"{volume}:{LOGS_VOLUME_MOUNT}"
    root_run = ["run", "--rm", "--user", "root", "-v", mount, image]
    current = docker([*root_run, "stat", "-c", "%u:%g", LOGS_DIR])
    if current.returncode != 0:
        return
    have = current.stdout.strip()
    if have == wanted:
        return
    print(f"repairing app_logs ownership (was {have}, now {wanted})", flush=True)
    repair_script = f"chown -R {wanted} {LOGS_DIR} && chmod {LOGS_DIR_MODE} {LOGS_DIR}"
    repair = docker([*root_run, "sh", "-c", repair_script])
    if repair.returncode != 0:
        raise DockerRunError(
            repair.stderr.strip() or f"app_logs repair exited {repair.returncode}"
        )


# --- live memory -------------------------------------------------------------


def read_live_available(
    meminfo_path: Path, cgroup_path: Path, vm_meminfo: Callable[[], str | None]
) -> LiveMemory:
    """Available memory now: this host's MemAvailable (capped by the cgroup limit),
    else the Docker VM's via `vm_meminfo`, else unknown. Malformed readings fall
    through to the next source."""
    meminfo_text = _read_optional(meminfo_path)
    host_available = (
        parse_meminfo(meminfo_text, "MemAvailable") if meminfo_text else None
    )
    if host_available is not None:
        cgroup_text = _read_optional(cgroup_path)
        cgroup_max = parse_cgroup_max(cgroup_text) if cgroup_text else None
        if cgroup_max is not None:
            host_available = min(host_available, cgroup_max)
        return LiveMemory(host_available, LIVE_SOURCE_HOST)
    vm_text = vm_meminfo()
    vm_available = parse_meminfo(vm_text, "MemAvailable") if vm_text else None
    if vm_available is not None:
        return LiveMemory(vm_available, LIVE_SOURCE_VM)
    return LiveMemory(None, LIVE_SOURCE_NONE)


def _run_docker_short(args: list[str]) -> subprocess.CompletedProcess[str]:
    """`run_docker` with the live-memory read's short timeout."""
    try:
        return subprocess.run(
            ["docker", *args],
            capture_output=True,
            text=True,
            timeout=LIVE_MEMORY_DOCKER_TIMEOUT_SECONDS,
        )
    except subprocess.TimeoutExpired as timed_out:
        raise DockerRunError(
            f"docker {args[0]} timed out after {LIVE_MEMORY_DOCKER_TIMEOUT_SECONDS}s"
        ) from timed_out
    except OSError as launch_error:
        raise DockerRunError(str(launch_error)) from launch_error


def hub_vm_meminfo(hub_project: str, docker: DockerRunner) -> str | None:
    """The Docker VM's /proc/meminfo, read inside the running hub db container
    (a container sees its kernel's meminfo). None on any failure; never raises."""
    ps_args = [
        "ps",
        "-q",
        "--filter",
        f"label=com.docker.compose.project={hub_project}",
        "--filter",
        "label=com.docker.compose.service=db",
        "--filter",
        "status=running",
    ]
    try:
        listed = docker(ps_args)
        container_ids = listed.stdout.split() if listed.returncode == 0 else []
        if not container_ids:
            return None
        meminfo = docker(["exec", container_ids[0], "cat", "/proc/meminfo"])
    except (DockerRunError, OSError, UnicodeDecodeError):
        return None
    return meminfo.stdout if meminfo.returncode == 0 else None


def live_usable_gb(live: LiveMemory) -> float | None:
    """The tests' usable share of the live reading (the MEM_SAFETY margin applied)."""
    if live.available_bytes is None:
        return None
    return live.available_bytes * DEFAULT_MEM_SAFETY / BYTES_PER_GB


def workers_that_fit(usable_gb: float, base_gb: float, worker_gb: float) -> int:
    """Test workers a run can start in `usable_gb`; 0 when not even one fits.
    Round before flooring, as in `_memory_guard`."""
    return max(0, math.floor(round((usable_gb - base_gb) / worker_gb, 6)))


def _live_memory(hub_project: str) -> LiveMemory:
    return read_live_available(
        DEFAULT_MEMINFO_PATH,
        DEFAULT_CGROUP_PATH,
        lambda: hub_vm_meminfo(hub_project, _run_docker_short),
    )


# --- spoke admission ---------------------------------------------------------


def _admission_value(env: dict[str, str], key: str) -> int:
    raw_value = env.get(key, "")
    if not (raw_value.isascii() and raw_value.isdecimal()):
        raise CorruptCapacityFile(f"{key} missing or invalid")
    return int(raw_value)


def admission_decision(
    running_projects: list[str],
    self_project: str,
    hub_project: str,
    env: dict[str, str],
) -> AdmissionResult:
    """Admit `self_project` unless it would be one spoke past U4I_SPOKE_MAX.

    `running_projects` is one compose-project label per running container on the
    shared network. The hub and empty labels never count, a project counts once,
    and a spoke that is already running is always admitted (re-running `make up`).
    Raises `CorruptCapacityFile` when an ADMISSION_KEYS value is missing or invalid.
    """
    values = {key: _admission_value(env, key) for key in ADMISSION_KEYS}
    labels = {project.strip() for project in running_projects}
    distinct = labels - {"", hub_project}
    others = tuple(sorted(distinct - {self_project}))
    spoke_count = len(others) + 1
    if self_project in distinct or spoke_count <= values["U4I_SPOKE_MAX"]:
        return AdmissionResult(admitted=True, others=others, message="")
    hub_gb = values["U4I_HUB_IDLE_MB"] / MB_PER_GB
    spoke_gb = values["U4I_SPOKE_IDLE_MB"] / MB_PER_GB
    n_max = values["U4I_N_MAX"]
    total_gb = hub_gb + spoke_count * spoke_gb + _gb_needed(n_max)
    message = (
        f"refusing spoke {spoke_count} ({self_project}) — hub {hub_gb:.2f} GB + "
        f"{spoke_count} × {spoke_gb:.2f} GB idle spokes + one full test run "
        f"({BASE_GB:.2f} + {n_max} × {WORKER_GB:.2f} GB) = {total_gb:.2f} GB exceeds "
        f"usable {values['U4I_USABLE_MB'] / MB_PER_GB:.2f} GB "
        f"(U4I_SPOKE_MAX={values['U4I_SPOKE_MAX']}). "
        f"Running spokes: {', '.join(others)}. "
        "Stop one with 'make down' in its checkout."
    )
    return AdmissionResult(admitted=False, others=others, message=message)


def _admit(args: argparse.Namespace, docker: DockerRunner) -> int:
    """Refuse (exit 1) a spoke start the admission ceiling can't hold.

    Reads the capacity file only (never probes). A docker failure is loud and
    never falls back to admitting. Count-then-start: two spokes starting at once
    can both be admitted (a documented race, like `_ports-resolve`'s).
    """
    output: Path = args.output
    if not output.exists():
        print(
            f"{ADMISSION_PREFIX}{output} does not exist — run 'make capacity'",
            file=sys.stderr,
        )
        return 1
    try:
        env = read_env(output)
    except (OSError, UnicodeDecodeError) as read_error:
        print(
            f"{ADMISSION_PREFIX}{read_error} — run 'make capacity'",
            file=sys.stderr,
        )
        return 1
    ps_args = [
        "ps",
        "--filter",
        f"network={args.network}",
        "--filter",
        "status=running",
        "--format",
        COMPOSE_PROJECT_FORMAT,
    ]
    try:
        listed = docker(ps_args)
    except (DockerRunError, OSError) as docker_error:
        print(f"{ADMISSION_PREFIX}docker ps failed — {docker_error}", file=sys.stderr)
        return 1
    if listed.returncode != 0:
        reason = listed.stderr.strip() or f"exited {listed.returncode}"
        print(f"{ADMISSION_PREFIX}docker ps failed — {reason}", file=sys.stderr)
        return 1
    try:
        decision = admission_decision(
            listed.stdout.splitlines(), args.project, args.hub_project, env
        )
    except CorruptCapacityFile as bad_value:
        print(
            f"{ADMISSION_PREFIX}{bad_value} in {output} — run 'make capacity'",
            file=sys.stderr,
        )
        return 1
    if decision.admitted:
        return 0
    print(f"{ADMISSION_PREFIX}{decision.message}", file=sys.stderr)
    return 1


# --- subcommands -------------------------------------------------------------


def _foreign_primary_root(output: Path) -> str | None:
    """PRIMARY_ROOT when `output` is not the primary clone's capacity file, else None.

    None too when PRIMARY_ROOT is unset (a direct run outside make, unit tests).
    """
    primary_root = os.environ.get(PRIMARY_ROOT_ENV_VAR, "")
    if not primary_root:
        return None
    primary_file = Path(primary_root) / PRIMARY_CAPACITY_RELATIVE_PATH
    if output.resolve() == primary_file.resolve():
        return None
    return primary_root


def _generate(
    output: Path,
    host_probe: Probe,
    n_ui_flag: int | str | None,
    n_int_flag: int | str | None,
    mem_fraction_flag: float | str | None,
) -> None:
    # The recorded overrides are read after the (slow) docker probe, as close
    # to the atomic replace as possible, to narrow the read-then-replace window.
    existing_text = _read_existing_text(output)
    existing = _parse_env(existing_text) if existing_text is not None else None
    overrides = _resolve_overrides(
        existing or {}, n_ui_flag, n_int_flag, mem_fraction_flag
    )
    mem_fraction = (
        overrides.mem_fraction
        if overrides.mem_fraction is not None
        else DEFAULT_MEM_FRACTION
    )
    capacity = derive(host_probe, overrides, mem_fraction, DEFAULT_MEM_SAFETY)
    content = render_env(
        capacity, host_probe, overrides, fingerprint(host_probe, overrides)
    )
    new_values = _parse_env(content)
    if _is_consistent(existing_text, new_values):
        print(f"capacity unchanged ({output})")
        return
    _write_atomically(output, content)
    print(f"capacity regenerated ({output})")
    # A first write has nothing to compare against; `make up` creates the stack.
    changed = changed_interlocks(existing, new_values) if existing else []
    primary_root = _foreign_primary_root(output)
    if primary_root is not None:
        hub_changed = [key for key in changed if key in HUB_READ_KEYS]
        if hub_changed:
            note = PRIMARY_ONLY_NOTE.format(primary_root=primary_root)
            print(f"{note} (changed: {', '.join(hub_changed)})")
        changed = [key for key in changed if key not in HUB_READ_KEYS]
    for tier_keys, message in (
        (SPOKE_INTERLOCK_KEYS, SPOKE_RECREATE_MESSAGE),
        (HUB_INTERLOCK_KEYS, HUB_RECREATE_MESSAGE),
    ):
        tier_changed = [key for key in changed if key in tier_keys]
        if tier_changed:
            print(f"{message} (changed: {', '.join(tier_changed)})")


def _ensure(output: Path, host_probe: Probe) -> None:
    """Regenerate when P is missing, a key was deleted, the fingerprint moved, or
    the file disagrees with a fresh render (e.g. a hand-edited U4I_SPOKE_MAX).

    Every file value comes from the fingerprinted inputs, so re-deriving on a
    fingerprint match is pure computation and a consistent file is left untouched.
    """
    existing_text = _read_existing_text(output)
    existing = _parse_env(existing_text) if existing_text is not None else None
    if existing is not None and all(key in existing for key in ENV_KEYS):
        overrides = _resolve_overrides(existing, None, None, None)
        host_fingerprint = fingerprint(host_probe, overrides)
        if existing.get(FINGERPRINT_KEY) == host_fingerprint:
            mem_fraction = (
                overrides.mem_fraction
                if overrides.mem_fraction is not None
                else DEFAULT_MEM_FRACTION
            )
            capacity = derive(host_probe, overrides, mem_fraction, DEFAULT_MEM_SAFETY)
            content = render_env(capacity, host_probe, overrides, host_fingerprint)
            if _is_consistent(existing_text, _parse_env(content)):
                return
    _generate(output, host_probe, None, None, None)


def _live_line(live: LiveMemory) -> str:
    usable_gb = live_usable_gb(live)
    if usable_gb is None:
        return "live: unavailable — static capacity applies"
    workers = workers_that_fit(usable_gb, BASE_GB, WORKER_GB)
    return (
        f"live: {usable_gb:.1f} GB usable now ({live.source}) — {workers} workers fit"
    )


def _show(
    output: Path, hub_project: str | None, live_memory: Callable[[str], LiveMemory]
) -> int:
    """Print the capacity file, then live memory. Without `hub_project` only this
    host's file is read (no VM attempt)."""
    if not output.exists():
        print(f"{output} does not exist; run 'make capacity'", file=sys.stderr)
        return 1
    text = output.read_text()
    existing = _parse_env(text)
    decision_lines = [
        line.removeprefix(DECISION_PREFIX)
        for line in text.splitlines()
        if line.startswith(DECISION_PREFIX)
    ]
    rows = {**existing, "U4I_SLUG": os.environ.get("U4I_SLUG", "")}
    key_width = max(len(key) for key in rows)
    print(f"capacity ({output})")
    for decision in decision_lines:
        print(f"  {decision}")
    for key, value in rows.items():
        print(f"  {key.ljust(key_width)}  {value or '-'}")
    live = (
        live_memory(hub_project)
        if hub_project is not None
        else read_live_available(
            DEFAULT_MEMINFO_PATH, DEFAULT_CGROUP_PATH, lambda: None
        )
    )
    print(_live_line(live))
    return 0


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="make capacity",
        description="Derive worker counts and interlocks from this Docker host.",
    )
    subcommands = parser.add_subparsers(dest="command", required=True)

    generate_parser = subcommands.add_parser(
        "generate", help="write the capacity env file"
    )
    generate_parser.add_argument("--output", type=Path, required=True)
    worker_flag = _auto_or(int, "an integer")
    generate_parser.add_argument("--n-ui", type=worker_flag)
    generate_parser.add_argument("--n-int", type=worker_flag)
    generate_parser.add_argument("--mem-fraction", type=_auto_or(float, "a number"))

    for name, help_text in (
        ("ensure", "regenerate only when the host fingerprint changed"),
        ("logs-owner-fix", "re-own the app_logs log dir to HOST_UID:HOST_GID"),
    ):
        subcommand_parser = subcommands.add_parser(name, help=help_text)
        subcommand_parser.add_argument("--output", type=Path, required=True)

    show_parser = subcommands.add_parser(
        "show", help="print the resolved capacity table and live memory"
    )
    show_parser.add_argument("--output", type=Path, required=True)
    # The VM reading (macOS/Colima) goes through the hub db; without it only the host file is read.
    show_parser.add_argument("--hub-project")

    admit_parser = subcommands.add_parser(
        "admit", help="refuse a spoke start past the U4I_SPOKE_MAX ceiling"
    )
    admit_parser.add_argument("--output", type=Path, required=True)
    admit_parser.add_argument("--project", required=True)
    admit_parser.add_argument("--hub-project", required=True)
    admit_parser.add_argument("--network", required=True)
    return parser


def main(
    argv: list[str],
    probe_host: Callable[[], Probe] = _probe_host,
    docker_runner: DockerRunner = run_docker,
    live_memory: Callable[[str], LiveMemory] = _live_memory,
) -> int:
    args = _build_parser().parse_args(argv)
    try:
        if args.command == "show":
            return _show(args.output, args.hub_project, live_memory)
        if args.command == "admit":
            return _admit(args, docker_runner)
        if args.command == "logs-owner-fix":
            project = os.environ.get(PROJECT_ENV_VAR, "")
            if not project:
                print(
                    f"make capacity: {PROJECT_ENV_VAR} is not set — run logs-owner-fix "
                    "through make (make up), which computes the spoke's compose project",
                    file=sys.stderr,
                )
                return 1
            _logs_owner_fix(args.output, project, docker_runner)
            return 0
        host_probe = probe_host()
        if args.command == "generate":
            _generate(args.output, host_probe, args.n_ui, args.n_int, args.mem_fraction)
        else:
            _ensure(args.output, host_probe)
    except DockerInfoError as docker_error:
        print(f"make capacity: docker info failed — {docker_error}", file=sys.stderr)
        return 1
    except DockerRunError as docker_error:
        print(f"make capacity: docker failed — {docker_error}", file=sys.stderr)
        return 1
    except (InfeasibleCapacity, CorruptCapacityFile) as bad_value:
        print(f"make capacity: {bad_value}", file=sys.stderr)
        return 1
    except (OSError, UnicodeDecodeError) as file_error:
        print(f"make capacity: {file_error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
