"""Host capacity derivation, run by `make capacity` from the repo root.

Derives the UI and integration pytest-xdist worker counts from the Docker
host's cores and memory, plus the ceilings that must grow with them (the
metrics-Redis database count, and the shared Postgres cluster's
`max_connections`, test-role connection limit and `shared_buffers`). Stdlib
only: it runs on the host under bare mise python, before any container exists.

Subcommands (see `main`): `generate` writes the gitignored env file,
`ensure` regenerates it only when the host fingerprint changed (run before
every stack/test target), `show` prints the resolved values, and
`logs-owner-fix` re-owns the `app_logs` volume's log dir to the recorded
HOST_UID:HOST_GID (run before every stack start).
"""

from __future__ import annotations

import argparse
import hashlib
import math
import os
import subprocess
import sys
import tempfile
from collections.abc import Callable
from dataclasses import dataclass, replace
from pathlib import Path
from typing import TypeVar

# Metrics-Redis indices no test run may lease; mirrors
# len(scripts.testrun_resources.METRICS_RESERVED_INDICES) (a parity test pins it).
METRICS_REDIS_RESERVED_DBS: int = 1
# How many simultaneous pytest invocations each Redis lease pool must hold: the
# metrics pool at n_max (derived per host), and the shared-redis session pool at
# HARD_N_CEILING (fixed, see SHARED_REDIS_DATABASES), so two runs always fit both.
LEASE_CONCURRENT_RUNS: int = 2
# Assumes SQLAlchemy's library-default QueuePool (pool_size=5 + max_overflow=10):
# the app sets no explicit pool options (backend/__init__.py only defaults
# SQLALCHEMY_ENGINE_OPTIONS to {}). Update this if pool settings are ever added
# to SQLALCHEMY_ENGINE_OPTIONS in backend/config.py.
CONN_PER_WORKER: int = 15
CONN_BASE: int = 50
# The cluster's max_connections = the test role's limit + dev app/workflow
# headroom + Postgres's superuser_reserved_connections default.
DEV_CONN_BUDGET: int = 30
SUPERUSER_RESERVED: int = 3
# shared_buffers = 1/64 of usable memory, clamped (a shared dev box, not prod).
PG_SHARED_BUFFERS_MIN_MB: int = 64
PG_SHARED_BUFFERS_MAX_MB: int = 256
PG_SHARED_BUFFERS_DIVISOR: int = 64
MB_PER_GB: int = 1024
# The per-run worker cap: each worker leases one shared-redis session index.
HARD_N_CEILING: int = 30
# Shared-redis indices no test run may lease: dev DB 0 and the session pool's base DB.
SESSION_REDIS_RESERVED_DBS: int = 2
SHARED_REDIS_DATABASES_FLOOR: int = 32
BASE_GB: float = 2.0
WORKER_GB: float = 0.5
DEFAULT_MEM_FRACTION: float = 0.70
DEFAULT_MEM_SAFETY: float = 0.90

N_UI_MIN: int = 2
N_UI_MAX: int = 12
N_INT_MIN: int = 2
N_INT_MAX: int = 16
REDIS_METRICS_DATABASES_FLOOR: int = 16
BYTES_PER_GB: int = 1024**3

BINDING_CPU: str = "cpu"
BINDING_MEMORY: str = "memory"
BINDING_OVERRIDE: str = "override"

DEFAULT_MEMINFO_PATH: Path = Path("/proc/meminfo")
DEFAULT_CGROUP_PATH: Path = Path("/sys/fs/cgroup/memory.max")
BYTES_PER_KB: int = 1024
DOCKER_INFO_TIMEOUT_SECONDS: int = 30
AUTO: str = "auto"

# `logs-owner-fix`: the project label must track compose.local.yaml's `name:`.
LOGS_VOLUME_FILTERS: tuple[str, ...] = (
    "label=com.docker.compose.project=u4i-local",
    "label=com.docker.compose.volume=app_logs",
)
WEB_IMAGE: str = "u4i-local-web:latest"
LOGS_VOLUME_MOUNT: str = "/app/volume"
LOGS_DIR: str = f"{LOGS_VOLUME_MOUNT}/logs"
LOGS_DIR_MODE: str = "775"  # as web's image sets it
# A 0 uid/gid (root host) maps here, mirroring docker/Dockerfile.Local's fallback.
ROOT_ID_FALLBACK: int = 1001
DOCKER_RUN_TIMEOUT_SECONDS: int = 120

GENERATED_HEADER: str = "# GENERATED by make capacity — DO NOT EDIT"
DECISION_PREFIX: str = "# decision: "
FINGERPRINT_KEY: str = "U4I_CAPACITY_FINGERPRINT"
OVERRIDE_N_UI_KEY: str = "U4I_OVERRIDE_N_UI"
OVERRIDE_N_INT_KEY: str = "U4I_OVERRIDE_N_INT"
OVERRIDE_MEM_FRACTION_KEY: str = "U4I_OVERRIDE_MEM_FRACTION"
# Values baked into running containers: a change needs `make up [p=…] d=1`.
INTERLOCK_KEYS: tuple[str, ...] = (
    "REDIS_METRICS_DATABASES",
    "U4I_PG_TEST_CONN_LIMIT",
    "U4I_PG_MAX_CONN",
    "U4I_PG_SHARED_BUFFERS_MB",
    "HOST_UID",
    "HOST_GID",
)
# Every `KEY=value` line `render_env` emits, in order.
ENV_KEYS: tuple[str, ...] = (
    "U4I_N_UI",
    "U4I_N_INT",
    "U4I_N_MAX",
    "REDIS_METRICS_DATABASES",
    "U4I_PG_TEST_CONN_LIMIT",
    "U4I_PG_MAX_CONN",
    "U4I_PG_SHARED_BUFFERS_MB",
    "HOST_UID",
    "HOST_GID",
    FINGERPRINT_KEY,
    OVERRIDE_N_UI_KEY,
    OVERRIDE_N_INT_KEY,
    OVERRIDE_MEM_FRACTION_KEY,
)

ValueT = TypeVar("ValueT", int, float)


class InfeasibleCapacity(ValueError):
    """A requested worker count or memory fraction cannot run on this host."""


class DockerInfoError(RuntimeError):
    """`docker info` failed or printed something unparseable."""


class DockerRunError(RuntimeError):
    """A `logs-owner-fix` docker command failed to launch or its repair failed."""


class CorruptCapacityFile(ValueError):
    """The capacity env file holds a value `logs-owner-fix` cannot use."""


DockerRunner = Callable[[list[str]], subprocess.CompletedProcess[str]]


@dataclass(frozen=True)
class Probe:
    ncpu: int
    mem_total_bytes: int
    mem_available_bytes: int | None
    cgroup_max_bytes: int | None
    host_uid: int
    host_gid: int


@dataclass(frozen=True)
class Overrides:
    n_ui: int | None = None
    n_int: int | None = None
    mem_fraction: float | None = None


@dataclass(frozen=True)
class Capacity:
    n_ui: int
    n_int: int
    n_max: int
    redis_metrics_databases: int
    pg_test_conn_limit: int
    pg_max_conn: int
    pg_shared_buffers_mb: int
    usable_gb: float
    binding_constraint: str


def clamp(value: int, low: int, high: int) -> int:
    return max(low, min(value, high))


def round_up_pow2(value: int) -> int:
    return 1 << max(value - 1, 0).bit_length()


# The local shared `redis --databases` count (docker/compose.local.yaml hardcodes
# it; a parity test pins the two together). Minus SESSION_REDIS_RESERVED_DBS, it
# leaves a session index per worker for LEASE_CONCURRENT_RUNS runs at HARD_N_CEILING.
SHARED_REDIS_DATABASES: int = max(
    SHARED_REDIS_DATABASES_FLOOR,
    round_up_pow2(SESSION_REDIS_RESERVED_DBS + LEASE_CONCURRENT_RUNS * HARD_N_CEILING),
)


def _usable_gb(probe: Probe, mem_fraction: float, mem_safety: float) -> float:
    total_gb = probe.mem_total_bytes / BYTES_PER_GB * mem_fraction
    known_available = [
        available_bytes
        for available_bytes in (probe.mem_available_bytes, probe.cgroup_max_bytes)
        if available_bytes is not None
    ]
    if not known_available:
        return total_gb
    return min(total_gb, min(known_available) / BYTES_PER_GB * mem_safety)


def _memory_guard(usable_gb: float) -> int:
    # Round before flooring: binary-float rounding on usable_gb (e.g. 237.99999999999997
    # instead of 238.0) can otherwise make the floor under-count by one worker.
    return max(1, math.floor(round((usable_gb - BASE_GB) / WORKER_GB, 6)))


def _gb_needed(worker_count: int) -> float:
    return BASE_GB + worker_count * WORKER_GB


def _resolve_workers(
    knob: str,
    cpu_derived: int,
    override: int | None,
    memory_guard: int,
    usable_gb: float,
) -> tuple[int, bool]:
    """Return (worker count, whether memory reduced the CPU-derived value)."""
    if override is None:
        return min(cpu_derived, memory_guard), memory_guard < cpu_derived
    if override < 1:
        raise InfeasibleCapacity(
            f"{knob}={override} is below 1 worker; "
            f"rerun with {knob}>=1 (or {knob}=auto)"
        )
    if override > HARD_N_CEILING:
        raise InfeasibleCapacity(
            f"{knob}={override} exceeds the per-run hard ceiling of "
            f"{HARD_N_CEILING} (shared redis runs --databases "
            f"{SHARED_REDIS_DATABASES}, sized so {LEASE_CONCURRENT_RUNS} "
            f"concurrent runs of {HARD_N_CEILING} workers each lease one "
            f"session index per worker); rerun with {knob}<={HARD_N_CEILING}"
        )
    if override > memory_guard:
        raise InfeasibleCapacity(
            f"{knob}={override} needs {_gb_needed(override):.1f} GB but only "
            f"{usable_gb:.1f} GB is usable (at most {memory_guard} workers fit); "
            f"rerun with a smaller {knob} or raise U4I_MEM_FRACTION on a dedicated host"
        )
    return override, False


def derive(
    probe: Probe,
    overrides: Overrides,
    mem_fraction: float,
    mem_safety: float,
) -> Capacity:
    """Derive worker counts and interlocks from a host probe.

    `mem_fraction` is caller-resolved: `overrides.mem_fraction` when set,
    else `DEFAULT_MEM_FRACTION`. Raises `InfeasibleCapacity` when an override
    cannot run on this host.

    `mem_safety` is always the internal `DEFAULT_MEM_SAFETY` constant, not a
    user-exposed knob (no override path feeds it), so it is not validated here.
    """
    if not 0 < mem_fraction <= 1:
        raise InfeasibleCapacity(
            f"U4I_MEM_FRACTION={mem_fraction} is outside (0, 1]; "
            f"rerun with U4I_MEM_FRACTION between 0 and 1 (or U4I_MEM_FRACTION=auto)"
        )
    usable_gb = _usable_gb(probe, mem_fraction, mem_safety)
    memory_guard = _memory_guard(usable_gb)

    n_ui, ui_memory_bound = _resolve_workers(
        "U4I_N_UI",
        clamp(probe.ncpu * 2 // 3, N_UI_MIN, N_UI_MAX),
        overrides.n_ui,
        memory_guard,
        usable_gb,
    )
    n_int, int_memory_bound = _resolve_workers(
        "U4I_N_INT",
        clamp(probe.ncpu, N_INT_MIN, N_INT_MAX),
        overrides.n_int,
        memory_guard,
        usable_gb,
    )

    if ui_memory_bound or int_memory_bound:
        binding_constraint = BINDING_MEMORY
    elif overrides.n_ui is not None or overrides.n_int is not None:
        binding_constraint = BINDING_OVERRIDE
    else:
        binding_constraint = BINDING_CPU

    n_max = max(n_ui, n_int)
    pg_test_conn_limit = n_max * CONN_PER_WORKER + CONN_BASE
    # Sized from the fingerprinted inputs only (no MemAvailable), because
    # shared_buffers is an interlock and must not jitter between runs.
    stable_usable_gb = _usable_gb(
        replace(probe, mem_available_bytes=None), mem_fraction, mem_safety
    )
    return Capacity(
        n_ui=n_ui,
        n_int=n_int,
        n_max=n_max,
        redis_metrics_databases=max(
            REDIS_METRICS_DATABASES_FLOOR,
            round_up_pow2(METRICS_REDIS_RESERVED_DBS + LEASE_CONCURRENT_RUNS * n_max),
        ),
        pg_test_conn_limit=pg_test_conn_limit,
        pg_max_conn=pg_test_conn_limit + DEV_CONN_BUDGET + SUPERUSER_RESERVED,
        pg_shared_buffers_mb=clamp(
            int(stable_usable_gb * MB_PER_GB) // PG_SHARED_BUFFERS_DIVISOR,
            PG_SHARED_BUFFERS_MIN_MB,
            PG_SHARED_BUFFERS_MAX_MB,
        ),
        usable_gb=usable_gb,
        binding_constraint=binding_constraint,
    )


# --- probing -----------------------------------------------------------------


def parse_meminfo(text: str, key: str) -> int | None:
    """Return `key`'s value from /proc/meminfo text in bytes, or None.

    A malformed value is treated like a missing key (unknown), not an error.
    """
    for line in text.splitlines():
        name, _, rest = line.partition(":")
        if name == key:
            try:
                return int(rest.split()[0]) * BYTES_PER_KB
            except (IndexError, ValueError):
                return None
    return None


def parse_cgroup_max(text: str) -> int | None:
    """Return a cgroup v2 `memory.max` limit in bytes; None for `max`.

    A malformed value is treated like a missing file (unknown), not an error.
    """
    limit = text.strip()
    if limit == "max":
        return None
    try:
        return int(limit)
    except ValueError:
        return None


def parse_docker_info(output: str) -> tuple[int, int]:
    """Parse `docker info --format '{{.NCPU}} {{.MemTotal}}'` into (cores, bytes)."""
    fields = output.split()
    if len(fields) != 2 or not all(
        field.isascii() and field.isdecimal() for field in fields
    ):
        raise DockerInfoError(f"unexpected docker info output: {output!r}")
    return int(fields[0]), int(fields[1])


def run_docker_info() -> str:
    try:
        result = subprocess.run(
            ["docker", "info", "--format", "{{.NCPU}} {{.MemTotal}}"],
            capture_output=True,
            text=True,
            timeout=DOCKER_INFO_TIMEOUT_SECONDS,
        )
    except subprocess.TimeoutExpired as timed_out:
        raise DockerInfoError(
            f"docker info timed out after {DOCKER_INFO_TIMEOUT_SECONDS}s"
        ) from timed_out
    except OSError as launch_error:
        raise DockerInfoError(str(launch_error)) from launch_error
    if result.returncode != 0:
        raise DockerInfoError(
            result.stderr.strip() or f"docker info exited {result.returncode}"
        )
    return result.stdout


def _read_optional(path: Path) -> str | None:
    try:
        return path.read_text()
    except OSError:
        return None


def probe(
    docker_info_reader: Callable[[], str],
    meminfo_path: Path,
    cgroup_path: Path,
) -> Probe:
    """Probe the Docker host. Missing meminfo/cgroup files (macOS) give None."""
    ncpu, mem_total_bytes = parse_docker_info(docker_info_reader())
    meminfo_text = _read_optional(meminfo_path)
    cgroup_text = _read_optional(cgroup_path)
    return Probe(
        ncpu=ncpu,
        mem_total_bytes=mem_total_bytes,
        mem_available_bytes=(
            parse_meminfo(meminfo_text, "MemAvailable") if meminfo_text else None
        ),
        cgroup_max_bytes=parse_cgroup_max(cgroup_text) if cgroup_text else None,
        host_uid=os.getuid(),
        host_gid=os.getgid(),
    )


def _probe_host() -> Probe:
    return probe(run_docker_info, DEFAULT_MEMINFO_PATH, DEFAULT_CGROUP_PATH)


# --- env file ----------------------------------------------------------------


def fingerprint(host_probe: Probe, overrides: Overrides) -> str:
    """Hash of the stable host inputs. Excludes mem_available (jitters per run)."""
    source = (
        f"{host_probe.ncpu}|{host_probe.mem_total_bytes}|"
        f"{host_probe.cgroup_max_bytes}|{host_probe.host_uid}|{host_probe.host_gid}|"
        f"{overrides.n_ui}|{overrides.n_int}|{overrides.mem_fraction}"
    )
    return hashlib.sha256(source.encode()).hexdigest()


def _blank_if_none(value: int | float | None) -> str:
    return "" if value is None else str(value)


def render_env(
    capacity: Capacity, host_probe: Probe, overrides: Overrides, fp: str
) -> str:
    values = {
        "U4I_N_UI": capacity.n_ui,
        "U4I_N_INT": capacity.n_int,
        "U4I_N_MAX": capacity.n_max,
        "REDIS_METRICS_DATABASES": capacity.redis_metrics_databases,
        "U4I_PG_TEST_CONN_LIMIT": capacity.pg_test_conn_limit,
        "U4I_PG_MAX_CONN": capacity.pg_max_conn,
        "U4I_PG_SHARED_BUFFERS_MB": capacity.pg_shared_buffers_mb,
        "HOST_UID": host_probe.host_uid,
        "HOST_GID": host_probe.host_gid,
        FINGERPRINT_KEY: fp,
        OVERRIDE_N_UI_KEY: _blank_if_none(overrides.n_ui),
        OVERRIDE_N_INT_KEY: _blank_if_none(overrides.n_int),
        OVERRIDE_MEM_FRACTION_KEY: _blank_if_none(overrides.mem_fraction),
    }
    decision = (
        f"{DECISION_PREFIX}n_ui={capacity.n_ui} n_int={capacity.n_int} "
        f"binding={capacity.binding_constraint} usable_gb={capacity.usable_gb:.1f}"
    )
    body = "".join(f"{key}={value}\n" for key, value in values.items())
    return f"{GENERATED_HEADER}\n{decision}\n{body}"


def _parse_env(text: str) -> dict[str, str]:
    parsed: dict[str, str] = {}
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        parsed[key] = value
    return parsed


def read_env(path: Path) -> dict[str, str]:
    """Return the `KEY=value` lines of an env file; comments are ignored."""
    return _parse_env(path.read_text())


def changed_interlocks(old: dict[str, str], new: dict[str, str]) -> list[str]:
    return [key for key in INTERLOCK_KEYS if old.get(key) != new.get(key)]


def _write_atomically(path: Path, content: str) -> None:
    """Write via a same-directory temp file + os.replace (no partial reads).

    The file keeps NamedTemporaryFile's owner-only 0600 mode: only host-side
    make/compose (running as this user) read it.
    """
    temp_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            "w",
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as temp_file:
            temp_path = Path(temp_file.name)
            temp_file.write(content)
        os.replace(temp_path, path)
    except BaseException:
        if temp_path is not None:
            temp_path.unlink(missing_ok=True)
        raise


# --- override resolution -----------------------------------------------------


def _auto_or(
    parse: Callable[[str], ValueT], kind: str
) -> Callable[[str], ValueT | str]:
    """Build an argparse `type=` that accepts `parse`-able values or `auto`."""

    def parse_flag(value: str) -> ValueT | str:
        if value == AUTO:
            return AUTO
        try:
            return parse(value)
        except ValueError as bad_value:
            raise argparse.ArgumentTypeError(
                f"expected {kind} or '{AUTO}', got {value!r}"
            ) from bad_value

    return parse_flag


def _recorded(
    recorded: dict[str, str], key: str, parse: Callable[[str], ValueT]
) -> ValueT | None:
    raw_value = recorded.get(key, "")
    if not raw_value:
        return None
    try:
        return parse(raw_value)
    except ValueError as bad_value:
        raise InfeasibleCapacity(
            f"recorded {key}={raw_value!r} is malformed; "
            f"rerun with 'make capacity' and that knob set to a value or 'auto'"
        ) from bad_value


def _resolve(
    flag_value: ValueT | str | None, recorded_value: ValueT | None
) -> ValueT | None:
    """A flag wins (`auto` clears); no flag reuses the recorded override.

    The flag parsers yield a number or the literal `AUTO`, so any str is `auto`.
    """
    if flag_value is None:
        return recorded_value
    if isinstance(flag_value, str):
        return None
    return flag_value


def _resolve_overrides(
    recorded: dict[str, str],
    n_ui_flag: int | str | None,
    n_int_flag: int | str | None,
    mem_fraction_flag: float | str | None,
) -> Overrides:
    return Overrides(
        n_ui=_resolve(n_ui_flag, _recorded(recorded, OVERRIDE_N_UI_KEY, int)),
        n_int=_resolve(n_int_flag, _recorded(recorded, OVERRIDE_N_INT_KEY, int)),
        mem_fraction=_resolve(
            mem_fraction_flag, _recorded(recorded, OVERRIDE_MEM_FRACTION_KEY, float)
        ),
    )


def _read_existing(path: Path) -> dict[str, str] | None:
    return read_env(path) if path.exists() else None


# --- app_logs ownership ------------------------------------------------------


def run_docker(args: list[str]) -> subprocess.CompletedProcess[str]:
    """Run `docker <args>`; a launch failure or timeout raises DockerRunError."""
    try:
        return subprocess.run(
            ["docker", *args],
            capture_output=True,
            text=True,
            timeout=DOCKER_RUN_TIMEOUT_SECONDS,
        )
    except subprocess.TimeoutExpired as timed_out:
        raise DockerRunError(
            f"docker {args[0]} timed out after {DOCKER_RUN_TIMEOUT_SECONDS}s"
        ) from timed_out
    except OSError as launch_error:
        raise DockerRunError(str(launch_error)) from launch_error


def _lookup(docker: DockerRunner, args: list[str]) -> str:
    """Stripped stdout of a docker lookup; empty (skip) when it exits non-zero."""
    result = docker(args)
    if result.returncode != 0:
        sys.stderr.write(result.stderr)
        return ""
    return result.stdout.strip()


def _logs_owner(recorded: dict[str, str], output: Path) -> str:
    """The `uid:gid` web runs as: the recorded host ids, 0 mapped to 1001."""
    raw_ids = (recorded.get("HOST_UID", ""), recorded.get("HOST_GID", ""))
    if not all(raw_id.isascii() and raw_id.isdecimal() for raw_id in raw_ids):
        raise CorruptCapacityFile(
            f"HOST_UID/HOST_GID invalid in {output} — run 'make capacity'"
        )
    owner_ids = [int(raw_id) or ROOT_ID_FALLBACK for raw_id in raw_ids]
    return ":".join(str(owner_id) for owner_id in owner_ids)


def _logs_owner_fix(output: Path, docker: DockerRunner) -> None:
    """Re-own the app_logs log dir to HOST_UID:HOST_GID when another uid owns it.

    Uses `docker run` against the existing web image, not `compose run`, so a
    missing volume is never created (and seeded by a stale image). Skips
    quietly with no volume, image, or log dir yet (a fresh machine).
    """
    volume_filters = [
        flag
        for volume_filter in LOGS_VOLUME_FILTERS
        for flag in ("--filter", volume_filter)
    ]
    volume = _lookup(docker, ["volume", "ls", "-q", *volume_filters])
    image = _lookup(docker, ["image", "ls", "-q", WEB_IMAGE])
    if not volume or not image:
        return
    wanted = _logs_owner(read_env(output), output)
    mount = f"{volume}:{LOGS_VOLUME_MOUNT}"
    root_run = ["run", "--rm", "--user", "root", "-v", mount, image]
    current = docker([*root_run, "stat", "-c", "%u:%g", LOGS_DIR])
    if current.returncode != 0:
        return
    have = current.stdout.strip()
    if have == wanted:
        return
    print(f"repairing app_logs ownership (was {have}, now {wanted})", flush=True)
    repair_script = f"chown -R {wanted} {LOGS_DIR} && chmod {LOGS_DIR_MODE} {LOGS_DIR}"
    repair = docker([*root_run, "sh", "-c", repair_script])
    if repair.returncode != 0:
        raise DockerRunError(
            repair.stderr.strip() or f"app_logs repair exited {repair.returncode}"
        )


# --- subcommands -------------------------------------------------------------


def _generate(
    output: Path,
    host_probe: Probe,
    n_ui_flag: int | str | None,
    n_int_flag: int | str | None,
    mem_fraction_flag: float | str | None,
) -> None:
    # The recorded overrides are read after the (slow) docker probe, as close
    # to the atomic replace as possible, to narrow the read-then-replace window.
    existing = _read_existing(output)
    overrides = _resolve_overrides(
        existing or {}, n_ui_flag, n_int_flag, mem_fraction_flag
    )
    mem_fraction = (
        overrides.mem_fraction
        if overrides.mem_fraction is not None
        else DEFAULT_MEM_FRACTION
    )
    capacity = derive(host_probe, overrides, mem_fraction, DEFAULT_MEM_SAFETY)
    content = render_env(
        capacity, host_probe, overrides, fingerprint(host_probe, overrides)
    )
    new_values = _parse_env(content)
    if existing == new_values:
        print(f"capacity unchanged ({output})")
        return
    _write_atomically(output, content)
    print(f"capacity regenerated ({output})")
    # A first write has nothing to compare against; `make up` creates the stack.
    changed = changed_interlocks(existing, new_values) if existing else []
    if changed:
        print(
            f"recreate required: run 'make up [p=…] d=1' (changed: {', '.join(changed)})"
        )


def _ensure(output: Path, host_probe: Probe) -> None:
    """Regenerate when P is missing, a key was deleted, or the fingerprint moved.

    Values are deliberately not re-derived here: the fingerprint excludes the
    mem_available jitter, so a matching, complete file is left untouched.
    """
    existing = _read_existing(output)
    if existing is not None and all(key in existing for key in ENV_KEYS):
        overrides = _resolve_overrides(existing, None, None, None)
        if existing.get(FINGERPRINT_KEY) == fingerprint(host_probe, overrides):
            return
    _generate(output, host_probe, None, None, None)


def _show(output: Path) -> int:
    if not output.exists():
        print(f"{output} does not exist; run 'make capacity'", file=sys.stderr)
        return 1
    text = output.read_text()
    existing = _parse_env(text)
    decision_lines = [
        line.removeprefix(DECISION_PREFIX)
        for line in text.splitlines()
        if line.startswith(DECISION_PREFIX)
    ]
    rows = {**existing, "U4I_SLUG": os.environ.get("U4I_SLUG", "")}
    key_width = max(len(key) for key in rows)
    print(f"capacity ({output})")
    for decision in decision_lines:
        print(f"  {decision}")
    for key, value in rows.items():
        print(f"  {key.ljust(key_width)}  {value or '-'}")
    return 0


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="make capacity",
        description="Derive worker counts and interlocks from this Docker host.",
    )
    subcommands = parser.add_subparsers(dest="command", required=True)

    generate_parser = subcommands.add_parser(
        "generate", help="write the capacity env file"
    )
    generate_parser.add_argument("--output", type=Path, required=True)
    worker_flag = _auto_or(int, "an integer")
    generate_parser.add_argument("--n-ui", type=worker_flag)
    generate_parser.add_argument("--n-int", type=worker_flag)
    generate_parser.add_argument("--mem-fraction", type=_auto_or(float, "a number"))

    for name, help_text in (
        ("ensure", "regenerate only when the host fingerprint changed"),
        ("show", "print the resolved capacity table"),
        ("logs-owner-fix", "re-own the app_logs log dir to HOST_UID:HOST_GID"),
    ):
        subcommand_parser = subcommands.add_parser(name, help=help_text)
        subcommand_parser.add_argument("--output", type=Path, required=True)
    return parser


def main(
    argv: list[str],
    probe_host: Callable[[], Probe] = _probe_host,
    docker_runner: DockerRunner = run_docker,
) -> int:
    args = _build_parser().parse_args(argv)
    try:
        if args.command == "show":
            return _show(args.output)
        if args.command == "logs-owner-fix":
            _logs_owner_fix(args.output, docker_runner)
            return 0
        host_probe = probe_host()
        if args.command == "generate":
            _generate(args.output, host_probe, args.n_ui, args.n_int, args.mem_fraction)
        else:
            _ensure(args.output, host_probe)
    except DockerInfoError as docker_error:
        print(f"make capacity: docker info failed — {docker_error}", file=sys.stderr)
        return 1
    except DockerRunError as docker_error:
        print(f"make capacity: docker failed — {docker_error}", file=sys.stderr)
        return 1
    except (InfeasibleCapacity, CorruptCapacityFile) as bad_value:
        print(f"make capacity: {bad_value}", file=sys.stderr)
        return 1
    except (OSError, UnicodeDecodeError) as file_error:
        print(f"make capacity: {file_error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
