"""Unit tests for the host-side test token runner (`scripts/token_budget.py`).

No Docker is used: every case runs against a fabricated capacity file under
`tmp_path`, and the contention cases use real `fcntl.flock` locks held by real
subprocesses, so they run identically on a laptop, inside the web container,
and on a CI runner. Every wait the harness itself performs is bounded by
SYNC_TIMEOUT_SECONDS, and every spawned runner is killed (its whole process
group) in fixture teardown, so a deadlock in `acquire()` fails instead of hangs.
"""

from __future__ import annotations

import fcntl
import io
import itertools
import json
import math
import os
import signal
import stat
import subprocess
import sys
import time
from collections.abc import Callable, Iterator
from datetime import datetime
from pathlib import Path

import pytest

from scripts import capacity, token_budget
from scripts.token_budget import (
    BudgetError,
    BudgetFile,
    LiveMemory,
    format_failure_block,
    main,
    read_budget,
)

pytestmark = pytest.mark.unit

GIB: int = 1024**3
SYNC_TIMEOUT_SECONDS: int = 10
HARNESS_POLL_SECONDS: float = 0.05
PROJECT_ROOT: Path = Path(__file__).resolve().parents[2]
DECISION: str = "n_ui=2 n_int=4 binding=cpu usable_gb=9.6 spoke_max=4"
BUDGET: int = 4
TEST_SLUG: str = "tokentest"
# A child command that records when it started, then waits (bounded) for a
# release marker, so the test — not wall-clock timing — decides when it exits.
MARKER_CHILD: str = (
    "import pathlib, sys, time\n"
    "pathlib.Path(sys.argv[1]).write_text(str(time.time_ns()))\n"
    "deadline = time.monotonic() + float(sys.argv[3])\n"
    "while not pathlib.Path(sys.argv[2]).exists() and time.monotonic() < deadline:\n"
    "    time.sleep(0.02)\n"
)
# A child command that records its own argv (after the marker path) as JSON.
ARGV_CHILD: str = (
    "import json, sys\nopen(sys.argv[1], 'w').write(json.dumps(sys.argv[2:]))\n"
)
BASE_GB: float = 2.0
WORKER_GB: float = 0.5
# Live usable memory every runner sees unless a test says otherwise: room for far
# more workers than BUDGET, so the memory gate never binds by accident.
AMPLE_USABLE_GB: float = 60.0
MEMINFO_NAME: str = "meminfo"
# Never created: every runner reads no cgroup limit, not the real host's.
NO_CGROUP_NAME: str = "no-cgroup"
ELASTIC_ERROR: str = (
    "token budget: an elastic run (--min-tokens < --tokens) needs @TOKENS@ in the "
    "command\n"
)


def _write_meminfo(path: Path, usable_gb: float) -> Path:
    """A /proc/meminfo whose MemAvailable gives `usable_gb` live usable GB.

    Written atomically: a runner polling the file must never read it half written
    (that would parse as unreadable and fall back to static capacity).
    """
    available_kb = int(usable_gb / token_budget.MEM_SAFETY * GIB) // 1024
    staging = path.with_name(f"{path.name}.tmp")
    staging.write_text(
        f"MemTotal:       {available_kb * 2} kB\nMemAvailable:   {available_kb} kB\n"
    )
    os.replace(staging, path)
    return path


def _write_capacity(path: Path, n_max: str = str(BUDGET)) -> Path:
    """The capacity file, plus an ample meminfo beside it that `_run_args` and the
    `spawn` fixture point every runner at (with a missing cgroup file), so no test
    reads the real host's."""
    path.write_text(
        "# GENERATED by make capacity — DO NOT EDIT\n"
        f"# decision: {DECISION}\n"
        "U4I_N_UI=2\n"
        f"U4I_N_MAX={n_max}\n"
        "U4I_BASE_MB=2048\n"
        "U4I_WORKER_MB=512\n"
    )
    _write_meminfo(path.with_name(MEMINFO_NAME), AMPLE_USABLE_GB)
    return path


def _live(usable_gb: float) -> LiveMemory:
    """A host reading whose live usable memory is `usable_gb`."""
    return LiveMemory(int(usable_gb / token_budget.MEM_SAFETY * GIB), "host")


class FakeTime:
    """A clock plus a sleep that advances it: no acquire() case waits in real time."""

    def __init__(self) -> None:
        self.now = 0.0

    def clock(self) -> float:
        return self.now

    def sleep(self, seconds: float) -> None:
        self.now += seconds


def _scripted(*readings: LiveMemory) -> Callable[[], LiveMemory]:
    """Answer each live-memory read from `readings`, repeating the last one."""
    remaining = list(readings)

    def read() -> LiveMemory:
        return remaining.pop(0) if len(remaining) > 1 else remaining[0]

    return read


def _acquire(
    lock_dir: Path,
    tokens: int,
    min_tokens: int,
    live_memory: Callable[[], LiveMemory],
    fake_time: FakeTime,
    out: io.StringIO,
    max_wait: float | None = None,
    memory_wait: float = token_budget.MEMORY_WAIT_SECONDS,
    sleep: Callable[[float], None] | None = None,
) -> token_budget.Acquired:
    token_budget.ensure_lock_dir(lock_dir)
    return token_budget.acquire(
        lock_dir,
        tokens,
        min_tokens,
        BudgetFile(BUDGET, DECISION, BASE_GB, WORKER_GB),
        "unit-label",
        TEST_SLUG,
        max_wait,
        memory_wait,
        fake_time.clock,
        sleep or fake_time.sleep,
        live_memory,
        out,
    )


def _release_acquired(acquired: token_budget.Acquired) -> None:
    """Undo a successful acquire(): unlock its slots and its turnstile."""
    token_budget._release(acquired.fds)
    os.close(acquired.turnstile_fd)


def _turnstile_free(lock_dir: Path) -> bool:
    """Whether the turnstile can be locked right now (probe, then let go)."""
    descriptor = token_budget._try_lock(lock_dir / token_budget.TURNSTILE_NAME)
    if descriptor is None:
        return False
    os.close(descriptor)
    return True


class SteppingClock:
    """A clock that advances `step` seconds on every call, calling `on_tick`
    with each value it returns (before returning it)."""

    def __init__(
        self, step: float, on_tick: Callable[[float], None] = lambda now: None
    ) -> None:
        self.step = step
        self.on_tick = on_tick
        self.now = -step

    def __call__(self) -> float:
        self.now += self.step
        self.on_tick(self.now)
        return self.now


def _locked_slots(lock_dir: Path) -> list[int]:
    return [
        index
        for index in range(BUDGET)
        if token_budget._is_locked(lock_dir / f"{token_budget.SLOT_PREFIX}{index}")
    ]


def _wait_for(predicate: Callable[[], bool], description: str) -> None:
    deadline = time.monotonic() + SYNC_TIMEOUT_SECONDS
    while not predicate():
        if time.monotonic() >= deadline:
            pytest.fail(
                f"timed out after {SYNC_TIMEOUT_SECONDS}s waiting for {description}"
            )
        time.sleep(HARNESS_POLL_SECONDS)


def _read(path: Path) -> str:
    return path.read_text() if path.exists() else ""


def _slot_lines(lock_dir: Path) -> list[str]:
    return [
        line
        for slot in sorted(lock_dir.glob(f"{token_budget.SLOT_PREFIX}*"))
        for line in _read(slot).splitlines()
        if line.strip()
    ]


def _slot_fields(line: str) -> dict[str, str]:
    return dict(field.split("=", 1) for field in line.split())


class Runner:
    """A `python -m scripts.token_budget run …` subprocess logging to a file."""

    def __init__(self, process: subprocess.Popen[bytes], log: Path) -> None:
        self.process = process
        self.log = log

    def output(self) -> str:
        return _read(self.log)

    def wait(self) -> int:
        try:
            return self.process.wait(timeout=SYNC_TIMEOUT_SECONDS)
        except subprocess.TimeoutExpired:
            pytest.fail(
                f"runner did not exit within {SYNC_TIMEOUT_SECONDS}s:\n{self.output()}"
            )


def _reset_sigint_to_default() -> None:
    # A SIG_IGN inherited from the test process (e.g. a nohup'd pytest) would stop
    # the runner's Python from installing KeyboardInterrupt for SIGINT.
    signal.signal(signal.SIGINT, signal.SIG_DFL)


@pytest.fixture
def capacity_file(tmp_path: Path) -> Path:
    return _write_capacity(tmp_path / "capacity.env")


@pytest.fixture
def lock_dir(tmp_path: Path) -> Path:
    return tmp_path / "tokens"


@pytest.fixture
def spawn(
    tmp_path: Path, capacity_file: Path, lock_dir: Path
) -> Iterator[Callable[..., Runner]]:
    """Start runners in their own process group; kill every group on teardown."""
    runners: list[Runner] = []

    def start(
        name: str,
        tokens: int,
        child: list[str],
        max_wait: float | None = None,
        meminfo: Path | None = None,
        settle_seconds: float = 0,
    ) -> Runner:
        """No settle window unless a test asks for one: the contention cases
        predate it, and a 20 s default would only slow them down."""
        log = tmp_path / f"{name}.log"
        argv = [
            sys.executable,
            "-m",
            "scripts.token_budget",
            "run",
            "--capacity-file",
            str(capacity_file),
            "--lock-dir",
            str(lock_dir),
            "--meminfo",
            str(meminfo or capacity_file.with_name(MEMINFO_NAME)),
            "--cgroup",
            str(capacity_file.with_name(NO_CGROUP_NAME)),
            "--settle-seconds",
            str(settle_seconds),
            "--tokens",
            str(tokens),
            "--label",
            name,
        ]
        if max_wait is not None:
            argv += ["--max-wait", str(max_wait)]
        with log.open("wb") as log_handle:
            process = subprocess.Popen(
                [*argv, "--", *child],
                cwd=PROJECT_ROOT,
                env={**os.environ, "U4I_SLUG": TEST_SLUG},
                stdout=log_handle,
                stderr=subprocess.STDOUT,
                start_new_session=True,
                preexec_fn=_reset_sigint_to_default,
            )
        runner = Runner(process, log)
        runners.append(runner)
        return runner

    try:
        yield start
    finally:
        for runner in runners:
            if runner.process.poll() is None:
                try:
                    os.killpg(runner.process.pid, signal.SIGKILL)
                except ProcessLookupError:
                    pass
            try:
                runner.process.wait(timeout=SYNC_TIMEOUT_SECONDS)
            except subprocess.TimeoutExpired:
                runner.process.kill()


def _marker_child(
    tmp_path: Path, name: str, lifetime_seconds: float = SYNC_TIMEOUT_SECONDS
) -> tuple[list[str], Path, Path]:
    """A MARKER_CHILD that self-exits after `lifetime_seconds` if never released."""
    started = tmp_path / f"{name}-started"
    release = tmp_path / f"{name}-release"
    child = [
        sys.executable,
        "-c",
        MARKER_CHILD,
        str(started),
        str(release),
        str(lifetime_seconds),
    ]
    return child, started, release


def _touch_child(marker: Path) -> list[str]:
    return [sys.executable, "-c", f"open({str(marker)!r}, 'w').close()"]


def _exit_child(code: int) -> list[str]:
    return [sys.executable, "-c", f"import sys; sys.exit({code})"]


def _run_args(
    capacity_file: Path,
    lock_dir: Path,
    tokens: str,
    command: list[str],
    max_wait: str = "0",
    extra_flags: tuple[str, ...] = (),
    meminfo: Path | None = None,
) -> list[str]:
    return [
        "run",
        "--capacity-file",
        str(capacity_file),
        "--lock-dir",
        str(lock_dir),
        "--meminfo",
        str(meminfo or capacity_file.with_name(MEMINFO_NAME)),
        "--cgroup",
        str(capacity_file.with_name(NO_CGROUP_NAME)),
        *extra_flags,
        "--tokens",
        tokens,
        "--label",
        "unit-label",
        "--max-wait",
        max_wait,
        "--",
        *command,
    ]


def _hold_slots(lock_dir: Path, indexes: list[int], label: str) -> list[int]:
    """Lock slot files in this process (distinct open file descriptions)."""
    lock_dir.mkdir(mode=0o700, exist_ok=True)
    held: list[int] = []
    for index in indexes:
        descriptor = os.open(
            lock_dir / f"{token_budget.SLOT_PREFIX}{index}",
            os.O_RDWR | os.O_CREAT,
            0o600,
        )
        fcntl.flock(descriptor, fcntl.LOCK_EX | fcntl.LOCK_NB)
        os.write(
            descriptor,
            f"pid={os.getpid()} slug=other label={label} tokens={len(indexes)} "
            "since=2026-09-29T00:00:00+00:00\n".encode(),
        )
        held.append(descriptor)
    return held


def _release_slots(descriptors: list[int]) -> None:
    for descriptor in descriptors:
        os.close(descriptor)


# --- read_budget -------------------------------------------------------------


def test_read_budget_returns_budget_decision_and_memory_model(
    capacity_file: Path,
) -> None:
    assert read_budget(capacity_file) == BudgetFile(
        BUDGET, DECISION, BASE_GB, WORKER_GB
    )


@pytest.mark.parametrize(
    "memory_lines",
    [
        "U4I_WORKER_MB=512\n",
        "U4I_BASE_MB=2048\n",
        "U4I_BASE_MB=abc\nU4I_WORKER_MB=512\n",
        "U4I_BASE_MB=2048\nU4I_WORKER_MB=0\n",
    ],
)
def test_read_budget_missing_or_invalid_memory_model(
    tmp_path: Path, memory_lines: str
) -> None:
    path = tmp_path / "capacity.env"
    path.write_text(f"# decision: {DECISION}\nU4I_N_MAX=4\n{memory_lines}")
    with pytest.raises(BudgetError) as error:
        read_budget(path)
    assert str(error.value) == (
        f"{path} missing or has no valid U4I_BASE_MB/U4I_WORKER_MB — run "
        "'make capacity'"
    )


def test_read_budget_missing_file(tmp_path: Path) -> None:
    with pytest.raises(BudgetError) as error:
        read_budget(tmp_path / "absent.env")
    assert str(error.value).endswith("run 'make capacity'")


@pytest.mark.parametrize("n_max", ["", "abc", "0", "-3", "1.5"])
def test_read_budget_invalid_n_max(tmp_path: Path, n_max: str) -> None:
    path = _write_capacity(tmp_path / "capacity.env", n_max)
    with pytest.raises(BudgetError) as error:
        read_budget(path)
    assert str(error.value).endswith("run 'make capacity'")


def test_read_budget_missing_n_max(tmp_path: Path) -> None:
    path = tmp_path / "capacity.env"
    path.write_text(f"# decision: {DECISION}\nU4I_N_UI=2\n")
    with pytest.raises(BudgetError) as error:
        read_budget(path)
    assert str(error.value) == (
        f"{path} missing or has no valid U4I_N_MAX — run 'make capacity'"
    )


def test_main_reports_missing_capacity_file(
    tmp_path: Path, lock_dir: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    marker = tmp_path / "ran"
    exit_code = main(
        _run_args(tmp_path / "absent.env", lock_dir, "1", _touch_child(marker))
    )
    assert exit_code == 1
    assert not marker.exists()
    assert capsys.readouterr().err.startswith("token budget: ")


# --- token validation --------------------------------------------------------


@pytest.mark.parametrize("tokens", ["0", "-1", "abc", ""])
def test_invalid_token_count_exits_1(
    tmp_path: Path,
    capacity_file: Path,
    lock_dir: Path,
    tokens: str,
    capsys: pytest.CaptureFixture[str],
) -> None:
    marker = tmp_path / "ran"
    exit_code = main(_run_args(capacity_file, lock_dir, tokens, _touch_child(marker)))
    assert exit_code == 1
    assert not marker.exists()
    assert capsys.readouterr().err.startswith("token budget: ")


def test_over_budget_request_is_refused_without_running(
    tmp_path: Path,
    capacity_file: Path,
    lock_dir: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    marker = tmp_path / "ran"
    exit_code = main(_run_args(capacity_file, lock_dir, "5", _touch_child(marker)))
    assert exit_code == 1
    assert not marker.exists()
    assert capsys.readouterr().err == (
        "token budget: this run needs 5 tokens but the host budget is 4 "
        f"(U4I_N_MAX in {capacity_file}); lower n= or raise it with "
        "'make capacity' in the primary clone\n"
    )


def test_missing_command_exits_1(
    capacity_file: Path, lock_dir: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    assert main(_run_args(capacity_file, lock_dir, "1", [])) == 1
    assert capsys.readouterr().err.startswith("token budget: ")


# --- exit codes and the failure block ----------------------------------------


def test_child_failure_propagates_and_prints_capacity_block(
    capacity_file: Path, lock_dir: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    assert main(_run_args(capacity_file, lock_dir, "2", _exit_child(3))) == 3
    err = capsys.readouterr().err
    assert "token budget: unit-label exited 3 — resolved capacity for this run:" in err
    assert f"  tokens (n):     2 of budget 4 (U4I_N_MAX, {capacity_file})" in err
    assert "  queued:         0.0s; other holders at start: 0 tokens" in err
    assert f"  decision:       {DECISION}" in err
    assert "  at ceiling:     no" in err
    # The child exits long before the first mid-run sample.
    assert "  memory:         60.00 GB usable at start (host)\n" in err
    assert "hint:" not in err


def test_failure_block_reports_the_granted_tokens_of_an_elastic_run(
    tmp_path: Path,
    capacity_file: Path,
    lock_dir: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    # floor((3.6 - 2.0) / 0.5) = 3 of the 4 requested workers fit.
    meminfo = _write_meminfo(tmp_path / "tight-meminfo", 3.6)
    child = [*_exit_child(4), "@TOKENS@"]
    exit_code = main(
        _run_args(
            capacity_file,
            lock_dir,
            "4",
            child,
            extra_flags=("--min-tokens", "1"),
            meminfo=meminfo,
        )
    )
    assert exit_code == 4
    err = capsys.readouterr().err
    assert f"  tokens (n):     3 of budget 4 (U4I_N_MAX, {capacity_file})" in err
    assert "  at ceiling:     no" in err
    assert "  memory:         3.60 GB usable at start (host)\n" in err


@pytest.mark.parametrize("code", [0, 130])
def test_child_success_or_interrupt_prints_no_block(
    capacity_file: Path,
    lock_dir: Path,
    code: int,
    capsys: pytest.CaptureFixture[str],
) -> None:
    assert main(_run_args(capacity_file, lock_dir, "1", _exit_child(code))) == code
    assert "resolved capacity" not in capsys.readouterr().err


def test_child_runs_after_acquiring(
    tmp_path: Path, capacity_file: Path, lock_dir: Path
) -> None:
    marker = tmp_path / "ran"
    assert main(_run_args(capacity_file, lock_dir, "4", _touch_child(marker))) == 0
    assert marker.exists()


def test_at_ceiling_prints_hint(
    capacity_file: Path, lock_dir: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    held = _hold_slots(lock_dir, [0, 1], "holder")
    try:
        assert main(_run_args(capacity_file, lock_dir, "2", _exit_child(1))) == 1
    finally:
        _release_slots(held)
    err = capsys.readouterr().err
    assert "other holders at start: 2 tokens (other/holder)" in err
    assert "  at ceiling:     yes  (tokens in use incl. this run == budget)" in err
    assert (
        "  hint:           timeouts or spurious login failures at the ceiling are "
        "often capacity, not product bugs — rerun with a lower n=" in err
    )


def test_below_ceiling_prints_no_hint(
    capacity_file: Path, lock_dir: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    held = _hold_slots(lock_dir, [0], "holder")
    try:
        assert main(_run_args(capacity_file, lock_dir, "2", _exit_child(1))) == 1
    finally:
        _release_slots(held)
    err = capsys.readouterr().err
    assert "other holders at start: 1 tokens (other/holder)" in err
    assert "  at ceiling:     no" in err
    assert "hint:" not in err


def test_format_failure_block_is_pure() -> None:
    lines = format_failure_block(
        label="test-x",
        exit_code=5,
        tokens=3,
        budget=4,
        capacity_file=Path("/cap.env"),
        queued_seconds=12.34,
        others_at_start=("a/test-y",),
        in_use_at_start=1,
        decision=DECISION,
        live_at_start=_live(3.6),
        min_live_usable_gb=0.8,
    )
    assert lines == [
        "token budget: test-x exited 5 — resolved capacity for this run:",
        "  tokens (n):     3 of budget 4 (U4I_N_MAX, /cap.env)",
        "  queued:         12.3s; other holders at start: 1 tokens (a/test-y)",
        "  at ceiling:     yes  (tokens in use incl. this run == budget)",
        f"  decision:       {DECISION}",
        "  memory:         3.60 GB usable at start, 0.80 GB lowest during run (host)",
        "  hint:           timeouts or spurious login failures at the ceiling are "
        "often capacity, not product bugs — rerun with a lower n=",
        "  hint:           host memory ran low (0.80 GB) during this run — failures "
        "may be memory pressure, not product bugs",
    ]


def _failure_block_memory_lines(
    live_at_start: LiveMemory, min_live_usable_gb: float | None
) -> list[str]:
    """The failure block's memory lines (below the ceiling: no ceiling hint)."""
    lines = format_failure_block(
        label="test-x",
        exit_code=1,
        tokens=1,
        budget=4,
        capacity_file=Path("/cap.env"),
        queued_seconds=0.0,
        others_at_start=(),
        in_use_at_start=0,
        decision=DECISION,
        live_at_start=live_at_start,
        min_live_usable_gb=min_live_usable_gb,
    )
    return [line for line in lines if "memory" in line]


def test_failure_block_memory_line_without_a_live_reading() -> None:
    assert _failure_block_memory_lines(LiveMemory(None, "none"), None) == [
        "  memory:         unavailable (static capacity)"
    ]


def test_failure_block_memory_line_with_only_a_mid_run_sample() -> None:
    assert _failure_block_memory_lines(LiveMemory(None, "none"), 0.8) == [
        "  memory:         unavailable at start, 0.80 GB lowest during run",
        "  hint:           host memory ran low (0.80 GB) during this run — failures "
        "may be memory pressure, not product bugs",
    ]


def test_failure_block_memory_line_without_a_mid_run_sample() -> None:
    assert _failure_block_memory_lines(_live(3.6), None) == [
        "  memory:         3.60 GB usable at start (host)"
    ]


def test_failure_block_has_no_memory_hint_at_the_low_memory_threshold() -> None:
    # Only a lowest reading strictly below LOW_MEMORY_GB earns the hint.
    assert _failure_block_memory_lines(_live(3.6), token_budget.LOW_MEMORY_GB) == [
        "  memory:         3.60 GB usable at start, 1.00 GB lowest during run (host)"
    ]


def test_queued_run_times_out_with_max_wait(
    tmp_path: Path,
    capacity_file: Path,
    lock_dir: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    marker = tmp_path / "ran"
    held = _hold_slots(lock_dir, [0, 1, 2], "holder")
    try:
        exit_code = main(_run_args(capacity_file, lock_dir, "2", _touch_child(marker)))
    finally:
        _release_slots(held)
    assert exit_code == 1
    assert not marker.exists()
    err = capsys.readouterr().err
    assert "token budget: waiting for 2 of 4 tokens — held by: other/holder (3)" in err
    assert "gave up" in err
    # The one slot it did lock was released on the way out.
    assert main(_run_args(capacity_file, lock_dir, "1", _exit_child(0))) == 0


# --- lock dir ----------------------------------------------------------------


def test_lock_dir_is_created_0700(capacity_file: Path, lock_dir: Path) -> None:
    assert main(_run_args(capacity_file, lock_dir, "1", _exit_child(0))) == 0
    assert lock_dir.stat().st_mode & 0o777 == 0o700
    assert (lock_dir / token_budget.TURNSTILE_NAME).exists()
    assert (lock_dir / f"{token_budget.SLOT_PREFIX}0").exists()


def test_lock_dir_owned_by_another_uid_is_refused(
    tmp_path: Path,
    capacity_file: Path,
    lock_dir: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    lock_dir.mkdir(mode=0o700)
    real_lstat = os.lstat
    foreign_uid = os.getuid() + 1

    def fake_lstat(path: str | os.PathLike[str], **kwargs: object) -> os.stat_result:
        result = real_lstat(path, **kwargs)
        if Path(str(path)) != lock_dir:
            return result
        fields = list(result)
        fields[4] = foreign_uid  # st_uid
        return os.stat_result(fields)

    monkeypatch.setattr(token_budget.os, "lstat", fake_lstat)
    marker = tmp_path / "ran"
    exit_code = main(_run_args(capacity_file, lock_dir, "1", _touch_child(marker)))
    monkeypatch.undo()
    assert exit_code == 1
    assert not marker.exists()
    err = capsys.readouterr().err
    assert err.startswith("token budget: ")
    assert f"uid {foreign_uid}" in err


def test_symlinked_lock_dir_is_refused(
    tmp_path: Path,
    capacity_file: Path,
    lock_dir: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    target = tmp_path / "elsewhere"
    target.mkdir(mode=0o700)
    lock_dir.symlink_to(target)
    marker = tmp_path / "ran"
    exit_code = main(_run_args(capacity_file, lock_dir, "1", _touch_child(marker)))
    assert exit_code == 1
    assert not marker.exists()
    assert list(target.iterdir()) == []
    err = capsys.readouterr().err
    assert err.startswith(f"token budget: {lock_dir} is a symlink or not a directory")


def test_group_readable_lock_dir_is_refused(
    tmp_path: Path,
    capacity_file: Path,
    lock_dir: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    lock_dir.mkdir(mode=0o700)
    real_lstat = os.lstat

    # Fake the mode rather than chmod the dir open: CodeQL flags any real chmod
    # that grants group/other access, even in a test.
    def fake_lstat(path: str | os.PathLike[str], **kwargs: object) -> os.stat_result:
        result = real_lstat(path, **kwargs)
        if Path(str(path)) != lock_dir:
            return result
        fields = list(result)
        fields[0] = stat.S_IFDIR | 0o750  # st_mode
        return os.stat_result(fields)

    monkeypatch.setattr(token_budget.os, "lstat", fake_lstat)
    marker = tmp_path / "ran"
    exit_code = main(_run_args(capacity_file, lock_dir, "1", _touch_child(marker)))
    monkeypatch.undo()
    assert exit_code == 1
    assert not marker.exists()
    assert capsys.readouterr().err == (
        f"token budget: {lock_dir} dir mode is 0750, expected 0700 — remove it and "
        "rerun\n"
    )


# --- CLI validation and robustness -------------------------------------------


@pytest.mark.parametrize("max_wait", ["nan", "inf", "-1"])
def test_invalid_max_wait_exits_1(
    tmp_path: Path,
    capacity_file: Path,
    lock_dir: Path,
    max_wait: str,
    capsys: pytest.CaptureFixture[str],
) -> None:
    marker = tmp_path / "ran"
    exit_code = main(
        _run_args(capacity_file, lock_dir, "1", _touch_child(marker), max_wait)
    )
    assert exit_code == 1
    assert not marker.exists()
    assert capsys.readouterr().err.startswith("token budget: --max-wait must be")


def test_command_not_found_exits_127_and_releases(
    capacity_file: Path, lock_dir: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    missing = ["/nonexistent-u4i-command"]
    assert main(_run_args(capacity_file, lock_dir, "1", missing)) == 127
    assert capsys.readouterr().err.startswith("token budget: cannot run")
    assert _turnstile_free(lock_dir)
    # Every slot is free again: a full-budget run needs no wait.
    assert main(_run_args(capacity_file, lock_dir, "4", _exit_child(0))) == 0


def test_signal_handlers_are_restored_after_the_child(
    capacity_file: Path, lock_dir: Path
) -> None:
    before = {
        signum: signal.getsignal(signum) for signum in (signal.SIGINT, signal.SIGTERM)
    }
    assert main(_run_args(capacity_file, lock_dir, "1", _exit_child(0))) == 0
    after = {
        signum: signal.getsignal(signum) for signum in (signal.SIGINT, signal.SIGTERM)
    }
    assert after == before


def test_acquire_heartbeats_then_gives_up(lock_dir: Path) -> None:
    held = _hold_slots(lock_dir, [0, 1, 2], "holder")
    ticks = itertools.count()

    def fake_clock() -> float:
        # Each call advances one heartbeat, so every poll pass is heartbeat-due.
        return float(next(ticks) * token_budget.HEARTBEAT_SECONDS)

    out = io.StringIO()
    try:
        with pytest.raises(BudgetError) as error:
            token_budget.acquire(
                lock_dir,
                2,
                2,
                BudgetFile(BUDGET, DECISION, 2.0, 0.5),
                "unit-label",
                TEST_SLUG,
                2 * token_budget.HEARTBEAT_SECONDS + 1,
                600,
                fake_clock,
                lambda seconds: None,
                lambda: LiveMemory(1_000_000_000_000, "host"),
                out,
            )
    finally:
        _release_slots(held)
    lines = out.getvalue().splitlines()
    assert lines[0] == (
        "token budget: waiting for 2 of 4 tokens — held by: other/holder (3)"
    )
    assert any(
        line.startswith("token budget: still waiting for 2 of 4 tokens (")
        for line in lines[1:]
    )
    assert "gave up" in str(error.value)


def test_stale_slot_is_skipped_in_best_effort_holders(
    tmp_path: Path,
    capacity_file: Path,
    lock_dir: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    lock_dir.mkdir(mode=0o700)
    finished = subprocess.Popen([sys.executable, "-c", "pass"])
    finished.wait(timeout=SYNC_TIMEOUT_SECONDS)
    (lock_dir / f"{token_budget.SLOT_PREFIX}0").write_text(
        f"pid={finished.pid} slug=other label=ghost tokens=1 "
        "since=2026-09-29T00:00:00+00:00\n"
    )
    # Holding the turnstile forces the runner onto the best-effort (content) read.
    turnstile = os.open(
        lock_dir / token_budget.TURNSTILE_NAME, os.O_RDWR | os.O_CREAT, 0o600
    )
    held: list[int] = []
    marker = tmp_path / "ran"
    try:
        fcntl.flock(turnstile, fcntl.LOCK_EX | fcntl.LOCK_NB)
        held = _hold_slots(lock_dir, [1], "holder")
        exit_code = main(_run_args(capacity_file, lock_dir, "1", _touch_child(marker)))
    finally:
        _release_slots(held)
        os.close(turnstile)
    assert exit_code == 1
    assert not marker.exists()
    err = capsys.readouterr().err
    assert "token budget: waiting for 1 of 4 tokens — held by: other/holder (1)" in err
    assert "ghost" not in err


# --- real fcntl contention between processes ---------------------------------


def test_queues_behind_holder_and_kernel_releases_on_sigkill(
    tmp_path: Path, lock_dir: Path, spawn: Callable[..., Runner]
) -> None:
    holder_child, holder_started, _ = _marker_child(tmp_path, "holder")
    holder = spawn("holder", 3, holder_child)
    _wait_for(lambda: len(_slot_lines(lock_dir)) == 3, "the holder's 3 slot lines")
    _wait_for(holder_started.exists, "the holder's child to start")

    waiter = spawn("waiter", 2, _touch_child(tmp_path / "waiter-ran"), max_wait=1.5)
    assert waiter.wait() == 1
    output = waiter.output()
    assert (
        f"token budget: waiting for 2 of 4 tokens — held by: {TEST_SLUG}/holder (3)"
        in output
    )
    assert "gave up" in output
    assert not (tmp_path / "waiter-ran").exists()

    os.killpg(holder.process.pid, signal.SIGKILL)
    holder.wait()
    full = spawn("full", 4, _touch_child(tmp_path / "full-ran"), max_wait=0)
    assert full.wait() == 0, full.output()
    assert "waiting" not in full.output()
    assert (tmp_path / "full-ran").exists()


def test_sigint_while_queued_exits_130_and_releases(
    tmp_path: Path, lock_dir: Path, spawn: Callable[..., Runner]
) -> None:
    holder_child, _, _ = _marker_child(tmp_path, "holder")
    spawn("holder", 3, holder_child)
    _wait_for(lambda: len(_slot_lines(lock_dir)) == 3, "the holder's 3 slot lines")

    queued_marker = tmp_path / "queued-ran"
    queued = spawn("queued", 2, _touch_child(queued_marker))
    _wait_for(
        lambda: "waiting for 2 of 4 tokens" in queued.output(),
        "the queued runner's wait line",
    )
    queued.process.send_signal(signal.SIGINT)
    assert queued.wait() == 130, queued.output()
    assert not queued_marker.exists()
    assert "resolved capacity" not in queued.output()

    probe = spawn("probe", 1, _touch_child(tmp_path / "probe-ran"), max_wait=0)
    assert probe.wait() == 0, probe.output()
    assert "waiting" not in probe.output()


def test_tty_sigint_while_child_runs_exits_130_without_block(
    tmp_path: Path, spawn: Callable[..., Runner]
) -> None:
    child, started, _ = _marker_child(tmp_path, "running")
    runner = spawn("running", 1, child)
    _wait_for(started.exists, "the runner's child to start")
    # A terminal Ctrl-C signals the whole foreground group: runner and child.
    os.killpg(runner.process.pid, signal.SIGINT)
    assert runner.wait() == 130, runner.output()
    assert "resolved capacity" not in runner.output()


def test_sigterm_to_runner_is_forwarded_to_child(
    tmp_path: Path, spawn: Callable[..., Runner]
) -> None:
    child, started, _ = _marker_child(tmp_path, "term")
    runner = spawn("term", 1, child)
    _wait_for(started.exists, "the runner's child to start")
    # Only the runner is signalled; the child can only die of it via forwarding.
    runner.process.send_signal(signal.SIGTERM)
    assert runner.wait() == 143, runner.output()
    assert (
        "token budget: term exited 143 — resolved capacity for this run:"
        in runner.output()
    )


def test_turnstile_holder_is_served_before_later_waiter(
    tmp_path: Path, lock_dir: Path, spawn: Callable[..., Runner]
) -> None:
    holder_child, _, holder_release = _marker_child(tmp_path, "holder")
    first_child, first_started, first_release = _marker_child(tmp_path, "first")
    second_child, second_started, second_release = _marker_child(tmp_path, "second")

    holder = spawn("holder", 3, holder_child)
    _wait_for(lambda: len(_slot_lines(lock_dir)) == 3, "the holder's 3 slot lines")
    first = spawn("first", 2, first_child)
    _wait_for(
        lambda: "waiting for 2 of 4 tokens" in first.output(),
        "the first waiter's wait line",
    )
    second = spawn("second", 1, second_child)
    _wait_for(
        lambda: "waiting for 1 of 4 tokens" in second.output(),
        "the second waiter's wait line",
    )
    assert f"{TEST_SLUG}/holder (3)" in second.output()
    assert f"{TEST_SLUG}/first (1)" in second.output()

    holder_release.touch()
    assert holder.wait() == 0, holder.output()
    _wait_for(first_started.exists, "the first waiter's child to start")
    _wait_for(second_started.exists, "the second waiter's child to start")

    # Each runner stamps `since=` as it locks a slot. The first waiter locks its
    # last slot while still holding the turnstile, and the second can lock
    # nothing until it gets the turnstile — so the first is served strictly
    # before the second. (Child start times are not compared: both children
    # start within one interpreter startup of each other, which is not ordered.)
    lines = [_slot_fields(line) for line in _slot_lines(lock_dir)]
    first_since = [fields["since"] for fields in lines if fields["label"] == "first"]
    second_since = [fields["since"] for fields in lines if fields["label"] == "second"]
    assert len(first_since) == 2
    assert len(second_since) == 1
    assert max(first_since) < second_since[0]

    first_release.touch()
    second_release.touch()
    assert first.wait() == 0, first.output()
    assert second.wait() == 0, second.output()


# --- live memory gate (acquire) ----------------------------------------------


def test_elastic_run_shrinks_to_the_workers_that_fit(lock_dir: Path) -> None:
    out = io.StringIO()
    # floor((3.6 - 2.0) / 0.5) = 3 workers fit.
    acquired = _acquire(lock_dir, 4, 1, _scripted(_live(3.6)), FakeTime(), out)
    try:
        assert acquired.granted == 3
        assert len(acquired.fds) == 3
        assert _locked_slots(lock_dir) == [0, 1, 2]
        assert acquired.live_at_start == _live(3.6)
        assert out.getvalue() == ""
    finally:
        _release_acquired(acquired)


def test_exact_run_waits_for_memory_then_starts(lock_dir: Path) -> None:
    out = io.StringIO()
    fake_time = FakeTime()
    acquired = _acquire(
        lock_dir, 4, 4, _scripted(_live(3.6), _live(4.0)), fake_time, out
    )
    try:
        assert acquired.granted == 4
        assert _locked_slots(lock_dir) == [0, 1, 2, 3]
        assert acquired.live_at_start == _live(4.0)
        assert acquired.memory_wait_seconds == token_budget.POLL_SECONDS
    finally:
        _release_acquired(acquired)
    assert out.getvalue().splitlines() == [
        "token budget: waiting for memory — need 4.00 GB for 4 workers, 3.60 GB "
        "usable (host); runs holding tokens: none"
    ]


def test_outside_memory_pressure_gives_up_after_memory_wait(lock_dir: Path) -> None:
    out = io.StringIO()
    fake_time = FakeTime()
    with pytest.raises(BudgetError) as error:
        _acquire(lock_dir, 1, 1, _scripted(_live(2.2)), fake_time, out, memory_wait=60)
    assert str(error.value) == (
        "gave up after 60s waiting for memory with no other test run holding "
        "tokens — need 2.50 GB, 2.20 GB usable (host); lower n= or free host "
        "memory (U4I_MEMORY_WAIT=60)"
    )
    assert fake_time.now == 60
    assert _locked_slots(lock_dir) == []


def test_memory_wait_behind_our_own_runs_has_no_deadline(lock_dir: Path) -> None:
    held = _hold_slots(lock_dir, [3], "holder")
    out = io.StringIO()
    fake_time = FakeTime()
    try:
        with pytest.raises(BudgetError) as error:
            _acquire(
                lock_dir,
                1,
                1,
                _scripted(_live(2.2)),
                fake_time,
                out,
                max_wait=120,
                memory_wait=60,
            )
    finally:
        _release_slots(held)
    # Still waiting well past memory_wait: only --max-wait ended it.
    assert str(error.value) == "gave up after 120.0s waiting for memory (--max-wait)"
    assert fake_time.now == 120
    assert "runs holding tokens: other/holder (1)" in out.getvalue()


def test_memory_wait_heartbeats(lock_dir: Path) -> None:
    out = io.StringIO()
    with pytest.raises(BudgetError):
        _acquire(
            lock_dir,
            1,
            1,
            _scripted(_live(2.2)),
            FakeTime(),
            out,
            max_wait=token_budget.HEARTBEAT_SECONDS + 1,
        )
    lines = out.getvalue().splitlines()
    body = (
        "need 2.50 GB for 1 workers, 2.20 GB usable (host); runs holding tokens: none"
    )
    assert lines == [
        f"token budget: waiting for memory — {body}",
        f"token budget: still waiting for memory (30s) — {body}",
    ]


def test_unreadable_live_memory_falls_back_to_static_capacity(lock_dir: Path) -> None:
    out = io.StringIO()
    acquired = _acquire(
        lock_dir, 4, 1, _scripted(LiveMemory(None, "none")), FakeTime(), out
    )
    try:
        assert acquired.granted == 4
        assert acquired.live_at_start == LiveMemory(None, "none")
    finally:
        _release_acquired(acquired)
    assert out.getvalue() == (
        "token budget: live memory unavailable — using static capacity\n"
    )


def test_extras_are_released_when_the_fit_drops_while_waiting(lock_dir: Path) -> None:
    held = _hold_slots(lock_dir, [2, 3], "holder")
    out = io.StringIO()
    try:
        # Ample memory first: it locks slots 0 and 1, then waits for 2 more.
        # Then only 1 worker fits: it keeps slot 0, releases slot 1, and starts.
        acquired = _acquire(
            lock_dir,
            4,
            1,
            _scripted(_live(AMPLE_USABLE_GB), _live(2.5)),
            FakeTime(),
            out,
        )
        try:
            assert acquired.granted == 1
            assert _locked_slots(lock_dir) == [0, 2, 3]
            assert _read(lock_dir / f"{token_budget.SLOT_PREFIX}1") == ""
            assert "tokens=1 " in _read(lock_dir / f"{token_budget.SLOT_PREFIX}0")
        finally:
            _release_acquired(acquired)
    finally:
        _release_slots(held)
    assert out.getvalue().startswith(
        "token budget: waiting for 4 of 4 tokens — held by: other/holder (2)"
    )


class _InterruptingSleep:
    """Advances FakeTime like its sleep, then raises KeyboardInterrupt (a Ctrl-C)
    on call number `interrupt_on`."""

    def __init__(self, fake_time: FakeTime, interrupt_on: int) -> None:
        self.fake_time = fake_time
        self.interrupt_on = interrupt_on
        self.calls = 0

    def __call__(self, seconds: float) -> None:
        self.calls += 1
        self.fake_time.sleep(seconds)
        if self.calls == self.interrupt_on:
            raise KeyboardInterrupt


def test_ctrl_c_during_memory_wait_releases_slots_and_turnstile(
    lock_dir: Path,
) -> None:
    held = _hold_slots(lock_dir, [2, 3], "holder")
    fake_time = FakeTime()
    try:
        # Ample memory first: it locks slots 0 and 1, then waits for 2 more.
        # Then no worker fits (fit 0 < 1): a memory wait, interrupted by Ctrl-C.
        with pytest.raises(KeyboardInterrupt):
            _acquire(
                lock_dir,
                4,
                1,
                _scripted(_live(AMPLE_USABLE_GB), _live(1.0)),
                fake_time,
                io.StringIO(),
                sleep=_InterruptingSleep(fake_time, interrupt_on=2),
            )
        assert _locked_slots(lock_dir) == [2, 3]
        turnstile = token_budget._try_lock(lock_dir / token_budget.TURNSTILE_NAME)
        assert isinstance(turnstile, int)
        os.close(turnstile)
    finally:
        _release_slots(held)


# --- turnstile hand-off (acquire) --------------------------------------------


def test_acquire_returns_still_holding_the_turnstile(lock_dir: Path) -> None:
    acquired = _acquire(
        lock_dir, 2, 2, _scripted(_live(AMPLE_USABLE_GB)), FakeTime(), io.StringIO()
    )
    try:
        # The caller (_run_child) closes it once the settle window ends.
        assert not _turnstile_free(lock_dir)
    finally:
        _release_acquired(acquired)
    assert _turnstile_free(lock_dir)


def test_acquire_closes_the_turnstile_when_max_wait_gives_up(lock_dir: Path) -> None:
    held = _hold_slots(lock_dir, [0, 1, 2, 3], "holder")
    try:
        with pytest.raises(BudgetError) as error:
            _acquire(
                lock_dir,
                1,
                1,
                _scripted(_live(AMPLE_USABLE_GB)),
                FakeTime(),
                io.StringIO(),
                max_wait=5,
            )
        assert "(--max-wait)" in str(error.value)
        assert _turnstile_free(lock_dir)
    finally:
        _release_slots(held)


def test_acquire_closes_the_turnstile_when_memory_wait_gives_up(
    lock_dir: Path,
) -> None:
    with pytest.raises(BudgetError) as error:
        _acquire(
            lock_dir,
            1,
            1,
            _scripted(_live(2.2)),
            FakeTime(),
            io.StringIO(),
            memory_wait=60,
        )
    assert "waiting for memory with no other test run holding tokens" in str(
        error.value
    )
    assert _turnstile_free(lock_dir)


# --- settle window and mid-run sampling (_run_child) -------------------------


def _held_turnstile(lock_dir: Path) -> int:
    token_budget.ensure_lock_dir(lock_dir)
    descriptor = token_budget._try_lock(lock_dir / token_budget.TURNSTILE_NAME)
    assert descriptor is not None
    return descriptor


def _run_child(
    command: list[str],
    turnstile_fd: int,
    settle_seconds: float,
    live_memory: Callable[[], LiveMemory],
    clock: Callable[[], float],
    out: io.StringIO,
) -> token_budget.ChildResult:
    return token_budget._run_child(
        command, turnstile_fd, settle_seconds, live_memory, clock, "unit-label", out
    )


@pytest.fixture
def fast_poll(monkeypatch: pytest.MonkeyPatch) -> None:
    """Shrink the child-wait poll so a fake-clock case loops without real 1 s
    waits; the fake clock, not the poll, decides when anything is due."""
    monkeypatch.setattr(token_budget, "POLL_SECONDS", 0.01)


def test_child_exiting_inside_the_settle_window_releases_the_turnstile(
    lock_dir: Path,
) -> None:
    turnstile = _held_turnstile(lock_dir)
    result = _run_child(
        _exit_child(0),
        turnstile,
        3600,
        _scripted(LiveMemory(None, "none")),
        time.monotonic,
        io.StringIO(),
    )
    assert result == token_budget.ChildResult(exit_code=0, min_live_usable_gb=None)
    assert _turnstile_free(lock_dir)


@pytest.mark.usefixtures("fast_poll")
def test_settle_window_closes_the_turnstile_while_the_child_runs(
    tmp_path: Path, lock_dir: Path
) -> None:
    settle_seconds = 3
    child, _, release = _marker_child(tmp_path, "settling")
    observed: list[tuple[float, bool]] = []

    def on_tick(now: float) -> None:
        observed.append((now, _turnstile_free(lock_dir)))
        if now >= settle_seconds + 3:
            release.touch()

    result = _run_child(
        child,
        _held_turnstile(lock_dir),
        settle_seconds,
        _scripted(LiveMemory(None, "none")),
        SteppingClock(1, on_tick),
        io.StringIO(),
    )
    assert result.exit_code == 0
    # Each tick probes before the pass acts on that tick's reading, so the
    # turnstile is still held at every tick up to the one where the window ends,
    # and free at every tick after it — while the child is still running.
    assert all(not free for now, free in observed if now <= settle_seconds)
    assert all(free for now, free in observed if now > settle_seconds)
    assert any(now > settle_seconds for now, _ in observed)


@pytest.mark.usefixtures("fast_poll")
def test_mid_run_low_memory_warns_once_and_reports_the_minimum(
    tmp_path: Path, lock_dir: Path
) -> None:
    child, _, release = _marker_child(tmp_path, "low")
    readings = [_live(3.6), _live(0.8), _live(0.9), _live(2.0)]
    served: list[LiveMemory] = []

    def live_memory() -> LiveMemory:
        reading = readings[min(len(served), len(readings) - 1)]
        served.append(reading)
        if len(served) >= len(readings):
            release.touch()
        return reading

    out = io.StringIO()
    result = _run_child(
        child,
        _held_turnstile(lock_dir),
        0,
        live_memory,
        SteppingClock(token_budget.MIDRUN_SAMPLE_SECONDS_HOST),
        out,
    )
    assert result.exit_code == 0
    assert result.min_live_usable_gb == pytest.approx(0.8)
    assert out.getvalue() == (
        "token budget: host memory low during unit-label — 0.80 GB usable (host); "
        "expect timeouts\n"
    )


@pytest.mark.usefixtures("fast_poll")
@pytest.mark.parametrize(
    ("available_bytes", "warns"),
    [
        # The smallest reading whose usable memory is >= LOW_MEMORY_GB (1.0 GB).
        (math.ceil(GIB / token_budget.MEM_SAFETY), False),
        # One byte less: strictly below it.
        (math.ceil(GIB / token_budget.MEM_SAFETY) - 1, True),
    ],
)
def test_mid_run_low_memory_threshold_is_strict(
    tmp_path: Path, lock_dir: Path, available_bytes: int, warns: bool
) -> None:
    child, _, release = _marker_child(tmp_path, "edge")

    def live_memory() -> LiveMemory:
        release.touch()
        return LiveMemory(available_bytes, "host")

    out = io.StringIO()
    result = _run_child(
        child,
        _held_turnstile(lock_dir),
        0,
        live_memory,
        SteppingClock(token_budget.MIDRUN_SAMPLE_SECONDS_HOST),
        out,
    )
    assert result.exit_code == 0
    assert result.min_live_usable_gb is not None
    assert ("host memory low" in out.getvalue()) is warns


@pytest.mark.usefixtures("fast_poll")
@pytest.mark.parametrize(
    ("source", "interval"),
    [
        ("host", token_budget.MIDRUN_SAMPLE_SECONDS_HOST),
        ("vm", token_budget.MIDRUN_SAMPLE_SECONDS_VM),
    ],
)
def test_mid_run_sampling_interval_follows_the_source(
    tmp_path: Path, lock_dir: Path, source: str, interval: int
) -> None:
    child, _, release = _marker_child(tmp_path, "sampled")
    clock = SteppingClock(token_budget.MIDRUN_SAMPLE_SECONDS_HOST)
    sampled_at: list[float] = []

    def live_memory() -> LiveMemory:
        sampled_at.append(clock.now)
        if len(sampled_at) >= 3:
            release.touch()
        return LiveMemory(8 * GIB, source)

    _run_child(child, _held_turnstile(lock_dir), 0, live_memory, clock, io.StringIO())
    first = token_budget.MIDRUN_SAMPLE_SECONDS_HOST
    assert sampled_at[:3] == [first, first + interval, first + 2 * interval]


# --- settle window across processes ------------------------------------------


def _since(fields: dict[str, str]) -> float:
    return datetime.fromisoformat(fields["since"]).timestamp()


def test_settle_window_delays_the_next_start(
    tmp_path: Path, lock_dir: Path, spawn: Callable[..., Runner]
) -> None:
    settle_seconds = 3
    # The test holds 2 slots, so A (3 tokens) takes the turnstile and waits for
    # its third: B, spawned now, deterministically queues behind A's turnstile.
    held = _hold_slots(lock_dir, [0, 1], "holder")
    a_child, a_started, a_release = _marker_child(tmp_path, "a")
    b_child, b_started, b_release = _marker_child(tmp_path, "b")
    try:
        runner_a = spawn("a", 3, a_child, settle_seconds=settle_seconds)
        _wait_for(
            lambda: (
                len([line for line in _slot_lines(lock_dir) if "label=a " in line]) == 2
            ),
            "A's first 2 slot lines",
        )
        runner_b = spawn("b", 1, b_child)
        _wait_for(
            lambda: "waiting for 1 of 4 tokens" in runner_b.output(),
            "B's wait line",
        )
    finally:
        _release_slots(held)
    _wait_for(a_started.exists, "A's child to start")
    _wait_for(b_started.exists, "B's child to start")

    lines = [_slot_fields(line) for line in _slot_lines(lock_dir)]
    a_since = max(_since(fields) for fields in lines if fields["label"] == "a")
    b_since = [_since(fields) for fields in lines if fields["label"] == "b"]
    # A stamps its last slot just before its child starts, so this is a lower
    # bound on A's child start: B locked nothing until A's window had run out.
    assert len(b_since) == 1
    assert b_since[0] >= a_since + settle_seconds

    a_release.touch()
    b_release.touch()
    assert runner_a.wait() == 0, runner_a.output()
    assert runner_b.wait() == 0, runner_b.output()


@pytest.mark.parametrize(
    ("tokens", "settle_seconds"),
    [
        # No window at all.
        (3, 0),
        # The small-run exemption: a run granted <= SETTLE_EXEMPT_MAX_WORKERS
        # workers skips a window longer than every harness wait (so a window
        # wrongly applied would time the wait below out).
        (1, 2 * SYNC_TIMEOUT_SECONDS),
        (2, 2 * SYNC_TIMEOUT_SECONDS),
    ],
)
def test_next_start_is_not_delayed_without_a_settle_window(
    tmp_path: Path,
    lock_dir: Path,
    spawn: Callable[..., Runner],
    tokens: int,
    settle_seconds: float,
) -> None:
    # A's child outlives every harness wait, so the turnstile can only come free
    # below because no window applied — not because A's child self-exited.
    a_child, a_started, a_release = _marker_child(
        tmp_path, "a", lifetime_seconds=3 * SYNC_TIMEOUT_SECONDS
    )
    b_child, b_started, b_release = _marker_child(tmp_path, "b")
    runner_a = spawn("a", tokens, a_child, settle_seconds=settle_seconds)
    _wait_for(a_started.exists, "A's child to start")
    _wait_for(lambda: _turnstile_free(lock_dir), "A to release the turnstile")
    assert runner_a.process.poll() is None, runner_a.output()  # A still running

    runner_b = spawn("b", 1, b_child)
    _wait_for(b_started.exists, "B's child to start")
    assert "waiting" not in runner_b.output()

    a_release.touch()
    b_release.touch()
    assert runner_a.wait() == 0, runner_a.output()
    assert runner_b.wait() == 0, runner_b.output()


# --- live memory gate (main) -------------------------------------------------


def test_tokens_placeholder_is_replaced_with_the_granted_count(
    tmp_path: Path, capacity_file: Path, lock_dir: Path
) -> None:
    marker = tmp_path / "argv.json"
    meminfo = _write_meminfo(tmp_path / "tight-meminfo", 3.6)
    child = [
        sys.executable,
        "-c",
        ARGV_CHILD,
        str(marker),
        "-n",
        "@TOKENS@",
        "x@TOKENS@",
    ]
    exit_code = main(
        _run_args(
            capacity_file,
            lock_dir,
            "4",
            child,
            extra_flags=("--min-tokens", "1"),
            meminfo=meminfo,
        )
    )
    assert exit_code == 0
    assert json.loads(marker.read_text()) == ["-n", "3", "x3"]


def test_elastic_run_without_placeholder_is_refused(
    tmp_path: Path,
    capacity_file: Path,
    lock_dir: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    marker = tmp_path / "ran"
    exit_code = main(
        _run_args(
            capacity_file,
            lock_dir,
            "2",
            _touch_child(marker),
            extra_flags=("--min-tokens", "1"),
        )
    )
    assert exit_code == 1
    assert not marker.exists()
    assert capsys.readouterr().err == ELASTIC_ERROR


@pytest.mark.parametrize(
    ("min_tokens", "message"),
    [
        ("3", "--min-tokens must be between 1 and --tokens (2), got 3"),
        ("0", "--min-tokens must be a positive integer, got '0'"),
        ("abc", "--min-tokens must be a positive integer, got 'abc'"),
    ],
)
def test_invalid_min_tokens_exits_1(
    tmp_path: Path,
    capacity_file: Path,
    lock_dir: Path,
    min_tokens: str,
    message: str,
    capsys: pytest.CaptureFixture[str],
) -> None:
    marker = tmp_path / "ran"
    exit_code = main(
        _run_args(
            capacity_file,
            lock_dir,
            "2",
            _touch_child(marker),
            extra_flags=("--min-tokens", min_tokens),
        )
    )
    assert exit_code == 1
    assert not marker.exists()
    assert capsys.readouterr().err == f"token budget: {message}\n"


@pytest.mark.parametrize("flag", ["--memory-wait", "--settle-seconds"])
@pytest.mark.parametrize("seconds", ["nan", "inf", "-1"])
def test_invalid_wait_seconds_exit_1(
    tmp_path: Path,
    capacity_file: Path,
    lock_dir: Path,
    flag: str,
    seconds: str,
    capsys: pytest.CaptureFixture[str],
) -> None:
    marker = tmp_path / "ran"
    exit_code = main(
        _run_args(
            capacity_file,
            lock_dir,
            "1",
            _touch_child(marker),
            extra_flags=(flag, seconds),
        )
    )
    assert exit_code == 1
    assert not marker.exists()
    assert capsys.readouterr().err.startswith(
        f"token budget: {flag} must be a finite number of seconds >= 0"
    )


def test_meminfo_flag_is_honoured(
    tmp_path: Path,
    capacity_file: Path,
    lock_dir: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    marker = tmp_path / "ran"
    meminfo = _write_meminfo(tmp_path / "tight-meminfo", 2.2)
    exit_code = main(
        _run_args(
            capacity_file,
            lock_dir,
            "1",
            _touch_child(marker),
            extra_flags=("--memory-wait", "0"),
            meminfo=meminfo,
        )
    )
    assert exit_code == 1
    assert not marker.exists()
    err = capsys.readouterr().err
    assert "token budget: waiting for memory — need 2.50 GB for 1 workers" in err
    assert "gave up after 0s waiting for memory with no other test run" in err


def test_unreadable_meminfo_without_hub_project_uses_static_capacity(
    tmp_path: Path,
    capacity_file: Path,
    lock_dir: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    marker = tmp_path / "ran"
    exit_code = main(
        _run_args(
            capacity_file,
            lock_dir,
            "4",
            _touch_child(marker),
            meminfo=tmp_path / "no-meminfo",
        )
    )
    assert exit_code == 0
    assert marker.exists()
    assert capsys.readouterr().err == (
        "token budget: live memory unavailable — using static capacity\n"
    )


def test_exact_run_waits_for_memory_across_processes(
    tmp_path: Path, spawn: Callable[..., Runner]
) -> None:
    meminfo = _write_meminfo(tmp_path / "tight-meminfo", 1.0)
    child, started, release = _marker_child(tmp_path, "exact")
    runner = spawn("exact", 2, child, meminfo=meminfo)
    _wait_for(lambda: "waiting for memory" in runner.output(), "the memory wait line")
    assert (
        "token budget: waiting for memory — need 3.00 GB for 2 workers, 1.00 GB "
        "usable (host); runs holding tokens: none" in runner.output()
    )
    assert not started.exists()

    _write_meminfo(meminfo, 8.0)
    _wait_for(started.exists, "the runner's child to start once memory frees")
    release.touch()
    assert runner.wait() == 0, runner.output()


# --- live memory parity with capacity.py -------------------------------------


class _RecordingDocker:
    """A docker runner that records each argv and answers from a script."""

    def __init__(self, *outputs: tuple[int, str]) -> None:
        self.outputs = list(outputs)
        self.calls: list[list[str]] = []

    def __call__(self, args: list[str]) -> subprocess.CompletedProcess[str]:
        self.calls.append(args)
        returncode, stdout = self.outputs.pop(0)
        return subprocess.CompletedProcess(["docker", *args], returncode, stdout, "")


PARITY_MEMINFO_TEXTS: tuple[str, ...] = (
    "MemTotal: 16384000 kB\nMemAvailable:    9437184 kB\n",
    "MemAvailable:\n",
    "MemAvailable: abc kB\n",
    "MemAvailableX:  5 kB\n",
    "",
)


def test_live_memory_constants_match_capacity() -> None:
    assert token_budget.MEM_SAFETY == capacity.DEFAULT_MEM_SAFETY
    assert (
        token_budget.LIVE_MEMORY_DOCKER_TIMEOUT_SECONDS
        == capacity.LIVE_MEMORY_DOCKER_TIMEOUT_SECONDS
        == 10
    )
    assert token_budget.DEFAULT_CGROUP_PATH == capacity.DEFAULT_CGROUP_PATH
    assert token_budget.DEFAULT_MEMINFO_PATH == capacity.DEFAULT_MEMINFO_PATH


@pytest.mark.parametrize("meminfo_text", PARITY_MEMINFO_TEXTS)
def test_parse_meminfo_matches_capacity(meminfo_text: str) -> None:
    assert token_budget.parse_meminfo(
        meminfo_text, "MemAvailable"
    ) == capacity.parse_meminfo(meminfo_text, "MemAvailable")


@pytest.mark.parametrize("host_text", [*PARITY_MEMINFO_TEXTS, None])
@pytest.mark.parametrize("cgroup_text", ["max\n", "4294967296\n", "junk\n", None])
@pytest.mark.parametrize("vm_text", [PARITY_MEMINFO_TEXTS[0], "MemAvailable:\n", None])
def test_read_live_available_matches_capacity(
    tmp_path: Path,
    host_text: str | None,
    cgroup_text: str | None,
    vm_text: str | None,
) -> None:
    meminfo_path = tmp_path / "meminfo"
    cgroup_path = tmp_path / "memory.max"
    if host_text is not None:
        meminfo_path.write_text(host_text)
    if cgroup_text is not None:
        cgroup_path.write_text(cgroup_text)
    ours = token_budget.read_live_available(meminfo_path, cgroup_path, lambda: vm_text)
    theirs = capacity.read_live_available(meminfo_path, cgroup_path, lambda: vm_text)
    assert (ours.available_bytes, ours.source) == (
        theirs.available_bytes,
        theirs.source,
    )
    assert token_budget.live_usable_gb(ours) == capacity.live_usable_gb(theirs)


@pytest.mark.parametrize("usable_gb", [0.0, 1.9, 2.0, 2.4999999, 2.5, 3.6, 9.6, 60.0])
@pytest.mark.parametrize(("base_gb", "worker_gb"), [(2.0, 0.5), (1.0, 0.25)])
def test_workers_that_fit_matches_capacity(
    usable_gb: float, base_gb: float, worker_gb: float
) -> None:
    assert token_budget.workers_that_fit(
        usable_gb, base_gb, worker_gb
    ) == capacity.workers_that_fit(usable_gb, base_gb, worker_gb)


@pytest.mark.parametrize(
    "outputs",
    [
        ((0, "abc123\n"), (0, PARITY_MEMINFO_TEXTS[0])),
        ((0, ""),),
        ((1, ""),),
        ((0, "abc123\n"), (1, "")),
    ],
)
def test_hub_vm_meminfo_matches_capacity(outputs: tuple[tuple[int, str], ...]) -> None:
    ours = _RecordingDocker(*outputs)
    theirs = _RecordingDocker(*outputs)
    assert token_budget.hub_vm_meminfo("u4i-hub-1000", ours) == (
        capacity.hub_vm_meminfo("u4i-hub-1000", theirs)
    )
    assert ours.calls == theirs.calls


@pytest.mark.parametrize(
    "failure",
    [
        subprocess.TimeoutExpired(["docker"], 10),
        FileNotFoundError("docker: not found"),
    ],
)
def test_hub_vm_meminfo_never_raises(failure: Exception) -> None:
    def failing_docker(args: list[str]) -> subprocess.CompletedProcess[str]:
        raise failure

    assert token_budget.hub_vm_meminfo("u4i-hub-1000", failing_docker) is None


def test_live_memory_reader_falls_back_to_the_vm(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    docker = _RecordingDocker((0, "abc123\n"), (0, PARITY_MEMINFO_TEXTS[0]))
    monkeypatch.setattr(token_budget, "_run_docker_short", docker)
    live = token_budget._live_memory_reader(
        tmp_path / "no-meminfo", tmp_path / NO_CGROUP_NAME, "u4i-hub-1000"
    )()
    assert live == LiveMemory(9437184 * 1024, token_budget.LIVE_SOURCE_VM)
    assert "label=com.docker.compose.project=u4i-hub-1000" in docker.calls[0]


def test_live_memory_reader_without_hub_project_never_calls_docker(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    docker = _RecordingDocker()
    monkeypatch.setattr(token_budget, "_run_docker_short", docker)
    live = token_budget._live_memory_reader(
        tmp_path / "no-meminfo", tmp_path / NO_CGROUP_NAME, None
    )()
    assert live == LiveMemory(None, token_budget.LIVE_SOURCE_NONE)
    assert docker.calls == []


# --- stdlib-only contract ----------------------------------------------------


def test_token_budget_module_is_stdlib_only() -> None:
    """`token_budget.py` runs on the host under bare mise python — stdlib only.

    Loaded by file path in a fresh interpreter with a pruned `sys.path` (no
    project root), so any third-party or `backend` import would either fail or
    show up in `sys.modules`.
    """
    probe_script = (
        "import importlib.util\n"
        "import sys\n"
        "sys.path = [p for p in sys.path if p not in ('', PROJECT_ROOT)]\n"
        "spec = importlib.util.spec_from_file_location('token_budget_leaf', MODULE_FILE)\n"
        "module = importlib.util.module_from_spec(spec)\n"
        # Register before exec so the frozen dataclasses can resolve their own
        # module under `from __future__ import annotations`.
        "sys.modules[spec.name] = module\n"
        "spec.loader.exec_module(module)\n"
        "forbidden = [name for name in sys.modules "
        "if name.split('.')[0] in ('flask', 'sqlalchemy', 'redis', 'backend')]\n"
        "assert forbidden == [], forbidden\n"
    )
    module_file = Path(token_budget.__file__).resolve()
    preamble = (
        f"PROJECT_ROOT = {str(module_file.parents[1])!r}\n"
        f"MODULE_FILE = {str(module_file)!r}\n"
    )
    result = subprocess.run(
        [sys.executable, "-c", preamble + probe_script],
        capture_output=True,
        text=True,
        timeout=SYNC_TIMEOUT_SECONDS,
    )
    assert result.returncode == 0, (
        f"token_budget module pulled in a non-stdlib import:\n"
        f"stdout={result.stdout}\nstderr={result.stderr}"
    )
