"""Unit tests for the host-side test token runner (`scripts/token_budget.py`).

No Docker is used: every case runs against a fabricated capacity file under
`tmp_path`, and the contention cases use real `fcntl.flock` locks held by real
subprocesses, so they run identically on a laptop, inside the web container,
and on a CI runner. Every wait the harness itself performs is bounded by
SYNC_TIMEOUT_SECONDS, and every spawned runner is killed (its whole process
group) in fixture teardown, so a deadlock in `acquire()` fails instead of hangs.
"""

from __future__ import annotations

import fcntl
import io
import itertools
import os
import signal
import stat
import subprocess
import sys
import time
from collections.abc import Callable, Iterator
from pathlib import Path

import pytest

from scripts import token_budget
from scripts.token_budget import BudgetError, format_failure_block, main, read_budget

pytestmark = pytest.mark.unit

SYNC_TIMEOUT_SECONDS: int = 10
HARNESS_POLL_SECONDS: float = 0.05
PROJECT_ROOT: Path = Path(__file__).resolve().parents[2]
DECISION: str = "n_ui=2 n_int=4 binding=cpu usable_gb=9.6 spoke_max=4"
BUDGET: int = 4
TEST_SLUG: str = "tokentest"
# A child command that records when it started, then waits (bounded) for a
# release marker, so the test — not wall-clock timing — decides when it exits.
MARKER_CHILD: str = (
    "import pathlib, sys, time\n"
    "pathlib.Path(sys.argv[1]).write_text(str(time.time_ns()))\n"
    "deadline = time.monotonic() + float(sys.argv[3])\n"
    "while not pathlib.Path(sys.argv[2]).exists() and time.monotonic() < deadline:\n"
    "    time.sleep(0.02)\n"
)


def _write_capacity(path: Path, n_max: str = str(BUDGET)) -> Path:
    path.write_text(
        "# GENERATED by make capacity — DO NOT EDIT\n"
        f"# decision: {DECISION}\n"
        "U4I_N_UI=2\n"
        f"U4I_N_MAX={n_max}\n"
    )
    return path


def _wait_for(predicate: Callable[[], bool], description: str) -> None:
    deadline = time.monotonic() + SYNC_TIMEOUT_SECONDS
    while not predicate():
        if time.monotonic() >= deadline:
            pytest.fail(
                f"timed out after {SYNC_TIMEOUT_SECONDS}s waiting for {description}"
            )
        time.sleep(HARNESS_POLL_SECONDS)


def _read(path: Path) -> str:
    return path.read_text() if path.exists() else ""


def _slot_lines(lock_dir: Path) -> list[str]:
    return [
        line
        for slot in sorted(lock_dir.glob(f"{token_budget.SLOT_PREFIX}*"))
        for line in _read(slot).splitlines()
        if line.strip()
    ]


def _slot_fields(line: str) -> dict[str, str]:
    return dict(field.split("=", 1) for field in line.split())


class Runner:
    """A `python -m scripts.token_budget run …` subprocess logging to a file."""

    def __init__(self, process: subprocess.Popen[bytes], log: Path) -> None:
        self.process = process
        self.log = log

    def output(self) -> str:
        return _read(self.log)

    def wait(self) -> int:
        try:
            return self.process.wait(timeout=SYNC_TIMEOUT_SECONDS)
        except subprocess.TimeoutExpired:
            pytest.fail(
                f"runner did not exit within {SYNC_TIMEOUT_SECONDS}s:\n{self.output()}"
            )


def _reset_sigint_to_default() -> None:
    # A SIG_IGN inherited from the test process (e.g. a nohup'd pytest) would stop
    # the runner's Python from installing KeyboardInterrupt for SIGINT.
    signal.signal(signal.SIGINT, signal.SIG_DFL)


@pytest.fixture
def capacity_file(tmp_path: Path) -> Path:
    return _write_capacity(tmp_path / "capacity.env")


@pytest.fixture
def lock_dir(tmp_path: Path) -> Path:
    return tmp_path / "tokens"


@pytest.fixture
def spawn(
    tmp_path: Path, capacity_file: Path, lock_dir: Path
) -> Iterator[Callable[..., Runner]]:
    """Start runners in their own process group; kill every group on teardown."""
    runners: list[Runner] = []

    def start(
        name: str, tokens: int, child: list[str], max_wait: float | None = None
    ) -> Runner:
        log = tmp_path / f"{name}.log"
        argv = [
            sys.executable,
            "-m",
            "scripts.token_budget",
            "run",
            "--capacity-file",
            str(capacity_file),
            "--lock-dir",
            str(lock_dir),
            "--tokens",
            str(tokens),
            "--label",
            name,
        ]
        if max_wait is not None:
            argv += ["--max-wait", str(max_wait)]
        with log.open("wb") as log_handle:
            process = subprocess.Popen(
                [*argv, "--", *child],
                cwd=PROJECT_ROOT,
                env={**os.environ, "U4I_SLUG": TEST_SLUG},
                stdout=log_handle,
                stderr=subprocess.STDOUT,
                start_new_session=True,
                preexec_fn=_reset_sigint_to_default,
            )
        runner = Runner(process, log)
        runners.append(runner)
        return runner

    try:
        yield start
    finally:
        for runner in runners:
            if runner.process.poll() is None:
                try:
                    os.killpg(runner.process.pid, signal.SIGKILL)
                except ProcessLookupError:
                    pass
            try:
                runner.process.wait(timeout=SYNC_TIMEOUT_SECONDS)
            except subprocess.TimeoutExpired:
                runner.process.kill()


def _marker_child(tmp_path: Path, name: str) -> tuple[list[str], Path, Path]:
    started = tmp_path / f"{name}-started"
    release = tmp_path / f"{name}-release"
    child = [
        sys.executable,
        "-c",
        MARKER_CHILD,
        str(started),
        str(release),
        str(SYNC_TIMEOUT_SECONDS),
    ]
    return child, started, release


def _touch_child(marker: Path) -> list[str]:
    return [sys.executable, "-c", f"open({str(marker)!r}, 'w').close()"]


def _exit_child(code: int) -> list[str]:
    return [sys.executable, "-c", f"import sys; sys.exit({code})"]


def _run_args(
    capacity_file: Path,
    lock_dir: Path,
    tokens: str,
    command: list[str],
    max_wait: str = "0",
) -> list[str]:
    return [
        "run",
        "--capacity-file",
        str(capacity_file),
        "--lock-dir",
        str(lock_dir),
        "--tokens",
        tokens,
        "--label",
        "unit-label",
        "--max-wait",
        max_wait,
        "--",
        *command,
    ]


def _hold_slots(lock_dir: Path, indexes: list[int], label: str) -> list[int]:
    """Lock slot files in this process (distinct open file descriptions)."""
    lock_dir.mkdir(mode=0o700, exist_ok=True)
    held: list[int] = []
    for index in indexes:
        descriptor = os.open(
            lock_dir / f"{token_budget.SLOT_PREFIX}{index}",
            os.O_RDWR | os.O_CREAT,
            0o600,
        )
        fcntl.flock(descriptor, fcntl.LOCK_EX | fcntl.LOCK_NB)
        os.write(
            descriptor,
            f"pid={os.getpid()} slug=other label={label} tokens={len(indexes)} "
            "since=2026-09-29T00:00:00+00:00\n".encode(),
        )
        held.append(descriptor)
    return held


def _release_slots(descriptors: list[int]) -> None:
    for descriptor in descriptors:
        os.close(descriptor)


# --- read_budget -------------------------------------------------------------


def test_read_budget_returns_budget_and_decision(capacity_file: Path) -> None:
    assert read_budget(capacity_file) == (BUDGET, DECISION)


def test_read_budget_missing_file(tmp_path: Path) -> None:
    with pytest.raises(BudgetError) as error:
        read_budget(tmp_path / "absent.env")
    assert str(error.value).endswith("run 'make capacity'")


@pytest.mark.parametrize("n_max", ["", "abc", "0", "-3", "1.5"])
def test_read_budget_invalid_n_max(tmp_path: Path, n_max: str) -> None:
    path = _write_capacity(tmp_path / "capacity.env", n_max)
    with pytest.raises(BudgetError) as error:
        read_budget(path)
    assert str(error.value).endswith("run 'make capacity'")


def test_read_budget_missing_n_max(tmp_path: Path) -> None:
    path = tmp_path / "capacity.env"
    path.write_text(f"# decision: {DECISION}\nU4I_N_UI=2\n")
    with pytest.raises(BudgetError) as error:
        read_budget(path)
    assert str(error.value) == (
        f"{path} missing or has no valid U4I_N_MAX — run 'make capacity'"
    )


def test_main_reports_missing_capacity_file(
    tmp_path: Path, lock_dir: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    marker = tmp_path / "ran"
    exit_code = main(
        _run_args(tmp_path / "absent.env", lock_dir, "1", _touch_child(marker))
    )
    assert exit_code == 1
    assert not marker.exists()
    assert capsys.readouterr().err.startswith("token budget: ")


# --- token validation --------------------------------------------------------


@pytest.mark.parametrize("tokens", ["0", "-1", "abc", ""])
def test_invalid_token_count_exits_1(
    tmp_path: Path,
    capacity_file: Path,
    lock_dir: Path,
    tokens: str,
    capsys: pytest.CaptureFixture[str],
) -> None:
    marker = tmp_path / "ran"
    exit_code = main(_run_args(capacity_file, lock_dir, tokens, _touch_child(marker)))
    assert exit_code == 1
    assert not marker.exists()
    assert capsys.readouterr().err.startswith("token budget: ")


def test_over_budget_request_is_refused_without_running(
    tmp_path: Path,
    capacity_file: Path,
    lock_dir: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    marker = tmp_path / "ran"
    exit_code = main(_run_args(capacity_file, lock_dir, "5", _touch_child(marker)))
    assert exit_code == 1
    assert not marker.exists()
    assert capsys.readouterr().err == (
        "token budget: this run needs 5 tokens but the host budget is 4 "
        f"(U4I_N_MAX in {capacity_file}); lower n= or raise it with "
        "'make capacity' in the primary clone\n"
    )


def test_missing_command_exits_1(
    capacity_file: Path, lock_dir: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    assert main(_run_args(capacity_file, lock_dir, "1", [])) == 1
    assert capsys.readouterr().err.startswith("token budget: ")


# --- exit codes and the failure block ----------------------------------------


def test_child_failure_propagates_and_prints_capacity_block(
    capacity_file: Path, lock_dir: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    assert main(_run_args(capacity_file, lock_dir, "2", _exit_child(3))) == 3
    err = capsys.readouterr().err
    assert "token budget: unit-label exited 3 — resolved capacity for this run:" in err
    assert f"  tokens (n):     2 of budget 4 (U4I_N_MAX, {capacity_file})" in err
    assert "  queued:         0.0s; other holders at start: 0 tokens" in err
    assert f"  decision:       {DECISION}" in err
    assert "  at ceiling:     no" in err
    assert "hint:" not in err


@pytest.mark.parametrize("code", [0, 130])
def test_child_success_or_interrupt_prints_no_block(
    capacity_file: Path,
    lock_dir: Path,
    code: int,
    capsys: pytest.CaptureFixture[str],
) -> None:
    assert main(_run_args(capacity_file, lock_dir, "1", _exit_child(code))) == code
    assert "resolved capacity" not in capsys.readouterr().err


def test_child_runs_after_acquiring(
    tmp_path: Path, capacity_file: Path, lock_dir: Path
) -> None:
    marker = tmp_path / "ran"
    assert main(_run_args(capacity_file, lock_dir, "4", _touch_child(marker))) == 0
    assert marker.exists()


def test_at_ceiling_prints_hint(
    capacity_file: Path, lock_dir: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    held = _hold_slots(lock_dir, [0, 1], "holder")
    try:
        assert main(_run_args(capacity_file, lock_dir, "2", _exit_child(1))) == 1
    finally:
        _release_slots(held)
    err = capsys.readouterr().err
    assert "other holders at start: 2 tokens (other/holder)" in err
    assert "  at ceiling:     yes  (tokens in use incl. this run == budget)" in err
    assert (
        "  hint:           timeouts or spurious login failures at the ceiling are "
        "often capacity, not product bugs — rerun with a lower n=" in err
    )


def test_below_ceiling_prints_no_hint(
    capacity_file: Path, lock_dir: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    held = _hold_slots(lock_dir, [0], "holder")
    try:
        assert main(_run_args(capacity_file, lock_dir, "2", _exit_child(1))) == 1
    finally:
        _release_slots(held)
    err = capsys.readouterr().err
    assert "other holders at start: 1 tokens (other/holder)" in err
    assert "  at ceiling:     no" in err
    assert "hint:" not in err


def test_format_failure_block_is_pure() -> None:
    lines = format_failure_block(
        label="test-x",
        exit_code=5,
        tokens=3,
        budget=4,
        capacity_file=Path("/cap.env"),
        queued_seconds=12.34,
        others_at_start=("a/test-y",),
        in_use_at_start=1,
        decision=DECISION,
    )
    assert lines == [
        "token budget: test-x exited 5 — resolved capacity for this run:",
        "  tokens (n):     3 of budget 4 (U4I_N_MAX, /cap.env)",
        "  queued:         12.3s; other holders at start: 1 tokens (a/test-y)",
        "  at ceiling:     yes  (tokens in use incl. this run == budget)",
        f"  decision:       {DECISION}",
        "  hint:           timeouts or spurious login failures at the ceiling are "
        "often capacity, not product bugs — rerun with a lower n=",
    ]


def test_queued_run_times_out_with_max_wait(
    tmp_path: Path,
    capacity_file: Path,
    lock_dir: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    marker = tmp_path / "ran"
    held = _hold_slots(lock_dir, [0, 1, 2], "holder")
    try:
        exit_code = main(_run_args(capacity_file, lock_dir, "2", _touch_child(marker)))
    finally:
        _release_slots(held)
    assert exit_code == 1
    assert not marker.exists()
    err = capsys.readouterr().err
    assert "token budget: waiting for 2 of 4 tokens — held by: other/holder (3)" in err
    assert "gave up" in err
    # The one slot it did lock was released on the way out.
    assert main(_run_args(capacity_file, lock_dir, "1", _exit_child(0))) == 0


# --- lock dir ----------------------------------------------------------------


def test_lock_dir_is_created_0700(capacity_file: Path, lock_dir: Path) -> None:
    assert main(_run_args(capacity_file, lock_dir, "1", _exit_child(0))) == 0
    assert lock_dir.stat().st_mode & 0o777 == 0o700
    assert (lock_dir / token_budget.TURNSTILE_NAME).exists()
    assert (lock_dir / f"{token_budget.SLOT_PREFIX}0").exists()


def test_lock_dir_owned_by_another_uid_is_refused(
    tmp_path: Path,
    capacity_file: Path,
    lock_dir: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    lock_dir.mkdir(mode=0o700)
    real_lstat = os.lstat
    foreign_uid = os.getuid() + 1

    def fake_lstat(path: str | os.PathLike[str], **kwargs: object) -> os.stat_result:
        result = real_lstat(path, **kwargs)
        if Path(str(path)) != lock_dir:
            return result
        fields = list(result)
        fields[4] = foreign_uid  # st_uid
        return os.stat_result(fields)

    monkeypatch.setattr(token_budget.os, "lstat", fake_lstat)
    marker = tmp_path / "ran"
    exit_code = main(_run_args(capacity_file, lock_dir, "1", _touch_child(marker)))
    monkeypatch.undo()
    assert exit_code == 1
    assert not marker.exists()
    err = capsys.readouterr().err
    assert err.startswith("token budget: ")
    assert f"uid {foreign_uid}" in err


def test_symlinked_lock_dir_is_refused(
    tmp_path: Path,
    capacity_file: Path,
    lock_dir: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    target = tmp_path / "elsewhere"
    target.mkdir(mode=0o700)
    lock_dir.symlink_to(target)
    marker = tmp_path / "ran"
    exit_code = main(_run_args(capacity_file, lock_dir, "1", _touch_child(marker)))
    assert exit_code == 1
    assert not marker.exists()
    assert list(target.iterdir()) == []
    err = capsys.readouterr().err
    assert err.startswith(f"token budget: {lock_dir} is a symlink or not a directory")


def test_group_readable_lock_dir_is_refused(
    tmp_path: Path,
    capacity_file: Path,
    lock_dir: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    lock_dir.mkdir(mode=0o700)
    real_lstat = os.lstat

    # Fake the mode rather than chmod the dir open: CodeQL flags any real chmod
    # that grants group/other access, even in a test.
    def fake_lstat(path: str | os.PathLike[str], **kwargs: object) -> os.stat_result:
        result = real_lstat(path, **kwargs)
        if Path(str(path)) != lock_dir:
            return result
        fields = list(result)
        fields[0] = stat.S_IFDIR | 0o750  # st_mode
        return os.stat_result(fields)

    monkeypatch.setattr(token_budget.os, "lstat", fake_lstat)
    marker = tmp_path / "ran"
    exit_code = main(_run_args(capacity_file, lock_dir, "1", _touch_child(marker)))
    monkeypatch.undo()
    assert exit_code == 1
    assert not marker.exists()
    assert capsys.readouterr().err == (
        f"token budget: {lock_dir} dir mode is 0750, expected 0700 — remove it and "
        "rerun\n"
    )


# --- CLI validation and robustness -------------------------------------------


@pytest.mark.parametrize("max_wait", ["nan", "inf", "-1"])
def test_invalid_max_wait_exits_1(
    tmp_path: Path,
    capacity_file: Path,
    lock_dir: Path,
    max_wait: str,
    capsys: pytest.CaptureFixture[str],
) -> None:
    marker = tmp_path / "ran"
    exit_code = main(
        _run_args(capacity_file, lock_dir, "1", _touch_child(marker), max_wait)
    )
    assert exit_code == 1
    assert not marker.exists()
    assert capsys.readouterr().err.startswith("token budget: --max-wait must be")


def test_command_not_found_exits_127_and_releases(
    capacity_file: Path, lock_dir: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    missing = ["/nonexistent-u4i-command"]
    assert main(_run_args(capacity_file, lock_dir, "1", missing)) == 127
    assert capsys.readouterr().err.startswith("token budget: cannot run")
    # Every slot is free again: a full-budget run needs no wait.
    assert main(_run_args(capacity_file, lock_dir, "4", _exit_child(0))) == 0


def test_signal_handlers_are_restored_after_the_child(
    capacity_file: Path, lock_dir: Path
) -> None:
    before = {
        signum: signal.getsignal(signum) for signum in (signal.SIGINT, signal.SIGTERM)
    }
    assert main(_run_args(capacity_file, lock_dir, "1", _exit_child(0))) == 0
    after = {
        signum: signal.getsignal(signum) for signum in (signal.SIGINT, signal.SIGTERM)
    }
    assert after == before


def test_acquire_heartbeats_then_gives_up(lock_dir: Path) -> None:
    held = _hold_slots(lock_dir, [0, 1, 2], "holder")
    ticks = itertools.count()

    def fake_clock() -> float:
        # Each call advances one heartbeat, so every poll pass is heartbeat-due.
        return float(next(ticks) * token_budget.HEARTBEAT_SECONDS)

    out = io.StringIO()
    try:
        with pytest.raises(BudgetError) as error:
            token_budget.acquire(
                lock_dir,
                2,
                BUDGET,
                "unit-label",
                TEST_SLUG,
                2 * token_budget.HEARTBEAT_SECONDS + 1,
                fake_clock,
                out,
            )
    finally:
        _release_slots(held)
    lines = out.getvalue().splitlines()
    assert lines[0] == (
        "token budget: waiting for 2 of 4 tokens — held by: other/holder (3)"
    )
    assert any(
        line.startswith("token budget: still waiting for 2 of 4 tokens (")
        for line in lines[1:]
    )
    assert "gave up" in str(error.value)


def test_stale_slot_is_skipped_in_best_effort_holders(
    tmp_path: Path,
    capacity_file: Path,
    lock_dir: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    lock_dir.mkdir(mode=0o700)
    finished = subprocess.Popen([sys.executable, "-c", "pass"])
    finished.wait(timeout=SYNC_TIMEOUT_SECONDS)
    (lock_dir / f"{token_budget.SLOT_PREFIX}0").write_text(
        f"pid={finished.pid} slug=other label=ghost tokens=1 "
        "since=2026-09-29T00:00:00+00:00\n"
    )
    # Holding the turnstile forces the runner onto the best-effort (content) read.
    turnstile = os.open(
        lock_dir / token_budget.TURNSTILE_NAME, os.O_RDWR | os.O_CREAT, 0o600
    )
    held: list[int] = []
    marker = tmp_path / "ran"
    try:
        fcntl.flock(turnstile, fcntl.LOCK_EX | fcntl.LOCK_NB)
        held = _hold_slots(lock_dir, [1], "holder")
        exit_code = main(_run_args(capacity_file, lock_dir, "1", _touch_child(marker)))
    finally:
        _release_slots(held)
        os.close(turnstile)
    assert exit_code == 1
    assert not marker.exists()
    err = capsys.readouterr().err
    assert "token budget: waiting for 1 of 4 tokens — held by: other/holder (1)" in err
    assert "ghost" not in err


# --- real fcntl contention between processes ---------------------------------


def test_queues_behind_holder_and_kernel_releases_on_sigkill(
    tmp_path: Path, lock_dir: Path, spawn: Callable[..., Runner]
) -> None:
    holder_child, holder_started, _ = _marker_child(tmp_path, "holder")
    holder = spawn("holder", 3, holder_child)
    _wait_for(lambda: len(_slot_lines(lock_dir)) == 3, "the holder's 3 slot lines")
    _wait_for(holder_started.exists, "the holder's child to start")

    waiter = spawn("waiter", 2, _touch_child(tmp_path / "waiter-ran"), max_wait=1.5)
    assert waiter.wait() == 1
    output = waiter.output()
    assert (
        f"token budget: waiting for 2 of 4 tokens — held by: {TEST_SLUG}/holder (3)"
        in output
    )
    assert "gave up" in output
    assert not (tmp_path / "waiter-ran").exists()

    os.killpg(holder.process.pid, signal.SIGKILL)
    holder.wait()
    full = spawn("full", 4, _touch_child(tmp_path / "full-ran"), max_wait=0)
    assert full.wait() == 0, full.output()
    assert "waiting" not in full.output()
    assert (tmp_path / "full-ran").exists()


def test_sigint_while_queued_exits_130_and_releases(
    tmp_path: Path, lock_dir: Path, spawn: Callable[..., Runner]
) -> None:
    holder_child, _, _ = _marker_child(tmp_path, "holder")
    spawn("holder", 3, holder_child)
    _wait_for(lambda: len(_slot_lines(lock_dir)) == 3, "the holder's 3 slot lines")

    queued_marker = tmp_path / "queued-ran"
    queued = spawn("queued", 2, _touch_child(queued_marker))
    _wait_for(
        lambda: "waiting for 2 of 4 tokens" in queued.output(),
        "the queued runner's wait line",
    )
    queued.process.send_signal(signal.SIGINT)
    assert queued.wait() == 130, queued.output()
    assert not queued_marker.exists()
    assert "resolved capacity" not in queued.output()

    probe = spawn("probe", 1, _touch_child(tmp_path / "probe-ran"), max_wait=0)
    assert probe.wait() == 0, probe.output()
    assert "waiting" not in probe.output()


def test_tty_sigint_while_child_runs_exits_130_without_block(
    tmp_path: Path, spawn: Callable[..., Runner]
) -> None:
    child, started, _ = _marker_child(tmp_path, "running")
    runner = spawn("running", 1, child)
    _wait_for(started.exists, "the runner's child to start")
    # A terminal Ctrl-C signals the whole foreground group: runner and child.
    os.killpg(runner.process.pid, signal.SIGINT)
    assert runner.wait() == 130, runner.output()
    assert "resolved capacity" not in runner.output()


def test_sigterm_to_runner_is_forwarded_to_child(
    tmp_path: Path, spawn: Callable[..., Runner]
) -> None:
    child, started, _ = _marker_child(tmp_path, "term")
    runner = spawn("term", 1, child)
    _wait_for(started.exists, "the runner's child to start")
    # Only the runner is signalled; the child can only die of it via forwarding.
    runner.process.send_signal(signal.SIGTERM)
    assert runner.wait() == 143, runner.output()
    assert (
        "token budget: term exited 143 — resolved capacity for this run:"
        in runner.output()
    )


def test_turnstile_holder_is_served_before_later_waiter(
    tmp_path: Path, lock_dir: Path, spawn: Callable[..., Runner]
) -> None:
    holder_child, _, holder_release = _marker_child(tmp_path, "holder")
    first_child, first_started, first_release = _marker_child(tmp_path, "first")
    second_child, second_started, second_release = _marker_child(tmp_path, "second")

    holder = spawn("holder", 3, holder_child)
    _wait_for(lambda: len(_slot_lines(lock_dir)) == 3, "the holder's 3 slot lines")
    first = spawn("first", 2, first_child)
    _wait_for(
        lambda: "waiting for 2 of 4 tokens" in first.output(),
        "the first waiter's wait line",
    )
    second = spawn("second", 1, second_child)
    _wait_for(
        lambda: "waiting for 1 of 4 tokens" in second.output(),
        "the second waiter's wait line",
    )
    assert f"{TEST_SLUG}/holder (3)" in second.output()
    assert f"{TEST_SLUG}/first (1)" in second.output()

    holder_release.touch()
    assert holder.wait() == 0, holder.output()
    _wait_for(first_started.exists, "the first waiter's child to start")
    _wait_for(second_started.exists, "the second waiter's child to start")

    # Each runner stamps `since=` as it locks a slot. The first waiter locks its
    # last slot while still holding the turnstile, and the second can lock
    # nothing until it gets the turnstile — so the first is served strictly
    # before the second. (Child start times are not compared: both children
    # start within one interpreter startup of each other, which is not ordered.)
    lines = [_slot_fields(line) for line in _slot_lines(lock_dir)]
    first_since = [fields["since"] for fields in lines if fields["label"] == "first"]
    second_since = [fields["since"] for fields in lines if fields["label"] == "second"]
    assert len(first_since) == 2
    assert len(second_since) == 1
    assert max(first_since) < second_since[0]

    first_release.touch()
    second_release.touch()
    assert first.wait() == 0, first.output()
    assert second.wait() == 0, second.output()


# --- stdlib-only contract ----------------------------------------------------


def test_token_budget_module_is_stdlib_only() -> None:
    """`token_budget.py` runs on the host under bare mise python — stdlib only.

    Loaded by file path in a fresh interpreter with a pruned `sys.path` (no
    project root), so any third-party or `backend` import would either fail or
    show up in `sys.modules`.
    """
    probe_script = (
        "import importlib.util\n"
        "import sys\n"
        "sys.path = [p for p in sys.path if p not in ('', PROJECT_ROOT)]\n"
        "spec = importlib.util.spec_from_file_location('token_budget_leaf', MODULE_FILE)\n"
        "module = importlib.util.module_from_spec(spec)\n"
        # Register before exec so the frozen dataclasses can resolve their own
        # module under `from __future__ import annotations`.
        "sys.modules[spec.name] = module\n"
        "spec.loader.exec_module(module)\n"
        "forbidden = [name for name in sys.modules "
        "if name.split('.')[0] in ('flask', 'sqlalchemy', 'redis', 'backend')]\n"
        "assert forbidden == [], forbidden\n"
    )
    module_file = Path(token_budget.__file__).resolve()
    preamble = (
        f"PROJECT_ROOT = {str(module_file.parents[1])!r}\n"
        f"MODULE_FILE = {str(module_file)!r}\n"
    )
    result = subprocess.run(
        [sys.executable, "-c", preamble + probe_script],
        capture_output=True,
        text=True,
        timeout=SYNC_TIMEOUT_SECONDS,
    )
    assert result.returncode == 0, (
        f"token_budget module pulled in a non-stdlib import:\n"
        f"stdout={result.stdout}\nstderr={result.stderr}"
    )
