name: CI

on: 
  push:
  pull_request:
    branches:
      - main

jobs:
    format:
        name: 'Format'
        uses: ./.github/workflows/format.yml
        with:
            branch_ref: ${{ github.ref }}

    lint:
        needs: "format"
        name: 'Lint'
        uses: ./.github/workflows/lint.yml
        with:
            branch_ref: ${{ github.ref }}

    test:
        name: 'Test'
        uses: ./.github/workflows/test.yml
        with:
            branch_ref: ${{ github.ref }}
        secrets:
            MAILJET_API_KEY: ${{ secrets.MAILJET_API_KEY }}
            MAILJET_SECRET_KEY: ${{ secrets.MAILJET_SECRET_KEY }}
            BASE_EMAIL: ${{ secrets.BASE_EMAIL }}



