# Making this the name so badge shows something understandable
name: CI and Tests

on: 
  pull_request:
    branches:
      - main
      - dev

jobs:
    format:
        name: 'Code Quality'
        uses: ./.github/workflows/format.yml
        with:
            branch_ref: ${{ github.ref }}

    lint:
        needs: 'format'
        name: 'Code Quality'
        uses: ./.github/workflows/lint.yml
        with:
            branch_ref: ${{ github.ref }}

    test:
        needs: 'lint'
        name: 'Test'
        uses: ./.github/workflows/test.yml
        with:
            branch_ref: ${{ github.ref }}
        secrets:
            MAILJET_API_KEY: ${{ secrets.MAILJET_API_KEY }}
            MAILJET_SECRET_KEY: ${{ secrets.MAILJET_SECRET_KEY }}
            BASE_EMAIL: ${{ secrets.BASE_EMAIL }}
