name: Lint Python

on:
  push:
    branches: [backend, frontend, dev, main]
  pull_request:
    branches: [backend, frontend, dev, main]
  
jobs:
  build-test-container:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Check Python with Black
      uses: psf/black@stable
      with:
        options: " --verbose"       
    - name: Verify Python with Black
      uses: psf/black@stable
      with:
        options: "--check --verbose"
    - name: Check for modified files
      id: git-check
      run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
    - name: Commit Lint Changes
      if: steps.git-check.outputs.modified == 'true'
      run: |
        git config --global user.name '${{ secrets.NAME }}'
        git config --global user.email '${{ secrets.MY_EMAIL }}'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git branch
      # git commit -am "Automated changes"
      # git push
