name: Lint Python

on:
  push:
    branches: [backend, frontend, dev, main]
  pull_request:
    branches: [backend, frontend, dev, main]
  
jobs:
  build-test-container:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
#     # Docker Hub image that `container-job` executes in
#     container: python:3.10.12-bookworm

#     # Service containers to run with `container-job`
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Check Python with Black
      uses: psf/black@stable
      with:
        options: " --verbose"       
    - name: Verify Python with Black
      uses: psf/black@stable
      with:
        options: "--check --verbose"
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Commit Lint Changes
      uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: '${{ steps.extract_branch.outputs.branch }}' #optional defaults to master


