name: Lint Python

on:
  push:
    branches: [backend, frontend, dev, main]
  pull_request:
    branches: [backend, frontend, dev, main]
  
jobs:
  build-test-container:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: python:3.10.12-bookworm

    # Service containers to run with `container-job`
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install Black
      run: |
        python -m pip install --upgrade pip
        pip install black
        
#     - name: Linting
#       run: |
#         black --check reorder-python-imports .

    - name: Check Python with Black
      uses: psf/black@stable
      with:
        options: " --verbose"
