name: Lint

on:
  push:
    branches: [backend, frontend, dev, main]
  pull_request:
    branches: [backend, frontend, dev, main]
    
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Lint Python with Black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
